### ISSUE TITLE
yAxis.tickFormat in StackedArea Chart doesn't seem to work anymore

### ISSUE THREAD

**Issue by ingodjango** [novus/nvd3#1000]
Hi,
I try to set a tickFormat on yAxis since I have big numbers I have an issue displaying and since these are finance numbers I also do replace the shortnames (k,M,G ...).

                chart.yAxis.tickFormat(function(d){return d3.format('.2s')(d).replace('k', 'Tsd').replace('M', 'Mio').replace('G', 'Mrd')});

I'm using d3 3.5.5 and nvd3 1.7.1.
Last version it worked with nvd3 1.1.4b

Here is a fiddle:
http://jsfiddle.net/h7b55hmw/

Any idea what's wrong?
Thanks.

**Comment by liquidpele** [comment]
Works fine on latest development branch code:  

http://jsfiddle.net/h7b55hmw/1/
