### ISSUE TITLE
Incorrect position of tooltip on second chart if FireFox. 

### ISSUE THREAD

**Issue by vehpsr** [novus/nvd3#1004]
Hi guys.

behavior is next:
I render two lineCharts on single page.
First lineChart tooltip popup will render as expected (when you hover over point).
Second lineChart tooltip will render correctly in x-coordinate, but y-coordinate will be misplaced (actually it will be from first chart (please see img attached)) for all chart points.
![ff_nvd3_bug](https://cloud.githubusercontent.com/assets/3133265/7390082/edaab2ea-ee7c-11e4-8e0e-1d2e67fddbbe.png)

Works correctly in Chrome.

My FF version 37.0.2
nvd3 version 1.7.1
d3 version 3.5.5

minimal code to reproduce issue:
```html
<div id="avgRatingDiagram" class="metricDiagram avgRatingDiagram">
    <svg></svg>
    <script type="text/javascript">
        addStatisticsChart([{values:[{x: 13, y: 23}, {x: 23, y: 28}, {x: 33, y: 23}]}], "#avgRatingDiagram");
    </script>
</div>
<div id="songsCountDiagram" class="metricDiagram songsCountDiagram">
    <svg></svg>
    <script type="text/javascript">
        addStatisticsChart([{values:[{x: 15, y: 25}, {x: 20, y: 15}, {x: 25, y: 15}]}], "#songsCountDiagram");
    </script>
</div>
```
```javascript
function addStatisticsChart(data, selector) {
    nv.addGraph(function() {
        var chart = nv.models.lineChart()
            .forceY([10, 40])
            .showLegend(false);

        chart.xAxis.tickFormat(function(d) {
            return d3.time.format('%d/%m')(new Date(d))
        });

        d3.select(selector + ' svg')
            .datum(data)
            .call(chart);

        return chart;
    });
}
```
```css
.metricDiagram {
    display: inline-block;
    width: 450px;
    height: 250px;
}
```

**Comment by liquidpele** [comment]
tooltips were completely refactored in the current development branch please try that out

**Comment by vehpsr** [comment]
try on latest development branch version -- still the same.
one thing though: In original post I said that "x-coordinate is correct, but y -- off".
that's wrong (I was deceived by data because it has constant deltaX for both charts).
x-coordinate is also taken from First Chart.

**Comment by liquidpele** [comment]
should be fixed by https://github.com/novus/nvd3/pull/1079
