### ISSUE TITLE
Initial Chart Sizing Problems

### ISSUE THREAD

**Issue by WizardX94** [novus/nvd3#1006]
Hey guys, I'm working with the simple line chart, and I just want to have it initially fill up the page. If I set the initial dimensions of the chart to the window height and width, it works, but the x-axis label collides with the ticks. I have to resize the graph and then everything snaps to place. If I don't initially set the chart dimensions, I get a flat, smashed graph that resizes and snaps to. I was wondering if anyone had an idea as to what the cause or solution might be.

With initial sizes:
Before:
![image](https://cloud.githubusercontent.com/assets/2358739/7397275/e34f0f9a-ee6c-11e4-945e-5d21874818f7.png)

After:
![image](https://cloud.githubusercontent.com/assets/2358739/7397205/785fa65e-ee6c-11e4-9b9b-883c0433bae1.png)

Without initial sizes:
Before:
![image](https://cloud.githubusercontent.com/assets/2358739/7397226/9e1f840e-ee6c-11e4-9955-eb7b3fb880f5.png)

After:
Same as previous after.

**Comment by lucaslin** [comment]
Possibly related to #946

**Comment by WizardX94** [comment]
Really the main concern is that last graph. I don't want to set the width and height because one of the main needs is for the graph to be re-sizable. When the graph is called though, I get that scrunched mess instead of a graph that fills the window like when using the:
nv.utils.windowResize(function() { chart.update(); });

I'm currently looking for a way to update the chart without needing the window resized, but doing it right after the chart is called so it bypasses that collapsed result.

**Comment by WizardX94** [comment]
Figured it out. I am using JQuery with a loading div. The graph does not render until the loading div disappears and the svg for the graph is toggled. nvd3 was initially rendering the height for the graph based on a hidden element, which is 0. Not a bug, just stupidity.
