### ISSUE TITLE
Stacked area chart uses percent formatter for other types

### ISSUE THREAD

**Issue by jgrund** [novus/nvd3#1014]
The stacked area chart will use the percent formatter for numbers permanently if the chart is updated while a user is looking at the expanded style. Relevant code:

```
  if (stacked.style() === 'expand' || stacked.style() === 'stack_percent') {
    oldYTickFormat = yAxis.tickFormat();
    //Forces the yAxis to use percentage in 'expand' 
    yAxis.tickFormat(d3.format('%'));
  }
  else {
    if (oldYTickFormat) yAxis.tickFormat(oldYTickFormat);
  }

  g.select('.nv-y.nv-axis')
    .transition().duration(0)
    .call(yAxis);
```

To solve this, we could:

a) Cache the `d3.format('%')` call. That way we can compare if the current `tickFormat` is the same as our reference. If it is, we don't need to do an assignment, and we don't lose the original reference.

b) hold an object literal of styles to formatters, so we don't have the possibility to overwrite the "other" formatter when we update twice with expand or stack_percent.

I prefer the former personally. 

In a larger sense, I wonder if overwriting the tick format for percentage cases is what we want to do. 
It seems we take away control from the user in that they cannot override for that layout.

Perhaps exposing a method on this chart to override the formatting. That way, we could detect the user requested an override and not insert our custom code in that case.

**Comment by liquidpele** [comment]
I think this was *just* fixed this here:

https://github.com/novus/nvd3/pull/1001

**Comment by jgrund** [comment]
@liquidpele Nope, actually I wonder if that code will have the same issue I'm describing here. The issue is an update that forces the oldYTickFormat / oldValueFormatter to hold our percent formatter.
