### ISSUE TITLE
Please add sample graph or documentation to make human readable time axis.

### ISSUE THREAD

**Issue by Serveurperso** [novus/nvd3#1018]
Because i lost a lot of time to get this. Issue "solved" two year after, hard to find on google.
(chart = nv.models.lineChart)

````
        chart.lines.xScale(d3.time.scale());
        var timeFormat = d3.time.format('%H:%M:%S');
        chart.xAxis
            .showMaxMin(false)
            .tickFormat(timeFormat)
        ;
````

**Comment by Serveurperso** [comment]
Also there is a problem, useInteractiveGuideline do not work with this .tickFormat(timeFormat) trick !!!!!!

**Comment by Serveurperso** [comment]
I make a RRDtool like linegraph with this trick but there is a problem, The tooltip mouse bubble don't work with  .tickFormat(timeFormat)  :(:(:(

I make more testing before pull request this sample for documentation.

**Comment by Serveurperso** [comment]
I tested 

chart.interactiveLayer.tooltip.contentGenerator(function(data) {     return 'this is my custom content'; });

work only without  .tickFormat(timeFormat)

**Comment by Serveurperso** [comment]
It work. now I can make a cool sample for documentation...

````
        chart.lines.xScale(d3.time.scale());
        chart.xAxis
            .showMaxMin(false)
            .tickFormat(function(d) {
                return d3.time.format('%H:%M:%S')(new Date(d))
            });
        ;
````

**Comment by Serveurperso** [comment]
It work. now I can make a cool sample for documentation...
tooltip is now OK and xScale is nice:)

````
        chart.lines.xScale(d3.time.scale());
        chart.xAxis
            .showMaxMin(false)
            .tickFormat(function(d) {
                return d3.time.format('%H:%M:%S')(new Date(d))
            });
        ;
````

**Comment by liquidpele** [comment]
Does the time scale example we already have not show what you wanted? 

http://nvd3-community.github.io/nvd3/examples/TimeSeries.html

**Comment by liquidpele** [comment]
If you send us a pull request with another example that does something different then we'll take a look!

**Comment by Serveurperso** [comment]
You can look here : http://www.serveurperso.com/temp/pascal/graph.php (temp script on my server, realtime use F5, auto ajax refresh in the future)
I look the code of your sample tonight to compare. mine is different.
sorry for my english.
Pascal

**Comment by RenatoUtsch** [comment]
There are a lot of examples using time axis, even on nvd3's website.
