### ISSUE TITLE
Line plus bar chart

### ISSUE THREAD

**Issue by NSudhir** [novus/nvd3#1021]
Hello, 
Can some post the code for line-plus bar chart using sales-force analaytics api. I don't want the test json data to be shown in the chart, i want the data from the Matrix report(salesforce) to be shown on the chart. Like the below reference!
https://medium.com/salesforce-analytics/visualizing-salesforce-reports-with-d3-charts-c87517ab52b1

**Comment by liquidpele** [comment]
Lol... Are you asking someone to do your job?  ;)

**Comment by NSudhir** [comment]
Nope. i tried it on my end and i am not able to get 2 y axes. i am getting on one y axis for that. so i think there is a certain way to tweak the code(which i am using to parse the data from the report which i am not able to figure out). so that is what i mean actually.
https://jsfiddle.net/egLgaxc4/

**Comment by liquidpele** [comment]
You'll have to pull down the data from the salesforce api (I assume it's json, but even if xml or whatever it's the same) and then parse that into a json format that nvd3 expects... the format as shown in the example for the chart model in question:

http://nvd3-community.github.io/nvd3/examples/site.html

Essentially, you're going to have to have to transform the data into the appropriate json.

**Comment by liquidpele** [comment]
Oh, and as you might notice in the example code, it puts the bar on the left axis and the line on the right axis.  If you want to control which axis things go on, look at the multichart model.

**Comment by NSudhir** [comment]
ok i will take a look. Thank you.
