### ISSUE TITLE
How to delete Zoom (nv-context)  in LinePlusBarChart

### ISSUE THREAD

**Issue by ilariuss** [novus/nvd3#1030]
That's my problem, I need to delete nv-context, wheres the zoom places, like in the nvd3 example http://nvd3.org/examples/linePlusBar.html

I tried this method
<pre>
d3.select('#chart .nv-context').attr('visibility', 'hidden');
</pre>

But the functionality is still there.

I tried another option 
<pre>
 $('.nv-context').css('display', 'none')
</pre>

But, when the resolution changes, the responsive functionality makes the nv-context reappear.

Do you know how can I delete the zoom functionality in lineplusbarchart or, second option, how can I show bars and line in the same chart without zoom?

Thank you very much.

**Comment by ilariuss** [comment]
Ok, just solved watching the nvd3 library, as easy as .enableFocus(false)
<pre>
 var chart = nv.models.linePlusBarChart()
            .margin({ top: 30, right: 60, bottom: 50, left: 60 })
            .focusEnable(false)        
            .x(function (d, i) { return d.x })
            .y(function (d, i) { return d.y })
            .legendLeftAxisHint('(blabla)')
            .legendRightAxisHint('(blabla)')
            .noData('No data');
</pre>

**Comment by liquidpele** [comment]
Glad you figured it out, but also see the new docs :)

http://nvd3-community.github.io/nvd3/examples/documentation.html

**Comment by ilariuss** [comment]
Ooooooooooooh really thank you, I didn't know it.

**Comment by ilariuss** [comment]
FocusEnable I Meant

**Comment by guillim** [comment]
Also make sure you have:
`focusHeight = null`
otherwise you will have a resizing issue with the graph
