### ISSUE TITLE
LineChart Interactive and InteractiveGuide broken if x values are not sorted

### ISSUE THREAD

**Issue by cherokeejamessmith** [novus/nvd3#1035]
While the chart displays correctly, if the x values for any given series are not sorted, setting interactive or interactiveguide to true will result in only the first and last plot point becoming selectable. Also, the plot point selected is in the opposite direction on the x axis with respect to the mouse and the middle of the x axis. i.e. moving the mouse to the right half of the chart selects the first plot point on the left. Moving the mouse to the left half of the chart selects the last plot point on the right. This effects the tooltip in the same manner.

Example data:
```
		$scope.exampleData = [
			{
				key: "Series 1",
				values: [[1431550862000, 39.93], [1431550502000, 39.98], [1431550142000, 40.01], [1431549781000, 39.96], [1431549421000, 40.11]]
			}
		];
```

**Comment by liquidpele** [comment]
Yes, having he x values pre-sorted is a requirement for nvd3

**Comment by cherokeejamessmith** [comment]
Ahh, didn't see that in the documentation. Thanks!
