### ISSUE TITLE
Custom Graph background styling or specific point styling

### ISSUE THREAD

**Issue by yashutanna** [novus/nvd3#1037]
Hi all

I have been looking around for a while to change the background of a line graph to highlight specific ranges of the graph. for example, changing the background color of the chart under some value ```x```.

alternatively, I would like to change the styling of points that fall within this range. 

I've currently made a workaround in which i append a class to a point if it falls within some dynamic range, and can style that point accordingly. Although, a cleaner approach would be better suited. 

First prize, however would be to change the background of the graph in some ranges as below

![snip](https://cloud.githubusercontent.com/assets/6696871/7632881/20e4a42e-fa51-11e4-9a25-dd84acf7d3ff.PNG)

Please let me know if this is already a feature the I may have overlooked

**Comment by robinfhu** [comment]
Hi, we don't have this feature in NVD3 right now.  This is something you'll likely have to build yourself.  Many people fork NVD3 and add their own features to it.  

In order to do what you want, you likely need to append some svg rect elements to the chart and size them accordingly.
