### ISSUE TITLE
Tooltip doesn't work properly when using multiple charts

### ISSUE THREAD

**Issue by kartikb** [novus/nvd3#1041]
When I try to create multiple charts on a single web page and use the option useInteractiveGuideline(true) the tooltips don't show up correctly. They are all placed with respect to the first chart.

**Comment by liquidpele** [comment]
Use the development branch and see if that resolves your issue.  It has refactored tooltips.

**Comment by siliconalchemy** [comment]
Hi, I have the same problem - use multiple charts on a web page to display metrics with useInteractiveGuideline, and the tooltips all show relative not to the first chart but they only go down as far as the bottom of the page as it's rendered.  In other words if the page scrolls down with more charts past the initial scroll point, those tooltips all display at the point of the bottom of the screen before it's scrolled.

**Comment by liquidpele** [comment]
Please try the development branch or the v1.8.1-alpha tag, thanks.

**Comment by fnoopdogg** [comment]
Hi, this is from the development branch as of this morning.

**Comment by siliconalchemy** [comment]
Hi, this is from the development branch as of this morning.

**Comment by liquidpele** [comment]
Oh that's strange, I tested that at one point... Can you make a jsfiddle that demonstrates the issue?

**Comment by siliconalchemy** [comment]
Sure, I'll give it a go.  It's currently part of a large complex html template, so it might take me a while to isolate it.

**Comment by liquidpele** [comment]
Thanks!

**Comment by bwarren2** [comment]
I have hit this error as well, and replicated it in a [fiddle](https://jsfiddle.net/ye8Lbqqm/8/).

**Comment by kartikb** [comment]
@bwarren2 It seems fixed in your fiddle though..

**Comment by bwarren2** [comment]
When I mouseover the top 3 points in the second chart, I get no tooltip.  [This](http://imgur.com/a/I0eS2) is me mousing over the first chart, then a top point in the second chart.  Can you confirm what behavior you see?

I am using Firefox 38.0 on Ubuntu if it matters.

**Comment by liquidpele** [comment]
Seems to work for me... what browser/OS are you using?

**Comment by liquidpele** [comment]
Oh wait, you said that, doh

**Comment by kartikb** [comment]
Verified again it works fine.. I am on Chrome Version 43.0.2357.81 (64-bit)

**Comment by bwarren2** [comment]
Just tried Version 43.0.2357.125 unknown (64-bit) and it works.  I am not sure how to debug this sort of crossbrowser issue; in my cursory read, it doesn't look like nvd3 is using anything that is unevenly implemented.

**Comment by liquidpele** [comment]
Verified it doesn't work on FF on mac, looking into it.

**Comment by liquidpele** [comment]
Okay, so apparently firefox is not handling the ID name collisions for the voronoi clipping paths that d3 uses...   You can make it work by disabling the clipping for both charts, like so:

https://jsfiddle.net/ye8Lbqqm/10/

Notice I'm using the "showVoronoi(true)" option there just to make it display the hover-areas that it's using, for debugging purposes.   If you set clipVoronoi back to true then you'll see that for firefox it doesn't create the hover areas for many of the points in FF...   I'll have to play with options to work around this... probably just need to make the IDs unique per chart.

**Comment by liquidpele** [comment]
Fixed.

**Comment by bwarren2** [comment]
Can we push this into build/ for things like bower? :)

**Comment by liquidpele** [comment]
built again and pushed that up to master

**Comment by koote** [comment]
@liquidpele Hi liquidpele, I saw your fix was only in scatter.js, so did it mean your checkin fix the scatter chart only? I encountered the same issue in line chart had 10 lines, on FF & IE, Chrome didn't have this issue. 
I quick checked page source, pasted here, is it caused by the ID collision too? 

<g xmlns="http://www.w3.org/2000/svg" class="nv-point-paths">
    <path id="nv-path-0" style="fill: #e6e6e6; fill-opacity: 0.4; stroke: #c8c8c8; stroke-opacity: 1;" clip-path="url("#nv-clip-0")" d="M -10 170.682 L -10 171.221 L 30.1669 171.258 L 30.1664 170.806 L 30.1648 170.681 Z" />
    <path id="nv-path-1" style="fill: #e6e6e6; fill-opacity: 0.4; stroke: #c8c8c8; stroke-opacity: 1;" clip-path="url("#nv-clip-1")" d="M 30.1666 169.6 L 30.1667 169.874 L 31.759 169.873 L 90.5092 169.828 L 90.5053 169.603 Z" />
  .....
</g>
