### ISSUE TITLE
Next expected release date?

### ISSUE THREAD

**Issue by mpGitHub** [novus/nvd3#1044]
I noticed under "Milestones" the expected next release date no longer exists, but no official release has been posted.

I'm looking forward to some of the items in the Dev track.  Do we have a general idea when the next release date is expected?  

Thanks!

**Comment by liquidpele** [comment]
There is really only one bug left before the next release...  Unfortunately I'm dealing with life so its on hold... If anyone else wants to take a crack it is the last part of https://github.com/novus/nvd3/issues/971 ... See my last comment there.

**Comment by robinfhu** [comment]
@liquidpele I thought 'development' was getting merged to master.  Is that still happening?

**Comment by liquidpele** [comment]
Yea.  Moving though... I don't even have internet at home right now :p

**Comment by robinfhu** [comment]
I understand.  Things are busy at work so I have limited time as well.

**Comment by jjzazuet** [comment]
Hello again guys. So any news on this?

I might as well bake a cake with the merge happens XD. Cheers!

**Comment by liquidpele** [comment]
Released.

**Comment by mpGitHub** [comment]
Excellent, looking forward to checking this out.  I hope your move went well!

**Comment by jjzazuet** [comment]
Likewise. Hope the move ended well man. Also, please update the npm registry as well.

https://www.npmjs.com/search?q=nvd3

Thanks so much for your time and help guys! This is an *awesome* library. Cheers!
