### ISSUE TITLE
chart.interactiveLayer.tooltip.chartContainer() Not Functional?

### ISSUE THREAD

**Issue by iamwillburn** [novus/nvd3#1047]
I have a line chart which is contained in a div with overflow-x set to hidden.

As a result the tooltip is clipped when the mouse is hovering over the right edge of the chart.

I tried the following in the hope that it would cause the tooltip to see the container as the bounding area, but it had no effect (I can only assume I'm doing something incorrect, #mainChart is certainly not clipped by the overflow: hidden):
```
chart.interactiveLayer.tooltip.chartContainer(d3.select('#mainChart'))
```

Any help would be greatly appreciated.

**Comment by liquidpele** [comment]
Yea, it probably gets overwritten again.  For instance, if you look in the lineChart.js model, you see:

                interactiveLayer.tooltip
                    .position({left: e.mouseX + margin.left, top: e.mouseY + margin.top})
                    .chartContainer(that.parentNode)
                    etc etc etc

**Comment by iamwillburn** [comment]
Thanks for pointing me in the right direction.

I'd ideally have avoided it, but as it was the only way I could get a behaviour similar to what I want, I ended up changing that specific line of code to:
```
.chartContainer(document.body)
```
The tooltip no longer clips as it exists outside of the overflow:hidden element.

**Comment by hc000** [comment]
Is there anyway to set the chartContainer setting without modifying the library manually?
I noticed in the code several lines have it hard coded it to .chartContainer(that.parentNode)
