### ISSUE TITLE
publish nvd3 to npm. Currently npm has the wrong repo / project.

### ISSUE THREAD

**Issue by KSoto** [novus/nvd3#1048]
The other issue that is similar to this one is closed, so I opened a new one :)

The current package listed as "nvd3" on npm links to this project:
https://github.com/tjwebb/nvd3/blob/master/package.json

when it should link to this project:
https://github.com/novus/nvd3/blob/master/package.json

Notice that both package.json's list the "**name**" as "**nvd3**", however the one from "**tjwebb**" has **0 followers** and the one from "**novus**" (this one) has **3,751 followers**. 

I would love to do "***npm install nvd3***", however the name "nvd3" is already taken, and by the **wrong project**! (see https://www.npmjs.com/package/nvd3 )

I read the "package disputes" section from npm and it says to email tjwebb at me@traviswebb.com and ask him to rename his project or take it down ( see https://www.npmjs.com/policies/disputes ).

After that, you can publish by running "npm publish" (see https://docs.npmjs.com/cli/publish and https://gist.github.com/coolaj86/1318304 )

Thanks!

**Comment by liquidpele** [comment]
I sent the email and CC'd relevant parties.

**Comment by KSoto** [comment]
awesome, thank you @liquidpele ! ^-^

**Comment by liquidpele** [comment]
Yup, thanks for letting us know about it.  We *are* registered with bower IIRC though...

**Comment by KSoto** [comment]
Hah that's true! :)

**Comment by luisrudge** [comment]
pleeeeeeeeeeease make it happen :)

**Comment by luisrudge** [comment]
any news @liquidpele?

**Comment by liquidpele** [comment]
Nope.

**Comment by luisrudge** [comment]
Here's d3's package.json. They have a release model like yours.
https://github.com/mbostock/d3/blob/master/package.json

**Comment by tjwebb** [comment]
Yea, I published this awhile ago because nvd3 project seemed to only care about bower support.

Let me know who I should add as an owner and you can publish official versions hereafter.

**Comment by robinfhu** [comment]
@liquidpele  should at least be one of the owners.

**Comment by luisrudge** [comment]
awesome @tjwebb. Thanks for that! I think the npm command is `npm owner add username`

**Comment by liquidpele** [comment]
Well, i registered myself at npmjs:   https://www.npmjs.com/~liquidpele

Not too familiar with it though, can he add me as a contributor there?  I thought it just used the github url for all that info and that he'd have to unregister the nvd3 name and let us register it after that...

**Comment by luisrudge** [comment]
@liquidpele yes! @tjwebb can add you as an owner and then you'll be able to push it to npm.

npm has its own registry, but you still can use a package from github. `npm install novus/nvd3` would work too, but it's less discoverable.

**Comment by jjzazuet** [comment]
Any news on this one? I'm still getting version 1.1.15-beta2 version in the NPM registry. Thanks!

**Comment by liquidpele** [comment]
When I log into npmjs it says "0 Packages by liquidpele" so I assume I don't have access to the nvd3 package to change anything...  @tjwebb were you adding me, or is there something I need to do still, or can you change it to point to the main novus repo?

**Comment by liquidpele** [comment]
Okay, the npmjs people gave me the nvd3 name, so I published the novus code, should be good now?  Can someone verify?  https://www.npmjs.com/package/nvd3

**Comment by danielsneijers** [comment]
I just installed it from npm and it's working correctly
