### ISSUE TITLE
LESS Compilation?

### ISSUE THREAD

**Issue by bwarren2** [novus/nvd3#1061]
Is there interest in a factoring of the given CSS that uses LESS and some variables?  I am annealing NVD3 into my project, and working to make my tweaks more sustainable.

**Comment by liquidpele** [comment]
I'm a fan of less and scss but honestly I don't think this project is big/complicated enough for there to be a real benefit...

**Comment by bwarren2** [comment]
Personally, [this](https://gist.github.com/bwarren2/3b4b0956ae335f06d3bb) fits my brain better than [this](https://gist.github.com/bwarren2/37490d66d7fb567f2ffc), but you are right that it adds complexity for what is a pretty short css file already.
