### ISSUE TITLE
Extending charts?

### ISSUE THREAD

**Issue by illume** [novus/nvd3#1063]
Hello,

is there a recommend way to extend the charts?

There's a few things I do with d3 at the moment, just drawing on the charts. Drawing lines on some bar charts at certain levels, having some text show pointing at some things, and such.

The problem with this approach is that things don't resize, and it feels a bit hacky.

How should I extend charts?

**Comment by liquidpele** [comment]
Hmm... well we do use d3 signals in several cases, iirc there is a "finished rendering" one, so you could hook onto that to then do/redo your custom drawing stuff on the svg.

**Comment by robinfhu** [comment]
Extending basically involves forking the NVD3 repo and just adding the functionality you need into the code directly.  We don't have that many 'hooks' into the rendering logic unfortunately.  It's a good chance to learn how NVD3 works too!

**Comment by illume** [comment]
Thanks for the tips :)
