### ISSUE TITLE
nv.addGraph hijacking loop variable

### ISSUE THREAD

**Issue by c23gooey** [novus/nvd3#1064]
Hi there,

We are using nv.addGraph within a JS for loop - eg: for(var i=0;i<max;i++){...}

The loop variable "i" is used to define the element where the graph will be drawn - eg: $('#graph_'+i)

When i==0, nv.addGraph seems to be hijacking the variable and replacing its value. Doesnt seem to be happening with other values of i.

eg:

for(var i=0;i<max;i++){

console.log(i) // 0

nv.addGraph(function(){
  console.log(i) // 3
});

}

**Comment by robinfhu** [comment]
This has to do with JavaScript closures.  You likely need to create a closure:

     for(var i=0;i<max;i++){

        console.log(i) // 0

        (function(index) {
        nv.addGraph(function(){
             console.log(index) // 3
       });
       })(i);

    }
