### ISSUE TITLE
Chatroom?

### ISSUE THREAD

**Issue by bwarren2** [novus/nvd3#1066]
Is there an IRC or Gitter room for this project?  Having a venue for bouncing ideas around would be helpful that is less formal/obtrusive than the issue tracker would be nice.  

An example low-impact issue: would it be good to store availableHeight in the height var if height goes unset in discreteBarChart.js?  I am writing a transition to reorder and resize the bars of that chart, and I am having to calculate rect height as availableHeight - y(d.value); having the height the plot field would be helpful here.  Alternatively, if there is a better way to do this, a chatroom might be a better way of discovering it.

**Comment by liquidpele** [comment]
Chat is fast paced... Way faster than this small project.  Sometimes we can't respond for days....   I think the issue tracker is better suited myself.

**Comment by bwarren2** [comment]
OK, just wanted to make sure I was as nondisruptive as possible :) .  

For the low impact issue, what is the best way of redrawing bar heights?  I am currently using [this code](https://gist.github.com/bwarren2/62cf905052ca77dba712), but the magic [205](https://gist.github.com/bwarren2/62cf905052ca77dba712#file-gistfile1-js-L76) in calculating the new rect heights bothers me.  Is there a better way?

**Comment by bwarren2** [comment]
Closing for now.  I think the height storage code should function differently than it does, but do not have enough perspective to say so confidently.

**Comment by QuantumInformation** [comment]
Would love a chat room, just to bounce off ideas and questions with users. Most big open source projects have them and they have 0 cost to implement.

**Comment by KidA78** [comment]
@QuantumInformation @liquidpele 
I'd hang out in an IRC chatroom for NVD3 if it was available.  Maybe more for peer to peer guidance.
Although this couldn't all sit on one person's shoulders.  What often happens is you have a handful of people asking questions and zero giving answers.  It's just a matter of setting the tone for this kind of endeavor.

At any rate, @QuantumInformation +1 to bringing this up again.

**Comment by QuantumInformation** [comment]
Thx, I've been trying to solve an issue and I just signed up with the D3 slack channel, but the is only 1 other person online in the nvd3 room.

**Comment by KidA78** [comment]
@QuantumInformation is there an NVD3 Issue thread open with your problem?

**Comment by KidA78** [comment]
@QuantumInformation how does one join?  I don't see any register link anywhere.  I'm happy to join the nvd3 channel.

**Comment by QuantumInformation** [comment]
Its here:
https://d3js.slack.com/

**Comment by QuantumInformation** [comment]
I've posted here: https://d3js.slack.com/messages/nvd3/details/
The issue I'm having is that this doesn't do anything:
https://github.com/quantumjs/atmospheric-diagnostics/blob/master/src/AtmosphericDiagnostics.ts#L61

Even though my data arrives fine:

![image](https://cloud.githubusercontent.com/assets/216566/22997481/6c3c3b7a-f3ca-11e6-9f79-e0dd709f7686.png)

**Comment by KidA78** [comment]
Gotcha, it says just to contact an admin with no other info.  I sent a note to Mike Bostock directly, hopefully he can register me. 

<img width="449" alt="screen shot 2017-02-15 at 1 58 04 pm" src="https://cloud.githubusercontent.com/assets/1584090/22997346/d4b34bf6-f386-11e6-8034-cd0412507c91.png">

**Comment by liquidpele** [comment]
Yea I love slack but the invite only part makes it kind of unreasonable for easy chats.

**Comment by KidA78** [comment]
@QuantumInformation I'll check out your code in the meantime.  
No errors in the console?  
Could you expand the format of the data in `data.list`?

**Comment by QuantumInformation** [comment]
list:
![image](https://cloud.githubusercontent.com/assets/216566/22997772/b005f534-f3cb-11e6-802d-38820d56e47e.png)



![image](https://cloud.githubusercontent.com/assets/216566/22997743/994737ae-f3cb-11e6-9659-21ea114363ab.png)

**Comment by QuantumInformation** [comment]
No errors

**Comment by QuantumInformation** [comment]
The annon fn  in addGraph never seems to be excecuted

**Comment by liquidpele** [comment]
Please move discussion of a problem to a new open issue.

**Comment by QuantumInformation** [comment]
Ok, I didn't feel it warranted it because I was using typescript and might have something common but not an issue.

**Comment by liquidpele** [comment]
Opening issues is actually very helpful because others can find the discussions with a Google search so feel free to open any but it is just helpful to keep each discussion in a separate thread

**Comment by QuantumInformation** [comment]
@KidA78 this is how I got an invite: https://d3-slackin.herokuapp.com/

**Comment by KidA78** [comment]
@QuantumInformation I have some ideas and I think it's related to data format. Either way I'll share in slack when I get in, or if you create an issue here, that way others who are reading can benefit.   Up to you.

**Comment by QuantumInformation** [comment]
https://github.com/novus/nvd3/issues/1964
