### ISSUE TITLE
Best places to contribute?

### ISSUE THREAD

**Issue by bwarren2** [novus/nvd3#1072]
I really like nvd3 and want to help.  Are there particular bugs or extensions I could take a crack at?  I did not find much tagged for the 2.0 branch, so I don't know what is superceded by that/what to do to contribute to that branch.

**Comment by bwarren2** [comment]
Is JSDoc a good avenue to pursue?  Example-by-documentation is helpful, but conceptual documentation would also be useful (rather than forcing any novices to dive straight into the code).

**Comment by robinfhu** [comment]
I actually think diving into the code is the best place to start.  

One way I've learned d3, is to try building my own charting library (https://github.com/robinfhu/forest-d3).  By doing this, I learned about all the nuances that go into charting (like margins, width, height, transitions).

**Comment by liquidpele** [comment]
Hey there @bwarren2, just check out the latest from the master branch and get it building using the instructions from our readme, then you can look at the different models we have the logic split into...  if you're looking for issues, just view our nice big issues backlog :p
