### ISSUE TITLE
master is now the dev branch

### ISSUE THREAD

**Issue by liquidpele** [novus/nvd3#1075]
I merged everything into master, it is now the dev branch.  Any pull requests to development should be accepted then merged into master, but all new stuff should hopefully go to master like other projects to avoid confusion/etc.  I also put up a description of 1.8.1-alpha, and honestly I'm ready to just release it and fix any further bugs in another point release unless anyone objects...

**Comment by robinfhu** [comment]
Awesome, was wondering when this would happen :-)

**Comment by liquidpele** [comment]
So any objections to cutting 1.8.1?   There is a decent backlog of issues and pull requests now, so I'm a bit afraid to start that and introduce more bugs before the release...

**Comment by robinfhu** [comment]
@liquidpele  I think you're doing an excellent job taking over this project.  I don't object, and mainly because issues always arise (other open source charting libraries are the same, tons of issues).

**Comment by liquidpele** [comment]
I have made it so.
