### ISSUE TITLE
SVG height width 100% messing with the page layout

### ISSUE THREAD

**Issue by kartikb** [novus/nvd3#1084]
The CSS file is applying styles to global svg elements. This does affect other svg elements in the layout. Can we move the CSS for svg inside the .nvd3-svg block?

**Comment by liquidpele** [comment]
Should already be in latest version..

**Comment by kartikb** [comment]
yeah just realized that.. I see that in 1.7.1 it is not there in the minified version.. If I just use the minified css file instead will that harm in any way? Why were those styles added anyway?

**Comment by liquidpele** [comment]
Uh oh... Hmm, maybe making the minified CSS is messed up then....

**Comment by kartikb** [comment]
Can you have a look at the minified CSS in 1.7.1 and verify if it is usable or not?

**Comment by liquidpele** [comment]
But yea both css files should be the same logic.

**Comment by liquidpele** [comment]
Latest version is 1.8.1

**Comment by kartikb** [comment]
Its a development version.. I would prefer to wait for a stable release before I upgrade..

**Comment by liquidpele** [comment]
no it was released the other day as a full version

**Comment by kartikb** [comment]
oh yeah just saw that.. cool I will upgrade in that case..

**Comment by kartikb** [comment]
thanks
