### ISSUE TITLE
tooltip doesn't follow mouse in IE9...

### ISSUE THREAD

**Issue by jmensch1** [novus/nvd3#1085]
...because IE9 needs the vendor prefix for the css transform.  You can fix by adding one line at the code starting at line 741 in version 1.8.1:

.style('-webkit-transform', new_translate)
.style('-ms-transform', new_translate)           // new line
.style('opacity', 1);

Not that anyone should have to care about IE9

**Comment by liquidpele** [comment]
Seems like a simple fix with low risk, even though it's IE9
