### ISSUE TITLE
Wrong Tooltip positioning with Interactive Guideline

### ISSUE THREAD

**Issue by RenatoUtsch** [novus/nvd3#1088]
The new tooltip has had this problem since it was introduced. With the Interactive Guideline activated, if you create two charts the tooltip of the second chart will be wrongly positioned.

Here a jsfiddle demonstrating the problem:
http://jsfiddle.net/RenatoUtsch/43dhk8wp/

I know that 1.8.1-alpha isn't the latest version, but the cdnjs didn't have a newer version, and this still happens in the latest master commit.

**Comment by liquidpele** [comment]
Hmm, the 2nd tooltip shows up but stays at the very top of the chart instead of moving up and down like the first one...  thus not a critical bug, but certainly something that should be fixed.

**Comment by liquidpele** [comment]
Also, it's easier to use http://rawgit.com for examples, you can get a link to the latest code in master that way :)

**Comment by RenatoUtsch** [comment]
Oh, true. I'll keep that in mind.

This is kind of problematic, because on my web page if I display more than one chart at the same time either the tooltips are moved to the extreme top or to the extreme bottom.

And it seems that this happens with the first chart too:
![screen shot 2015-06-22 at 2 08 57 pm](https://cloud.githubusercontent.com/assets/836333/8287761/48695412-18e8-11e5-856c-991c8db9d44c.png)

I just added a lot of <p>.</p> after the script and the result was that.

**Comment by RenatoUtsch** [comment]
Discovered the cause of the problem. The tooltip is only positioned incorrectly if you add the SVGs directly to the body or to the same div. If you put each svg inside a different div, the tooltip is rendered correctly.

**Comment by liquidpele** [comment]
Yea, that would do it... the interactive guideline stores the tooltip in the svg's container div, so they would conflict if you didn't have them in separate containers.

**Comment by liquidpele** [comment]
Interesting that you said it worked before though... I tried not to change anything about the interactive guideline...

**Comment by RenatoUtsch** [comment]
Sorry, my bad. Without a div (with the svg directly on the body) it doesn't work with only one SVG also. I thought it was correct because I was rendering the chart at the top of the page. Putting the svg in the middle of the page directly in the body renders it incorrectly.
