### ISSUE TITLE
Hovering over the graph with any tooltip enabled gives an undefined error.

### ISSUE THREAD

**Issue by kartikb** [novus/nvd3#1089]
I just upgraded to 1.8.1 and all the tooltip stopped working. I see an error in the console. Please have a look at the screenshot attached.

**Comment by kartikb** [comment]
![screen shot 2015-06-22 at 10 09 58 am](https://cloud.githubusercontent.com/assets/10504334/8287818/254d96f8-18c7-11e5-9d4f-77ec9740ff24.png)

**Comment by liquidpele** [comment]
Well, it's one of two things:

1. As stated in the 1.8.1 changes, Tooltips were refactored - If you have customized your tooltips, note that you may need to adjust your custom functions as the data passed has changed format. See the new tooltip options in the documentation.  
2. It's a browser-specific problem, what browser/OS are you using?

Also, if you can make a jsfiddle that demonstrates the problem then that speeds up our ability to fix it a lot.

**Comment by liquidpele** [comment]
I saw this issue a bit ago, it's from an old d3 version.   Upgrade d3 to the min required version for nvd3.

**Comment by liquidpele** [comment]
uncaught TypeError:  n.interrupt is not a function

That was the error in text so google will find it :)

**Comment by kartikb** [comment]
yup you are correct.. tooltip.interrupt function is added in the newer versions of d3 and it is being used in 1.8.1 version of nvd3.

**Comment by liquidpele** [comment]
Looks like it was added in 3.3: 

https://github.com/mbostock/d3/pull/1458

min required version for nvd3 is 3.4.4

**Comment by kartikb** [comment]
Yeah upgrading the library fixes the issue. This can be closed.

**Comment by kartikb** [comment]
nvm its already closed :P
