### ISSUE TITLE
Very slow performance on Firefox

### ISSUE THREAD

**Issue by greenafrican** [novus/nvd3#1098]
Have a look at this chart https://s3-eu-west-1.amazonaws.com/graphflow-public/nvd3-example.html on Chrome and Firefox. Almost unusable on FF.

Am I doing something wrong / are there any tricks for better performance on FF?

**Comment by liquidpele** [comment]
Seems fine to me on FF on mac...   anyone else reproduce the slowness?

**Comment by greenafrican** [comment]
Not sure what was going on. Back from the office and it seems ok now. Still not Chrome quick but D3 never is. I'll close for now.
