### ISSUE TITLE
why is every second tick in the x axis set to opacity 0?

### ISSUE THREAD

**Issue by gb5256** [novus/nvd3#1101]
Hi there.
I have a very basic bar chart.

```
   var chart = nv.models.multiBarChart()
        .x(function (d) {
            return d[dataLabel]
        })    //Specify the data accessors.
        .y(function (d) {
            return d[dataValue]
        })
        .barColor([data_fill])
        .duration(300)
        .margin({left:margin.left,right:margin.right,top:100,bottom:80})
        .rotateLabels(45)
        .height(height)
        .showLegend(false)
        ;
```

But somehow every second bar has no label in the x-axis.
Looking at the html output, you can see that every sedond line and text has a opacity of zero:
![screen shot 2015-06-27 at 12 15 54](https://cloud.githubusercontent.com/assets/324658/8391523/926bda8a-1cc6-11e5-8b8b-4ec051b5ec37.png)
How can I change that?

**Comment by liquidpele** [comment]
the "zero" class should only be on the x and y axis itself (so if you're viewing negative numbers too and the regular lines don't line up exactly with the zeros then you can show it if you want).

To show it, just override the CSS:

    .nvd3-svg zero text{ opacity: 1 !important; }

**Comment by gb5256** [comment]
@liquidpele I do not understand what you mean.
I am using the standard CSS without any changes. I have not mentioned the zero anywhere.
The bar chart is as shown above.
Why is this behavoiur happening?

**Comment by liquidpele** [comment]
Can you provide a jsfiddle with an example to show what you mean then?

**Comment by gb5256** [comment]
@liquidpele 
Please check  this fiddle:
http://jsfiddle.net/fq7u3mqc/10/
The fiddle uses the css and the js right from the nvd3 github master.
So there are no changes or other scripts involved.
There you can see that only 2 of the labels on the x-axis are shown. All the others have a opactiy set to zero. I just would like to understand what the idea behind this behaviour is.

**Comment by crissty** [comment]
Hello
I have this problem, Did you get the solution?
I am not able to find why this behavior.

The odd x-axis labels have css online with opacity 0, and the pairs labels with opacity 1. I dont know in what moment this is applied.
Thanks!!

**Comment by k2ibegin** [comment]
same problem.. does anyone got a solution to this ? i am using angular and in my project dont have a css file separately , i set css via style tag in my html element, but in this case where to set this css with opacity 1 ? odd ones are coming with opacity 0 and even ones with 1

**Comment by k2ibegin** [comment]
@crissty i am having same issue, wrapping my head around it but no lead. Do you remember how did you solve this ?

**Comment by k2ibegin** [comment]
found it here .. 

just so that everyone can get it done quicker 

https://stackoverflow.com/questions/17101352/multibar-chart-with-nvd3-d3-only-shows-labels-for-every-other-tick-on-the-x-ax/17102125
