### ISSUE TITLE
Any way to make the Horizontal Multi-Bar vertical?

### ISSUE THREAD

**Issue by wry791** [novus/nvd3#1102]
I need to have the chart value label display when grouped. Don't need the stacked feature.  Stacked/Grouped Multi-Bar Chart don't have the ability to show the label with the value.

**Comment by liquidpele** [comment]
Yes that is not a feature for multibar currently, and I'm not sure it's valid for more than one series anyway since it would have to overlap then and it's much easier to rely on the axis and tooltip.   However, if you make a solution then send us a pull request and we'll check it out, cheers!

**Comment by elad** [comment]
I'd like a stack vertical multi-bar. :)

Good to know it doesn't exist though so I'll see if I can find the time to copy/paste the horizontal code and adjust it accordingly...
