### ISSUE TITLE
Labeling on the top of bar charts

### ISSUE THREAD

**Issue by jshek** [novus/nvd3#1105]
Hi,

   Is there a way to put a label on top of the nvd3 multi-bar charts?

Thanks

**Comment by liquidpele** [comment]
Not currently.

**Comment by jshek** [comment]
Hi Pele,

    Do you provide consulting services?  We have a client who is asking for this and we need to provide a solution ASAP.

Thanks

**Comment by liquidpele** [comment]
I'm not set up for consulting currently.... Sorry!  

The novus guys might, not sure honestly...

**Comment by liquidpele** [comment]
Oh, also discreteBarChart has that option if you were not aware.
