### ISSUE TITLE
How to disable auto sort on xasis nvd3 chart ?

### ISSUE THREAD

**Issue by khs123** [novus/nvd3#1110]
Hi all , Im a newbie .Now , im using nvd3 chart to create dashboard display page, but i have a issues , nvd3 line chart auto sort array value xAxis. Example: origin array --> [8,1,4,6] but nvd3 line chart display [1,4,6,8] but i dont want it . How to disable this function ? 
Thank all

**Comment by liquidpele** [comment]
Nvd3 expects the x values to be in order
