### ISSUE TITLE
Scatter Plot cannot show all the points

### ISSUE THREAD

**Issue by adamaiken89** [novus/nvd3#1111]
When I tried to display the keys with the same name, only one set of data can be shown. It worked fine in the previous version of nvd3.js

![screen shot 2015-06-30 at 2 11 23 pm](https://cloud.githubusercontent.com/assets/6821806/8424823/fe2d219e-1f31-11e5-920d-ba2e6f7bbcb8.png)

**Comment by liquidpele** [comment]
Why is that a valid use case??

**Comment by Aiken00** [comment]
Thank you for the reply.

My graph keys are input by different users. It is possible in my case that different users can input the same key for the same kind of projects

**Comment by liquidpele** [comment]
You might want to add _1 _2 etc to duplicates then...   Or if you really want it fixed feel free to fix and send us a pull request, but this is pretty edge case for us and not a big priority...
