### ISSUE TITLE
MultiBarChart stacked shows 1px bar height if value == 0

### ISSUE THREAD

**Issue by devilicecream** [novus/nvd3#1121]
![nvd3](https://cloud.githubusercontent.com/assets/2878227/8506120/afc1bd0a-21b9-11e5-93a7-533f27180555.png)

**Comment by liquidpele** [comment]
pending on the pull request.

**Comment by devilicecream** [comment]
Sorry for the late response. I'll set up the jsfiddle and I'll link it here.
