### ISSUE TITLE
tooltip with 'w' gravity jumps down when it hits top of window

### ISSUE THREAD

**Issue by jmensch1** [novus/nvd3#1124]
I'm using the tooltip with the default 'w' gravity, and when the tooltip hits the top of the window, it jumps down below the mouse instead of hugging the top of the window.  I found the problem in the code that calculates the tooltip position (starting at line 664 in version 1.8.1 dated 2015-06-17) -- 

```
switch (gravity) {
    case 'e':
        left = pos[0] - width - distance;
        top = pos[1] - (height / 2);
        tLeft = tooltipLeft(tooltipElem);
        tTop = tooltipTop(tooltipElem);
        if (tLeft < scrollLeft) left = pos[0] + distance > scrollLeft ? pos[0] + distance : scrollLeft - tLeft + left;
        if (tTop < scrollTop) top = scrollTop - tTop + top;     // LINE A
        if (tTop + height > scrollTop + windowHeight) top = scrollTop + windowHeight - tTop + top - height;
        break;
    case 'w':
        left = pos[0] + distance;
        top = pos[1] - (height / 2);
        tLeft = tooltipLeft(tooltipElem);
        tTop = tooltipTop(tooltipElem);
        if (tLeft + width > windowWidth) left = pos[0] - width - distance;
        if (tTop < scrollTop) top = scrollTop + 5;       // LINE B
        if (tTop + height > scrollTop + windowHeight) top = scrollTop + windowHeight - tTop + top - height;
        break;
```

Notice that the formula for calculating top is different for 'e' and 'w' (compare Line A with Line B).  To fix the problem, I simply made Line B the same as Line A, so Line B is now:

``` 
if (tTop < scrollTop) top = scrollTop - tTop + top;  
```

This fixed the issue in all browsers.

Thanks for your great work on this library, my client is very happy with it.

**Comment by liquidpele** [comment]
Hey there!   Can you send us a pull request with the fix?

**Comment by jmensch1** [comment]
Done!  Although it's saying something about a travis build error

**Comment by liquidpele** [comment]
You can ignore the travis build error... I broke the unit tests earlier today apparently :/

**Comment by RenatoUtsch** [comment]
Should this be closed?
