### ISSUE TITLE
Hovering over data-point in stackedAreaChart (interactiveGuideline) doesn't work in IE

### ISSUE THREAD

**Issue by lucaslin** [novus/nvd3#1125]
Not sure if this is already known, but in IE in stackedAreaChart, hovering over a point causes the point to stop being highlighted and the interactiveGuideline and tooltip to go away. This seems to happen on both master and dev versions.

http://plnkr.co/edit/RGxg04vhFvGl3uLTJ3Cy?p=preview

**Comment by liquidpele** [comment]
What version of IE?

**Comment by liquidpele** [comment]
confirmed with your verison, but works fine on latest code:   http://plnkr.co/edit/ugTe5V8ThmlSrXy2SV5T?p=preview
