### ISSUE TITLE
Colors not assigned properly in MultiBarChart, 1.8.1 minified

### ISSUE THREAD

**Issue by mrinx** [novus/nvd3#1126]
There is a problem in the minified 1.8.1 version of the library. When I create a multi bar chart and then toggle different datasets, the colors of the bars don't correspond with ones on the legend.

It works just fine with the non-minified version.

**Comment by FollonB** [comment]
It happens to me too. However, I can't get it to work with the non-minified version either.

Are you sure it is the 1.8.1 version you have non-minified?

**Comment by liquidpele** [comment]
If you're using master, then that's not 1.8.1 and it had some bugs that I just reverted.    If you want the actual stable branches, please use the tags.

**Comment by FollonB** [comment]
Thank you very much, the tag works perfectly.
Sorry for bothering.
