### ISSUE TITLE
Interactive guideline/tooltip showing strange results when data has gaps

### ISSUE THREAD

**Issue by dchurchill00** [novus/nvd3#1129]
I'm trying to show a simple line chart with a few series of data. The x axis represents dates (formatted ticks) while the y axis will just be arbitrary numbers for this case.

The data I have coming in may not have points for every date displayed on the graph, resulting in some gaps in the series. The line graph renders this perfectly fine by just connecting the 2 nearest points. The tooltip from the interactive guideline however seems to be drawing data from points nearest to where the user is mouse-hovering rather than omitting the series that don't have data for that point on the x axis. Furthermore, the title of the tooltip seems to be based on the nearest data point of the first data series, which results in incorrect dates in the popup in relation to where the user is mouse-hovering.

Here's an example of what I'm seeing:
![nvd3-tooltip-example](https://cloud.githubusercontent.com/assets/13276463/8622846/18fabdd8-26f3-11e5-85e9-dccabdaff31f.png)

The mouse cursor hovers over the single Series 2 point at 05/01. The tooltip does show the correct data for Series 2, but it's also  showing Series 1 and Series 3 data on totally different x-ticks. The title also is showing 05/03, which I gather is because that's Series 1's nearest point.

The same will happen on 05/04, where Series 2 will show the appropriate point, but Series 1 and 3 will also display with their nearest points on different dates. The label will jump between 05/03 and 05/05 depending on which side of 05/04 the mouse cursor is hovering.

Is there a way to tell the tooltip to only display data for the tick it's currently snapped to? I'm using this graph for customers looking at lab results for particular dates and currently the graph is going to give them very confusing popup results with this behavior of snapping to the nearest point instead of just omitting it if it's not there for the x-value in question.

Here's the JSFiddle from the screenshot: http://jsfiddle.net/hz1emh79/1/

Any assistance in this matter would be greatly appreciated. Aside from this little snag I'm really enjoying nvd3!

**Comment by liquidpele** [comment]
I updated the fiddle to include d3 so it worked, and to use the latest nvd3 code instead of the old old old code.   

https://jsfiddle.net/hz1emh79/2/

I think the interactive guideline currently assumes data for each series, as it'll try to find the nearest point for each thing...  however, I seem to remember someone changing the stacked area chart to be able to handle blank spots?    If you wanted to fok and change the behavior and send us a pull request we would certainly take a look :)

**Comment by jenicar** [comment]
@dchurchill00 
I've just come across this too... did you ever find a work around for this?
