### ISSUE TITLE
[Feature Request] Adding event points/ticks to a line chart

### ISSUE THREAD

**Issue by arjun010** [novus/nvd3#1132]
I was wondering if there was an option to add event points/ticks to a line chart.

For example, in a line chart where the x-axis ranges from 10.00AM-11.00AM. If one could add events at 10.15 am and 10.45 am, and then represent this event on the line chart using a point or a colored tick indicating an event at that point in time, it would be really helpful since this is a very common use case for time-series charts.

**Comment by liquidpele** [comment]
Nope, feel free to code it up and send us a pull request if you want and we'll take a look.   Cheers.

**Comment by arjun010** [comment]
I just used the chart.xAxis.tickValues() and a bit of css to get the job done.
Thanks.
