### ISSUE TITLE
Meteor nvD3 version 1.7.1

### ISSUE THREAD

**Issue by dohomi** [novus/nvd3#1134]
Hi Guys,

I just tried your package within a custom package and think that the ```Meteor```package is not up-to-date to 1.8.1 - with ```meteor add nvd3:nvd3```only 1.7.1 is getting installed. Does anybody knows if something went wrong with the package? Thanks

**Comment by liquidpele** [comment]
No idea, someone submitted the meteor thing, I'm not familiar with it.   If you take a look and see what's wrong, send us a pull request to fix it...

**Comment by dohomi** [comment]
Hi @liquidpele this issue might happen because the newest version is not marked as latest version? If I open the https://github.com/novus/nvd3/releases the latest stable release is ```1.7.1```.

**Comment by liquidpele** [comment]
oh, could be...  I made an v1.8.1 release:

https://github.com/novus/nvd3/releases/tag/v1.8.1

**Comment by dohomi** [comment]
Thanks for checking on this. I haven't seen an update on atmosphere yet but maybe it just takes a little while:
https://atmospherejs.com/nvd3/nvd3
