### ISSUE TITLE
Critical bug with the guidelined tooltip when scrolling

### ISSUE THREAD

**Issue by RenatoUtsch** [novus/nvd3#1138]
If the element that does the scrolling is not the body, the tooltip gets all buggy:
http://jsfiddle.net/RenatoUtsch/h4rvoehd/2/

Also, this only happens with the interactive guideline. Without it the tooltip is positioned correctly (as in the example).

**Comment by liquidpele** [comment]
huh, that's weird...

**Comment by jlwerenskjold** [comment]
I've noticed this but haven't had any success in fixing it yet. I have two different graphs on the same page  and while the first (top) graph's tooltip works fine the second (bottom) graph's tooltip is anchored on the bottom of the screen, just like the jsfiddle.

**Comment by RenatoUtsch** [comment]
Located where the bug is. It is in the gravity calculation:
https://github.com/novus/nvd3/blob/master/src/tooltip.js#L193

If you check the top and left values of the "pos" variable, everything is right. But when you check the "left"and "top" variables produced by this gravity switch, the height is wrong.

**Comment by RenatoUtsch** [comment]
The exact line where the bug happens is line 210 (for the 'w' gravity):
https://github.com/novus/nvd3/blob/master/src/tooltip.js#L210

**Comment by liquidpele** [comment]
We just merged this change recently, is it related? 

https://github.com/novus/nvd3/pull/1140/files

**Comment by RenatoUtsch** [comment]
No, because the last if's condition has no relation to what is executed in the loop before it.

**Comment by RenatoUtsch** [comment]
#1184 has a fix for one of the bugs causing this. The other is a bug in d3.mouse, so it isn't related to nvd3.

**Comment by RenatoUtsch** [comment]
This is fixed by #1190.

**Comment by kouddy** [comment]
I notice same problems too. Thanks for the fix.

**Comment by OctavioBR** [comment]
Thanks a lot for the fix Renato, tooltips works far better now. Valeu
