### ISSUE TITLE
LineChart livecode example doesn't give the full code

### ISSUE THREAD

**Issue by fresheneesz** [novus/nvd3#1143]
When trying out the code from the linechart example at  http://nvd3.org/livecode/index.html , I get a chart that looks like this:

![linechartincomplete](https://cloud.githubusercontent.com/assets/149531/8713136/e77fcb06-2b19-11e5-9c71-6021cb665d93.png)

While the version on the site looks like this:

![linechartfull](https://cloud.githubusercontent.com/assets/149531/8713154/28ea23ac-2b1a-11e5-8d07-1a2e1eccf8bc.png)

I'm using the code, data, and markup (what little there is) to render the graph, so I'm wondering what code is missing to make mine look like the example?

**Comment by fresheneesz** [comment]
nm, i didn't realize I needed a css sheet alongside the two javascript files.

**Comment by robinfhu** [comment]
I think you are missing the CSS file.

**Comment by fresheneesz** [comment]
Yup, that was it, thanks @robinfhu
