### ISSUE TITLE
sunburst chart not redrawing on calls to chart.update()

### ISSUE THREAD

**Issue by kimhanse** [novus/nvd3#1145]
I am trying to make the sunburst chart react to new data and resizes, but I have no luck.

I have created this example:
  http://plnkr.co/edit/XHPQSsHCvW0jo0psZWOy?p=preview
  * It changes mode between count and size when the Change mode button is clicked.
  * It changes data when Change data button is clicked.
  * It calls chart.update() when the window is resized.

I expected this to work a little like discrete bar chart.

**Comment by liquidpele** [comment]
Yea, I don't think I set up chart.update() on it when I created it... I'll see if I can get to that, but if you want to take a stab in the meantime you can send a pull request and we'll merge it in :)

**Comment by kimhanse** [comment]
I'd love to help and I did have a look at the code but my JavaScript coding skills are a bit rusty. Can you suggest which other graph with working update() I should have a look at in order to see how a possible solution could be structured?

**Comment by liquidpele** [comment]
All the other have chart.update() working....   as far as I'm aware :)

**Comment by Sghazzawi** [comment]
pull request in for this https://github.com/novus/nvd3/pull/1272
