### ISSUE TITLE
scatter.highlightPoint is broken

### ISSUE THREAD

**Issue by jgrund** [novus/nvd3#1147]
Highlighting a point with the scatter model currently runs this code:

```
this.highlightPoint = function (seriesIndex, pointIndex, isHoverOver) {
            nv.dom.write(function() {
                container.select(" .nv-series-" + seriesIndex + " .nv-point-" + pointIndex)
                    .classed("hover", isHoverOver);
            });
        };
```

The problem here is container.select updates the data for the point with the data it holds. Once that happens, future operations will throw errors.

For an example click on a series in the stacked area chart example.

We need to find a way to get the point without altering the data on the way.

**Comment by liquidpele** [comment]
Can you give specific reproduction steps?  The only thing I see when I click on an area is a lot of:

    Error: Invalid value for <g> attribute transform="translate(NaN,NaN)"

And that doesn't look related at all to the code you posted...

**Comment by jgrund** [comment]
yes.

1) Go here: http://nvd3-community.github.io/nvd3/examples/stackedAreaChart.html
2) Click on one of the series.
3) You should see this error in the console: `Uncaught TypeError: Cannot read property 'y' of undefined`

P.S. I have a pull request incoming.

**Comment by liquidpele** [comment]
pretty sure that was fixed in master already.

**Comment by jgrund** [comment]
Still looks broken in the code:

https://github.com/novus/nvd3/blob/master/src/models/scatter.js#L445

I'll pull master and verify.

**Comment by jgrund** [comment]
Ok, I just verified on latest master. My fix resolves both the issue I saw and `Invalid value for <g> attribute transform="translate(NaN,NaN)"` in master.

**Comment by jgrund** [comment]
Can we reopen this? Fixed in my PR.

**Comment by wayneseymour** [comment]
+1 for PR: scatter.highlightPoint is broken #1151

**Comment by johnsonw** [comment]
I'm seeing the same issue on my end as well. Please bring in the pull request.

**Comment by liquidpele** [comment]
cool, thanks guys.
