### ISSUE TITLE
Can not add to bower webjars because of license issue when deploying 1.8.1

### ISSUE THREAD

**Issue by manjoine** [novus/nvd3#1148]
Ran into this when trying to add 1.8.1 to bower webjars http://www.webjars.org/bower

Failed! No valid licenses found. Detected licenses: Apache License, v2.0 The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1 License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo. Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.

**Comment by liquidpele** [comment]
Hmm, looks like I fixed the license in package.json but not bower.json, here ya go:

https://github.com/novus/nvd3/pull/1149

If that doesn't work, then I'm not sure what to tell you though, the license identifiers are pretty standard

https://spdx.org/licenses/
