### ISSUE TITLE
Support for radar (Spider) charts

### ISSUE THREAD

**Issue by manjoine** [novus/nvd3#1150]
This is really a feature request but wonder if there is any hope in getting support for radar (spider) charts in the future?

https://github.com/alangrafu/radar-chart-d3

I would be glad to work on it if someone wants to point me in the right direction.

**Comment by liquidpele** [comment]
If someone builds one and submits a PR we'll take a look.   

To get started see:

https://github.com/novus/nvd3#contributing

In the repo, there is a src directory that has all the source files... each chart type is a different model.   stuff like lines.js are just for lines, and lineChart.js is a chart that uses lines.js... so the models can actually use one another.  If you start off by copying another chart like sunburst.js and sunburstChart.js and then modifying it to be your own chart you'll be able to see what's going on.  

When you make changes, you just need to build the project (see the readme linked above) and it'll put the built files in the "build" folder, which all the stuff in the "examples" folder uses...   so you'll probably want to make an example page too and link it in site.html with the others.    Also if you add new options, you'll want ot document those in the big json object at the bottom of documentation.html   

Cheers.

**Comment by jlahare** [comment]
is there any update over this ? is this graph available now ?
