### ISSUE TITLE
Strict-mode does not allow assignment to undefined variables: tooltips

### ISSUE THREAD

**Issue by koote** [novus/nvd3#1154]
I encountered this error when using NVD3 in an ASP.NET project, ASP.NET failed to minify nvd3 v1.8.1:

run-time error JS1300: Strict-mode does not allow assignment to undefined variables: tooltips

Here is the code causes this error:
    chart._options = Object.create({}, {
        ....
        tooltips:    {get: function(){return tooltips;}, set: function(_){tooltips=_;}},
        ....
    });

Seems the minifier complains the tooltips variable, it is not defined. I added a definition of 'tooltips' at the beginning of nv.models.boxPlotChart = function() {}, it may not the correct fix. 
Does anyone know if this issue has been addressed? Thanks.

**Comment by liquidpele** [comment]
Send us a pull request for it if you want :)

**Comment by koote** [comment]
@liquidpele Thanks for your quick response. Sorry I am new to GIT, does "pull request" mean you already have fix for this issue so you want me to sync the latest dev branch to get it fixed?

**Comment by liquidpele** [comment]
https://help.github.com/articles/using-pull-requests/

**Comment by koote** [comment]
@liquidpele Thanks, I have started one: https://github.com/novus/nvd3/pull/1161

**Comment by koote** [comment]
@liquidpele Thanks for the quick response!
