### ISSUE TITLE
Should tooltip.js be in models/

### ISSUE THREAD

**Issue by chmac** [novus/nvd3#1155]
Firstly, thanks for a great package. d3 seems to be very powerful, and nvd3 is very usable, a great combo.

Took me a while to find the tooltip model as it's `nv.models.tooltip()` but the code is in `src/tooltip.js` rather than `src/models/tooltip.js`...

**Comment by liquidpele** [comment]
eh, well, the only reason I didn't move it into there already was that the models directory has all charts in it, and the tooltip is really a component they use, like the interactive layer which is also in /src/ and not in the models directory.
