### ISSUE TITLE
multiChart tooltip valueFormatter is always overriden

### ISSUE THREAD

**Issue by chmac** [novus/nvd3#1156]
Example of the relevant code from `models/multiChart.js`:

```javascript
                tooltip
                    .duration(100)
                    .valueFormatter(function(d, i) {
                        return yaxis.tickFormat()(d, i);
                    })
                    .data(evt)
                    .position(evt.pos)
                    .hidden(false);
```

The `valueFormatter` is always set on the mouseover events, which makes it impossible to set a custom `valueFormatter`. Calling `chart.tooltip.valueFormatter()` has no effect, because of the code above.

The code above is required because it determines which yAxis to get the formatter from. However, it would be possible to make this behaviour optional, or use custom formatters which accept the yAxis as an argument and return a function. Are you open to a pull request implementing the latter?

**Comment by liquidpele** [comment]
Ah, yea, we should probably only use ._valueFormatter so that it only sets the value if it hasn't been overwritten manually with .valueFormatter... the underscore thing is something I added to fix a similar issue in another chart.

**Comment by liquidpele** [comment]
Feel free to implement it and send a pull request :)
