### ISSUE TITLE
Update gh-pages branch from master

### ISSUE THREAD

**Issue by chmac** [novus/nvd3#1160]
The `gh-pages` branch is quite old, for example, it doesn't include the `multiChart.html` example. Any harm in merging `master` into `gh-pages`?

**Comment by liquidpele** [comment]
Yea, the gh-pages that novus currently uses is totally different....   I don't think they want to do that.   master has what is shown as the nvd3-community page:   http://nvd3-community.github.io/nvd3/ where gh-pages here shows:  http://nvd3.org
