### ISSUE TITLE
what is the best to draw several charts but different style in a single page?

### ISSUE THREAD

**Issue by Kyeongan** [novus/nvd3#1165]
I have basic two line charts. I could change css in nv.d3.css file for style.
.nvd3.nv-line .nvd3.nv-scatter .nv-groups .nv-point {
  fill-opacity: 0.5;
  stroke-opacity: 1;
}
But, what is the best way to handle two different style charts in a single page?

line chart 1
![opacity-0](https://cloud.githubusercontent.com/assets/5505099/8861905/b39b9d62-3152-11e5-8c23-1e41521c5fd1.png)

line chart 2
![opacity-1](https://cloud.githubusercontent.com/assets/5505099/8861906/b39db50c-3152-11e5-9992-9815ede3b4fc.png)

**Comment by liquidpele** [comment]
you can specify the ID with the ID option and then use the ID to give each a different style

**Comment by Kyeongan** [comment]
Thanks @liquidpele 
I tried what you suggested but it doesn't work. This is my simple code.

#plot1 {
  margin:0;
}
#plot1 svg {
  height: 400px;
}

#plot2 {
  margin:0;
}
#plot2 svg {
  height: 400px;
}

Where should I specify different style?

So far, I use below code in a html file that looks override(?) the original style. yes, it doesn't change other html files. But still I am not clear that two div in a single file. 

.nvd3.nv-line .nvd3.nv-scatter .nv-groups .nv-point {
  fill-opacity: 0;
  stroke-opacity: 0;
}

Thanks,

**Comment by liquidpele** [comment]
Do chart.id('something'); and then use dev tools to see what the actual created I'd is for the chart (should have the string you gave in it) and use that I'd for your CSS stuff.

**Comment by Kyeongan** [comment]
@liquidpele I am sorry that I am not clear. Do you mean when addGraph function occurs?

like 
nv.addGraph(function() {
		var linechart = nv.models.lineChart()
... };
linechart.id('SomethingName');


FYI, this is the html div for now
<div id="offsetDiv">
	  <div id="plot1">
		<svg></svg>
	</div>

Thanks,

**Comment by liquidpele** [comment]
Yes.
