### ISSUE TITLE
 Input parameter of tooltip.contentGenerator callback missing 'point' property

### ISSUE THREAD

**Issue by koote** [novus/nvd3#1166]
I recently upgraded to nvd3 1.8.1-dev, it introduces a new tooltip model. I found that the input parameter of tooltip.contentGenerator callback has a property called 'point', which contains the user defined data associated with the active point cursor is hovering on.
However, I get a exception when composing tooltip content for multiBarChart, after some investigation, I found in this type of chart, input parameter doesn't contain 'point' property, instead, it has a property called 'data' which stores user defined data.
My question is why the structure of input parameter of tooltip.contentGenerator callback could be different, should not they keep consistent across all charts?

**Comment by liquidpele** [comment]
Point applies then scatter points (which line charts use too) but pie slices and bars are not points....   It's not consistent but the different chart models aren't all the same type of data.

**Comment by koote** [comment]
@liquidpele Thanks for your reply. But, since no help documents mentioned this subtle difference, users must sometime do debugging to find the correct variable, can we use 'data' in all charts?
