### ISSUE TITLE
valueFormatter not called when using useInteractiveGuideline

### ISSUE THREAD

**Issue by allhailwesttexas** [novus/nvd3#1178]
I'm trying to format the values in the interactive guidelines tooltip for a lineChart. I can do this for the header with `chart.tooltip.headerFormatter` which works just fine, but the `valueFormatter` never seems to fire, and I'm unable to change to format of the value. `keyFormatter` also works as expected.

I've made a [fiddle](https://jsfiddle.net/pt18h2zL/) which demonstrates the issue.

**Comment by milo-** [comment]
A little late to the party but I just ran into this issue today. The fix is to call the keyFormatter and valueFormatter on the interactiveLayer tooltip:

```
chart.interactiveLayer.tooltip.valueFormatter()
chart.interactiveLayer.tooltip.keyFormatter()
```

**Comment by liquidpele** [comment]
chart.interactiveLayer.tooltip.valueFormatter() is only valid if you have useInteractiveGuideline turned on, otherwise you just do chart.tooltip.valueFormatter().  

I updated the fiddle to use latest master, it appears to properly use valueFormatter now. 

https://jsfiddle.net/pt18h2zL/2/
