### ISSUE TITLE
Way to prevent highlight of undefined points?

### ISSUE THREAD

**Issue by jnfeinstein** [novus/nvd3#1180]
I'm building a lineChart that has gappy data.  I've installed handlers for `defined` and `pointActive`.  The gappy data is being represented as `undefined`, and the highlight tooltip is appearing with an "N/A".  I don't want the highlights to appear at all if the data isn't defined.  Is there a way to do this?

**Comment by liquidpele** [comment]
I think if you use normal tooltips instead of the interactive guideline then it does what you want.   The guideline tries to account for every series though.
