### ISSUE TITLE
Overriding / adding additional functionality to the mouse movements for tooltip?

### ISSUE THREAD

**Issue by hc000** [novus/nvd3#1181]
Is there anyway for me to override or add more things for the mouseenter/mouseleave events?

I would like to apply css to a different part of the screen based on the mouse movements.

**Comment by RenatoUtsch** [comment]
Look at chart.dispatch or chart.interactiveGuideline.dispatch.

**Comment by hc000** [comment]
Figured out a different way to do this without messing with the mouse events. thanks
