### ISSUE TITLE
Adding classes to datapoints/series?

### ISSUE THREAD

**Issue by bwarren2** [novus/nvd3#1186]
I am trying to move my styling away from declaring what color this or that series/data element is, and instead doing the styling in CSS and having the appropriate classes on the data.  However, it doesn't seem like there is a clean way for me to do this (in for example a scatterChart) without forking the scatter model and doing some monkeying.  This seems unclean for such a core capacity as class declaration; is there a better way I am not thinking of?  Maybe a model that implements scatterChart like scatterChart implements scatter, and doing postprocessing on each datapoint/series to apply a given class spec?

More generally, what are the core members an nvd3 model is intended to expose?  It seems like some models provide getX and getY (while others don't), and there is no hook for each series specifying its class.  Is there a spec somewhere for "good models implement these methods"?

**Comment by bwarren2** [comment]
I ended up using the post-render (2nd) argument in addGraph and some hacky d3.

    function(chart){
      var place = destination + ' path.nv-point';

      d3.selectAll(place).attr(
        'class',
        function(d){
            var classstr = (d[0].extradata || {}).classstr || '';
            return d3.select(this).attr('class') + ' '+ classstr;
        }
      );
    }

**Comment by danzera** [comment]
I have something similar working for me, but I've noticed that toggling a line on/off with the legend causes the class to be removed, but doesn't get re-added when the line reappears as this callback is only called on the initial render. Did you run into this?

`      return chart;

    }, () => { // post-render callback function included to show data points along lines
      // add dots to data points on chart -- these are not included when the lines are re-drawn following a legend click
      d3.selectAll('.nv-point').style("stroke-width", "5px").style("fill-opacity", ".95").style("stroke-opacity", ".95");
      }
    });`

**Comment by danzera** [comment]
I have something similar working for me, but I've noticed that toggling a line on/off with the legend causes the class to be removed, but doesn't get re-added when the line reappears as this callback is only called on the initial render. Did you run into this?

```
chart = nv.addGraph(function() {
  // chart code
  return chart;
}, function() {
  // add dots to data points on chart -- drawn initially, but don't get redrawn after toggling lines on/off via the legend
  d3.selectAll('.nv-point').style("stroke-width", "5px").style("fill-opacity", ".95").style("stroke-opacity", ".95");
}
```
