### ISSUE TITLE
Overriding/customize Tooltip gravity modes and chartContainer

### ISSUE THREAD

**Issue by hc000** [novus/nvd3#1187]
Due to some other library css conflicts (http://jsfiddle.net/7wdka3hr/3/) having the tooltip in the body fixes the issue that I am having.

What is the best approach to override or change the settings without actually changing the library? or perhaps the library can add a new feature to be able to pass a function for the gravity with custom logic just returning top/left.

I want to set these

    chartContainer = document.body 

and add a new case

    left = event.pageX+5;
    if (left+width+10 > windowWidth) left = left - width - 10;
    top = event.pageY-(height / 2);
    if (top+(height / 2) + 10 > windowHeight) top = top - (height / 2) - 5;
    if (top-window.pageYOffset < 0 ) top = window.pageYOffset+50;

**Comment by spiermar** [comment]
@hc000 are the changes stable enough to submit a pull request?

https://github.com/novus/nvd3/compare/master...att-innovate:master

**Comment by liquidpele** [comment]
It says it can't merge.... Tooltip were just fixed up a lot, so your issue might even be fixed already in master....  Or merge our master into your branch to fix any conflicts and then make the pull request.

**Comment by hc000** [comment]
the nvd3 fork i have is outdated, they reworked much of the code. let me test on the latest nvd3.
if it didn't work then we would just introduce a new case for "body" and use the options to change how the tooltip is generated.

**Comment by spiermar** [comment]
@hc000 awesome. let us know if it's fixed and which version to pull. ;-)
