### ISSUE TITLE
Doubts about tooltip behavior

### ISSUE THREAD

**Issue by RenatoUtsch** [novus/nvd3#1188]
I am currently refactoring the tooltip model.

What is the usefulness of tooltip.fixedTop? Seems kinda useless to me.

What is the usefulness of tooltip.offset? Seems kinda useless to me. distance makes a lot of sense, but not offset.

Should the tooltip be allowed to be positioned in a different position from where the mouse is?

**Comment by RenatoUtsch** [comment]
Also, why both distance and offset properties? They both do the same thing, but offset is more general.

**Comment by RenatoUtsch** [comment]
Also, should the tooltip be positioned in a different position from where the mouse is?

**Comment by Alex--wu** [comment]
I am wondering why not keep two way of how the tooltip position: 1. body layer(current) 2.the svg layer(the old one)
For me I have to update my code and recalculate all the tooltips position since I update to the lastest nvd3 version.

**Comment by RenatoUtsch** [comment]
@Alex--wu, I am very interested in how you use tooltips in your code. Where do you position your tooltips?

**Comment by Alex--wu** [comment]
I put the tooltips on the xAxis and yAxis. My case is that one page have
multi charts, each charts has their tooltips. the tooltips only display on
their layer. These charts may cover one from another. I don't want them to
show on the body layer.

2015-08-10 17:35 GMT+02:00 Renato Utsch <notifications@github.com>:

**Comment by RenatoUtsch** [comment]
But, not counting the xAxis and yAxis tooltips, do more than one tooltip appears at the same time? Or only one each time?

**Comment by Alex--wu** [comment]
In my product, one case is the tooltip can be freeze when user doubleClick. Well anyway this is not problem. The trouble thing is just I need to add top: d3.event.pageY, left: d3.event.pageX to each of my charts. Instead of breaking changes of the tooltip position base on page, I prefer to add a option to upward compatible. Well it is not you changed that, forget it :P

**Comment by RenatoUtsch** [comment]
The normal tooltips already used pageX and pageY, I just standardized this
behaviour for guidelined tooltips too.

Em seg, 10 de ago de 2015 13:03, Alexander WU <notifications@github.com>
escreveu:

**Comment by tikitu** [comment]
We have a use case which might not be covered by the current implementation (or might well be and I'm just not seeing it). On a `multiBarChart` we would like to show a tooltip for each bar, with the location pinned: horizontally centered on the bar, and vertically either just above the tip of the bar or just under the top of the chart itself. For both horizontal and vertical positioning this means the tooltip does not really follow the mouse, except that it appears and disappears as the mouse enters and leaves a particular bar.

(If this is possible with the current setup I would love to hear how, and if your refactor would remove this functionality then please consider this a request not to!)

**Comment by Alex--wu** [comment]
Me too. We have a use case which need to show the tooltips on the Axis. I don't think the current version can meet the need. I really want to use the old tooltips model.

**Comment by RenatoUtsch** [comment]
@tikitu what you're asking for is not readily done in the current implementation.

What you and @Alex--wu can do is instantiate various nv.model.tooltip's and set their position and when they are shown. My refactor in fact makes doing this easier because with this pull request you'll be able to specify a position function for the tooltip, which could be made to display the tooltip on the axis or on each bar.

You'll just have to instantiate more tooltips than the default. But it can be done.

**Comment by RenatoUtsch** [comment]
#1190 was merged.

**Comment by TrueMan777** [comment]
I was using the fixedTop option to meet the design concept. So I am keen to make it working again. Is forking the code the only option for me now? I can't find from the code any other way how I can make it working.
