### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by dmanquestica** [novus/nvd3#1197]
We're currently using the bullet chart, but noticed some inconsistency between the formatting of the axis and the formatting of the numbers in the mouse over pop-ups. When the axis shows numbers larger than 999, it shows the thousands comma separator, however in the pop-ups when you mouse over certain areas, it does not.

One possible way to fix this would be to apply consistent formatting between the axis and pop-ups. Or have a way of passing in a formatting function so that the value are correctly formatted for display, but doesn't interfere with any calculations needing the values themselves.

Thanks.

**Comment by liquidpele** [comment]
Feel free to send us pull requests for anything you think needs fixing or that could work better :)
