### ISSUE TITLE
MultiChart stateChange event is not triggered (error)

### ISSUE THREAD

**Issue by lukaprelic** [novus/nvd3#1202]
The stateChange event doesn't get triggered and it cant be caught using:
```
        chart.dispatch.on('stateChange.chart1', function (newState) {
            console.log('test');
        });
```
The given error is: 
```
Uncaught TypeError: Cannot read property 'on' of undefined
```

I tested using the multichart example provided in the repo. Is there another way to catch legend clicks or state changes for multichart?

thanks

**Comment by yppeaxy** [comment]
I think I am seeing the same problem for line-with-focus-chart: 'stateChange' event is not triggered.

**Comment by liquidpele** [comment]
Try using latest code in master... Thought we fixed that.

**Comment by yppeaxy** [comment]
I just looked at my version and figured out that dispatch was not calling
it. I do see it's being called in the current version.
Thank you for such a quick replay!
