### ISSUE TITLE
sparkline and sparklinePlus don't seem to dispatch any event

### ISSUE THREAD

**Issue by michalgm** [novus/nvd3#1207]
It's possible that I'm missing something. I'm trying to register handlers for the renderEnd event on a sparklinePlus chart, but it seems that chart.dispatch is not defined. Here's a plunkr example:
http://plnkr.co/edit/b1G8iAqryYdf9FCKU65x?p=preview

Any thoughts? Thanks you.

**Comment by Sghazzawi** [comment]
I have a pull request in w/ a fix for this.  
See http://plnkr.co/edit/oh8bSaKP5VGvjXngTGz3?p=preview for example

**Comment by liquidpele** [comment]
merged the PR, closing this.  Thanks!
