### ISSUE TITLE
Safari tooltip is transitioning in from upper left...

### ISSUE THREAD

**Issue by cymen** [novus/nvd3#1208]
When I use Safari on charts with tooltip enabled, the tooltip transitions in from the upper left of the page. You can see it in action on the examples page here:

http://nvd3-community.github.io/nvd3/examples/site.html

With these examples:

* LinePlusBarChart
* MultiChart
* ScatterChart

When using Safari of course. I'm using Safari Version 8.0.8 (10600.8.9). This may be related but unclear: https://github.com/novus/nvd3/pull/1172.

**Comment by cymen** [comment]
I tried applying the fix in #1172 locally but it is still broken for me.

**Comment by cheniel** [comment]
Noticed the same issue today :(

**Comment by liquidpele** [comment]
I just merged that and rebuilt master, please check the latest master to see if this is fixed. 

Safari is the new IE  -_-

**Comment by cheniel** [comment]
Works for me on lineChart.

**Comment by cymen** [comment]
I still see the same issue on:

* LinePlusBarChart
* MultiChart
* ScatterChart

I cleared the cache on Safari.

@cheniel Can you try one of the above -- I'm using the exact name. It works fine for me on lineChart but that uses the other type of tooltip that is just fine. Are you using Safari v8 or v9?

**Comment by cheniel** [comment]
Won't be able to get around to trying one of those in a while, but I'm on 8.0.7 (10600.7.12)

**Comment by cheniel** [comment]
Just tested it out on my other computer, running Safari 8.0.8 (10600.8.9). Works fine

**Comment by cymen** [comment]
@cheniel Are you testing one of the specific ones I mentioned above? As mentioned earlier, lineChart is fine for me too but the other three exhibit the bug.

Here is a screencap of the failure: https://www.youtube.com/watch?v=aB5HT-WxFwY

**Comment by cheniel** [comment]
Yup, tried it on all of those. Looks like you are viewing here? http://nvd3-community.github.io/nvd3/examples/site.html I believe that is based off of this repository, which does not have the updated nvd3: https://github.com/nvd3-community/nvd3/tree/gh-pages

Clone master and open linePlusBarChart.html

**Comment by cymen** [comment]
Whoops. I misread. I pulled verified the bug while looking at local checkout too -- rolled it back and it is buggy, went to HEAD and it's fixed.

Thanks! I'll close this.
