### ISSUE TITLE
Issue with Tooltip in Multichart

### ISSUE THREAD

**Issue by uenz** [novus/nvd3#1210]
The key (Name) of a line is only shown in multichart tooltip if the line is of type area. See the [MultiChart](https://raw.githubusercontent.com/novus/nvd3/master/examples/multiChart.html) sample. The keys are only shown for the first two Lines (item0 and item1). Putting a console.log(d) in keyFormatter shows undifined for all other types than area. User specific valueFormatter is not called. I tried a console.log("valueFormatter") in the valueFormatter in the offical source. It was also not called.

**Comment by liquidpele** [comment]
I think I just merged in a fix for that this morning, can you check the latest code in master?

**Comment by uenz** [comment]
In the master branch the files ( nv.d3.js / nv.d3.min.js) in the build 
folder are still the old ones. Unfortunately i don't now how to 
"rebuild" the build folder or
how to test the fix without a new nv.d3.js

**Comment by liquidpele** [comment]
I built latest and pushed it up.

**Comment by uenz** [comment]
Now it works with type area and line. Not with bar and scatter.
As a quick hack i also added the "key: evt.series.key" to 
mouseover_scatter and mousover_bar.
It works with scatter, but not with bar which have a different 
definition of evt.series evt['series'].

**Comment by cheniel** [comment]
Works for me on a lineChart.

**Comment by liquidpele** [comment]
Someone fixed it for the rest and I merged that, closing this.
