### ISSUE TITLE
Move Y-origin for bar-chart?

### ISSUE THREAD

**Issue by aquila** [novus/nvd3#1212]
I would like to plot data where the Y-origin is -90 instead of 0. The goal is that -80 shows up as a bar with height 10, between -90 and -80 on the Y axis, instead of a bar of height 80 from 0 to -80. Is this possible? I tried playing with yRange and yDomain but those functions do different things.

**Comment by liquidpele** [comment]
check out the xRange option, you can specify the actual ranges to use if needed.

https://nvd3-community.github.io/nvd3/examples/documentation.html
