### ISSUE TITLE
Stacked multiBarHorizontalChart doesn't occupy svg's whole width

### ISSUE THREAD

**Issue by angularbv** [novus/nvd3#1215]
Hey, MultiBarHorizontalChart doen't seem to occupy the whole SVG width. I didn't specify width, by default it takes 100%width right? If I specify width it is not updated when window is resized. Do anyone have solution for this?

**Comment by liquidpele** [comment]
There are default margins and other offsets, you can override with the options on the chart, see the docs.    If you find there is an issue beyond that, please provide a jsfiddle demonstrating the issue using the latest code in master (link to that using rawgit.com).   cheers.
