### ISSUE TITLE
Seeing Nothing  in interactive guides on stacked area charts

### ISSUE THREAD

**Issue by dava2788** [novus/nvd3#1218]
I know there is a bug open for a:
Seeing "NaN" sometimes in interactive guides on stacked area charts #1081
And that happen when I change the  yaxis to:
.tickFormat(function (d) { return d3.time.format("%X")(new Date(d)) });

![image](https://cloud.githubusercontent.com/assets/1749777/9526494/d691a3a6-4ca6-11e5-8e22-959e94844ce1.png)

But also when I change the yaxis to :
.tickFormat(function (d) { return d3.time.format("%B")(new Date(d)) });
the Interactive guides doesn't show the month name:

![image](https://cloud.githubusercontent.com/assets/1749777/9526447/99d5defa-4ca6-11e5-8cc6-eed87ee78835.png)

Does anyone solve this issue?

Thank you in advance.

Best Regards

**Comment by liquidpele** [comment]
Can you create a jsfiddle that shows the issue? 

Please use the latest code in  master for it (using rawgit.com to link to latest here on github)
