### ISSUE TITLE
unable to live update a stackedAreaChart() ?

### ISSUE THREAD

**Issue by raybellis** [novus/nvd3#1226]
I'm trying to perform real-time updates on a stackedAreaChart(), but for reasons I don't understand the data array that I'm passing via `.datum()` doesn't appear to be the one actually attached to the SVG.

My code looks something like:

    var my_array = [];
    var datum = [ {
        key: "key1", values: my_array
    }];

    d3.select(selector).datum(datum).call(chart);

Subsequent examination of the `datum` object appears to show that the `values` array has been replaced with a new array.

If I replace the `stackedAreaChart()` with a `multiBarChart()` my code works as expected, albeit with the wrong visuals.

**Comment by liquidpele** [comment]
Yea, calling datum() attaches the new array.   You should just update the datum object itself and then call chart.update()

**Comment by raybellis** [comment]
OK, thanks - I've been able to resolve this (albeit at the expensive of a minor layer violation) by calling `d3.select('foo').datum()` to retrieve the current datum object and then updating that directly.
