### ISSUE TITLE
Adding option for line icon in legend

### ISSUE THREAD

**Issue by syndesis** [novus/nvd3#1231]
I wanted to use a line icon instead of the circle in the legend for a multiChart with a line graph in it.  I added a data option called legendIconType to allow this.  For example:

var data = [{type: 'line', values: [1, 2, 3, 4, 5], yAxis: 1, legendIconType: 'line'}];

It's rendered initially as stroke-width: 4 and shrinks to 2 when it's disabled.

**Comment by liquidpele** [comment]
Send up a pull request... if you use the built in d3 symbols, check in nv.util, there is a custom symbol getter there that allows people to add their own symbols to use (currently used by scatter chart).
