### ISSUE TITLE
Tooltip position is off when container's css is `display: flex`

### ISSUE THREAD

**Issue by DmitryEfimenko** [novus/nvd3#1233]
I have a use case with [angular-material](https://material.angularjs.org/0.10.1/#/), which uses `flex` for their layout grid. Most likely the issue will show itself with the upcoming [Bootstrap 4](http://v4-alpha.getbootstrap.com/), which has an option to use `flex` as well.

See this [plunker](http://plnkr.co/edit/L4zvBO92I56yf0hkJ8g0?p=preview) to see issue in action.
There is more details about issue in the first paragraph in plunker.

**Comment by RenatoUtsch** [comment]
This should have been fixed by #1190.

**Comment by DmitryEfimenko** [comment]
Works on the plunker I provided. Awesome job!
