### ISSUE TITLE
how to get current colors used for series?

### ISSUE THREAD

**Issue by DmitryEfimenko** [novus/nvd3#1234]
I know one could set colors using an array:
```
var colors = ['#4078c0', '#569e3d'];
chart.color = colors;
```
But is there a way to get currently used colors as array?
Particularly I'm interested in the case when colors weren't set yet.
```
var colors = ??
```

**Comment by liquidpele** [comment]
It's not a set array or anything, basically given the keys, we just have d3 hand us colors from a set of 20 that they have internal.  If you want to predict them, then you should set the colors yourself with the colors option.  

For isntance, check out the "color" option here:

https://nvd3-community.github.io/nvd3/examples/documentation.html#lineChart

**Comment by DmitryEfimenko** [comment]
Thanks a lot!
