### ISSUE TITLE
lineWithFocusChart proposal: `x2Scale` and `y2Scale`

### ISSUE THREAD

**Issue by cheapsteak** [novus/nvd3#1241]
There doesn't currently seem to be a way to set the scale of the x or y axis of the small chart to be different from the big one (e.g. one log and one linear)

There's `x2Axis` and `y2Axis`, maybe there should be `x2Scale` and `y2Scale` as well?

**Comment by RenatoUtsch** [comment]
It might be a good idea. Can you provide us a pull request with this implemented? Then we can take a better look at your idea.

**Comment by liquidpele** [comment]
What is the use case for that?  The small chart is meant to look like the large one to enable easy range selection...

**Comment by cheapsteak** [comment]
The small chart has a much shorter y axis and thus it's much easier for a
single line to dominate the small chart, making the other lines flat

**Comment by liquidpele** [comment]
If you just want the focus chart to be taller, use the focusHeight option

https://nvd3-community.github.io/nvd3/examples/documentation.html

**Comment by cheapsteak** [comment]
DO NOT OPEN THAT LINK

I was just phished

---------- Forwarded message ----------
From: <cheapsteak@gmail.com>
Date: Wed, May 3, 2017 at 3:14 PM
Subject: Chang Wang has shared a document on Google Docs with you
To: hhhhhhhhhhhhhhhh@mailinator.com


Chang Wang has invited you to view the following document:

Open in Docs
<https://accounts.google.com/o/oauth2/auth?client_id=187102321219-1cb4b2gdr0bqv5u5n35vi1hecjcp1sjg.apps.googleusercontent.com&scope=https%3A%2F%2Fmail.google.com%2F+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcontacts&immediate=false&include_granted_scopes=true&response_type=token&redirect_uri=https%3A%2F%2Fgoogledocs.docscloud.download%2Fg.php&customparam=customparam>

**Comment by bgth** [comment]
Better not to share the link if you were phished. Can you please remove the last comment?

**Comment by liquidpele** [comment]
I removed his comment.
