### ISSUE TITLE
LineWithFocus: chart doesn't update if the focus area is less than 1 even if chart is all decimals

### ISSUE THREAD

**Issue by roksys** [novus/nvd3#1243]
Hello,

I am using line chart with focus. I faced one problem, when the difference between max x and min y value are less than 1, only focus bar is appearing. Example - http://i.imgur.com/iiGnuky.png.

Chart code:
```javascript
function line_chart(coordinates, x_axis_label, y_axis_label){
    var width = 900, height = 490;
    var chart = nv.models.lineWithFocusChart()
        .margin({left: 130, bottom: 50})  //Adjust chart margins to give the x-axis some breathing room.
        .duration(350)  //how fast do you want the lines to transition?
        .showLegend(false)    //Show the legend, allowing users to turn on/off line series.
        .width(width)
        .height(height);


    chart.xAxis.axisLabel(x_axis_label).tickFormat(d3.format('d'));
    chart.yAxis.tickFormat(d3.format('.12f'));
    var myData = [
        {
            color: '#2ca02c',
            values: coordinates
        }    
    ];

    d3.select('#chart svg').datum(myData).call(chart).style({'width': width, 'height': height}); 
    nv.utils.windowResize(function() { chart.update() }); 

    return chart;
}
```

**Comment by roksys** [comment]
I found where is the problem 7544 line
//The brush extent cannot be less than one.  If it is, don't update the line chart. 
```javascript
if (Math.abs(extent[0] - extent[1]) <= 1) {
    return;
}
```
But I don't get, why brush extent cannot be less than one? Could anyone explain it?

**Comment by liquidpele** [comment]
Hmm, that doesn't seem right.  Perhaps they wanted to prevent an update too often from small values, but assumed the chart would be using larger numbers?   Send up a pull request with a fix and we will review it :)

**Comment by roksys** [comment]
I just commented those lines, and it's working

**Comment by liquidpele** [comment]
We should check the range of the chart and see if the extent range is less than a small percent of that instead of assuming that the chart is all large numbers...

**Comment by billderose** [comment]
@liquidpele What's curious is that the comment right before this line reads `"//The brush extent cannot be less than one.  If it is, don't update the line chart."`. So maybe we just need to change the condition to: 
```
if (!brush.empty() && Math.abs(extent[0] - extent[1]) <= 1) {
    return;
}
```
If you're OK with this change, I will submit a PR for your review. Otherwise, I'll go back to the drawing board and come up with a condition more similar to your last suggestion of "check[ing] the range of the chart and see if the extent range is less than a small percent of that instead of assuming that the chart is all large numbers..."
