### ISSUE TITLE
feature request: "reduceXticks" for stackedAreaChart (or even all charts?)

### ISSUE THREAD

**Issue by jduhls** [novus/nvd3#1244]
I can use "reduceXticks(false)" on multiBarChart but when I switch to stackedAreaChart this does not work/cannot control x ticks. How can I consistently display x ticks across different chart models?

**Comment by liquidpele** [comment]
Feel free to look over the options that exist:

https://nvd3-community.github.io/nvd3/examples/documentation.html

If what's there doesn't meet your needs, then you'll want to add them and send us a pull request with the new options.  Cheers.
