### ISSUE TITLE
interactive guideline tooltip custom valueFormatter

### ISSUE THREAD

**Issue by pgrm** [novus/nvd3#1247]
I've seen dozens of issues about this, but I'm not entirely sure if this part has been already mentioned:

The `valueFormatter` can be overwritten via `chart.interactiveGuideline.tooltip.valueFormatter(newCustomFormatter)` or better it could be overwritten, because the valueFormatter is being set inside the function. What that means:

after deleting the following lines:

    .valueFormatter(function(d,i) {
        return d == null ? "N/A" : yAxis.tickFormat()(d);
    })

from [lineChart.js](https://github.com/novus/nvd3/blob/master/src/models/lineChart.js#L256) and [lineWithFocusChart.js](https://github.com/novus/nvd3/blob/master/src/models/lineWithFocusChart.js#L333) I can now set the tooltip as described above. Or actually I'm using [angular-nvd3](https://github.com/krispo/angular-nvd3) for that and that needs also some more fixes, but it works.

Now I don't know what could break by removing those lines, but now it works es expected and I can define my custom format also for interactive guidelines.

So, could this be implemented? Or does it break terribly something else?

**Comment by RenatoUtsch** [comment]
Does it work as expected? I thought that specifying a new value formatter would just replace the old function.

If the default value formatter functions aren't specified, what happens? How is the data formatted?

**Comment by metysj** [comment]
The 'old' function is reset every time because it's inside the 'elementMousemove' handler

**Comment by liquidpele** [comment]
Oh, yea that's weird... it has it setting that here:

https://github.com/novus/nvd3/blob/master/src/models/lineChart.js#L415

but, it's already being set up here:

https://github.com/novus/nvd3/blob/master/src/models/lineChart.js#L64

so I think the place inside of the mousemove handler should just be deleted?

**Comment by pgrm** [comment]
it seems to be working now for me, without the fix
