### ISSUE TITLE
Align mouseover coloring of different chart types

### ISSUE THREAD

**Issue by consense** [novus/nvd3#1252]
See the default project examples:
when mousing over a segment in a donut/pie chart the color gets lighter. In basically all other chart types the behavior is reversed - mouseover makes the color darker.
While not a technical bug, this is a needless visual inconsistency which makes it hard to use different chart types together with a common color scheme.

Please excuse and close the issue if there is some deeper reasoning behind this inconsistent behavior I am unaware of.

**Comment by RenatoUtsch** [comment]
Yeah, you're right.

If you are able to, it would be very helpful if you provided a pull request with the fix. If not, maybe someone will look into this later.

**Comment by Sghazzawi** [comment]
I have a pull request in for this

https://github.com/novus/nvd3/pull/1267

**Comment by liquidpele** [comment]
merged.

**Comment by bluesliverx** [comment]
I'm using the library in an app where hovering wasn't available, so in order to reverse this to original behavior I just did this in css:

```
.nvd3.nv-pie path {
	fill-opacity: 1 !important;
}
.nvd3.nv-pie .hover path {
	fill-opacity: 0.7 !important;
}
```

This took me forever to track down since I couldn't figure out what was setting the color.  Turns out it was simple css :/
