### ISSUE TITLE
legend.maxKeyLength is in master branch, but not CDN

### ISSUE THREAD

**Issue by lucaslin** [novus/nvd3#1256]
Don't know if this is the right place to mention this, but I noticed that it is not in the CDN
https://cdn.rawgit.com/novus/nvd3/v1.8.1/build/nv.d3.js

Perhaps relevant:
The build for master has "dev" in the header
https://github.com/novus/nvd3/blob/master/build/nv.d3.js

while the build for development does not
https://github.com/novus/nvd3/blob/development/build/nv.d3.js

is there a mix-up?

**Comment by liquidpele** [comment]
Master is current development, not the 1.8.1 release.   See the tags for official releases.

**Comment by liquidpele** [comment]
Oh, development is stale... going to delete that branch soon.   Sorry for any confusion there ;)
