### ISSUE TITLE
Due to the furious legend the first pie chart colors are overwriting the rest of the pie charts

### ISSUE THREAD

**Issue by vineelal** [novus/nvd3#1259]
I have two pie charts with two different set of the colors. First chart is having the legend type as furious. Due to which the second pie chart colors are overwritten by the first pie chart colors. Adding the pluncker for reference [pluncker](http://plnkr.co/edit/wKLeovBFGNmeeILd3hWT?p=preview).

**Comment by liquidpele** [comment]
You can't use the exact same data object for both charts.   Here is your plunker fixed:

http://plnkr.co/edit/pK1b3kDBMT1C0Gah6Jhm?p=preview
