### ISSUE TITLE
PR 1245 Not Published to Atmosphere JS

### ISSUE THREAD

**Issue by jdlubrano** [novus/nvd3#1261]
Changes from #1245 were never published to [Atmosphere](atmospherejs.com).  I have created #1260 to automate the process for future releases; however, the changes from PR 1245 probably need to be published manually.

If you know who owns the _nvd3_ Meteor developer account, it might be as easy as running `meteor publish` from the nvd3 root directory; however, for the updated code to propagate to Atmosphere, the _package.js_ file might require a new version number.  I am not 100% sure how the Atmosphere publish workflow resolves code updates.

If you would rather defer any potential Atmosphere headaches to me, I would happily join the NVD3 Meteor organization as a package maintainer although I don't profess to be an expert in the area.  Nevertheless, I would consider it a privilege to learn the details of Meteor package maintenance through NVD3.  

For details of how to potentially add me as a package maintainer see http://stackoverflow.com/questions/29267399/how-to-add-collaborator-for-meteor-package-in-atmosphere.

**Comment by liquidpele** [comment]
https://atmospherejs.com/nvd3/nvd3 1.8.1 is there, #1245 is not in a release yet, which is why it's not available there.

**Comment by dandv** [comment]
@jdlubrano, I've added you as a member of the nvd3 Meteor Developer organization. This [means](http://stackoverflow.com/questions/32859416/what-are-the-differences-between-meteor-developer-organization-members-and-pack) you can publish and update any packages under the nvd3 namespace.
