### ISSUE TITLE
Series number changes on line charts bug.

### ISSUE THREAD

**Issue by npezolano** [novus/nvd3#1278]
In the following example,  when we disable the first "Sine Wave", the "Cosine Wave" changes from a line to a dotted line, how can we prevent that from happening? This is due to the series number of the underlying changing on disabling a line.

```html
<html>
<head>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.js"></script>
<script src="https://cdn.rawgit.com/novus/nvd3/master/build/nv.d3.min.js"></script>
<link href="https://cdn.rawgit.com/novus/nvd3/master/build/nv.d3.min.css" rel="stylesheet">
<style>
#chart svg {
  height: 400px;
}
#chart g.nv-scatter g.nv-series-0 path.nv-point
{
    fill-opacity: 1;
    stroke-opacity: 1;
}
#chart g.nv-series-0 path.nv-line
{
    stroke-opacity: 0;
}

</style>
</head>
<body>
<div id="chart">
  <svg></svg>
</div>
<script type="text/javascript">
data = function() {
  var sin = [],
      cos = [];

  for (var i = 0; i < 100; i++) {
    sin.push({x: i, y: Math.sin(i/10), shape: 'square'});
    cos.push({x: i, y: .5 * Math.cos(i/10)});
  }

  return [
    {
      values: sin,
      key: 'Sine Wave',
      color: '#ff7f0e'
    },
    {
      values: cos,
      key: 'Cosine Wave',
      color: '#2ca02c'
    }
  ];
}
nv.addGraph(function() {
  var chart = nv.models.lineChart();

  chart.xAxis
      .axisLabel('Time (ms)')
      .tickFormat(d3.format(',r'));

  chart.yAxis
      .axisLabel('Voltage (v)')
      .tickFormat(d3.format('.02f'));

  d3.select('#chart svg')
      .datum(data())
    .transition().duration(500)
      .call(chart);

  nv.utils.windowResize(chart.update);

  return chart;
});
</script>
</body>
</html>
```

**Comment by npezolano** [comment]
Example in images,

![With both enabled](http://imgur.com/RRa3zrx.png)

![With the Sine Wave disabled](http://imgur.com/9Lulpy7.png)

**Comment by liquidpele** [comment]
First off, your example appears to be using d3 version 2.10, but our minimum version is 3.4.4, I'm surprised it worked at all...   if it still doesn't work, please create a jsfiddle showing the issue, linking to the latest code in master using rawgit.com, thank you!

**Comment by npezolano** [comment]
Here you go, same problem with latest D3 and latest NVD3.

http://jsfiddle.net/0m8jzetx/1/

**Comment by liquidpele** [comment]
Well, at some point we added the "classed" option on the series that lets you set a class name so that you don't need to rely on the series number... however, it looks like the DOM builds in a way that it only applies to the lines and not the scatter chart points -_-

https://jsfiddle.net/0m8jzetx/2/

Marking as a bug.

**Comment by liquidpele** [comment]
This is where the class gets set for the lines:

https://github.com/novus/nvd3/blob/master/src/models/line.js#L106

If you have time, you can do the same thing in scatter.js and send up a pull request :)

**Comment by npezolano** [comment]
Thanks, I think that fixes it.
