### ISSUE TITLE
Best way to refactor line & stackedArea to not use nv.models.scatter

### ISSUE THREAD

**Issue by slestang** [novus/nvd3#1279]
I use NVD3 to draw multi-lines and stacked area charts with about 500 point per series and multiple graph per page and the performance are way too slow. I use the dev tools of Chrome to see what was taking CPU & memory and I see that the scatter plot used in background by these 2 types of chart is consuming a big part of the resources. I work-around it with:
```javascript
scatter.pointActive(function (d) { return false})
```
in *line.js* and my graphs are now rendered 2 to 4 times faster.

If I understood correctly, the background scatter plot is only used to display the tooltips. But I only need the interactive guide line, I don't need the tooltips.

So I try to figure out a proper way to refactor the files lines.js & stackedArea.js to add an option to deactivate the scatter plot but it seems to deeply integrated.
I try to comment all lines using the variable *scatter* from *line.js* but the chart stop working and I can't figure why.

Did anybody have an idea how to properly make the scatter plot optional into these 2 types of chart?
I am OK making a PR but I need an idea on how to do that change.

**Comment by liquidpele** [comment]
You can turn of voronoi clipping (faster), turn off voronoi altogether (even faster!), or turn off all interactive-ness (fastest) using the interactive(false) option. 

https://nvd3-community.github.io/nvd3/examples/documentation.html

**Comment by slestang** [comment]
I already deactivate voronoi and it was faster but not fast enough.
I finally found that adding *notActive: true* to every value object disable the creation of the scatter point and allow me to have better performance and still show the interactive guide line.

**Comment by liquidpele** [comment]
Ah, forgot about that!   Good call.

You can also just do this which affects every point instead of specifying it manually in the data. 

    chart.pointActive(function(d) { return false });
