### ISSUE TITLE
Interactive guideline only works for first two data points

### ISSUE THREAD

**Issue by mjcmatrix** [novus/nvd3#1280]
In my use case, interactive guidelines only work for the first two data points. (JSFiddle provided.)
If you move the pointer along the tooltip follows, but the interactive guideline does not move and the tooltip data stays on either data point 0 or 1.

![chart_example](https://cloud.githubusercontent.com/assets/9001393/10257450/6ccd7aba-694f-11e5-9cfc-e4c7f7af3084.png)

I have a date x-axis (in the data this is represented as a string). I figure I must be doing something wrong in the data or chart setup, but my data is ordered, etc. and I cannot find a cause or solution yet.

Currently testing on NVD3 version: 1.8.1-dev with D3 version: 3.5.6.
This happens on both lineChart and stackedAreaChart.

https://jsfiddle.net/mcjs/d0bqt65z/

I don't seem to be able to work around this issue. Could it be a bug or is it simply user error?

**Comment by Sghazzawi** [comment]
Have you tried to represent your dates as milliseconds?

**Comment by liquidpele** [comment]
@RenatoUtsch this maybe has something to do with your tooltip refactoring??

**Comment by RenatoUtsch** [comment]
Probably not.

I had this kind of problem when the data that I used as input for the chart had inverted x values (they were diminishing instead of growing), but on the example this doesn't seem to happen.

**Comment by RenatoUtsch** [comment]
Here, I fixed it.

https://jsfiddle.net/3kwkLh4h/

Problem with how the data was being formatted.

**Comment by liquidpele** [comment]
Thanks @RenatoUtsch !

**Comment by mjcmatrix** [comment]
Thanks for the help and the solution. I hadn't thought to use milliseconds yet. I based my application on a combination of code from the nvd3 examples (one example has a Date x-axis). I had spent a lot of time on this issue and pretty much exhausted web search by now and had reverted to trial and error, so you have probably saved me several more days of diagnostics.

**Comment by RenatoUtsch** [comment]
I already spent a lot of time on this issue also hehe

You're welcome.
