### ISSUE TITLE
MultiBarHorizontal Chart vertical (x) axis width

### ISSUE THREAD

**Issue by mdthornton** [novus/nvd3#1281]
Hi

Creating my first charts with this library.... tried to find answer so sorry if it has already been asked.
Is it possible to adjust the width of the vertical axis on multibarhorizontal chart?
See my example below.

I'm setting the chart height (as a function of number of data items) but that doesn't seem to affect the rendered width.

Thanks in advance.
Mike

![nvd3](https://cloud.githubusercontent.com/assets/14947202/10258587/6f19ff86-692d-11e5-9c2b-25d9c0d197ab.png)

**Comment by liquidpele** [comment]
https://nvd3-community.github.io/nvd3/examples/documentation.html#axis

So for a chart such as multiBarHorizontalChart, you'll see th elist of components that make up the chart:

https://nvd3-community.github.io/nvd3/examples/documentation.html#multiBarHorizontalChart

One is yAxis, another is xAxis... those are axis objects....  so you can do something like:

    chart.yAxis.width(100);

**Comment by mdthornton** [comment]
Thanks but this doesn't work as expected.....
Example, try changing the y-axis width in the line chart example (live code).
The rendering of the labels themselves seems to be independent of this option.

**Comment by mdthornton** [comment]
The fix for this is to set chart margin.

In my case for horizontal bars, increase the left margin, eg:
      chart.margin({ top: 30, right: 20, bottom: 50, left: 200 });

**Comment by liquidpele** [comment]
oooh, so the labels were being cut off by the chart.   I see, sorry, from the image it looked like the chart margin was already much wider than the axis margin due to all that white space on the left.

**Comment by mdthornton** [comment]
no worries. many thanks for the links above and assist.
