### ISSUE TITLE
[Feature Request] Built-in exporting to png/jpeg/pdf

### ISSUE THREAD

**Issue by ovvn** [novus/nvd3#1283]
This issue raised at https://github.com/novus/nvd3/issues/218
My points are
1. Function that grabs all external styles can be a part of utils.js
2. PhantomJS is only needed for generating pdf, we can generate png/jpeg without it on the client once all styles are there (via the function that grabs external styles or if SVG's styles are inline). See the link https://gist.github.com/Caged/4649511

**Comment by liquidpele** [comment]
Send up a pull request if you like :)
