### ISSUE TITLE
showing lables and legends on the Sunburst chart  # liquidpele

### ISSUE THREAD

**Issue by nounla** [novus/nvd3#1284]
I am new to NVD3 sunburst chart and tried to show labels and legend for sun burst chart.
can we show labels and legend for sun burst chart using nvd3 and if yes, how?

**Comment by liquidpele** [comment]
Nope, no labels or legend.  It depends on the tooltip as the data/slices are typically a lot more compact than a pie chart and the legend doesn't make much sense with the child/parent relationship of the data.  If you want to implement something though, feel free to send us a pull request.
