### ISSUE TITLE
Documentation for using the Symbol function with data

### ISSUE THREAD

**Issue by jackmarketon** [novus/nvd3#1289]
There is no documentation about being able to change the symbols.

It's changed via the data:

```
...
[{x: 1, y: 2, symbol: 'square'}]
...
```

This should really be in the wiki somewhere, although I'm unsure of where to put it (otherwise I'd add it myself)

**Comment by liquidpele** [comment]
Yea, we really do need to document those... there are several special attributes you can set that override options for specific points

I created a wiki page for it, feel free to edit:   https://github.com/novus/nvd3/wiki/Data-Attributes

**Comment by liquidpele** [comment]
hmm, I assume you can edit it... can you?

**Comment by jackmarketon** [comment]
@liquidpele yep closing ticket!
