### ISSUE TITLE
is it possible to design real time charts with nvd3.js

### ISSUE THREAD

**Issue by krishnakanthpps** [novus/nvd3#1295]
I would like to embed real time charts on my php page. Would nvd3.js be a good idea? Mine is a startup and I am looking for a best available open source solution. The graphs look great and but can I embed them in my php page as real time charts with data coming in the form of json maybe be polled rom a log file.

**Comment by robinfhu** [comment]
Yes, you can create a real time chart.  There should be an example in the code.
