### ISSUE TITLE
pie chart takes only first 10 colors from aray

### ISSUE THREAD

**Issue by aanuprab** [novus/nvd3#1298]
var gColors = [  array of 30 colors  ];

var chart = nv.models.pieChart();
chart.color(gColors);

When I plot the pie chart, it takes only the first 10 colors from the array after which all the remaining colors in the pie chart are black.

Any help?

**Comment by liquidpele** [comment]
Can you give a jsfiddle to see the bug, using the latest master branch code?   Link to latest using rawgit.com

**Comment by liquidpele** [comment]
So....  Not an issue?

**Comment by aanuprab** [comment]
sorry, I figured out a piece of our code internally was messing up the array values. It was removing the hash (#) sign from the hex code after the 10th element. My bad!

**Comment by liquidpele** [comment]
np, glad you figured it out!
