### ISSUE TITLE
Multichart changing series type creates render issue

### ISSUE THREAD

**Issue by boysmovie** [novus/nvd3#1299]
When I first plot a multichart with one series of type "bar", it renders beautifully. But if I change the chart type to "line" and update the data then the bar (remnants) still exists.

Please see screenshot below. As you can see the line series is "red" color but the old bar series with blue still rendered.

**Comment by aanuprab** [comment]
If it helps, did some additional debugging:

when bar is plotted and then series type is updated to line, the rect elements under .bars1Wrap > .nv-groups never get cleared

For now I put a hack. I am clearing the chart elements before the update.
$("#chart .nv-groups").empty();
$("#chart .stack1Wrap .nv-areaWrap").empty();
