### ISSUE TITLE
Settings Documentation

### ISSUE THREAD

**Issue by jlukic** [novus/nvd3#1304]
Hi, feel free to close this if i'm missing something. It appears that a lot of the [settings in the documentation](http://nvd3-community.github.io/nvd3/examples/documentation.html) have no description. 

Is this the best location for looking up settings, or is there somewhere else? 

For example in one of the demos I noticed
```
chart.legend
  .vers('furious') 
;
```

Looking up the description of what 'vers' does or what furious means leads to "No info for this option yet..."  text in settings.
http://nvd3-community.github.io/nvd3/examples/documentation.html#legend

It actually appears that most settings for legend have no documentation.

**Comment by liquidpele** [comment]
Yup, many are missing.  If anyone wants to go through and enter any please send a pull request to the novus repo, not this one.  :)

**Comment by liquidpele** [comment]
Oh wait this is the novus repo.  Lol.  Sorry, on mobile.

**Comment by jlukic** [comment]
Thanks, glad there are some [inline comments](https://github.com/novus/nvd3/blob/master/src/models/legend.js) to start learning from

**Comment by liquidpele** [comment]
Docs are defined in big json obj at bottom of documentation.html just fyi
