### ISSUE TITLE
Mixing Candlestick and Line Charts

### ISSUE THREAD

**Issue by potsit** [novus/nvd3#1305]
I have 2 series I want to put one the same chart. The first series I just want to be a normal line chart. The second series I want to be a candlestick. Is it possible to do this in one chart?

**Comment by liquidpele** [comment]
Not currently no, multichart doesn't include candlestick charts as an option.

**Comment by petr-permyakov** [comment]
hi @potsit , did you find a solution? I have the same issue as well

**Comment by liquidpele** [comment]
Someone would have to modify multichart and send a pull request.  Multichart combines various charts, but its a bit manual in integrating each one.
