### ISSUE TITLE
Scatter distY too long on mouseover

### ISSUE THREAD

**Issue by justinjhendrick** [novus/nvd3#1306]
When I mouseover a point in a scatter plot, there are lines that come from each axis. The problem is that the line from the Y axis extends past the point.

![nvd3_distx_too_long](https://cloud.githubusercontent.com/assets/4964444/10569424/de74c51e-75f3-11e5-8fdd-086a342d29c5.png)

I'm using version 1.8.1 and below is the relevant code.

    function scatter_data() {
        var x = $('#plot_x_select').val();
        var y = $('#plot_y_select').val();
        var group = $('#plot_group_select').val();
        var data = setup_data(group);
        var grouped_data = {};
        var label = 'pulsar';
        $.each(groups, function (index) {
            grouped_data[groups[index]] = [];
        })
        if (array_data[x] === undefined) {
            return [];
        }
        $.each(array_data[x], function (i) {
            if (array_data[x][i] !== undefined &&
                array_data[y][i] !== undefined ) {
                var x_str = array_data[x][i];
                var y_str = array_data[y][i];
                var x_val = Number(x_str);
                var y_val = Number(y_str);
                grouped_data[array_data[group][i]].push({
                    x: x_val,
                    y: y_val,
                    shape: get_shape(array_data[group][i]),
                    label: array_data[label][i],
                    size: get_size(array_data[group][i]),
                    x_label: $('#plot_x_select option:selected').text(),
                    y_label: $('#plot_y_select option:selected').text(),
                });
            }
        })
        for (i = 0; i < data.length; i++) {
            data[i].values = grouped_data[data[i].key];
        }
        return data;
    }
    
    function scatter_plot() {
        nv.addGraph(function () {
            data = scatter_data()
            var chart = nv.models.scatterChart()
                .showDistX(true)
                .showDistY(true);

            d3.select('#chart svg')
                .datum(data)
                .transition().duration(500)
                .call(chart);

            nv.utils.windowResize(chart.update);

            return chart;
        });
    }

**Comment by liquidpele** [comment]
Try latest master branch... Think it is fixed already.

**Comment by justinjhendrick** [comment]
Yep. You're right. Thanks!
