### ISSUE TITLE
(Scatter) Tooltip rendering has slowed down with new chrome version (v46)

### ISSUE THREAD

**Issue by Kyeongan** [novus/nvd3#1308]
After updated chrome, tooltip rendering (scatter, x, y lines) has dramatically slowed down. I found that it had the same issues with v38 ('https://github.com/novus/nvd3/issues/702')

Anyone have the similar issues?

Thanks,

**Comment by Kyeongan** [comment]
IE and Edge have same issues   (Windows 10)
Safari has no issues (OS X El Capitan)

**Comment by liquidpele** [comment]
Can't reproduce... examples at https://nvd3-community.github.io/nvd3/examples/site.html  all work fine for me using chrome 46 on osx.

**Comment by liquidpele** [comment]
Can you verify those work for you, and if so is there an example you can show the issue somewhere?

**Comment by Kyeongan** [comment]
Could you go at http://www.scholarplot.com and run with any input (ex. "John Mustard") with different browsers? You will see the difference. I am figuring out why.

**Comment by liquidpele** [comment]
/me opens javascript console

> nv
> Object {version: "1.1.15b", dev: true, tooltip: Object, utils: Object, models: Object…}

You should probably update to a non-ancient version ;)

**Comment by Kyeongan** [comment]
Do you suggest to update v1.8.1? Let me see. But still curious why not Safari.

**Comment by liquidpele** [comment]
pay attention to the fact that tooltips were refactored in 1.8.1, so if you use custom tooltip stuff, you'll likely have to fix that.   1.7.1 is a good step, it should be completely backward compatible and has the chrome fixes.   This particular issue was an issue in chrome for a long time, no idea why you didn't see it before.  Fixes in 1.71. worked around it by redoing how we created the voronoi graph.

**Comment by Kyeongan** [comment]
Thank you!

**Comment by Kyeongan** [comment]
What is the best way to update the nvd3 library and have customized tooltips?
Should I include "src/tooltip.js" if I want to customize it?
Or, have myTooltip.js file and overwrite certain functions on it? (still need to include tooltip.js? or just include myTooltip.js?)

Thanks,

**Comment by liquidpele** [comment]
on the GitHub page there is a link to the documentation which lists out the options for the tooltip object which let you completely customize the interior of the tooltip

**Comment by Kyeongan** [comment]
Just wanted to tell nvd3 lib is stable. the performance issue from Chrome v46 that was already reported to Google Dev group and patched.
