### ISSUE TITLE
can nvd3 change the chart type dynamically like google chart

### ISSUE THREAD

**Issue by litaotao** [novus/nvd3#1311]
bellow is a screenshot of google chart in its [main page](https://developers.google.com/chart/)

it can change the chart type using the buttons bellow the graph, I browsed the examples but don't find any example like this. 

So I want to ask does nvd3 support kinds of this transform ? if not, how can I implement this in my project?

thanks a lot.

![2015-10-20 11 03 03](https://cloud.githubusercontent.com/assets/4660350/10611448/c4fd156e-777e-11e5-8bba-fef546292e0d.png)

**Comment by liquidpele** [comment]
It's never been something we considered or tested.   You're welcome to develop it into nvd3 yourself, send us a pull request and we'll be happy to review it :)
