### ISSUE TITLE
Tooltips are broken with fastdom

### ISSUE THREAD

**Issue by cybermaxs** [novus/nvd3#1319]
There is a JS error (_Uncaught TypeError: Cannot read property 'clientX' of null_) and tooltips are not displayed when adding fastdom to an example of the current master branch.

![error](https://cloud.githubusercontent.com/assets/4004029/10710439/a9866766-7a5a-11e5-9e29-f7ad00b3a4e0.JPG)

example with multiBarChart2.html : https://jsfiddle.net/2Lnee08t/1/

**Comment by ryan-ju** [comment]
I got the same issue.  I wonder if there should be tests on FastDom integration.

**Comment by EvaSDK** [comment]
About fastdom integration tests, see also #1628
