### ISSUE TITLE
Retire or replace old website

### ISSUE THREAD

**Issue by csvan** [novus/nvd3#1323]
A lot of NVD3 related Google searches still lead to the old website (http://nvd3.org/), which has badly outdated docs and solutions. It would be good if it were either shut down, replaced by the new one, or otherwise made to carry prominent notices that it is obsolete.

**Comment by liquidpele** [comment]
@robinfhu do you guys use/update that site?  It's just the gh-pages branch of this repo right?

**Comment by robinfhu** [comment]
Yes, I believe the gh-pages branch handles that website.

**Comment by robinfhu** [comment]
I'm okay with maybe renaming the gh-pages branch to something like 'gh-pages-old'.  And you could explore making the new documentation page the default landing page.

**Comment by litaotao** [comment]
but actually, I like the old one [http://nvd3.org/](http://nvd3.org/) much more than [http://nvd3-community.github.io/nvd3/examples/documentation.html](http://nvd3-community.github.io/nvd3/examples/documentation.html)


it's so fancy and attractive

**Comment by liquidpele** [comment]
Lol.   Send a pull request to the gh-pages branch to fix up that site then :)
