### ISSUE TITLE
 Meteor 1.7.1 Linechart attribute issue

### ISSUE THREAD

**Issue by Joe312341** [novus/nvd3#1345]
Hello,

After some testing it looks like the current way of adding certain attributes to the series object does not work in 1.7.1 as described in the example (see here http://nvd3.org/examples/line.html)

Example: of these attributes classed and fillOpacity does not work.
```
{
      area: true,
      values : [ [ 1 , 100] , [ 2 , 120] , [ 3 , 127] ],
      color: "#ff7f0e",
      fillOpacity: .9,
      classed: "some-class"
      key : "Quantity"
  }
```

Since 1.8.1 currently does not work for Meteor any workaround for this?

Thanks,
Joe

**Comment by liquidpele** [comment]
master has fixes for meteor, so next version should be good...
