### ISSUE TITLE
Has anyone done any waterfall chart ?

### ISSUE THREAD

**Issue by kamalpatel125** [novus/nvd3#1355]
Hello, 

I wonder if anybody has done the waterfall chart in nvd3 ?

Thanks for help in advance.

Regards,

Kamal.

**Comment by liquidpele** [comment]
Samples of waterfall charts:

http://bl.ocks.org/rsloan/7123450
http://www.highcharts.com/demo/waterfall

Not possible currently in nvd3, although it looks like someone could extend discreteBarChart to be able to have a min for each value to accomplish this.   Feel free to do it and send us a pull request :)
