### ISSUE TITLE
How to set custom  tooltips after upgrade from  1.7.1 to   1.8.1-dev?

### ISSUE THREAD

**Issue by kety33** [novus/nvd3#1359]
Hi , 
I try  to  upgrade  the  version  of  nvd3  from  1.7.1 to  1.8.1 ,
And  now ,I  see  in my charts the  default  tooltips  of  NVD3.
In  1.7.1  i  used  the  property   'tooltipContent'  that  allowed  me to define custom template of the  tooltips ,but  it  seems  to  ignore  it  in  version 1.8.1.

How  could I  define  custom  template for my  tooltips  in  version 1.8.1?

Thanks 
Kety

**Comment by liquidpele** [comment]
See contentGenerator option under the tooltip object.   Essentially, tooltips were moved into it's own object that is used for both the interactive guideline and regular tooltips.   

https://nvd3-community.github.io/nvd3/examples/documentation.html#tooltip

**Comment by kety33** [comment]
Thanks  for  the  quick  reply.
I  used  the contentGenerator,  it  work  perfect :)
