### ISSUE TITLE
Implementing new models and/or options

### ISSUE THREAD

**Issue by ghs** [novus/nvd3#1363]
First time around here so would like to apologize first if write something in not appropriate way.

I've been working on a project where a stacked chart with a brush was required. Because the current directive doesn't offer it, I had to implement something fast to do that. Also now have to implement a new event handler for the current brush ranges selection.

Before making any commit to the branch, would like to know if will be better to keep it as a new model, "stackedAreaWithBrush" or add it as an option to the current stackedAreaChart?

Thanks!

**Comment by liquidpele** [comment]
Add to the existing model if you can please.  You can look at the linechart to see how that toggles the brush.

**Comment by liquidpele** [comment]
Hmmm...   I also feel like there is an old closed PR that did this maybe...

**Comment by ghs** [comment]
OK, will use the existing one. And yes, I was basically doing the same as the line chart to make it work.

**Comment by liquidpele** [comment]
Going to close this, but feel free to still comment on it if you need anything.
