### ISSUE TITLE
<g> attribute transform=“translate(NaN,NaN)” when using Interactive Guideline

### ISSUE THREAD

**Issue by atais** [novus/nvd3#1373]
I did previously write about it on SO: http://stackoverflow.com/questions/33913680/g-attribute-transform-translatenan-nan-when-using-interactive-guideline

Everything is working fine, at the beginning. However if you decide to turn off (disable) one set of data the error rises:

```
Error: Invalid value for <g> attribute transform="translate(NaN,NaN)"
```
**I replicated the problem with a plunker:** http://plnkr.co/edit/e4D619?p=preview

*Disable any set to see the error in console. Resize the window and disable/enable the set to see the error again. Turn off useInteractiveGuideline to eliminate the errors.*

I know it uses angular wrapper, but locally I have this error replicated with clean nvd3 (not my solution). 
I am now redoing it using angular and my code is easier to present.

**Comment by kavwang** [comment]
I got the same problem. Actually I noticed that examples on the official website had the same problem.

**Comment by liquidpele** [comment]
Updated example to use latest code from master and the error no longer occures.

**Comment by liquidpele** [comment]
http://plnkr.co/edit/GigXLSr1JvcBHjdmEY3A?p=preview
