### ISSUE TITLE
Disable tooltip for specific series in multiBarHorizontalChart

### ISSUE THREAD

**Issue by RafaelAlbani** [novus/nvd3#1379]
Hi guys,

Is there some way to disable tooltip for specific series in multiBarHorizontalChart?

I've found this link below on the docs, but it seems that it only works for LineChart charts.

https://github.com/novus/nvd3/wiki/Data-Attributes

**Comment by liquidpele** [comment]
It might have only been implemented for that model... feel free to add the logic to other models that you need :)
