### ISSUE TITLE
Line chart tics wrongly aligned to grid when using datetype on xAxis

### ISSUE THREAD

**Issue by atais** [novus/nvd3#1382]
The problem I have encountered now is that my data is wrongly aligned with the Axis. Example plunker available here: http://plnkr.co/edit/jWEYt6?p=preview ,

I am using dates on my xAxis, which are parsed using d3 library:

```javascript
tickFormat: function(d) {return d3.time.format('%d/%m')(new Date(d))}
```
**Description:**

*I would expect the xAxis labels to be correspondent to the grid.*

*In the example you can clearly notice that the xAxis is not evenly devided (values: 06/11, 08/11, 11/11, 13/11). So usually 2 days and sometimes 3 days :)*

*What is worse - the peaks are not matching the grid. Example: 06/11 tick is really not even close to the grid's line where I guess it is supposed to be.*

I have also tried this on master's code from repo and it happens there too. There is a link to master version in the HTML head section.

I use angular wrapper atm but I do not think it is relevant here.
**Maybe it is D3 problem but I do not know how to debug it**

**Comment by liquidpele** [comment]
Your example looks fine to me.  Again, if you filter to show only date, it'll look weird if your data contains times.   For instance, in your example data you're using 1446850800000, which is 11/30/15 at 13:30:4, but it displays as just 11/30 even though it's going to be graphed closer to 11/31

**Comment by atais** [comment]
Ah! Well as usual - there is a time zone problem :-)

So the data actually is in CET +1. And in that timezone all the peaks are full days:
```javascript
02/11/2015 00:00:00
03/11/2015 00:00:00
04/11/2015 00:00:00
05/11/2015 00:00:00
```
etc.

So now I guess it is a matter of scaling xAxis to display full days only.

**Comment by atais** [comment]
I have solved it myself, the description is available here:
http://stackoverflow.com/questions/33959649/nvd3-line-chart-tics-wrongly-aligned-to-grid-when-using-datetype-on-xaxis
