### ISSUE TITLE
Blurred tooltip

### ISSUE THREAD

**Issue by AdamWaz** [novus/nvd3#1385]
When tooltip translate css property has floating-point number it's borders are blurred on Ubuntu Chrome.

**Comment by liquidpele** [comment]
Looks like you made a commit around this, please send a pull request if that fixed it.

**Comment by ywplee** [comment]
@AdamWaz can you put a pr for this commit? Thank you

**Comment by ywplee** [comment]
@AdamWaz since I haven't heard back from you for a while, I'll create a pr for this fix.
