### ISSUE TITLE
Create a custom pointShape

### ISSUE THREAD

**Issue by pihomeserver** [novus/nvd3#1386]
Hello,
I would like to know if it's possible to create a custom shape when a point is highlighted ? Instead of the classic circle, square, etc. I would like a circle filled with a color and with a thin border. I got the border only with the poinSize attribute set to 2 but don't know how to fill the circle with a color.

Any idea ?

**Comment by liquidpele** [comment]
Yes, there is an example of doing this in the scatter chart example, the 'X' shape is a custom one.   The scatter code is used by the line charts for their points so it applies to those as well. 

https://github.com/novus/nvd3/blob/master/examples/scatterChart.html#L32

**Comment by pihomeserver** [comment]
Thanks for the answer. I can create my own shape but with the same result than with 'circle'
If i set pointSize to 2 and the style with :
```css
.nv-point {
	stroke: #F00;
	fill: #0F0;
}
```
I have a thin red circle, one uncolored circle and a green point. The fill color does not seem to full fill the circle ...
I'm not sure it's related to nvd3 more than d3. I guess i am doing something wrong ...
