### ISSUE TITLE
Multi bar chart - Xaxis labels are overlapping

### ISSUE THREAD

**Issue by PavithraSivaraj** [novus/nvd3#1390]
In multi-bar chart the x-axis labels are overlapping on each other. Is there any way to make the text as ellipsis. I tried adding the overflow: hidden and text-overflow: ellipsis to the text element(label). It is not working. Is there any way to make the labels as ellipsis instead of rotating?

**Comment by MrKanthaliya** [comment]
you can rotate labels.
chart.xAxis.rotateLabels(-45);

**Comment by PavithraSivaraj** [comment]
When the labels are bigger, while rotating the labels the chart size is becoming very small. Is there any other way? 

Thanks in advance.

**Comment by matthewpolkiewiczsc** [comment]
+1, I'm having this same issue.

**Comment by MrKanthaliya** [comment]
Use reducexticks if its okay to not show all labels.

**Comment by matthewpolkiewiczsc** [comment]
For my use case I would still need to show all labels. Ideally it would be nice if the labels wrapped to stay below the bars, but I guess that's not possible.

**Comment by MrKanthaliya** [comment]
staggerLabels is another option..

**Comment by vineelal** [comment]
But staggerLabels option in not available in other types of charts like stackedAreaChart

**Comment by PavithraSivaraj** [comment]
I have modified it in the chartjs library since I couldn't found any other better solution. 

calculate the maximum label length and keep a truncated label like below. While calculating the xaxisLabelRotation if the rotation is less than 0 and the width is not very small then reduce the label length and then reset the labels based on the new length. 


After building the y-labels the code should be like below: 
`
this.buildYLabels();

this.xLabels = this.untruncatedLabel;
this.calculateXLabelRotation();

while(this.xLabelRotation > 0 && this.height > 180)
{
	var maxOfXLabels = this.xLabels[0].length;
	for(var i =0; i < this.xLabels.length; i++)
	{
		if(this.xLabels[i].length > maxOfXLabels)
		{
			maxOfXLabels = this.xLabels[i].length;
		}
	}
	this.labelLength = maxOfXLabels - 5;
	this.xLabels = this.labelLength > 0 ? this.xLabels.map(this.truncateLabel, this) : this.xLabels;
	this.calculateXLabelRotation();
}

if(this.height <= 180)
{
	this.labelLength = 4;
	this.xLabels = this.labelLength > 0 ? this.xLabels.map(this.truncateLabel, this) : this.xLabels;
	//this.calculateXLabelRotation();
	this.xLabelRotation = 0;
}

`

And the calculation of the truncated and non truncated labels will be before initializing the y labels like below : 
`Chart.Scale = Chart.Element.extend({
		initialize : function(){	
			this.untruncatedLabel = this.xLabels;
			this.fit();
		},
		truncateLabel: function(label) {
			if(label.length <=  this.labelLength)
			{
				return label;
			}
			else
			{
            	return label.substring(0, this.labelLength)+"...";
            }
        },
		buildYLabels : function(){
			this.yLabels = [];

			var stepDecimalPlaces = getDecimalPlaces(this.stepValue);

			for (var i=0; i<=this.steps; i++){
				this.yLabels.push(template(this.templateString,{value:(this.min + (i * this.stepValue)).toFixed(stepDecimalPlaces)}));
			}
			this.yLabelWidth = (this.display && this.showLabels) ? longestText(this.ctx,this.font,this.yLabels) : 0;
		},`

**Comment by devsandy** [comment]
can you provide any example for this i am trying the way you given for labels to be wrapped but not getting i am using chat options like this 
graph.options = {
                            chart: {
                                width: 500,
                                type: graph.type,
                                height: 500,
                                x: graph.type == 'stackedAreaChart' ? function (d) { return d[0]; } : function (d) { return d.label; },
                                y: graph.type == 'stackedAreaChart' ? function (d) { return d[1]; } : function (d) { return d.value; },....................................................................
