### ISSUE TITLE
Multichart — Negative stacked bars can not be toggled

### ISSUE THREAD

**Issue by phacks** [novus/nvd3#1391]
In a multichart with at least one line and two bars (one of which with positive values, the other negative, both stacked), an error is thrown when trying to toggle both bars (and a the second toggled bar is still present) :

`Uncaught TypeError: Cannot read property 'values' of undefined nv.d3.js:7620`

The error refers to this block, in which `data` is an empty array and `data[0]` is undefined : 

``` javascript
// HACK for negative value stacking
  if (stacked) {
    data[0].values.map(function(d,i) {
      var posBase = 0, negBase = 0;
      data.map(function(d, idx) {
        if (!data[idx].nonStackable) {
          var f = d.values[i]
          f.size = Math.abs(f.y);
          if (f.y<0)  {
            f.y1 = negBase;
            negBase = negBase - f.size;
          } else
          {
            f.y1 = f.size + posBase;
            posBase = posBase + f.size;
          }
        }

      });
    });
  }
```

I do not have a fix for this problem, but I created a jsFiddle so you can reproduce it : http://jsfiddle.net/L62mqmj8/

Thanks a lot for your help !

**Comment by jbeurel** [comment]
:+1: Needed

**Comment by tcheymol** [comment]
Wow, I got the same problem here
