### ISSUE TITLE
Boxplot improved format

### ISSUE THREAD

**Issue by Kyeongan** [novus/nvd3#1402]
Is there any option to have `mean` as an asterisk  (*) on the boxplot? Can we also have the `n` value above the top whisker similar to the image below.

![screen shot 2015-12-18 at 4 16 09 pm](https://cloud.githubusercontent.com/assets/5505099/11908560/b7b77262-a5a2-11e5-909f-6e22244825b4.png)

**Comment by liquidpele** [comment]
Not that I know of (I didn't make that model)... you'll have to add that feature if you'd like it :)
