### ISSUE TITLE
Update 'nvd3' npm module

### ISSUE THREAD

**Issue by ovvn** [novus/nvd3#1404]
The npm module was published 6 months ago. It makes sense to use the latest api in order to utilize new chart components parameters.

**Comment by topicus** [comment]
+1

**Comment by Maskl** [comment]
+1

**Comment by rbvea** [comment]
+1

**Comment by rdubigny** [comment]
+1

**Comment by liquidpele** [comment]
Well, I made release 1.8.2 but npmjs hadn't picked it up yet... not sure what's up with that

**Comment by mqklin** [comment]
very strange..........................

**Comment by liquidpele** [comment]
Okay, looks like you have to do "npm publish" every damn time -_-

https://stackoverflow.com/questions/13507763/do-i-need-to-publish-to-npm-every-time-i-update-a-package-available-via-git

I guess I'll try setting up travis to do it for me at some point.

**Comment by mqklin** [comment]
looks much better ;)

**Comment by mqklin** [comment]
@liquidpele , can you publish *dev* version as well?

**Comment by liquidpele** [comment]
yep.

**Comment by liquidpele** [comment]
Hmm... I pushed up dev before I build the latest files, and it won't let you publish again with the same version... lol

https://github.com/npm/npm/issues/9266

npmjs really makes their thing a pain in the ass to use.

**Comment by liquidpele** [comment]
I don't think they ever intended people to publish dev versions.

**Comment by ThomasBrierley** [comment]
I think this probably has more to do with adhering to the well reasoned git best practice of not changing which commit a published tag points to... it just has the potential to cause so much pain for users. I find it painful enough that tags can be removed, but I guess the logic there is to get version range selectors to automatically downgrade from seriously broken releases.

Is it possible to use a distinct "dev" tag to prevent this in future? I've seen some repositories use a ```-dev``` postfix on versioned tags. Although I have no idea how well this integrates with npm.

**Comment by liquidpele** [comment]
I published 1.8.2-dev from just master branch, no tags involved.  I dunno...   Not that worried about it I guess, people should use the 1.8.2 I published from the v1.8.2 tag.

**Comment by liquidpele** [comment]
had to remove 1.8.2-dev from npm, as people asking for latest were getting that and it's the under development code.
