### ISSUE TITLE
Stacked + Multibar chart

### ISSUE THREAD

**Issue by quadrologic** [novus/nvd3#1405]
Is there an ability to merge Stacked bar chart and MultiBar chart?
I need columns to group like in MultiBar, and some of the columns should be Stacked.
That is, there will be 3 colums for each value which is located on x axis: the firts is bar, the second and the third are stacked.

**Comment by liquidpele** [comment]
You an make an attribute on a series called "nonStackable" and set it to true, then that series won't stack even if you change it to stacked.
