### ISSUE TITLE
Sample 'Your first line chart' doesnt work

### ISSUE THREAD

**Issue by GerhardKreuzer** [novus/nvd3#1416]
Hi,
just tried this sample, doesn't work out. 'a.map' throuws an error cause a isn't defines, for what reason ever.

With best regards

Gerhard

**Comment by liquidpele** [comment]
Can you link to what example you're looking at?

**Comment by GerhardKreuzer** [comment]
Oh, sorry, to Long ago .. but currently happy with nvd3.
