### ISSUE TITLE
Interpolation

### ISSUE THREAD

**Issue by GerhardKreuzer** [novus/nvd3#1417]
Hi,
how can I set the Interpolation method for a lind graph?

Thanks for helping.

With best regards

Gerhard

**Comment by mgalloue** [comment]
Hi,
As you can see on the [documentation](http://nvd3-community.github.io/nvd3/examples/documentation.html#lineChart) you can set the interpolation method like this: chart.interpolate("linear")

Regards,

**Comment by GerhardKreuzer** [comment]
Thanks.

 

Sorry, but can’t view the documentation, web site doesn’t respond today (in the morning), maybe it works some other day?

 

With best regards

 

Gerhard

 

Von: Mathilde [mailto:notifications@github.com] 
Gesendet: Montag, 04. Jänner 2016 14:09
An: novus/nvd3
Cc: GerhardKreuzer
Betreff: Re: [nvd3] Interpolation (#1417)

 

Hi,
As you can see on the documentation <http://nvd3-community.github.io/nvd3/examples/documentation.html#lineChart>  you can set the interpolation method like this: chart.interpolate("linear")

Regards,

**Comment by mgalloue** [comment]
Oh weird, it works well on my side. I copy the interesting part then:

Description:
controls the line interpolation between points, many options exist, see the D3 reference:
https://github.com/mbostock/d3/wiki/SVG-Shapes#line_interpolate
Input Type(s):
string
Default:
linear
Example(s):
chart.interpolate("linear")
chart.interpolate("step")

**Comment by GerhardKreuzer** [comment]
.. thanks.

 

Is it possible to have an interpolation method on a line. So one chart, two lines and each line has it‘s own interpolation method?

 

With best regards

 

Gerhard

 

Von: Mathilde [mailto:notifications@github.com] 
Gesendet: Montag, 04. Jänner 2016 14:37
An: novus/nvd3
Cc: GerhardKreuzer
Betreff: Re: [nvd3] Interpolation (#1417)

 

Oh weird, it works well on my side. I copy the interesting part then:

Description:
controls the line interpolation between points, many options exist, see the D3 reference:
https://github.com/mbostock/d3/wiki/SVG-Shapes#line_interpolate
Input Type(s):
string
Default:
linear
Example(s):
chart.interpolate("linear")
chart.interpolate("step")

**Comment by mgalloue** [comment]
Mmmm, not sure about that...

**Comment by liquidpele** [comment]
no, it's not currently supported by line, just for the whole chart.

**Comment by GerhardKreuzer** [comment]
.. thanks.

 

Gerhard

 

Von: liquidpele [mailto:notifications@github.com] 
Gesendet: Mittwoch, 27. Jänner 2016 21:43
An: novus/nvd3
Cc: GerhardKreuzer
Betreff: Re: [nvd3] Interpolation (#1417)

 

no, it's not currently supported by line, just for the whole chart.
