### ISSUE TITLE
No live update of line chart

### ISSUE THREAD

**Issue by GerhardKreuzer** [novus/nvd3#1418]
Hi,
tried to update a linechart. I take the linechart.html sample and incorporated it in one of my pages. Works fine, but I can't update the data.
After playing around I found a method which works out.

Any explainations for a newbee??

function update()
		{
			data = generateRandomData();
			chart.update; // nothing happens
			d3.select('#chart1').datum(data).call(chart);  // works
		};
Forget to say, that I used the both update methods mutual exclusive to test it out.
Just removed the // characters ..

With best regards

Gerhard

**Comment by mgalloue** [comment]
Hi,
In your example you need to use .datum() because you re-assign a new data set.
If you want to use chart.update() function you have to change data object itself (like data[0].values[0].y = 10).

Regards,

Mathilde

**Comment by GerhardKreuzer** [comment]
.. ok, thanks Mathilde

 

Von: Mathilde [mailto:notifications@github.com] 
Gesendet: Montag, 04. Jänner 2016 14:04
An: novus/nvd3
Cc: GerhardKreuzer
Betreff: Re: [nvd3] No live update of line chart (#1418)

 

Hi,
In your example you need to use .datum() because you re-assign a new data set.
If you want to use chart.update() function you have to change data object itself (like data[0].values[0].y = 10).

Regards,

Mathilde

**Comment by mqklin** [comment]
@GerhardKreuzer, close the issue if that's all

**Comment by GerhardKreuzer** [comment]
This works now, but can't do it periodically. Only if the Debugger is on, but this is maybe another issue
