### ISSUE TITLE
Background color Stacked Area Chart

### ISSUE THREAD

**Issue by jcrichard** [novus/nvd3#1419]
Hi all,

The background color of Stacked Area Chart is white by default but I would like transparent like for bar chart.

How can I do that ,

thanks a lot

**Comment by mgalloue** [comment]
You can define a transparent color using "rgba(x, y, z, 0)" but I'm not sure it's what you want, what do you mean by "like for chart" ?

**Comment by jcrichard** [comment]
Because I do not have this problem for bar chart. For example if I insert my graph in an HTML page with custom background I can see it when I use bar chart but I can't  with stacked area chart because the chart background is white.

**Comment by mgalloue** [comment]
Can you provide a jsfiddle with your example?

**Comment by mgalloue** [comment]
If I well understand what you need, you can add this into your css: 
`.nvd3.nv-stackedAreaChart rect{
    opacity: 1!important;
    fill:white;
}`

**Comment by jcrichard** [comment]
Yes that's working perfectly thanks a lot.
