### ISSUE TITLE
Scale, Domain

### ISSUE THREAD

**Issue by GerhardKreuzer** [novus/nvd3#1424]
Hi,
I want to have a fix scale in y.
My Signal is about +-0.1 sometimes but I want to have a chart with +-10 in y.
Currently the chart resizes automatically to fit the signal, this is not natural.
I tried this line:

chart.yScale(d3.scale.linear().domain([-10, 10]));

Doesnt work out, any idea?

With best regards

Gerhard

**Comment by mgalloue** [comment]
Hi,
You can try chart.yAxis.domain([-10,10]);

Regards,

**Comment by GerhardKreuzer** [comment]
.. ok, thanks.
Found another way:

chart = nv.models.lineChart()
            .options({
                       transitionDuration: 300,
                       useInteractiveGuideline: true,
                       yDomain : [-10, 10]
                     })
          ;
Will also try your solution.

I have still problems viewing the documentation.
Now I read the script behind documentation.html, which contains the Information, but hard to read and follow ...

With best regards

Gerhard

**Comment by GerhardKreuzer** [comment]
.. sorry Mathilde but your statement didn't workout here.
Maybe it will be a good idea, to find out the correct way(s) and write this into the documentation, each technical viewing needs something like this (to compare signal properties).

With best regards

Gerhard

**Comment by mgalloue** [comment]
Oh sure, using yDomain is totally the correct way, I just missed this option!
I don't understand why documentation doesn't work on your side, still working on mine...

**Comment by mgalloue** [comment]
Can you please close the issue if it's ok for you ?
Thanks,

**Comment by GerhardKreuzer** [comment]
Hi,
tried to open it on the web site, waiting for a long time, no response.
Have a local copy, changed the script path to get it from the github server, but still no success.

I gon't use Git and so I don't have the whole repository here, just want to use nv ...

With best regards

Gerhard

**Comment by GerhardKreuzer** [comment]
Ok, Close it.

With best regards

Gerhard
