### ISSUE TITLE
Update stacked bar chart with click event

### ISSUE THREAD

**Issue by jcrichard** [novus/nvd3#1429]
Hi all,

I would like to know if it is possible to add a click event in stacked bar chart. For example with http://nvd3.org/examples/multiBar.html I would like to click on a bar (stream 1 for instance) and then  the bar chart  will be updated with new data and new legend.

I can do it with a  <select> element  where I choose the data but I would like to know if there is an easy way to do it with a click event.

edit:

In fact if I use onClick I can update my chart like :

     myChart = d3.select('#multibarchart svg').on('click',
  	    	    function(){

	    		  var n = d3.select("rect")
	    		  .text(function(d) {
	    			  return d.label
	    		  })
	    		  console.log(n);
	    	  });

I have something in the console.
 I have two problems:
- first I don't no how tow get the key of the bar I click on (I would like stream # 1 for instance)
- second when I click on the legend to select data, I loss my click property

Thanks for your help

Thanks a lot.

**Comment by jcrichard** [comment]
In fact if I use onClick I can update my chart like :

     myChart = d3.select('#multibarchart svg').on('click',
  	    	    function(){

	    		  var n = d3.select("rect")
	    		  .text(function(d) {
	    			  return d.label
	    		  })
	    		  console.log(n);
	    	  });



I have two problems:
- first I don't no how tow get the key of the bar I click on (I would like stream # 1 for instance)
- second when I click on the legend to select data, I loss my click property

Thanks for your help

Thanks a lot.

**Comment by mgalloue** [comment]
Hi, can you provide an example on a jsfiddle? It will be easier for me to help you.
Thanks

**Comment by jcrichard** [comment]
Hi,

this jsfiddle shows that I loss the click property:

http://jsfiddle.net/jrichard/z4aZ4/615/

**Comment by jcrichard** [comment]
Oh I think I found the solution adding one click in my updateFunction:

http://jsfiddle.net/jrichard/z4aZ4/619/

Is it the good way to do that ?

**Comment by jcrichard** [comment]
I tried several ways but each time clicking on the legend make my onclick disappear

**Comment by jcrichard** [comment]
Hi 

I still have not  find a solution. Is it possble to do that with NVD3 or I should do my own stacked bar chart in D3?

**Comment by liquidpele** [comment]
You had an ancient version on that jsfiddle... I updated it to use the latest code on master.  I also attached to the renderEnd dispatch so that after the chart re-renders it always re-attaches the on-click events. 

https://jsfiddle.net/n57ee84g/1/

**Comment by jcrichard** [comment]
Thanks a lot and thanks for your work it is really a great tool.

**Comment by arojoal** [comment]
Thanks for your examples. I need something similar with an aditional requirement.. I would like to "attach" a key to each bar and, when an specific bar is clickd i would like to get that key in order to use it to , for example, filter results for that key. How could I do it?
