### ISSUE TITLE
showAxes option

### ISSUE THREAD

**Issue by sbai** [novus/nvd3#143]
I'd like to see a showAxes option added to all the charts, similar to the existing showLegend and showControls options. This would just disable rendering any tick labels and such along the axes if showAxes is set to false.

**Comment by ImranAhmed** [comment]
Is there anyway to set showXAxis to false but still have the grid lines appear on the chart? At the moment setting this to false also removes the vertical grid lines for the x axis labels.

**Comment by robinfhu** [comment]
@ImranAhmed there's no way to do it with javascript. You can use CSS to add display:none to the axes elements you don't want.
