### ISSUE TITLE
Combine both axis of LinePlusBarChart

### ISSUE THREAD

**Issue by AlbRoehm** [novus/nvd3#1430]
Hi, 

i'm trying to create a Chart using LinePlusBarChart model. I added a bar series and 2 line series and changed some colors. Everything's fine except that the bars and the lines should be scaled together and not seperatly. The lines should show data like mean/min/max which is not really working well if they are scaled differently. I already tried to use a fixed domain for the axis which is working but on the cost of the rescaling feature if you use the focus. I think i should somehow put all the data together an scale the axis according to the complete data, but failing to accomplish this.  Any help would be appreciated.

**Comment by mgalloue** [comment]
Hi, can you please provide a jsfiddle with your example?

**Comment by AlbRoehm** [comment]
I'm sorry cant setup a jsfiddle right now, but i have a working example on our server you could take a look at. 
http://banksoft.igd-r.fraunhofer.de/diatrace/dhc_proto_vis/nvd3/dhc_daychart.html

**Comment by AlbRoehm** [comment]
If you take a look at your example at http://nvd3-community.github.io/nvd3/examples/linePlusBarChart.html you can see my problem. I want the left and right y axis to be scaled together.

**Comment by mgalloue** [comment]
If I well understand what you want, I guess you can ha

**Comment by AlbRoehm** [comment]
Thanks for your help! I think you got me right. I had something similar to your solution but, if you hover over the biggest blue bar, you'll see that it is not scaled correctly(Data=19, on the Axis = 21). Also the feature of adjust the view if you have only low values is lost with this fixed yDomain1. 
![clipboard02](https://cloud.githubusercontent.com/assets/8029910/12235968/7e1c7d4e-b877-11e5-8d34-5a038996a993.jpg)

**Comment by mgalloue** [comment]
Mmm right my bad, I didn't check the values..Why do you want 2 axis If it's the same scale? I'm a little busy right now but if I have time I will take a second look.

**Comment by AlbRoehm** [comment]
I dont really need 2 Axis, i just looked into your examples and found this one with 2 axis, and tryed to change it a little to fit my need. if you can tell me how use only one axis i guess it would be fine too. I looked at your multiChart already but didnt find the clue how to put all the series on the same axis

**Comment by mgalloue** [comment]
Yes, multiChart seems to be more appropriated in your case. To put all the series on the same axis just set all the yAxis to 1. Look at [this](https://github.com/novus/nvd3/blob/master/examples/multiChart.html) example and set all yAxis to 1. You have all the series on the same axis.

**Comment by AlbRoehm** [comment]
Thanks to your hint i was able to fix it. I had to add .yDomain(yDomain1) to both axis, bars, lines and calculate the yDomain1 according to the data inside the brush similar to focusBarsWrap.

The multiChart doesn't has a focus, that's why i chose the LinePlusBarChart

**Comment by raphael-psr** [comment]
@AlbRoehm I'm having the same issue, do you have the jsfiddle of a working example?

**Comment by AlbRoehm** [comment]
@raphael-psr 
I'm sorry i don't have access to the code anymore. Maybe you can look at https://jsfiddle.net/9x1y68sn/3/ . If i remember correctly you have to change the code of bars (729) and lines (736) and add the same domain. I tryed, but i couldn't remeber my solution. Sorry to be not much help :(
