### ISSUE TITLE
Multichart scatter type does not render

### ISSUE THREAD

**Issue by laxu** [novus/nvd3#1431]
If a series is set as scatter type in a multichart, it does not render at all. Below you can find example of this using code from examples.

http://plnkr.co/edit/rh0cLdjHpS0yVsqXiTKd?p=preview

**Comment by mgalloue** [comment]
It not seems to be supported as you can see on the (documentation)[http://nvd3-community.github.io/nvd3/]. You can use type "bar", "line" and "area". This is an enhancement request.

**Comment by mgalloue** [comment]
My bad, it should work..

**Comment by mgalloue** [comment]
I tried with the current NVD3 build on master branch and it works.

**Comment by liquidpele** [comment]
Looks to be fixed in master already then.   closing, please re-open if you have further issues.
