### ISSUE TITLE
Uncaught TypeError: arcs[idx] is not a function

### ISSUE THREAD

**Issue by AaronMegaphone** [novus/nvd3#1441]
Hi there,

I'm having an interesting issue. I'm trying to generate a varying number of pie charts on a page. But, every once in a while I get this error `Uncaught TypeError: arcs[idx] is not a function`. I can guarantee it to occur if I set the duration above 1, apparently setting it to 1 mitigates the problem. It occurs more frequently the more pie charts I generate on a page. Any advice is greatly appreciated. 

Here is what I have

``` javascript
var chart_pie_contents_non_trivia = nv.models.pieChart()
        .margin({top: 0, right: 0, bottom: 0, left: 0})
        .x(function(d) { return d.label })
        .y(function(d) { return d.value })
        .growOnHover(false)
        .showLabels(true)
        .showLegend(false)
        .labelThreshold(.05)
        .valueFormat(d3.format(".0f"))
        .labelType("percent")
        .donut(true)
        .donutRatio(0.1);
```

``` javascript
nv.addGraph(function() {
   d3.select("#chart_pie_content_<%= content.content_nr %> svg")
      .datum( <%= content.pie_chart_non_trivia.html_safe %>)
      .transition().duration(1) //changing the duration to 1200 makes it fail all the time
      .call(chart_pie_contents_non_trivia);
    nv.utils.windowResize( function() {
       chart_pie_contents_non_trivia.update();
    })
    return chart_pie_content_<%= content.content_nr %>;
});
```
The stuff between <%= %> is just ruby code to generate dynamic content

Here is an image of my console

![screen shot 2016-01-12 at 4 53 37 pm](https://cloud.githubusercontent.com/assets/15112402/12278099/27039390-b94d-11e5-869b-8584346d480c.png)

and here we can see a chart partially rendered

![screen shot 2016-01-12 at 4 55 03 pm](https://cloud.githubusercontent.com/assets/15112402/12278119/41c4cc6c-b94d-11e5-8621-1273e9b4e2fc.png)

Note there are charts above it that are fully rendered. 

Please any help is appreciated, I've been stuck on this for a while.

**Comment by AaronMegaphone** [comment]
I was able to solve this by placing the nv.models.pieChart() inside the nv.addGraph() function

**Comment by qstrahl** [comment]
@AaronMegaphone Can you please elaborate on your solution? Where are you calling `nv.addGraph`, what does your code look like now? This issue is ruining my life.

**Comment by AaronMegaphone** [comment]
@qstrahl It would kind of look like this: 

    nv.addGraph(function() {
       var chart_pie_contents = nv.models.pieChart()
       ...
       d3.select("#chart_pie_content_<%= content.content_nr %> svg")
       ...
       nv.utils.windowResize( function() {
           chart_pie_contents.update();
       })
       return chart_pie_content_<%= content.content_nr %>;
    });

**Comment by liquidpele** [comment]
Yes, you're supposed to use addGraph to create the graphs like all the examples show.

**Comment by ShineOfFire** [comment]
AddGraph not resolve this problem i have same problem when i update my data if i remove one key is crashed
