### ISSUE TITLE
Updating graphs by clicking on other pieces of other graphs

### ISSUE THREAD

**Issue by jhwhite** [novus/nvd3#1445]
Is it possible to "attach" graphs? 

For example if I have two pie charts, if I click on a slice of one of the pie charts, it updates the entirety of the other pie chart?

**Comment by jcrichard** [comment]
I think you can, it is similar to what like I did for bar chart https://github.com/novus/nvd3/issues/1429. Just add a click event on the element you click and then update the other pie chart. But you will probably face the same problem I have when you click on the legend.

**Comment by liquidpele** [comment]
You can attach events to the dispatch object on each chart to catch clicks, then just update the chart data for another chart and call chart.update().
