### ISSUE TITLE
multiChart doesn't dispatch 'renderEnd' event

### ISSUE THREAD

**Issue by ddykhoff** [novus/nvd3#1446]
graph = nv.addGraph({
        generate: function() { 	   
            chart = nv.models.multiChart();
            chart.dispatch.on('renderEnd', function(){ 
                console.log('render complete'); 
            });
        }
    });

This above code results in 

    Uncaught TypeError: Cannot read property 'on' of undefined

from the d3 library.

**Comment by ddykhoff** [comment]
I was able to enable it by modifying the distribution file nv.d3.js, but the event gets called at the incorrect time as the chart is still being rendered when it is called. There appears to be some sort of animation going on that prevents this from working as expected.

**Comment by liquidpele** [comment]
You should just have to use addGraph's callback. 

    var chart;
    graph = nv.addGraph({
        generate: function() {     
            chart = nv.models.multiChart();
        },
        callback: function() {
            chart.dispatch.on('renderEnd', function(){ 
                console.log('render complete'); 
            });
        }
    });

**Comment by ddykhoff** [comment]
Hi @liquidpele, it looks like the callback function is called before the animations are completed for multiChart, i.e. renderEnd isn't exactly true as it is still rendering (if you consider animating part of rendering, which the other charts seem to do).

**Comment by verasztol** [comment]
Hi! 
Try this:
`scope.options = {
            chart: {
              lines1: {
                dispatch: {
                  renderEnd: function() {
                    // TODO
                  }
                }
              },`
