### ISSUE TITLE
Programatically select a line in a line chart

### ISSUE THREAD

**Issue by mpGitHub** [novus/nvd3#1447]
Is there a way to easily select a particular line in a line chart?  The closest suggestion I've found was to try and trigger a click on a particular legend element.  So maybe something like this might work?
<pre>
var ev = document.createEvent("SVGEvents");
ev.initEvent("click",true,true);

var target = $("svg>g>path[fill='#0011cc']").get(0); // get the SVG element here
target.dispatchEvent(ev);  // like $(target).trigger('click') - but working!
</pre>
Is there a better suggested approach to this?  Perhaps something baked into NVD3 that I haven't found yet?

Thanks!

**Comment by mpGitHub** [comment]
Still not sure this is the "approved" route, but for those out there this worked for me.

<pre>
   // Create SVG event  
   var ev = document.createEvent("SVGEvents");
   ev.initEvent("dblclick",true,true);

   //Find the Legend items
   var legendItems = $("#myChart svg").find(".nv-legend").find(".nv-series") ;
   // Pick the 4th legend item and select it
   var target = legendItems[3];
   target.dispatchEvent(ev);
</pre>

**Comment by mpGitHub** [comment]
Ok - this seems to work in both Chrome/IE.

It still would be nice for a cleaner approach, but this works well...  I found some of this logic in this post: http://stackoverflow.com/questions/9063383/how-to-invoke-click-event-programmatically-in-d3

<pre>
      // Find the legend in the chart
      legendItems = d3.select("#myChart svg").select(".nv-legend").selectAll(".nv-series") ;

      // Grab the second item in the legend...
      // (just randomly picking one here to show how it works)
      var target = legendItems[0][1];
      // Common function to use for a trigger
      jQuery.fn.d3DblClick = function () {
         this.each(function (i, e) {
             var evt ;
            //This is true for IE,chrome,firefox
            if(document.createEvent){
               // To create a mouse event , first we need to create an event and then initialize it.
               evt = document.createEvent("MouseEvents");
               evt.initMouseEvent("dblclick",true,true,window,0,0,0,0,0,false,false,false,false,0,null);
            }
            else{
               evt = new MouseEvent('dblclick', {
                  'view': window,
                  'bubbles': true,
                  'cancelable': true
               });
            }

            e.dispatchEvent(evt);
         });
      };
      // Execute double click 
      $(target).d3DblClick();
</pre>

**Comment by liquidpele** [comment]
You should be able to just set the "disabled" attribute on all the series objects except the one you want to display and then call chart.update()

https://github.com/novus/nvd3/blob/master/src/models/lineChart.js#L222
