### ISSUE TITLE
Chart suggestion: histogram with optional cumulative frequency/distribution line

### ISSUE THREAD

**Issue by daluu** [novus/nvd3#1455]
Great sample charts. This is an enhancement request: It would be nice if in the future, an example for histogram was added. Furthermore, even better would be an example for histogram with a cumulative frequency/distribution line on the same chart.

I like this chart http://nvd3.org/examples/linePlusBar.html, port that to what I describe?

What I'm referring to is this: http://www.tulane.edu/~salem/Images/Cumulative-Histogram.gif

d3 has some histogram examples, though none with the cumulative frequency line: http://bl.ocks.org/mbostock/3048450
http://www.frankcleary.com/making-an-interactive-histogram-in-d3-js/

I think I may have found something for cumulative frequency/distribution, but not quite histogram: http://racingtadpole.com/blog/curve-fitting-cdf-js-d3/

**Comment by liquidpele** [comment]
You can use linePlusBar to do it, you'd just have to calculate the cumulative values yourself.

**Comment by daluu** [comment]
Sadly, it doesn't seem intuitive from the linePlusBar example how to modify it for a histogram with CDF line, since the example seems to expect the input data in a certain format rather than it being flexible and a brief look at the nvd3.org site doesn't appear to mention documentation for this library so I can figure out what to do in terms of formatting/rendering. I don't have time right now to delve into code to reverse engineer the logic.

I got halfway there, converting a sample input data format to the linePlusBar chart format in the example, and the rendered chart is in the pattern I'm expecting to be (the line and the bars) however, it looks messed up. I'm simply using the example code as is with slight changes to account for the histogram data. See attached screenshot for reference.

I had better luck following another solution, with this result: https://gist.github.com/daluu/f58884c24ff893186416, visualized at http://bl.ocks.org/daluu/f58884c24ff893186416

the linePlusBar version is here: https://gist.github.com/daluu/6930fa129bffea638189

What changes need to be made to make it look more like the other solution, or even the original linePlusBar example (but for a histogram)?

**Comment by daluu** [comment]
![screen shot 2016-01-26 at 7 36 38 pm](https://cloud.githubusercontent.com/assets/637306/12603090/4fb5ff40-c464-11e5-8eaa-b7c7c7689a79.png)

**Comment by daluu** [comment]
I assume it is a possibility of dataset being small (at least with respect to the points on the line), how to make the code adjust for any given dataset size (large & small)?
