### ISSUE TITLE
LinePlusBarChart: set Brush to minimal fixed size

### ISSUE THREAD

**Issue by AlbRoehm** [novus/nvd3#1460]
I'm working on Chart using the LinePlusBarChart and I'm trying to set the Brush somehow to a fixed minimal size of for example 10 Items. Is there any easy solution which i'm not able to see right now. Thanks for your help in adavance

https://jsfiddle.net/9x1y68sn/3/

I found something similar in pure d3:
http://bl.ocks.org/raffazizzi/3691274

**Comment by liquidpele** [comment]
IIRC, you can use the brushExtent option:

https://nvd3-community.github.io/nvd3/examples/documentation.html
