### ISSUE TITLE
What is the difference between `1.8.2` and `1.8.2-dev`?

### ISSUE THREAD

**Issue by tellnes** [novus/nvd3#1462]
Hi

I see that you have cut two releases today. Their version naming indicates that the last one is a dev version? In that case, maybe you should not mark that as the latest but instead mark `1.8.2` as the latest stable version.

Btw, your changelog states
```
Lots of community bugfixes and a few extra minor features
```

Since you are writing extra minor features, maybe this should have been a minor version bump?

**Comment by liquidpele** [comment]
master branch has the -dev on it so that people realize it's under development and isn't a stable release.

**Comment by tellnes** [comment]
Maybe you can mark `1.8.2` as `latest` then and `1.8.2-dev` as eg `dev`. Right now if you do `npm install nvd3` or has eg `~1.8.1` in your package.json fil, then you will get `1.8.2-dev`.

For details, see
https://docs.npmjs.com/cli/dist-tag
https://docs.npmjs.com/cli/publish

**Comment by liquidpele** [comment]
I unpublished 1.8.2-dev
