### ISSUE TITLE
Tooltip doesn't hide when scrolling out of svg

### ISSUE THREAD

**Issue by jamiis** [novus/nvd3#1463]
video of the bug in action: https://youtu.be/65XYhICEcvw

Basically [`mouseHandler()`](https://github.com/novus/nvd3/blob/master/build/nv.d3.js#L222) isn't called on scroll events for the svgContainer. I've fiddled with `svgContainer.on("scroll", mouseHandler)`, similar to [here](https://github.com/novus/nvd3/blob/master/build/nv.d3.js#L361) and also `d3.select(window).on("scroll",mouseHandler)` (which, obviously, doesn't work when calculating `d3.mouse(window)`). 

I'll continue fiddling but thought I'd drop this here to see if this bug is known or if someone is already working on it.

**Comment by liquidpele** [comment]
I think this might have just been fixed please check the latest build in master

**Comment by jamiis** [comment]
@liquidpele just upgraded from `1.8.1` to `1.8.2` and the bug is still present

**Comment by liquidpele** [comment]
master has a bunch of bug fixes that aren't in the latest release

**Comment by jamiis** [comment]
wasn't 1.8.2 cut two days ago? are you saying master has a bunch of bug fixes within the past couple of days?

**Comment by liquidpele** [comment]
yes there was a you large backlog of pull requests going back about 2 months I cut the release and then merged a lot of thise

**Comment by jamiis** [comment]
bug persists when using `1.8.2-dev`, `nvd3/build/nv.d3.js`, [`6ab9646`](https://github.com/novus/nvd3/commit/6ab9646366f4052fc2465f53c9a9265f7b5f8c97)

**Comment by liquidpele** [comment]
Cool, thanks for verifying!

**Comment by jamiis** [comment]
May not add any new information, but the bug is occurring on iOS as well: https://youtu.be/J9b6HRFUyyY that's a tricky case to handle since it's about detecting the position of the tooltip in relation to the svg than the mouse in relation to the svg

**Comment by jamiis** [comment]
this is my current solution that I'm using outside of nvd3

```
d3.select(window).on("scroll."+chart.id(), function() {
    chart.tooltip.hidden(true);
    chart.interactiveLayer.tooltip.hidden(true);
});
```

where `chart` is a nvd3 chart. I hide both the regular tooltip and the interactiveLayer tooltip to cover both cases for `userInteractiveGuidelines`.

**Comment by Tahirhan** [comment]
Same issue on safari browser
