### ISSUE TITLE
Two y axis

### ISSUE THREAD

**Issue by GerhardKreuzer** [novus/nvd3#1465]
Hi,
I have to plot voltage and current in one Chart, so it will be fine to have two y axis (maybe one left and one right) to have voltage and current readings.

Any Chance to get this?

With best regards

Gerhard

**Comment by liquidpele** [comment]
You can use multiChart and put one on each y axis.

**Comment by GerhardKreuzer** [comment]
.. sorry to bother you, just look at the samokes, only found LineChart with Bar which shows two y axis, can’t found a sample called ‚multiChart‘

 

With best regards

 

Gerhard

 

Von: liquidpele [mailto:notifications@github.com] 
Gesendet: Mittwoch, 27. Jänner 2016 22:20
An: novus/nvd3
Cc: GerhardKreuzer
Betreff: Re: [nvd3] Two y axis (#1465)

 

You can use multiChart and put one on each y axis.

**Comment by liquidpele** [comment]
View the examples that are included in the repository here: 

https://nvd3-community.github.io/nvd3/examples/site.html
