### ISSUE TITLE
Animate pie chart on page load

### ISSUE THREAD

**Issue by jhwhite** [novus/nvd3#1466]
I found closed issue #485 and I'm trying to do the same thing. I was curious if this was ever implemented.

Thanks!

**Comment by liquidpele** [comment]
nope, you'd have to add in the functionality

**Comment by jessenieminen** [comment]
I took a quick swing at implementing this and run into some issues. Basically I'd like to keep the current animation for toggling on and off individual slices but then use this something like the first part of the animation [here](bl.ocks.org/mbostock/4341574)  for the initial load but couldn't find a way to make that happen.

Do you have a suggestion on how to implement something like that @liquidpele? Is there some way to replace an existing transition for an element after the transition has completed on the page load? I tried the "end" callback for the transition but was just able to add another animation on top of the previous one, not replace it.
