### ISSUE TITLE
Regression: renderEnd not fired for lineChart

### ISSUE THREAD

**Issue by peller** [novus/nvd3#1468]
See [this fiddle](https://jsfiddle.net/2wfy7g32/1/) running with v1.8.1

and [this fiddle](https://jsfiddle.net/2wfy7g32/2/) with v1.8.2

Look for the console log `"RENDEREND"`  It only appears in the first fiddle.

**Comment by liquidpele** [comment]
huh, that's weird.  looks like a bug.

**Comment by mehranshakeri** [comment]
+1

**Comment by mattkolb** [comment]
renderEnd does appear to fire for models without duration (ie. a pie chart fires but line and discrete bar do not). Calling chart.duration(250) means that renderEnd gets called on page load, but it doesn't get called when the window is resized (ie. nv.utiles.windowResize(function() { chart.update(); })

For the line chart, I don't actually get any events dispatched.

I hope that debug info helps trigger an idea for a fix.

Tried updating to 1.8.2 today to take advantage of all of the great work on tooltips, but this is holding us back. It would also be great to have the following bug fix rolled out in the next version (valueFormatter is hard coded in 1.8.2):
https://github.com/novus/nvd3/blob/master/src/models/lineChart.js#L421

**Comment by peller** [comment]
bump

**Comment by ffffranklin** [comment]
+1

**Comment by liquidpele** [comment]
If anyone would like to take this defect on, please send me a pull request :)

**Comment by peller** [comment]
@liquidpele would welcome some clues on where to look

**Comment by mehranshakeri** [comment]
I just checked your fiddle links in first post and it seems it works fine with "1.8.4-dev". Can anyone else confirm that it's fixed in the latest version?

**Comment by peller** [comment]
yes, thanks @mehranshakeri  It appears to be fixed in 1.8.4

**Comment by liquidpele** [comment]
neat.  good work everyone!   :p
