### ISSUE TITLE
Uncaught TypeError: chart.tooltipContent is not a function

### ISSUE THREAD

**Issue by zoe-stockholm** [novus/nvd3#1471]
I've encountered a error like the title when I reload the page since this morning. The pie chart didn't appear BUT It was working smoothly before. The js code below. I saw one guy asked the similar issue on stackoverflow 1 hour before me. check the link http://stackoverflow.com/questions/35125110/django-nvd3-chart-tooltipcontent-is-not-a-function

Does anyone have any idea? Is it somewhere I did wrong or is it because NVD3's issue? Many thanks! 

<script>
    data_piechart_container_797342=[{"values": [{"value": 3.0, "label": "_BRITNY SALES / SALES"}, {"value": 3.0, "label": "Sveriges Byggindustrier / SALES"}, {"value": 2.0, "label": "_BRITNY INTERN TID / INTERNAL"}], "key": "Serie 1"}];
    nv.addGraph(function() {
        var chart = nv.models.pieChart();
        chart.margin({top: 30, right: 60, bottom: 20, left: 60});
        var datum = data_piechart_container_797342[0].values;
    chart.tooltipContent(function(key, y, e, graph) {
          var x = String(key.data.label);
          var y = String(key.data.value);
              var y =  String(y)  + ' H';
              tooltip_str = '<center><b>'+x+'</b></center>' + y;
              return tooltip_str;
              });
        chart.showLabels(true);
            chart.donut(false);
    chart.showLegend(true);
        var mycolor = new Array();
            mycolor[0] = "blue";
            mycolor[1] = "blue";
            mycolor[2] = "yellow";
        chart
            .x(function(d) { return d.label })
            .y(function(d) { return d.value });
        chart.height(450);
        chart.color(mycolor);
            d3.select('#piechart_container_797342 svg')
            .datum(datum)
            .transition().duration(500)
            .attr('height', 450)
            .call(chart);
        });
   </script>

**Comment by liquidpele** [comment]
tooltipContent was deprecated, and tooltip was moved into it's own object.

Use chart.tooltip.contentGenerator(), and pass in a function that builds the content.

https://nvd3-community.github.io/nvd3/examples/documentation.html#tooltip

**Comment by zoe-stockholm** [comment]
perfectly working right now! Thanks there!
