### ISSUE TITLE
If axis labels are rotated, on chart.update, the label positions are miscalculated

### ISSUE THREAD

**Issue by mikeyoon** [novus/nvd3#1475]
I noticed that if the axis labels are rotated, on the first chart render, they are placed as expected. On subsequent chart.updates, they will be misplaced due to the rotated labels affecting the textHeight calculations.

Here's a jsfiddle with the issue. You can trigger if by resizing your window after it renders. https://jsfiddle.net/L7jndb81/

The code at issue I think is the following:

```javascript
xTicks.each(function(d,i){
  var box = this.getBoundingClientRect();
  var width = box.width;
  textHeight = box.height;
  if(width > maxTextWidth) maxTextWidth = width;
});
rotateLabelsRule = 'rotate(' + rotateLabels + ' 0,' + (textHeight/2 + axis.tickPadding()) + ')';
```

On the first pass, the textHeight is set correctly, but after that since the axis persists and the height of the box is affected by the initial rotation. Not sure what the best solution is right now. An easy one might be to reset the rotation before doing the calculations, but that might be visible to the user.

**Comment by liquidpele** [comment]
Updated jsfiddle to use master branch code:

https://jsfiddle.net/L7jndb81/1/

to reproduce, look at the labels under the x-axis, adjust the height, and you'll see the jump to the right just a bit as soon as you trigger the chart.update (even if you only adjust height and not width!).
