### ISSUE TITLE
multiBarChart series do not overlap

### ISSUE THREAD

**Issue by atais** [novus/nvd3#1476]
I have created an example with data that I am having issue with:
http://plnkr.co/edit/ORxpcn

Basically, if the 1st serie x-axis range is from (100,200) and second is from (0,150) the axis is not properly drawn and thus data is displayed not in the correct order. The only solution is to have all series including the full domain with 0 values, which I would like to avoid.

**Comment by liquidpele** [comment]
multiBar uses an ordinal scale, not linear.  Each series should have the same x value so that they can stack.
