### ISSUE TITLE
Serious regression in pie chart sizing

### ISSUE THREAD

**Issue by mikeyoon** [novus/nvd3#1481]
Due to a change in #1408, pie charts will most likely be set to the wrong size when rendered without a 500px container. On top of that, because availableWidth and availableHeight are both derived from pie.width and pie.height (which are then also dependent on availableWidth/Height), each successive chart.update pass will likely cause the pie chart to shrink.

Here's a fiddle that demonstrates the issue. https://jsfiddle.net/L7jndb81/3/. If you click a legend option on and off, the pie chart will shrink each time.

**Comment by liquidpele** [comment]
Well shit, that's bad.  Okay, reverting that one.
