### ISSUE TITLE
nvd3 chart in angular throws TypeError: tickExit.call is not a function

### ISSUE THREAD

**Issue by Malrok** [novus/nvd3#1486]
I am using nvd3.js to display charts in an angular project. I have created the following directive:
`.directive('lineChart', function($window) {
  return {
    restrict: 'E',
    scope: {
      // Bind the data to the directive scope.
      data: '=',
      // Allow the user to change the dimensions of the chart.
      height: '@',
      width: '@'
    },
    // The svg element is needed by D3.
    template: '<svg ng-attr-height="{{ height }}" ng-attr-width="{{ width }}"></svg>',
    link: function(scope, element) {
      var d3 = $window.d3;
      var nv = $window.nv;

      var svg = element.find('svg'),
      chart;

      // This function is called when the data is changed.
      var update = function() {
        d3.select(svg[0])
          .datum(scope.data)
          .call(chart);
      };

      // Render the chart every time the data changes.
      // The data is serialized in order to easily check for changes.
      scope.$watch(function() { return angular.toJson(scope.data); }, function() {
        // The chart may not have been initialized at this point so we need
        // to account for that.
        if (chart) {
          update();
        }
      });
`
This throws the following error:

`TypeError: tickExit.call is not a function
at SVGGElement.<anonymous> (d3.js:8673)
at d3.js:8561
at d3_selection_each (d3.js:890)
at Array.d3_transitionPrototype.each (d3.js:8559)
at Array.axis (d3.js:8643)
at Array.d3_selectionPrototype.call (d3.js:897)
at SVGGElement.<anonymous> (nv.d3.js:1086)
at d3.js:884
at d3_selection_each (d3.js:890)
at Array.d3_selectionPrototype.each (d3.js:883)`

In the function d3.svg.axis of the d3.js file, I changed:
`tickExit = d3.transition(tick.exit()).style("opacity", ε).remove()`
to
`tickExit = d3.transition(tick.exit()).style("opacity", ε)`
and did not have an issue anymore.

I am not sure wether the problem comes from d3 or nvd3...

The versions I am using are 
d3 3.5.14 
nvd3 1.8

**Comment by liquidpele** [comment]
Seems like angular is doing something to make d3 lose track of the nodes in the svg.  Regardless, you might want to use something like angular-nvd3.
