### ISSUE TITLE
Not possible to put legend in line chart on the bottom

### ISSUE THREAD

**Issue by slavede** [novus/nvd3#1487]
Currently, there is no option for positioning legend in line chart, it's always on top. It would be great if we could pass in an option for placing legend on the bottom/right/left...

**Comment by liquidpele** [comment]
Others have added a legendPosition option to pie chart and I think one other chart, but only options for those so far are top and right.  If you'd like to code it up, please send a pull request :)

**Comment by liquidpele** [comment]
https://nvd3-community.github.io/nvd3/examples/documentation.html#pieChart

**Comment by slavede** [comment]
Hey, I have created pull request for this here https://github.com/novus/nvd3/pull/1491. Can you validate and accept? Thanks!
