### ISSUE TITLE
Chart data point markers are layered below the chart axes with new release

### ISSUE THREAD

**Issue by mgalloue** [novus/nvd3#1489]
Hi @liquidpele, with the last nvd3 release, there is an issue with point markers as you can see on the following screenshots. Now they are displayed below the chart axis so less visible. Do you know to what changes it is due?
![p1](https://cloud.githubusercontent.com/assets/6142727/12842464/505b42ca-cbf3-11e5-8a22-d07b636f20ca.jpg)
![p2](https://cloud.githubusercontent.com/assets/6142727/12842466/5261f8c0-cbf3-11e5-99d7-81c8e4be0707.jpg)

**Comment by liquidpele** [comment]
Not sure, the top image is of a pretty old version so a ton was changed in between the two.  

It's probably due to clipping being set exactly on the chart instead of +-20px or so like it used to be for that reason.

**Comment by mgalloue** [comment]
@liquidpele Do you know what can I do to enlarge clipping or use an other way to put it behind?

**Comment by liquidpele** [comment]
I'd have to look into it, but it'll be a couple weeks before I can sit down and actually do any development on it.

**Comment by sandyjoshi** [comment]
@liquidpele , @mgalloue any work around for this ? I am getting similar issue.

**Comment by mgalloue** [comment]
Hi @sandyjoshi , PR #1726 fix this issue.

**Comment by liquidpele** [comment]
merged PR.

**Comment by mgalloue** [comment]
Thanks
