### ISSUE TITLE
Displaying Values on top of Stacked/Grouped Multi-Bar Chart

### ISSUE THREAD

**Issue by azitabh** [novus/nvd3#150]
I want to display values on top of multi bar chart. Doing so is quite simple in simple line graph. But, `.showValues(true)` doesn't seem to work in multi chart.

Is there a way to do this?

**Comment by ieglonew01f** [comment]
@jmaroa ref https://stackoverflow.com/questions/30621208/how-to-display-values-in-stacked-multi-bar-chart-nvd3-graphs/31865794
