### ISSUE TITLE
Chart Height Not Variable

### ISSUE THREAD

**Issue by davidjmcclelland** [novus/nvd3#1510]
New to NVD3, trying to make chart fill a div. Works with width, not height. 
- Tried changing css in live code examples: changing height made them shorter and clipped contents
- tried setting chart.height to '100%' - no effect
- \+ set CSS on containing div to '100%' - no effect

Meanwhile width _is_ responsive via windowResize method.
I saw some earlier issues reported Feb '15 - were these fixes released? Is there a workaround? Working example with responsive height? (could not find one)

Thank you!

**Comment by davidjmcclelland** [comment]
had to add height resize to the container in my app, such as $(chartContainerId).height(thisWidget.height); Unclear why this was not required for width to work the same way.

**Comment by cht8687** [comment]
+1

**Comment by liquidpele** [comment]
height = 100% is a tricky CSS thing, but it definitely works as seen in the examples here where the size is 100% of the screen. 

https://nvd3-community.github.io/nvd3/examples/lineChart.html
