### ISSUE TITLE
bower latest version is not the currently latest verion

### ISSUE THREAD

**Issue by torstenloos** [novus/nvd3#1514]
My issue is  that the latest version that I get over bower is 1.8.2 from 2016-01-24: /* nvd3 version 1.8.2 (https://github.com/novus/nvd3) 2016-01-24 */

and not the actually latest version 1.8.2-dev from 2016-02-05:
/* nvd3 version 1.8.2-dev (https://github.com/novus/nvd3) 2016-02-05 */

Can anybody help me how I can get the 1.8.2-dev Version over bower ?

**Comment by ehartford** [comment]
you can't get the dev version over bower.  bower only has released versions.

**Comment by torstenloos** [comment]
@ehartford  thanks! So there is no way i can get dev version through bower?

**Comment by EvaSDK** [comment]
See http://stackoverflow.com/questions/16949173/how-to-install-latest-untagged-state-of-a-repo-using-bower

**Comment by torstenloos** [comment]
thanks @EvaSDK ! exactly what i was looking for.
