### ISSUE TITLE
Is there a map/geo location/heat map example somewhere?

### ISSUE THREAD

**Issue by ackimwilliams** [novus/nvd3#1515]
Can someone post a map/geo location/heat map example somewhere?

**Comment by liquidpele** [comment]
Not part of nvd3, but pure d3 examples exist online if you google for them.

**Comment by liquidpele** [comment]
PS:  If you want it as part of nvd3, please feel free to create a new model and submit it as a pull request.   Most of our models are community created, so any new ones are greatly appreciated :)

**Comment by ackimwilliams** [comment]
Thanks @liquidpele
