### ISSUE TITLE
Looking for documentation or API

### ISSUE THREAD

**Issue by commadelimited** [novus/nvd3#152]
This charting library looks pretty nice, and has some slick functionality. I'm looking for docs that will augment the numerous examples you've published. For example the discreteBarChart example...

It has methods for the following:

````
.staggerLabels(true)
.tooltips(true)
.showValues(true)
````

But I can't find docs for those methods (short of looking in the source code). I'm also trying to find an option for displaying whole numbers instead of decimal formatted numbers. I've taken the example data from the discreteBarChart example and converted the numbers to integers:

```
historicalBarChart = [
	{
		key: "Cumulative Return",
		values: [
			{
				label : "A",
				value : 29
			},
			{
				label : "B",
				value : 32
			},
			{
				label : "C",
				value : 120
			},
			{
				label : "D",
				value : 24
			},
			{
				label : "E",
				value : 98
			}
		]
	}
];
```

But the tooltip keeps displaying them as decimals. There might be an option or method that would solve that for me, but I can't find it.

**Comment by liquidpele** [comment]
https://nvd3-community.github.io/nvd3/examples/documentation.html
