### ISSUE TITLE
Prototype.js method collision

### ISSUE THREAD

**Issue by proteantech** [novus/nvd3#1559]
I believe there is a method collision with prototype.js and (nv.d3 and/or d3). Prototype.js defines the methods every/all and these same methods are being used in nv.d3 and I'm pretty sure they are not expecting the Prototype.js  to be define as well. The error I'm getting occurs on this snippet of code in nv.d3.js in the transition method (around line #1107) version 1.8.2 with d3.v3 3.5.5. There many other usages of `every` where this could theoretically occur as well.

I am not sure where the `every` method is even being defined. I don't see it used at all in d3.js and I only see it used in nv.d3, not defined anywhere.

Someone may have been on to this a while back:

Conflict with Prototype.js #402 
https://github.com/mbostock/d3/issues/402

Trying to identify the root cause or a possible workaround for this b/c I'm working in a large legacy application that uses Prototype.js and wanted to include a nv.d3 lineWithFocusChart chart, but currently blocked by this issue.

I attached a stacktrace as a screenshot.
![nvd3-prototype-stacktrace](https://cloud.githubusercontent.com/assets/5607395/13643894/0b57951c-e5f1-11e5-8e86-0cd6d48d8ad4.png)

Here's the part of the prototype.js code where the error is being thrown from. It appears in the trace as `application.js`

```javascript
function all(iterator, context) {
    iterator = iterator || Prototype.K;
    var result = true;
    this.each(function(value, index) {
      result = result && !!iterator.call(context, value, index);
      if (!result) throw $break;
    });
    return result;
  }
```

and you can see in this piece of prototype.js it is aliasing `all` with `every`:

```javascript
return {
    each:       each,
    eachSlice:  eachSlice,
    all:        all,
    every:      all,
    any:        any,
    some:       any,
...
}
```

**Comment by liquidpele** [comment]
Array.every etc has been party of core javascript for a while.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every

**Comment by falbrech-hsdg** [comment]
@liquidpele I do not understand how this solves the issue. I ran into the same issue today when I wanted to embed an NVD3 chart into a Jenkins Plugin, where prototype.js is also included on the page and I have no control over that.

It would be great if you could provide some hints how to avoid this error being raised.

**Comment by falbrech-hsdg** [comment]
Okay, understood your comment. Obviously, the version of prototype.js used by Jenkins (PrototypeJS 1.7) replaces the Array.prototype.every method without checking if it exists.

I added code to my JavaScript which replaces the method again, with the polyfill suggested by Mozilla:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/every#Polyfill
