### ISSUE TITLE
Download previous releases

### ISSUE THREAD

**Issue by Halleck45** [novus/nvd3#1568]
Hi,

Where can I download previous releases of nvd3 ? Where can i find 1.6.1, 1.6.2... tags ?

Thanks for your help !

**Comment by liquidpele** [comment]
Those versions don't exist, there was a big version jump due to BS.

**Comment by Halleck45** [comment]
Ok. Thanks for your reply

**Comment by gpakosz** [comment]
That being said, npm has `1.1.10`, `1.1.12`, `1.1.13`, `1.1.14` and `1.1.15` versions. Could please add tags so that old bower projects work when specifying e.g. `1.1.x` please ?

**Comment by liquidpele** [comment]
there are tags for older releases already, they were just all beta apparently (I never worked on those)
