### ISSUE TITLE
Line chart rewind x values and update with line break

### ISSUE THREAD

**Issue by ceteagle** [novus/nvd3#1588]
I've added the following data points to a line chart:
x: 1, y: 2
x: 2, y: 3
x: 3, y: 2.5
x: 4, y: 5.5

I want to rewind to x=3 and start drawing the line using a new y value:
x: 3, y: 3
x: 4, y: 6

![linechart](https://cloud.githubusercontent.com/assets/7862395/14289864/aea2ef0c-fb2a-11e5-845d-a77c22b98cab.png)

but I do not want the line connecting [4,5.5] to [3,3].  I would like something like this:
![linechart2](https://cloud.githubusercontent.com/assets/7862395/14290030/76b1791e-fb2b-11e5-9ecd-eb8505b22366.png)

Here is the test script I'm using:

        var keyValuePairArray =
        [
            {
                key: "data",
                values:
                    [
                        { x: 1, y: 2 },
                        { x: 2, y: 3 },
                        { x: 3, y: 2.5 },
                        { x: 4, y: 5.5 }
                    ]
            }
        ];

        var theChart = null;

        nv.addGraph(function () {
            theChart = nv.models
                .lineChart()
                .margin({ left: 100, right: 100 });

            theChart.xAxis
                .axisLabel("X Axis Data");

            theChart.yAxis
                .axisLabel("Y Axis Data");

            d3.select('#chart')
                .datum(keyValuePairArray)
                .call(theChart);

            nv.utils.windowResize(theChart.update);

            return theChart;
        });

        keyValuePairArray[0].values.push({ x: 3, y: 3 });
        keyValuePairArray[0].values.push({ x: 4, y: 6 });

Is this possible?  Thanks in advance.

**Comment by Snuggert** [comment]
```
var keyValuePairArray =
    [
        {
            key: "data",
            values:
                [
                    { x: 1, y: 2 },
                    { x: 2, y: 3 },
                    { x: 3, y: 2.5 },
                    { x: 4, y: 5.5 }
                ]
        },{
            key: "data2",
            values: []
        }
    ];

    var theChart = null;

    nv.addGraph(function () {
        theChart = nv.models
            .lineChart()
            .margin({ left: 100, right: 100 });

        theChart.xAxis
            .axisLabel("X Axis Data");

        theChart.yAxis
            .axisLabel("Y Axis Data");

        d3.select('#chart')
            .datum(keyValuePairArray)
            .call(theChart);

        nv.utils.windowResize(theChart.update);

        return theChart;
    });

    keyValuePairArray[1].values.push({ x: 3, y: 3 });
    keyValuePairArray[1].values.push({ x: 4, y: 6 });
```

You could try this?

**Comment by ceteagle** [comment]
Thank you for your response.  Your suggestion will add another item to the legend and will also show two lines in different colors.  We want to show a single set of data that was recalculated.  A colleague informed me that passing an empty data set will work:

        keyValuePairArray[0].values.push({});
        keyValuePairArray[0].values.push({ x: 3, y: 3 });
        keyValuePairArray[0].values.push({ x: 4, y: 6 });

I tried this and I am able to get the plot that I need.
