### ISSUE TITLE
Solid background Vs. Patterns

### ISSUE THREAD

**Issue by Nazarah** [novus/nvd3#1590]
Instead of showing bars, lines, pie charts etc. in solid colors, is there any way to show them with different patterns?
Examples are in given screenshots.
![potw_hatchfill_04](https://cloud.githubusercontent.com/assets/17976243/14348228/bf5c4a2e-fcc3-11e5-8043-e1040b447cfb.png)
![jfreechartlinechartdemo5](https://cloud.githubusercontent.com/assets/17976243/14348259/f48d11ba-fcc3-11e5-98e6-d1e280517aae.PNG)

**Comment by liquidpele** [comment]
You can apply patterns with CSS3, but there isn't any way to do it just as an option in nvd3

**Comment by liquidpele** [comment]
Oh, lines can be dashed, and points can be different symbols of course.
