### ISSUE TITLE
TypeError: tooltip.interrupt is not a function

### ISSUE THREAD

**Issue by brylie** [novus/nvd3#1597]
When hovering the mouse cursor over a time series chart, the following error appears in the browser console:

```
TypeError: tooltip.interrupt is not a function
```

# Environment
Our package.json contains the following related dependencies:

- "d3": "^3.5.16",
- "nvd3": "^1.8.2"

# Related issue(s)
Issue #1089 indicates this should be resolved by using D3.js > 3.3 and NVD3 > 1.8.1. However, our requirements exceed these, and the error remains.

**Comment by brylie** [comment]
I found out that our version of D3 was pinned to 1.0.0 by our project, in a different file.

**Comment by maristhek** [comment]
Same issue now Jul 2016 : 
tooltip.interrupt is not a function - marked as solved #1597 but not working in the following project : 
ASP.NET MVC5 project, framework 4.51
D3.js 3.5.17
nvd3.js 1.8.3-dev
