### ISSUE TITLE
ReferenceError: d3 is not defined

### ISSUE THREAD

**Issue by brylie** [novus/nvd3#1598]
We are trying to use NVD3 in a file, via an `import` statement:

```js
import d3 from "d3";
console.log(d3) // shows that D3 is successfully imported

import nvd3 from "nvd3";
```

The page fails to render, and the following appears in the developer console:

```
ReferenceError: d3 is not defined
  require<.node_modules.nvd3.build["nv.d3.js"]/<()  modules.js:9745
  require<.node_modules.nvd3.build["nv.d3.js"]() modules.js:9731
 ...
```

How can we include NVD3, so that it sees the D3 object?

# Background
We are building with Meteor.js, and would like to [use ES2015 modules](http://guide.meteor.com/1.3-migration.html#modules) now that Meteor 1.3 has been released. It is unclear to us how to include the NVD3 NPM package in our project.

**Comment by bobylito** [comment]
d3 is used globally in nvd3, which means that even if you require d3 in your script, it doesn't make it available for nvd3.

**Comment by brylie** [comment]
Thanks @bobylito. What approach do you recommend instead?

**Comment by bobylito** [comment]
Is there a global scope on Meteor that any script script will fallback on? @brylie

**Comment by brylie** [comment]
Hm, we can include the nvd3 package in our /lib folder, and it will be included globally. However, we are moving to a modular design, where we explicitly handle dependencies via ES2015 `import`.

**Comment by bobylito** [comment]
NVD3 can easily be imported with import. The only problem is that D3 has to be available globally. In a browser setup you could do:

```js
import d3 from 'd3';
window.d3 = d3;

// then do the NVD3 stuff you want to do
```

I guess putting d3 in the lib folder should work as well.

**Comment by TheDoozyLulu** [comment]
What is the solution? I'm getting the same error.
