### ISSUE TITLE
Data is not being displayed in code adapted from example.

### ISSUE THREAD

**Issue by isaacsanders** [novus/nvd3#1625]
Hey all,

I am trying to use NVD3 from elm, and I am having trouble.

When this code runs it displays the two axes, but they are both placed horizontally and are very crowded. The data is not displayed.

I have found that the data is in the SVG, but it is outside of the bounds and 1 by 18 pixels.

The data I am using is the example data from the nvd3.org example for the stacked area chart.

The code is very close to the same example.

Below is the exact code being used. Any help is appreciated.

– Isaac

```javascript
(function() {
  var nv = this.nv;
  var d3 = this.d3;
  Elm.Native.NVD3 = {};
  Elm.Native.NVD3.make = function(elm) {
    'use strict';

    elm.Native = elm.Native || {};
    elm.Native.NVD3 = elm.Native.NVD3 || {};
    if (elm.Native.NVD3.values) return elm.Native.NVD3.values;

    var stackedAreaChart = function(jsonBlob) {
      var data = JSON.parse(jsonBlob);

      var chart;
      nv.addGraph(function() {
        chart = nv.models.stackedAreaChart()
        .x(function(d) { return d[0] })
        .y(function(d) { return d[1] })
        .useInteractiveGuideline(true)
        .duration(200);

        chart.xAxis
        .tickFormat(function(d) { 
          return d3.time.format('%x')(new Date(d))
        });

        chart.yAxis
        .tickFormat(d3.format(',.2f'));

        d3.select('#chart')
        .datum(data)
        .transition().duration(200)
        .call(chart);

        nv.utils.windowResize(chart.update);

        return chart;
      });
      return chart;
    };
    return elm.Native.NVD3.values = { "stackedAreaChart": stackedAreaChart }
  }
}).call(this);
```

**Comment by liquidpele** [comment]
If you experience a bug please provide a jsfiddle or the like demonstrating the problem, using the latest build files in master via rawgit.com.  Thanks!

**Comment by isaacsanders** [comment]
Turns out it is a problem with the Virtual DOM side of Elm. closing

**Comment by pachopepe** [comment]
I solved the issue changing the `svg` tag to a `div` on the `view` (elm side) and adding a `svg` node on the javascript side before the nvd3 select:

```
var div = document.getElementById("chart");
var svg = document.createElementNS("http://www.w3.org/2000/svg","svg");
div.appendChild(svg);
d3.select("#chart svg") 
...
```

Hope this helps
