### ISSUE TITLE
Tooltip vs. Legend

### ISSUE THREAD

**Issue by aabg21** [novus/nvd3#1634]
Hi guys,
I wonder if I'm the only one here who noticed the differences between the circles in legends and the squares in tooltips.
I couldn't find any way to make one look like the other.
![image](https://cloud.githubusercontent.com/assets/3430504/14986511/e6b893d4-1154-11e6-8319-1415058bc048.png)

**Comment by liquidpele** [comment]
the main reason I did that is because one is a button and the other is a tag on a table row.
