### ISSUE TITLE
Which version is stable ?

### ISSUE THREAD

**Issue by Great-Fred** [novus/nvd3#1651]
Which version should we use to be sure to have a stable version ?
The last build in the "Master" branch (currently, '1.8.3-dev') or the one with the most recent tag (currently, '1.8.3') ?
The site "http://nvd3.org" proposes to download the version of the "Master" branch but, as it is suffixed with "-dev", I 'm not sure of its stability.

**Comment by liquidpele** [comment]
master is the current development branch.   the version tags are all "stable"

**Comment by Great-Fred** [comment]
OK, thank you :) .
But, why "http://nvd3.org" proposes to download the version of the "Master" branch, if it's a development branch ?
This is the main access for "https://github.com/novus/nvd3", no ?
