### ISSUE TITLE
Error with axis in LinePlusBarChart. 1.8.3 version

### ISSUE THREAD

**Issue by Josmorsot** [novus/nvd3#1661]
Hello, I've found an error in LinePlusChart.
In line 7241 are defined functions: getBarsAxis and getLinesAxis.
These methods are used to show "tooltip" but returns are switched.

![image](https://cloud.githubusercontent.com/assets/7818205/15283918/45fbb774-1b4e-11e6-8089-c6f9eab92074.png)

y2Axis should be, by default, linesAxis. So, these lines must be changed to:

    var getBarsAxis = function() {
        return !switchYAxisOrder
            ? { main: y1Axis, focus: y3Axis }
            : { main: y2Axis, focus: y4Axis }
    }

    var getLinesAxis = function() {
        return !switchYAxisOrder
            ? { main: y2Axis, focus: y4Axis }
            : { main: y1Axis, focus: y3Axis }
    }

This error causes, by placing the cursor over lines/bar, values were not displayed correctly formated (Right axis using left axis formatter):
![image](https://cloud.githubusercontent.com/assets/7818205/15284090/8dc659f0-1b4f-11e6-9210-3a11d66fcefb.png)

**Comment by tlercher** [comment]
I can confirm this. Already made PR #1650 for this.

**Comment by mrvicadai** [comment]
problem confirmed; @tlercher 's PR should fix this problem.
