### ISSUE TITLE
Tooltip doesn't hide when legend is uncheck in linePlusBarChart.

### ISSUE THREAD

**Issue by umair-khanzada** [novus/nvd3#1664]
Hi, 
   i am facing the same issue. [https://github.com/krispo/angular-nvd3/issues/433](https://github.com/krispo/angular-nvd3/issues/433)
i remove angular-nvd3 and then use simple nvd3 chart but still i am facing same issue.

**Comment by frozenshadow** [comment]
Same problem with the latest release (1.8.5) on the MultiChart.
