### ISSUE TITLE
Tooltip guidelines do not move to correct position on re-scale

### ISSUE THREAD

**Issue by MKHenson** [novus/nvd3#1668]
Hi there, I seem to have uncovered a bug in the library which affects both my code and one of the examples. The tooltip guidelines (those circles that follow the lines) don't seem to work when lines are hidden and the graph re-scales. 

![screenshot](https://cloud.githubusercontent.com/assets/2727104/15391585/cc87d3a0-1db9-11e6-83bc-3af38566e72e.png)

Notice how after I hide the green lines, the tooltip guide still exists at its previous scale position (even though the values in the tooltip are correct)

![screenshot](https://cloud.githubusercontent.com/assets/2727104/15391621/07901336-1dba-11e6-9464-05d341013113.png)

This problem seems to exist on the version I downloaded from the site (The version in the build/nvd3.js says 1.8.3-dev). If you open the lineChart.html example. Notice how when it loads, the tooltip guidelines work for all lines as expected. Then, untick the sine wave, cosine wave and random points legends. Notice how the graph has rescaled - but the tooltip guides are gone/in the wrong position.

![screenshot](https://cloud.githubusercontent.com/assets/2727104/15391720/c3a1bd54-1dba-11e6-9521-c7d51070ad8e.png)

**Comment by izy-izzy** [comment]
Confirmed. I've also found out this bug. Needed to downgrade versions.

**Comment by ThomasBrierley** [comment]
Pretty sure this is a duplicate of #1865 please test on **1.8.5-dev** to confirm.

**Comment by MKHenson** [comment]
Yep, looks like that's resolved in 1.8.5. Thanks
