### ISSUE TITLE
Sunburst regression from 1.8.2 to 1.8.3

### ISSUE THREAD

**Issue by manbearwiz** [novus/nvd3#1679]
[This sunburst chart](http://plnkr.co/edit/xUuvoPeEIQNvpYjRT6Go?p=preview) uses nvd3#1.8.2. If you go into the `index.html` and import version 1.8.3, some segments are missing from the chart.

**Comment by liquidpele** [comment]
Yea, there is definitely something weird going on there...   if you can track down the specific commit that did it the I can revert it...

**Comment by manbearwiz** [comment]
After further investiagtion, its related to https://github.com/novus/nvd3/commit/0e097bceb3f3b4ebc4c183c180f81cdabb60bbeb. The new implementation requires a key be defined and if one is not defined it uses the the name as a key. In the plnkr above, the names are not unique, resulting in the missing pieces. So this is probably working as intended.

Due to the nature of this chart and the high likelihood of duplicate names, I think their would be a benefit to adding some check when rendering and to `console.warn` if their data contains duplicate keys.

**Comment by liquidpele** [comment]
Sounds reasonable, send us a pull request with the change and we'll take a look
