### ISSUE TITLE
rendering of chart size based on filtered value.

### ISSUE THREAD

**Issue by Nazarah** [novus/nvd3#1696]
In some of your charts when a specific filtering is deselected or selected, the chart size gets rendered. i.e. it either becomes bigger (with other curves and value range expanded) on filtering. I want to keep the chart size fixed however I want to filter the data. Is there any ways for that?

Example:  http://nvd3.org/examples/scatter.html

**Comment by liquidpele** [comment]
You can specify the exact range/scale or use forceX to put specific values on the axis so that it doesn't resize the axis. 

https://nvd3-community.github.io/nvd3/examples/documentation.html
