### ISSUE TITLE
Y Axis rendered off the canvas

### ISSUE THREAD

**Issue by jsancio** [novus/nvd3#17]
I am trying to use nvd3's lineChart model and I notice that the y axis label is getting rendered off the screen. The following code (this is pretty much the code from the sample page):

``` javascript
var chart = nv.models.lineChart();

chart.xAxis
    .axisLabel('Time (ms)')
    .tickFormat(d3.format(',r'));

chart.yAxis
    .axisLabel('Voltage (v)')
    .tickFormat(d3.format('.02f'));

d3.select('#chart svg')
    .datum(data())
  .transition().duration(500)
    .call(chart);
```

Generates a text element with the following values:

``` html
<text class="nv-axislabel"
      text-anchor="middle"
      transform="rotate(-90)"
      y="-63"
      x="-160">
Voltage (v)
</text>
```

I simply made the following change to src/models/axis.js:

```
diff --git a/src/models/axis.js b/src/models/axis.js
index 123cfbb..80db73e 100644
--- a/src/models/axis.js
+++ b/src/models/axis.js
@@ -210,7 +210,7 @@ nv.models.axis = function() {
           axisLabel.enter().append('text').attr('class', 'nv-axislabel')
               .attr('text-anchor', rotateYLabel ? 'middle' : 'end')
               .attr('transform', rotateYLabel ? 'rotate(-90)' : '')
-              .attr('y', rotateYLabel ? (-Math.max(margin.left,width) + 12) : -10); //TO
+              .attr('y', rotateYLabel ? (-Math.max(margin.left,width) + 25) : -10); //TO
           axisLabel
               .attr('x', rotateYLabel ? (-scale.range()[0] / 2) : -axis.tickPadding());
           if (showMaxMin) {
```

Which generates the following svg:

``` html
<text class="nv-axislabel"
      text-anchor="middle"
      transform="rotate(-90)"
      y="-50"
      x="-160">
Voltage (v)
</text>
```

I don't really know if this is the correct solution or if it breaks other graphs. I am not super familiar with d3.js or nvd3.js. Let me know if you need more information. Thanks!

**Comment by sashadt** [comment]
Having the same problem.  Since Y axis values can vary a lot, using ```margin="{left:100}"``` is not a good solution, because covering the corner cases or very large values results in too much space left over in most situations.

**Comment by proteusvacuum** [comment]
Another solution is to scale your axis values when they go above a certain threshold. 

```js
var si_prefix_formatter = d3.format('.3s'),
    integer_formatter = d3.format(',.1d');

chart.yAxis.tickFormat(function(d){
    if(d >= Math.pow(10,4)){
        return si_prefix_formatter(d);
    }
    return integer_formatter(d);
})
```

This adds SI prefixes to your axis labels whenever they are above 10k (i.e. you get 5,000, 10.0k, 11.3k etc.)

**Comment by Raviraj20** [comment]
Need a help how to change the separation line from 0.0 to 10 in Yaxis

**Comment by StoneCypher** [comment]
are you seriously resurrecting a five year old bug thread to ask for technical support
