### ISSUE TITLE
How can I pre-select in code the control option for a chart?

### ISSUE THREAD

**Issue by pgrm** [novus/nvd3#1700]
Some chart types have control options (different chart types offer different options):

- stacked
- grouped
- stream
- expanded

I can show those options for the user via `chart.showControls(true)` but I couldn't find a way to read those values and set them on an existing chart. Is it possible? Maybe I was looking for the wrong term.

Thx

**Comment by liquidpele** [comment]
Been a while since I did that... pretty sure you do chart.dispatch.changeState(...), the defaultState option looks to be deprecated in favor of that.  

https://nvd3-community.github.io/nvd3/examples/documentation.html#stackedAreaChart
