### ISSUE TITLE
CSP Nonce support?

### ISSUE THREAD

**Issue by RobertBaron** [novus/nvd3#1707]
nv.d3.min.js:3 Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self' nonce-EDNnf03nceIOfn39fn3e9h3sdfa 'nonce-EDNnf03nceIOfn39fn3e9h3sdfa'". Either the 'unsafe-inline' keyword, a hash ('sha256-TUTFkbtcsqn32NVB3jeElSn6mWqH4QucJQzVBcSldRg='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by liquidpele** [comment]
I have no idea what this is.

**Comment by RobertBaron** [comment]
Same issue as: http://stackoverflow.com/questions/38155335/csp-errors-with-the-angular-nvd3-package

**Comment by liquidpele** [comment]
Okay, read through the docs.  

This is not an nvd3 issue, the end user is responsible for setting up their CSP headers and specifying the nonce hash in whatever script or style tags are necessary... whether that is done themselves or by a 3rd party library like angular-nvd3 that wraps nvd3.   

resources:
https://blog.mozilla.org/security/2014/10/04/csp-for-the-web-we-have/
https://www.w3.org/TR/CSP11/
