### ISSUE TITLE
LightWeight options for donut pie chart

### ISSUE THREAD

**Issue by psmod2** [novus/nvd3#1708]
Hi,

In my Angular app I am displaying a donut pie chart - it is shown for several items through a ```ng-repeat```.

The issue is displaying the charts is effecting performance so i want to ask whats the most 'light-weight' options set I can use - at present I have:

(note i dont want no hovering, selection or filtering - its literally just to display data):

```
chart: {
            type: 'pieChart',
            donut: true,
            showLegend: false,
            donutRatio: 0.6,
            tooltip: {
                enabled: false
            },
            margin : {top: 0, right: 0, bottom: 0, left: 0},
            height: 100
}
```

**Comment by liquidpele** [comment]
If you need something super lightweight, you can just use chart type of 'pie', there are examples of using just the raw subtypes that don't include any of the tooltip/etc stuff.  

https://nvd3-community.github.io/nvd3/examples/pie.html
