### ISSUE TITLE
Pie Chart - Prevent hover over display

### ISSUE THREAD

**Issue by psmod2** [novus/nvd3#1709]
Hi,

I have a pie chart but cant disable the hover over effect - I've disabled the labels from showing however when I hover over it still increases the size of the pie section - is it possible to switch off?

```
chart: {
            type: 'pieChart',
            donut: true,
            showLegend: false,
            donutRatio: 0.6,
            tooltip: {
                enabled: false
            },
            margin : {top: 0, right: 0, bottom: 0, left: 0},
            height: 100
 }
```

**Comment by liquidpele** [comment]
https://nvd3-community.github.io/nvd3/examples/documentation.html#pieChart

growOnHover option.
