### ISSUE TITLE
StackedAreaChart Problems: about date values, hide controls, and size too small

### ISSUE THREAD

**Issue by hustcer** [novus/nvd3#171]
There are a few problems in stackedAreaChart:
1. The x axis dates values are unix timestamp, which is quite inconvenient and not intuitive for us. Currently, If we don't use unix time stamp the tooltips won't show up.
2. When we hide the controls by ".showControls(false)", the legends won't flow to the left of the chart, especially when the svg element has a smaller width and height, the legends just aligned vertically, which will make the chart much lower.
3. Check out the https://github.com/novus/nvd3/blob/master/examples/stackedAreaChart.html example, if we add ".width(300).height(250)" to the chart settings, and open it in the browser the chart will be messed up. Sometimes we use it as a small widget but if the display area is too small, then the chart was broken.

**Comment by liquidpele** [comment]
Really old and the major issue was fixed, closing it.  Please open any still existing issues based on the latest version, thanks!
