### ISSUE TITLE
Trigger windowResize when changing orientation of tablet device?

### ISSUE THREAD

**Issue by brylie** [novus/nvd3#1710]
We are using NVD3 on a tablet. When changing the tablet orientation, e.g. from portrait to landscape, the `nv.utils.windowResize()` function does not seem to trigger chart.update. How can we trigger chart.update() when changing device orientation on tablet/phone devices?

**Comment by liquidpele** [comment]
https://stackoverflow.com/questions/5284878/how-do-i-correctly-detect-orientation-change-using-javascript-and-phonegap-in-io

Then just call chart.update() when it triggers.
