### ISSUE TITLE
Line chart with Strings or Dates in x axis is failing 

### ISSUE THREAD

**Issue by vineelal** [novus/nvd3#1716]
Observe the images, a linechart which has x axis data as "A", "B" is failing.

![linechart](https://cloud.githubusercontent.com/assets/4658864/16585036/7f5a5736-42dc-11e6-8296-be9f3d782196.png)
![linechartdata](https://cloud.githubusercontent.com/assets/4658864/16585038/804d9676-42dc-11e6-8afb-8f610d9f52aa.png)

**Comment by liquidpele** [comment]
Please create a jsfiddle that demonstrates the issue, linking to the latest code in master via rawgit.com

**Comment by liquidpele** [comment]
Okay, this is just invalid.   Line charts use a linear scale, not an ordinal scale.  You would want to use a bar chart for this, or manually set the scale type.   

https://github.com/d3/d3-3.x-api-reference/blob/master/Scales.md

https://nvd3-community.github.io/nvd3/examples/documentation.html#lineChart  (see xScale option)
