### ISSUE TITLE
nvd3 npm package not working with d3 4.0.0

### ISSUE THREAD

**Issue by ehartford** [novus/nvd3#1719]
npm package not working with d3 4.0.0

    "dependencies": {
      "d3": "^4.0.0",
      "express": "^4.14.0",
      "nvd3": "^1.8.3",
      "phantom": "^2.1.9"
    }

npm WARN nvd3@1.8.3 requires a peer of d3@^3.4.4 but none was installed.

For now I am reverting to d3 3.4.4 to work around.

**Comment by liquidpele** [comment]
Yes, I already updated the readme to say d3 4.x isnt' supported yet.
