### ISSUE TITLE
tooltip.interrupt is not a function in MVC5 project

### ISSUE THREAD

**Issue by maristhek** [novus/nvd3#1735]
Same issue as #1597 now Jul 2016 : 
tooltip.interrupt is not a function - marked as solved #1597 but not working in the following project : 
ASP.NET MVC5 project, framework 4.51
D3.js 3.5.17
nvd3.js 1.8.3-dev

**Comment by liquidpele** [comment]
Please create a jsfiddle or similar demonstrating the problem, linking to the latest code in the master branch via rawgit.com.   Thanks!

**Comment by maristhek** [comment]
Hello :

 

The tooltip.interrupt code that errors out is being called from a cshtml page using Microsoft's Razor language in a Microsoft MVC5 project.  The same exact code runs perfectly on a standalone HTML page.  There are not any significant differences in the js nor html markups.

The major differences is :  the MVC5 code uses an AJAX call to the MVC controller which in turn loads the data (JSON) via an ADO.NET call to a SQL Server stored procedure and returns it to the page for rendering.  The HTML version loads the JSON file from disk.  In either case the data stream is exacly the same.

The structure of the MVC project and its link to a SQL Server makes it difficult to reproduce on jsFiddle.

 

Is it possible that a page or partial page request is being generated by the tooltip.interrupt call which in turn would be routed through a (non-existent) controller in the MVC infrastructure.

 

I haven't examined the nvd3 nor d3 code in depth but am wondering if there are any latent depency mismatches wrt to node, jQuery, bootstrap, etc. versions that are managed by the Nuget machinery in an MVC project.

 

Thanks.

**Comment by maristhek** [comment]
It appears that .transition is not supported in nvd3.

Changed -
from svg.transition().duration(0).call(chart);
to
svg.call(chart);

Works as expected
