### ISSUE TITLE
tooltip bug and points not shown bug in different versions

### ISSUE THREAD

**Issue by gregoks** [novus/nvd3#1736]
Hi,

In internet explorer sometimes the tooltip is missing when hovering over the points in line chart, as I understand this issue might have been fixed in 1.8.4 version but there is another bug that makes the points half hidden when you hover over a point on line zero:

![image](https://cloud.githubusercontent.com/assets/15245808/16909262/3b38898a-4cda-11e6-8243-1786a11c53ee.png)

The points are fully seen only in version 1.8.1. So if I use version 1.8.2+ I have the points bug, if I use 1.8.1 version, I have the tooltip bug :(

Any solution?

Thanks,

Greg

**Comment by gregoks** [comment]
this is how the point looks in 1.8.1 version (which works):

![image](https://cloud.githubusercontent.com/assets/15245808/16909344/d6353d98-4cda-11e6-8cab-b8fc85e94754.png)

**Comment by liquidpele** [comment]
Actually that last bug was also fixed, although I think it's only in master.  

https://github.com/novus/nvd3/commit/8a08c7d8a581a16ea1def7e41f3b4ffba4217bce

**Comment by gregoks** [comment]
Thanks! Do you know when the new and fixed version will be released?

**Comment by liquidpele** [comment]
I try to push out a bugfix release every few months, since I JUST did one it might be a bit but you can pull latest master and just do "grunt production" to build off the latest source yourself.
