### ISSUE TITLE
What is the difference between bullet and bulletChart?

### ISSUE THREAD

**Issue by olivermue** [novus/nvd3#1738]
Both chart types are claiming that they are an implementation of a [bullet chart](http://projects.instantcognition.com/protovis/bulletchart/) and both are looking more or less the same if you instantiate them.

Nevertheless, both are having different features:
### bulletChart ###
- has an `update()` method.
- shows a `noData` message provided if nothing is there to be shown.
- `ticks` can be explicitly set.

### bullet ###
- can colorize and label multiple ranges.
- can additionally show a marker line.
- ticks can also be explicitly set, but the property name is `forceX`.
- the measure can get a different color.

I think it would be a good idea to merge these two things and take the best features from both. Nevertheless this would be a breaking change (one name would die, the provided data object has different and/or new property names).

So what do others thinking about it? Did I miss something and there are a good reasons why both implementations are co-existing?

**Comment by liquidpele** [comment]
The gist is that *Chart things add tooltips, axis, etc... so line.js just does lines, and lineChart.js is a full line chart with axis and tooltips etc.... multiChart uses line.js as well, so does linePlusBarChart.js...  and line.js even re-uses scatter.js.  Basically it's a component vs full chart implementation thing.  I'm not as familiar with the bullet ones as I don't personally use them, but they follow the same setup.

**Comment by olivermue** [comment]
@liquidpele: If that's the case, then both are definitely not correctly implemented, cause they are laying next to each other and making not use of each other. If you take a look at a diff between both files, you see that both are making much the same despite the differences I pointed out above.

**Comment by liquidpele** [comment]
feel free to send us a pull request that cleans up anything that bugs you...
