### ISSUE TITLE
way to display ticks/lines on multi bar horizontal chart

### ISSUE THREAD

**Issue by alisonstiel** [novus/nvd3#1752]
Hello, 
I'm using Multi Bar Horizontal Chart to graph the amount of days per event.
Is there a way to at ticks/lines on each bar, to make each event bar a sort of timeline?
Let me know if any more clarification is needed.

![screen shot 2016-07-28 at 3 02 07 pm](https://cloud.githubusercontent.com/assets/16496917/17225880/b1695eac-54d4-11e6-8ff1-16a0ac2251c3.png)

**Comment by Whymess** [comment]
Did you check stackoverflow? Try posting your question there.

**Comment by liquidpele** [comment]
The examples/docs show most of the available features you can use. 

https://nvd3-community.github.io/nvd3/examples/documentation.html

https://nvd3-community.github.io/nvd3/examples/site.html
