### ISSUE TITLE
Incorrect guideline point of line-chart after turning on/off series

### ISSUE THREAD

**Issue by fan-self** [novus/nvd3#1759]
Incorrect guideline point of line-chart after turning on/off series:
### **Initialization: the points are showing correctly.**

![initialization](https://cloud.githubusercontent.com/assets/20783245/17322037/2519eb30-58ce-11e6-8df4-59ec9a019644.png)
### **Turn off series: the point is off the line.**

![turn off](https://cloud.githubusercontent.com/assets/20783245/17322063/40bf2490-58ce-11e6-9b21-e2f0cee027ae.png)

I try to correct the problem like below:
1. in nv.models.lineChart, modified as [fix: revert highlight point index value](https://github.com/novus/nvd3/commit/405efe26f826bd36cc8b24eacd82712f2c4e7c56)
   ![modification_1](https://cloud.githubusercontent.com/assets/20783245/17322162/ab1614b6-58ce-11e6-9e7e-5908ed7593e8.png)
2. in nv.models.scatter
   ![modification_2](https://cloud.githubusercontent.com/assets/20783245/17322200/e71bea9e-58ce-11e6-930c-0f05941331da.png)
   (I supposed the logScale would always be _TRUE_)

The guideline point seems to be correct after modifications as above.

Is that correct??

ps: I'm using nvd3 1.8.4.

**Comment by ThomasBrierley** [comment]
Hi @fan-self I think this may have been the same issue as #1865 which has just been fixed on **1.8.5-dev**, are you able to check your example again with this version?

**Comment by fan-self** [comment]
thanks for your reply, i did a double check and it was resolved. @ThomasBrierley
