### ISSUE TITLE
Display all spots not only max, min, current point.

### ISSUE THREAD

**Issue by se7enzone** [novus/nvd3#1776]
I tried many times to extending nv.models.sparkline() but nothing happened.
If someone knows how to display all spots let me know.

Or if not, please upgrade nvd3 sparkline chart with option that display all points.

**Comment by jambanagar** [comment]
I don't believe that's the purpose of sparkline, instead line chart would display all the points.

If you still need all the points, just extend your implementation by creating the circles (nv-point) in the

**Comment by se7enzone** [comment]
@jambanagar 
Can you create Plunker and extend custom function?

**Comment by liquidpele** [comment]
sparkline shouldn't show all points, if you need that use a regular line chart and hide the axis.  

https://nvd3-community.github.io/nvd3/examples/documentation.html#lineChart
