### ISSUE TITLE
Multi-bar-horizontal-chart bars are overlaping 

### ISSUE THREAD

**Issue by mubashar-ali-arif** [novus/nvd3#1792]
When we're using a Multi-bar-horizontal-chart the few bars are hide/overlap each others. When we filtered using lagends we can see those hide bars. Please see the highlighted part of attached image (this is one of case).

Any help to resolve this issue?

![multibar_horizental_bars_overlapped](https://cloud.githubusercontent.com/assets/10595996/17916513/90b4ac1c-69e6-11e6-9669-fe969dc6346f.JPG)

**Comment by mubashar-ali-arif** [comment]
Anyone can help to resovle this bar overlaping isuse? Any workaround?

**Comment by mubashar-ali-arif** [comment]
Anyone can help to resovle this bar overlaping isuse? Any workaround?

**Comment by liquidpele** [comment]
You closed this issue... re-open it if it is still a problem in latest master branch build.

**Comment by mubashar-ali-arif** [comment]
Unattensionly clicked on 'Closed and Comment' button and I noticed it later.
Let me try with lateset version and will get back to here if I still have same issue.  Is there any workaround with version 'nvd3 version 1.8.1'.

Any help will be appricated.

**Comment by liquidpele** [comment]
Any fixes will go into master, you'd have to patch older versions yourself. 

Let me know if it's still an issue in latest master... if so, then if you can create a jsfiddle linking to the latest master build files (you can do this via rawgit.com) that demonstrates the issue then it will be much easier for someone to debug since reproducing is always a challenge and often times a wild goose chase ;)

**Comment by mubashar-ali-arif** [comment]
I tried with latest version but still have same issue. I created plunker to demonstrate this issue. In demo you can see lot of bars are overlapping each other. So I have bind an event on each bar which triggers on click. but when I mouse over the bar and that bar get went behind the other bar and cannot trigger the event for actual one. 

You can find link here. [Plunker](http://plnkr.co/edit/vu7Oa5t1ANwztwxyY5AN?p=preview)

Any help will be appreciated.





![nvd3_bar_overlapping_highlights](https://cloud.githubusercontent.com/assets/10595996/19064236/86afa4c4-8a3e-11e6-94db-73951530d516.JPG)

**Comment by liquidpele** [comment]
Well, that's angular-nvd3, not just regular nvd3....  however, it looks like you have your data all random, it needs to be in the same order.... for each series the "Pre Vet" needs to be the first item in the array, etc.  nvd3 just loops over arrays in many cases and things needs to be pre-ordered properly.

**Comment by mubashar-ali-arif** [comment]
After putting data in same order, no more bar overlapping.
@liquidpele, Thank you.
