### ISSUE TITLE
X axis with dates multiChart model

### ISSUE THREAD

**Issue by Siva-Siva** [novus/nvd3#180]
I have tried using the multiChart model with dates as the values for the x axis. It seems to display but the spacing between the ticks are not correct. 

I have tried using the changes done here 

https://github.com/novus/nvd3/pull/156

but it does not seem to fix the problem.

Does anyone have a working example of the multiChart model using dates for the x axis, or any way I can go around this issue?

**Comment by volmerf** [comment]
I'm also curious what the solution was. I'm not getting any labels on my xAxis.
