### ISSUE TITLE
Support v4+ of d3?

### ISSUE THREAD

**Issue by andrewstoker** [novus/nvd3#1812]
Are there any plans for nvd3 to support version 4 of d3?

**Comment by ehartford** [comment]
Duplicate of https://github.com/novus/nvd3/issues/1681

**Comment by liquidpele** [comment]
nvd3 is almost entirely community driven at this point, so anyone who would like v4 support please send us a pull request :)

**Comment by bgth** [comment]
Can you please check #2082 and see if anyone can spare some time on the migration to v4? Thanks in advance..
