### ISSUE TITLE
Boxplot with 0 values for either high whisker or low whisker do not display

### ISSUE THREAD

**Issue by mraziz** [novus/nvd3#1816]
<img width="169" alt="screen shot 2016-09-15 at 4 01 28 pm" src="https://cloud.githubusercontent.com/assets/2287538/18570323/c293651a-7b5d-11e6-8aee-32f0dcee7028.png">

**Comment by mraziz** [comment]
After digging around this is easily solved by changing line 2088 from:
`if (f(d)) {`
to
`f (f(d) >= 0) {`

**Comment by liquidpele** [comment]
Please send a pull request :)

**Comment by billderose** [comment]
@liquidpele  please see fix in this PR: https://github.com/novus/nvd3/pull/1834
@mraziz's suggestion isn't quite right because it would ignore whiskers with negative values. what we really want is to check if the whiskers are `null` or `undefined`, as I've done in the fixed branch.

**Comment by liquidpele** [comment]
merged, thanks!
