### ISSUE TITLE
Chord Diagrams?

### ISSUE THREAD

**Issue by rogeralsing** [novus/nvd3#1818]
Is it possible to create Chord diagrams using nvD3 or do I have to resort directly to D3 for this?
![chord](http://i.stack.imgur.com/6GdL4.png)

What I'm trying to ask is, is it possible to hook into the underlying d3 bits through nvD3?

**Comment by liquidpele** [comment]
That model hasn't been created no, closest thing is this style which was just merged into master recently:   https://bost.ocks.org/mike/sankey/
