### ISSUE TITLE
Add chart padding

### ISSUE THREAD

**Issue by hlehmann** [novus/nvd3#1822]
Currently the minimum value touch the bottom of the chart but it would be nice to have the possibility to add some space between the minimum point and the bottom.

1- It gives more visibility of extremes values
2- It avoids hiding parts of the chart when using interpolation:
![2016-09-19 16-58-30](https://cloud.githubusercontent.com/assets/3891004/18636806/6828ff6a-7e8a-11e6-8892-663cd6befd5a.png)

a chart.padding(...) similar to margin could be a solution ?

**Comment by liquidpele** [comment]
You can set the range or domain on the axis however you like, or even use forceX/forceY to force the axis to include only specific points.  See docs.
