### ISSUE TITLE
Upgrade to Angular 2.0.0, binding problems now

### ISSUE THREAD

**Issue by carmenbranje** [novus/nvd3#1824]
I am now getting this error

Can't bind to 'options' since it isn't a known property of 'nvd3'. ("-lg-8 piechart_container" style="padding:0px;" (window:resize)="onResize($event)">

        <nvd3 [ERROR ->][options]="options" [data]="data"></nvd3>
    </div>

"): DonutChartComponent@3:14
Can't bind to 'data' since it isn't a known property of 'nvd3'. ("iner" style="padding:0px;" (window:resize)="onResize($event)">

        <nvd3 [options]="options" [ERROR ->][data]="data"></nvd3>
    </div>

I changed the Component file as per the changes introduced in RC6. 

`@Component({
    selector: 'coaching-planner',
  
    templateUrl: 'app/coaching-planner/coaching-planner.component.html',
    styleUrls: ['app/coaching-planner/coaching-planner.component.css']
})

@NgModule({
        declarations: [TreeComponent]
})`

**Comment by liquidpele** [comment]
Wrong project this is not angular
