### ISSUE TITLE
How to integrate nvd3'stackedAreWithFocusChart with my existing project?

### ISSUE THREAD

**Issue by scheung38** [novus/nvd3#1826]
Will be easier to migrant my existing project to nv3 or the other way round? As there seems to be lots of configuration files to take care of? For example if I want to use the stackedAreWithFocusChart.html, what associated files do I need to import and use with my project? 

Specifically my MongodB data is external to the app and read into my server.js via

myapp/server.js:

```
// Connection URL
var url = 'mongodb://ec2-XX-XX-X-XXX.us-west-2.compute.amazonaws.com:27017/storedata';

var MongoClient = require('mongodb').MongoClient, assert = require('assert');
MongoClient.connect(url, function (err, db) {
    assert.equal(null, err);
    console.log("Connected successfully to energy server!");

    // console.log('All energy data : ', db.energydata.find().pretty());
    // insertDocuments(db, function () {
        findDocuments(db, function () {
            db.close();
        });
    // });
});

//Insert a Document
insertDocuments = function (db, callback) {
    // Get the documents collection
    var collection = db.collection('energydata');
    // Insert some documents
    collection.insertMany([
        {a:1}, {a:2}, {a:3}
    ], function (err, result) {
        assert.equal(err, null);
        assert.equal(3, result.result.n);
        assert.equal(3, result.ops.length);
        console.log("Inserted 3 documents into the collection for testing only");
        callback(result);
    });
};

findDocuments = function (db, callback) {

    var collection = db.collection('energydata');
    var myCount = db.collection('energydata').count();
    // Find some documents
    collection.find({}).toArray(function (err, docs) {
        assert.equal(err, null);
        console.log("Found the following records");
        console.log(docs);
        console.log('Counted number of documents : ', myCount);
        callback(docs);
    });
};
```

But not sure how to integrate stackedAreaWithFocusChart.html into my project and use my extracted data, with a starter kit from stormpath-react-sample

**Comment by liquidpele** [comment]
See the examples directory in the repo.

**Comment by scheung38** [comment]
I can grab the index.html and place into chrome to view the 

Welcome to NVD3 page with examples 

But within the project after 

npm install 
npm start

Missing script: start?

**Comment by liquidpele** [comment]
just clone the repo, and then view index.html in your browser.   It loads a site that lets you load the examples from the examples folder into an iframe there.  It also displays documentation.

**Comment by scheung38** [comment]
Thanks where is the data coming from?

**Comment by liquidpele** [comment]
Again, view the examples and their code.   This is an open source project, if you require in depth support, I suggest you look at paid options like amcharts or highcharts.  

https://www.amcharts.com/

http://www.highcharts.com/
