### ISSUE TITLE
Ugly font when Arial font is not present

### ISSUE THREAD

**Issue by guilhermeasg** [novus/nvd3#1830]
Currently, the library's CSS hardcodes Arial as the only font, without fallback. This causes text on graphs to be displayed with Serif fonts (default) on Linux and other systems with no Arial font installed (see screenshot). There should at least be a fallback option to the system's `sans-serif` font.

![area](https://cloud.githubusercontent.com/assets/6297901/18842588/e424f2f2-83eb-11e6-8fee-dc0f34dee94f.png)

![donut](https://cloud.githubusercontent.com/assets/6297901/18842602/ee5e1e9c-83eb-11e6-8837-5583aa37b259.png)

**Comment by liquidpele** [comment]
fixed via https://github.com/novus/nvd3/pull/1831
