### ISSUE TITLE
In the CSS, it's best-practice to list vendor prefixes before the real, unprefixed property

### ISSUE THREAD

**Issue by stowball** [novus/nvd3#1833]
It's to safeguard in case the prefixed property was buggy or the unprefixed one changed how it works somehow.

For instance, [in lines.css L21](https://github.com/novus/nvd3/blob/master/src/css/lines.css#L21), `transition` should come last.

It would be even better if the prefixes were added with Autoprefixer on build though.

**Comment by liquidpele** [comment]
Send us a pull request for any fixes you think are needed :)

**Comment by stowball** [comment]
Here you go :) https://github.com/novus/nvd3/pull/1835
