### ISSUE TITLE
Width of the label

### ISSUE THREAD

**Issue by smvasq** [novus/nvd3#1843]
as I can give more width to the label?

 I need to use long labels and they are displayed cut

<img src="https://cloud.githubusercontent.com/assets/12416278/19318958/1240967c-9081-11e6-9c50-ab61c4fa4ea0.png">

`$scope.options = {
            chart: {
                type: 'discreteBarChart',
                height: 350,
                width: 500,
                margin: {
                top: 20,
                right: 20,
                bottom: 50,
                left: 120
                },

```
            x: function (d) {
                return d.label;
            },
            y: function (d) {
                return d.value + (1e-10);
            },
            showValues: true,
            valueFormat: function (d) {
                return d3.format(',.0f')(d);
                //return d3.format(',.0f')(d);
            },
            duration: 500,
            xAxis: {
                axisLabel: 'Llamantes',
                rotateLabels: 30

            },
            yAxis: {
                axisLabel: 'Cantidad de llamados',
                axisLabelDistance: -10,
                tickFormat: function(d){
                    //return d3.format(',.2f')(d);
                    return d3.format(',.0f')(d);
                }
            }
        }
    };`
```

**Comment by bgth** [comment]
Please increase left margin.

**Comment by liquidpele** [comment]
Use the margin option on the chart to give more margin on the left. . 

https://nvd3-community.github.io/nvd3/examples/documentation.html
