### ISSUE TITLE
Tooltips break for other charts on page if you redraw one of the charts

### ISSUE THREAD

**Issue by derekdon** [novus/nvd3#1845]
I created [an issue here](https://github.com/krispo/angular-nvd3/issues/556) but I think it may be actually more related to this project. Happy to close if this isn't the right place, let me know.

**Comment by liquidpele** [comment]
Try latest code in master.

**Comment by derekdon** [comment]
@liquidpele Cheers, npm installing it now direct from git. Will let you know.

**Comment by derekdon** [comment]
@liquidpele Unfortunately the issue is still present in the latest code installed by running:
```
npm install https://github.com/novus/nvd3/tarball/master --save
```

**Comment by liquidpele** [comment]
Hmm, really?  It should create a separate #id for every chart's tooltip, since each chart creates a new tooltip object each time, so one chart changing its tooltip id shouldn't impact any other charts.   

Can you reproduce in a jsfiddle using just pure nvd3?   If so I can look into it.

**Comment by derekdon** [comment]
@liquidpele Apologies the issue is in fact fixed in pure nvd3. Thanks for your help.

**Comment by liquidpele** [comment]
Awesome, thanks for confirming :)
