### ISSUE TITLE
Can you please clarify difference between nvd3 and nvd3-community?

### ISSUE THREAD

**Issue by andresn** [novus/nvd3#1853]
Hi There,

I realize "community" in one of the repo names / forks, making it pretty self-explanatory; however, it seems most of the dev activity today is going into nvd3.  Therefore, can you help me understand what the purpose of the nvd3-community repo is today?

Thank you in advance for your time!

**Comment by liquidpele** [comment]
I started nvd3-community as a fork when it looked like novus wasn't responding anymore.  Eventually they contacted me and added me to their github org, so now I just do all the work on their main repo.  I keep the other repo around as backup basically.

**Comment by andresn** [comment]
Ah, thank you @liquidpele!
