### ISSUE TITLE
Npm registry thinks 1.7.1 is the latest version.

### ISSUE THREAD

**Issue by jjzazuet** [novus/nvd3#1857]
Hi. In relation to issue #1855, the current build reported as latest in the NPM registry fell down to `1.7.1`.

I can see however that 1.8.4 still seems to be available. An issue arises where a module dependency declared as:

    "nvd3": "1.x.x"

Will now default to `1.7.1` instead of `1.8.4`. For now I just fixed the issue in my code by switching over to `1.8.x` in case folks out there experience the same issue.

Thanks!

**Comment by liquidpele** [comment]
Not sure how to fix that... npmjs should use the newest version properly and not be stupid...

**Comment by liquidpele** [comment]
I tried to publish 1.8.4 again but it says I can't.

**Comment by jjzazuet** [comment]
@liquidpele I mean, it's not a huge showstopper, so I guess this could wait until 1.8.5 (or whichever next version is upcoming) gets pushed into the NPM registry. I'll see if other projects have experienced the same issue.

Thanks for the help!

**Comment by csvan** [comment]
This is a huge issue. We depend on the tooltip changes and fixes introduced in 1.8.1 and up, and being limited to 1.7.1 breaks our current app completely.

As an aside, I would strongly recommend more focus on NPM (especially now that Yarn is gaining traction). Bower is on its way out.

**Comment by gschmottlach-xse** [comment]
+1

I can't use this module either in an Electron application. It looks like there was an attempt to address this issue [here](https://github.com/novus/nvd3/issues/1505l) but unfortunately the check is too restrictive in my environment. There needs to be another release cut (1.8.5?) that addresses [Issue 1505](https://github.com/novus/nvd3/issues/1505) properly and is cut with a proper date so NPM favors 1.8.5 rather than 1.7.1. My only other option is to fork this module but I'd rather see it addressed in a forthcoming release.

Thanks for your consideration . . .

**Comment by liquidpele** [comment]
I'll make a new release to resolve this I guess, however this is really a bug in npm I think as it should consider the latest as being the larger version and not just whatever the last thing published was.

**Comment by liquidpele** [comment]
I wonder if yarn has this issue...

**Comment by csvan** [comment]
As far as I know Yarn uses the NPM registry as well.

**Comment by gschmottlach-xse** [comment]
Will you address Issue 1505 and the problem with the overly restrictive check for require('d3') before this new release?

**Comment by JFox-sk** [comment]
About this I created issue for NPM: https://github.com/npm/npm/issues/14583

**Comment by JFox-sk** [comment]
@liquidpele please set `latest` tag for 1.8.4 version. For this you use command [npm dist-tag](https://docs.npmjs.com/cli/dist-tag).
Thank you.

**Comment by liquidpele** [comment]
That doesn't appear to do anything. 

```
$ npm dist-tag ls nvd3
latest: 1.7.1
$ npm dist-tag add nvd3@1.8.4 latest
+latest: nvd3@1.8.4
$ npm dist-tag ls nvd3
latest: 1.7.1
```

**Comment by zlogic** [comment]
Actually, the https://www.npmjs.com/package/nvd3 page now shows 1.8.4 as the latest release.

**Comment by JFox-sk** [comment]
It is right now.
![latest_tag](https://cloud.githubusercontent.com/assets/2402129/20266176/455a43b0-aa75-11e6-8588-7089a01d52c9.png)

@liquidpele good job :-) Thank you!

**Comment by liquidpele** [comment]
Okay cool, glad it's fixed.
