### ISSUE TITLE
TypeError: 'undefined' is not a function (evaluating 'i.includes(PIIViolatingUrls[t])') on PhantomJSDriver with Selenium

### ISSUE THREAD

**Issue by mthangaraj** [novus/nvd3#1862]
I have done the simple automation script with PhantomJS(1.9.0) Driver and Selenium produced following error TypeError: 'undefined' is not a function (evaluating 'i.includes(PIIViolatingUrls[t])').
My project lib folder contains phantomjsdriver-1.3.0.jar file

Actually am new for PhantomJS. Anyone please help me to solve the issue.

Mycode is:-

import java.util.concurrent.TimeUnit;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.phantomjs.PhantomJSDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
public class phantomjs {
	public static void main(String a[]){
		try{
			  WebDriver driver;
			  DesiredCapabilities dCaps = new DesiredCapabilities();
			  dCaps.setJavascriptEnabled(true);
			  dCaps.setCapability("browserConnectionEnabled", true);
			  dCaps.setCapability("takesScreenshot", false);
			   driver = new PhantomJSDriver();
			  String baseUrl = "http://www.mkyong.com/java/how-to-create-directory-in-java";
			  driver.manage().timeouts().implicitlyWait(30, TimeUnit.SECONDS);
			  driver.get(baseUrl);
                          WebElement element = driver.findElement(By.linkText("Android"));
			 if(element.isDisplayed()){
				 System.out.println("Displayed");
			 }else{
				 System.out.println("Not Displayed");
			 }
			  driver.findElement(By.linkText("Android")).click();
			  driver.findElement(By.linkText("Java Core")).click();
			  driver.findElement(By.name("q")).sendKeys("test");
                         driver.quit();
			
		}catch(Exception e){
			e.printStackTrace(); 
		 }
      }
}

Output:-

TypeError: 'undefined' is not a function (evaluating 'i.includes(PIIViolatingUrls[t])')

  http://cdn1.developermedia.com/a.min.js:1
  http://cdn1.developermedia.com/a.min.js:1
  http://cdn1.developermedia.com/a.min.js:1
  http://cdn1.developermedia.com/a.min.js:1
org.openqa.selenium.NoSuchElementException: Error Message => 'Unable to find element with link text 'Android''
 caused by Request => {"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"39","Content-Type":"application/json; charset=utf-8","Host":"localhost:23807","User-Agent":"Apache-HttpClient/4.5.2 (Java/1.8.0_101)"},"httpVersion":"1.1","method":"POST","post":"{\"using\":\"link text\",\"value\":\"Android\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/1b9dc7d0-a274-11e6-a8b3-49a5ef9bea2c/element"}
Command duration or timeout: 30.37 seconds
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'c7b525d', time: '2016-09-01 14:52:30 -0700'
System info: host: 'thangaraj', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.19.0-25-generic', java.version: '1.8.0_101'
Driver info: org.openqa.selenium.phantomjs.PhantomJSDriver
Capabilities [{applicationCacheEnabled=false, rotatable=false, handlesAlerts=false, databaseEnabled=false, version=1.9.0, platform=LINUX, browserConnectionEnabled=false, proxy={proxyType=direct}, nativeEvents=true, acceptSslCerts=false, driverVersion=1.0.3, locationContextEnabled=false, webStorageEnabled=false, browserName=phantomjs, takesScreenshot=true, driverName=ghostdriver, javascriptEnabled=true, cssSelectorsEnabled=true}]
Session ID: 1b9dc7d0-a274-11e6-a8b3-49a5ef9bea2c
*** Element info: {Using=link text, value=Android}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:206)
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:158)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:631)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:369)
	at org.openqa.selenium.remote.RemoteWebDriver.findElementByLinkText(RemoteWebDriver.java:426)
	at org.openqa.selenium.By$ByLinkText.findElement(By.java:246)
	at org.openqa.selenium.remote.RemoteWebDriver.findElement(RemoteWebDriver.java:361)
	at testing.phantomjs.main(phantomjs.java:32)
Caused by: org.openqa.selenium.remote.ScreenshotException: Screen shot has been taken
Build info: version: 'unknown', revision: 'c7b525d', time: '2016-09-01 14:52:30 -0700'
System info: host: 'thangaraj', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.19.0-25-generic', java.version: '1.8.0_101'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:138)
	... 6 more
Caused by: org.openqa.selenium.NoSuchElementException: Error Message => 'Unable to find element with link text 'Android''
 caused by Request => {"headers":{"Accept-Encoding":"gzip,deflate","Connection":"Keep-Alive","Content-Length":"39","Content-Type":"application/json; charset=utf-8","Host":"localhost:23807","User-Agent":"Apache-HttpClient/4.5.2 (Java/1.8.0_101)"},"httpVersion":"1.1","method":"POST","post":"{\"using\":\"link text\",\"value\":\"Android\"}","url":"/element","urlParsed":{"anchor":"","query":"","file":"element","directory":"/","path":"/element","relative":"/element","port":"","host":"","password":"","user":"","userInfo":"","authority":"","protocol":"","source":"/element","queryKey":{},"chunks":["element"]},"urlOriginal":"/session/1b9dc7d0-a274-11e6-a8b3-49a5ef9bea2c/element"}
For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
Build info: version: 'unknown', revision: 'c7b525d', time: '2016-09-01 14:52:30 -0700'
System info: host: 'thangaraj', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '3.19.0-25-generic', java.version: '1.8.0_101'
Driver info: driver.version: unknown

**Comment by liquidpele** [comment]
Problems with integrating with selenium is not related to this project.  Just glancing at your output though, the error seems to be "Unable to find element with link text 'Android''"
