### ISSUE TITLE
forced y axis rendering issue

### ISSUE THREAD

**Issue by NikolaMandic** [novus/nvd3#1866]
when I try to render graph with 

`.yDomain([0,35])`

then  on previous versions it went off bounds 
but with new versions it interpolates the off bounds parts and makes a quasi datapoint on the places where it breaks

so if a peak goes off bounds when y axis is forced in this way  it would be nice that it does not draw anything there 

here is how it worked before
http://jsfiddle.net/nj21t5tb/1/
it went out of bounds

here is how it works now
http://jsfiddle.net/nj21t5tb/3/
so for this specific use case what makes most sense to you to present this type of data
isn't it better not to interpolate while not going out of bounds

**Comment by NikolaMandic** [comment]
I'd have to double check this sorry for bugging

**Comment by Nucleotide** [comment]
It seems that both fiddles are with nv.version = '1.1.11b'

**Comment by NikolaMandic** [comment]
changed

**Comment by liquidpele** [comment]
IIRC, we changed the default interpolation at some point so that it was consistent across multiple models.   You can set it to whatever you like though, just use the interpolate(...) option.  

https://nvd3-community.github.io/nvd3/examples/documentation.html

**Comment by NikolaMandic** [comment]
hm we are trying to make it not interpolate when line is out of bounds of y axis(bounds set manually)
it seems that it does not come out of the box with changing how line is interpolated 
so most probably trying to make line undefined on that segment might do it
have to check that

**Comment by NikolaMandic** [comment]
or maybe custom interpolator might be more elegant

**Comment by NikolaMandic** [comment]
this is what I was hoping out of the box :-D
thanks all
http://bl.ocks.org/tomgp/77772ee20f8d509ad5b4

**Comment by NikolaMandic** [comment]
summary:
It seems that at current point in time stock interpolations don't do this specific use case
while using custom interpolator it is possible to have gaps in line where it goes out of bounds
closing in:
5 
4
3
2
1
closed!!!
