### ISSUE TITLE
Scatter: improper way to check if scale has been changed.

### ISSUE THREAD

**Issue by fan-self** [novus/nvd3#1879]
nv.models.scatter check if scale has been change by:
**var scaleDiff = x(1) !== x0(1) || y(1) !== y0(1) || z(1) !== z0(1);**

Use case: a lineChart with forceY([1]) .

![image](https://cloud.githubusercontent.com/assets/20783245/20785558/c7e50afe-b7db-11e6-832e-442a58cb2f74.png)

Click 'Show Focus' button to turn on the focus panel, like below, the point of interactive guide line is not anchored properly:
![image](https://cloud.githubusercontent.com/assets/20783245/20785617/15794582-b7dc-11e6-9ed8-d3de2198524c.png)
The height of chart(the upper part) has been changed while turn on the focus panel. But the scaleDiff is ‘false’ in that the upper value of y-scale-domain just set as 1.

Alternatives(??):

        var refVal = (x.range()[1] - x.range()[0]) / 2;
        var scaleDiff = x(refVal) !== x0(refVal);
        if (!scaleDiff) {
            refVal = (y.range()[1] - y.range()[0]) / 2;
            scaleDiff = y(refVal) !== y0(refVal);
            
            if (!scaleDiff) {
                refVal = (z.range()[1] - z.range()[0]) / 2;
                scaleDiff = z(refVal) !== z0(refVal);
            }
        }

**Comment by liquidpele** [comment]
I'm sorry, I'm not seeing anything wrong with those images.   

Can you elaborate exactly what is different about them that is wrong?

**Comment by ThomasBrierley** [comment]
I think fan-self is correct, I'm just making a PR for @1865 which I traced to scaleDiff being insufficient... I've tried using domain in addition to scale which appears to work for the test cases in that issue.

@fan-self can you post a jsfiddle to check if this is the same issue?

**Comment by fan-self** [comment]
Thanks for your replies.

https://jsfiddle.net/as881dyL/1/

The point is off the line after turning on the focus. @ThomasBrierley @liquidpele

**Comment by liquidpele** [comment]
Updated to actually use master branch.  Seems fine now. 

https://jsfiddle.net/as881dyL/3/
