### ISSUE TITLE
Set graph height, legend take the remaining height

### ISSUE THREAD

**Issue by EloHailwidis** [novus/nvd3#1883]
For now, the height param set the height for the whole thing (graph + legend). How can I set only the graph height ?

For example, the total height would be 500: we set 300 for the graph and the legend would fill the 200 left.

**Comment by liquidpele** [comment]
You can adjust by using chart.margin(...) and chart.legend.height(...) as needed. 

https://nvd3-community.github.io/nvd3/examples/documentation.html#legend

**Comment by EloHailwidis** [comment]
Thanks :)
