### ISSUE TITLE
Interactive guideline not working properly in line charts with time in x axis

### ISSUE THREAD

**Issue by adricu** [novus/nvd3#1897]
Hi guys!

I have had this issue since I began using NVD3.
When using line charts, if temporal data is used in the x axis, the interactive guideline doesn't work properly.
Versions:
d3: 3.5.17
nvd3: 1.8.5
Hover event doesn't seem to get the proper datapoints and it shows also previous/next datapoints if any of them are missing in the actual hover event. This behaviour is captured in the following pic:

![nvd3 issue](https://cloud.githubusercontent.com/assets/2545053/21190259/7f1d3058-c221-11e6-8e56-398d09135f87.png)

I also attach a fiddle where the issue is reproduced.

https://jsfiddle.net/c8qzbq7w/3/

Hope someone can help.

Thanks.

Adrián

**Comment by martinxyz** [comment]
It seems to happen whenever a line has points with X outside of the xDomain. To reproduce, edit test/lineChartTest.html line 240 and add `chart.xDomain([5, 70]);` (See my referenced issue above.)

**Comment by liquidpele** [comment]
Regarding it selecting the closest point, that's expected... interactive guideline requires that every series have data for ever x-axis point.   You can enter null for the values if you want, as shown here in an update to your jsfiddle:  https://jsfiddle.net/c8qzbq7w/5/    but that does leave breaks in the line.

**Comment by martinxyz** [comment]
@liquidpele yes, but it also happens when the x values for all lines are identical.

**Comment by liquidpele** [comment]
can you make a jsfiddle showing that?

**Comment by adricu** [comment]
@liquidpele Thanks for the aclaration, that solves this issue.

**Comment by martinxyz** [comment]
@liquidpele here is a much simpler fiddle: https://jsfiddle.net/menn1jhk/

**Comment by martinxyz** [comment]
On second check, this is indeed a different problem from the original issue. I'm opening a new one.

**Comment by martinxyz** [comment]
Split off into new issue: https://github.com/novus/nvd3/issues/1913
