### ISSUE TITLE
How can i show blank line for missing data

### ISSUE THREAD

**Issue by johirbuet** [novus/nvd3#1915]
I am requesting data from November 1 to December 31 and trying to plot a line chart using NVD3. But for some issue the Novemeber data is missing from data source. But my chart only shows decemeber chart givimg me the illusion that november data was not requested. Is there any option in NVD3 which will allow me to draw a blank line showing some blank line for the month novemeber?

**Comment by liquidpele** [comment]
You can use null for the value of missing data, or you can use forceX or other options to manually set the range/domain of the x axis.  

https://nvd3-community.github.io/nvd3/examples/documentation.html#axis

**Comment by johirbuet** [comment]
Thanks. Got the idea
