### ISSUE TITLE
nvd3 bar chart ploblem

### ISSUE THREAD

**Issue by gatspy** [novus/nvd3#1927]
Nvd3 how to achieve such a bar chart?
[bar chart ](http://raywinstead.com/bp/bpmonth1a.jpg)

**Comment by Craicerjack** [comment]
This is not what issues are for.

**Comment by liquidpele** [comment]
View the examples in the repo, view the documentation, this is open source, have fun :)

https://nvd3-community.github.io/nvd3/examples/documentation.html
