### ISSUE TITLE
How to force x axis in mutlichart?

### ISSUE THREAD

**Issue by adishap** [novus/nvd3#1939]
I want to show start and ending dates on x axis where I have data available for few dates between both start date and end date.

**Comment by bgth** [comment]
please share a jsfiddle for what you have and what change you want in that jsfiddle.

**Comment by jeznag** [comment]
Did you try `multiChart.xAxis.showMinMax(true);`

**Comment by adishap** [comment]
@jeznag that worked. Thanks.
