### ISSUE TITLE
Wrong y axis in multibar chart

### ISSUE THREAD

**Issue by djKooks** [novus/nvd3#1942]
I checked that y axis shows wrong max size in multiBarChart.

<img width="555" alt="screen shot 2017-01-31 at 1 47 21 pm" src="https://cloud.githubusercontent.com/assets/1720209/22452656/16b1803a-e7bc-11e6-9d49-5174c573857e.png">

<img width="553" alt="screen shot 2017-01-31 at 1 51 39 pm" src="https://cloud.githubusercontent.com/assets/1720209/22452741/c64add48-e7bc-11e6-97f0-a0bf544cb5ab.png">

As you see, max value of y axis is 9.8, though biggest size of bar is 67.2.
It only causes in 'Grouped' mode(not at 'Stacked'). This is the data form of this graph.
```
[{"key":"abc","color":"#23cfbd","values":[{"x":"direct","y":"67.23"},{"x":"organic_search","y":"22.98"},{"x":"social","y":"0.00"},{"x":"referral","y":"9.79"},{"x":"mail","y":"0.00"},{"x":"display_ad","y":"0.00"}]}]
```
Does anybody know about this?

**Comment by bgth** [comment]
Hi, Its the problem with your data. Please change the y Axis values to float instead of string. It will work.

**Comment by djKooks** [comment]
@bgth Thanks! You're right.
