### ISSUE TITLE
Memory leak causes browser tab to crash

### ISSUE THREAD

**Issue by rbgarga** [novus/nvd3#1956]
A bug was reported in pfSense and after digging into it a developer figured out it was related to nvd3. Details are on pfSense bug:

https://redmine.pfsense.org/issues/7157

Looks like root cause is https://github.com/novus/nvd3/blob/ff012b78a3af803243dad9e975032329e63fe367/src/models/axis.js#L383

```js
nv.utils.inheritOptionsD3(chart, scale, ['domain', 'range', 'rangeBand', 'rangeBands']);
```

**Comment by liquidpele** [comment]
They appear to be using 1.8.3, and it exists here in their repo:  
https://github.com/pfsense/pfsense/tree/master/src/usr/local/www/vendor/nvd3

Will look into the issue... or if you figure it out first just throw a PR my way :)

**Comment by liquidpele** [comment]
I build latest now, so the fix should be in the master branch build dir if you want to verify.

**Comment by jeffg2k** [comment]
I'm not sure that fixed the memory leak in nvd3 - at least not in the instance I'm seeing it.  Here is an example: http://jsfiddle.net/gzzdmz7j/
