### ISSUE TITLE
Uncaught ReferenceError: extraValue1 is not defined

### ISSUE THREAD

**Issue by lumberj** [novus/nvd3#1959]
```
nv.d3.js:9918 Uncaught ReferenceError: extraValue1 is not defined
    at SVGSVGElement.<anonymous> (nv.d3.js:9918)
```

See: https://github.com/novus/nvd3/commit/613b5cdeb5284f9bb2ef287b4712da56751a781e

Using `multiChart` with bars and setting `stacked: true` in the bar options will lead to this error.

jsFiddle using nvd3 from current master

https://jsfiddle.net/r9u7cv3p/1/

**Comment by lumberj** [comment]
Actually, looks like that happens whether or not `stacked` is set on the bar

**Comment by bgth** [comment]
Hi @lumberj, What you mentioned is an issue. Have sent a pull request.

**Comment by liquidpele** [comment]
merged and rebuilt master
