### ISSUE TITLE
Value displayed in yAxis isn't the correct

### ISSUE THREAD

**Issue by lsmagalhaes** [novus/nvd3#196]
I made a cumulativeLineChart (code [here](http://stackoverflow.com/questions/17790062/angular-d3-tickformat-using-a-strang-value-for-y?noredirect=1#comment25953660_17790062)) but there's a problem I'm struggling with: the value I created for the y axis isn't really used by the chart. For example, if some point has `y = 1.7205607426554128`, it's displayed as `0.3602803713277064`.

The chart doesn't seems wrong, I think this recalculation is keeping the proportions, but values displayed on the chart and tooltips are just wrong. I noted something else:

```
// suppose a set of a certain line
[a, b, ...., z] where each one is {x: x', y: y'}
a = {x: x', y: y', display: {y: y''}}, 
    fa = y' / y''  (it's usually 1/0, infinity)
b =  {x: x', y: y', display: {y: y''}}, 
    fb = y' / y'', where fb < fa
...
z = 
    fz = y' / y'', where fz < ... < fb < fa
```

In another words, there's a ratio decreasing over the iteration. What's going on, here?

**Comment by lizadaly** [comment]
In case anyone else finds this, this happens if your y-axis data is not in ascending order. This isn't documented; that would definitely have saved me a lot of time.

**Comment by liquidpele** [comment]
huh?  Do you mean the x-axis data?   nvd3 definitely requires that the x-axis values are ordered prior to giving them to nvd3 (for a variety of reasons).  So for instance a series can be [{x: 0, y: 3}, {x: 1, y: 2}, {x: 2, y: 8}], but [{x: 1, y:2}, {x: 2, y: 8}, {x: 0, y: 3}] will give strange behaviors.
