### ISSUE TITLE
Line chart with sum(yAxisValue)

### ISSUE THREAD

**Issue by mhinton311** [novus/nvd3#1962]
I am creating a line chart over a 15 minute time interval (xAxis) but want the yAxis to be a Sum/Running Total of the Y values passed in. 

Is this possible on the javascript side OR do I need to handle it when gathering the data? Can someone help me if so? 

Thanks.

**Comment by liquidpele** [comment]
nvd3 charts the exact data given, so you'll want to add up the running value before passing it in.
