### ISSUE TITLE
Function in addGraph never executes:

### ISSUE THREAD

**Issue by QuantumInformation** [novus/nvd3#1964]
Code is here:
https://github.com/quantumjs/atmospheric-diagnostics/blob/master/src/AtmosphericDiagnostics.ts#L61

Demo is here:
https://github.com/quantumjs/atmospheric-diagnostics/tree/master/demo

You need to run webpack on the root of the repo and in the demo folder to get the demo running:

End URL look something like this when running locally:

http://localhost:63342/atmospheric-diagnostics/demo/build/index.html

**Comment by QuantumInformation** [comment]
Live demo is here:
http://quantumjs.com/atmospheric-diagnostics/demo/build/

**Comment by QuantumInformation** [comment]
Data comes back:
![image](https://cloud.githubusercontent.com/assets/216566/22998255/d9dede1e-f3cd-11e6-81ef-af47eb47f594.png)

![image](https://cloud.githubusercontent.com/assets/216566/22998541/25803380-f3cf-11e6-899b-97f0cb840a66.png)

**Comment by bgth** [comment]
Hi @QuantumInformation, Can you please tell if you are using d3js 3.5.17 ? nvd3 supports only d3js 3.5 as of now. i saw you are using d3js 4.5 in your app.js.

**Comment by QuantumInformation** [comment]
Thanks @bgth I'm now getting proper errors )

Uncaught TypeError: nvd3_1.models.discreteBarChart(...).x(...).y(...).staggerLabels(...).tooltips is not a function
    at Object.generate (app.js:25256)
    at renderLoop (app.js:9822)

Would be great if the types were kept in sync: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/2f711746366f18454e4ef689ce79b43ef76a3f3c/nvd3/index.d.ts

**Comment by QuantumInformation** [comment]
My latest error:

![image](https://cloud.githubusercontent.com/assets/216566/23014506/39c6ab50-f427-11e6-9414-80dc845c7b3b.png)

For some reason my data expects to have a values props.

**Comment by QuantumInformation** [comment]
Really hard to debug this too that line is way too long!

**Comment by bgth** [comment]
Can you please check if data format matches and the tickformat matches as well to example given? https://nvd3-community.github.io/nvd3/

**Comment by QuantumInformation** [comment]
Ok I changed it to:    `.datum({values:data.list})`

![image](https://cloud.githubusercontent.com/assets/216566/23017661/14fabaf8-f433-11e6-9bd7-8b2a89e955a7.png)

![image](https://cloud.githubusercontent.com/assets/216566/23017667/1a8e1da2-f433-11e6-9355-25e4622a8da9.png)

**Comment by bgth** [comment]
Your problems with setup of the library should be over now. Now, you need to look at the input you are giving to the library. Please check if the data input to the library is formatted the way nvd3 requires and you should be good to go. [discreteBar](https://github.com/nvd3-community/nvd3/blob/gh-pages/examples/discreteBarChart.html)

**Comment by QuantumInformation** [comment]
thanks!
