### ISSUE TITLE
[legends/controls] Allow configuration / observation of chart controls

### ISSUE THREAD

**Issue by jfsiii** [novus/nvd3#198]
As far as I can tell, it's not possible to do the following on stacked charts:

 * change the text of the controls
 * observe clicks on controls (which *is possible* on legends, for example)

Exposing `controls` [as is done with other chart parts like `legend`](https://github.com/novus/nvd3/blob/master/src/models/multiBarTimeSeriesChart.js#L316) would solve most of the pain points.

It'd be nice if [`controlsData`](https://github.com/novus/nvd3/blob/master/src/models/multiBarTimeSeriesChart.js#L157) also got an accessor function, but just exposing `chart.controls` would be a big step.

**Comment by liquidpele** [comment]
Should be all working in latest dev.
