### ISSUE TITLE
First and Last Bar is cut off on the Historical Bar Graph

### ISSUE THREAD

**Issue by dekkofilms** [novus/nvd3#1985]
I'm just using dummy data right now, and I can't figure out why my bar chart's first bar is being cut off, and the last one being cut off in the midway point. This is my first time using nvd3/d3 and I'm just seeking some advice. I found a few github repos with open issues on this matter, but no strong solution yet.

Here is my code so far, but not much going on really:

```
$scope.options2 = {
  chart: {
      type: 'historicalBarChart',
      height: 276,
      x: function(d){return d[0];},
      y: function(d){return d[1];},
      showValues: true,
      legendPosition: false,
      xAxis: {
          axisLabel: 'Date',
          tickFormat: function(d) {
              return d3.time.format('%x')(new Date(d))
          },
          rotateLabels: 30,
          showMaxMin: false
      },
      yAxis: {
          axisLabel: 'Amount of Orders',
          axisLabelDistance: -10,
          tickFormat: function(d){
              return d3.format('d')(d);
          }
      },
      clipEdge: true,
  }
};
$scope.data2 = [
  {
    key: "Orders",
    bar: "true",
    values: [[1138683600000,10],[1148683600000,20],[1158683600000,15],[1168683600000,40]],
    color: '#79d8c5'
  }
];
```

And the output is:

<img width="637" alt="screen shot 2017-03-08 at 3 52 48 pm" src="https://cloud.githubusercontent.com/assets/14862852/23728452/791fd8f2-0422-11e7-993d-b774a006dd90.png">

**Comment by bgth** [comment]
The following code is angular nvd3. Can you please provide a jsfiddle with pure nvd3 with the above issue?

**Comment by dekkofilms** [comment]
http://jsfiddle.net/6kxrgta6/

**Comment by bgth** [comment]
This is an issue with nvd3. [historical Bar](http://jsfiddle.net/bgth/4d6e2njo/3/)

**Comment by jeznag** [comment]
Hi, have you tried using `padData(true)`? This fixes the issue:
![image](https://cloud.githubusercontent.com/assets/1034890/24336179/4319d056-12d6-11e7-8e86-ff3fdcd6423f.png)
