### ISSUE TITLE
nv causes Modernizr to throw error in IE8 because of console.log code

### ISSUE THREAD

**Issue by jacobq** [novus/nvd3#199]
The code snippet below (nv.js near line 38) assumes that typeof console.log == "function" but this is not true in IE8; it is actually "object". This defect is often masked because IE8 also does not natively support Function.prototype.bind, but it is often added with modernizr. In that case, this code causes modernizr to throw a TypeError because bind is called with an object instead of a function.

Here is an example of the error (use IE8):
http://jsfiddle.net/rJxy2/3/show/

I believe a simple work-around would be replacing "console.log" with 'typeof console.log === "function"' in the second the conditional. Perhaps there is a more elegant solution that will actually give full logging support to IE8, but that is not essential. Mainly it at least needs to not throw an error.

From https://github.com/novus/nvd3/blob/c57626ad9bfc3f791520202c1469c4934ebb99c4/nv.d3.js#L38

	// ********************************************
	//  Public Core NV functions

	// Logs all arguments, and returns the last so you can test things in place
	nv.log = function() {
	  if (nv.dev && console.log && console.log.apply)
		console.log.apply(console, arguments)
	  else if (nv.dev && console.log && Function.prototype.bind) {
		var log = Function.prototype.bind.call(console.log, console);
		log.apply(console, arguments);
	  }
	  return arguments[arguments.length - 1];
	};

**Comment by liquidpele** [comment]
IE8 isn't supported, and I made a check for console too so shoudl be fixed regardless.
