### ISSUE TITLE
cumulative line chart uses wrong algorithm

### ISSUE THREAD

**Issue by bernhard-42** [novus/nvd3#2013]
Currently cumulative line chart uses the formula `(y_i - v) / (1 + v)` to determine the relative change from `y_i` to the index value `v`.
This is not correct, the relative change for `y_i` is simply `(y_i - v) / v` (see also http://mbostock.github.io/protovis/ex/index-chart.html, where Mike uses
`return {index:i, price:((d-v)/v)}; }) ` )

I've issued pull request https://github.com/novus/nvd3/pull/2002 for this.

**Comment by bgth** [comment]
Can we please close this? Pull request #2002 is merged ..
