### ISSUE TITLE
How can I set background color for NVd3 Charts ?

### ISSUE THREAD

**Issue by TojThank** [novus/nvd3#2021]
I am trying to set background color for MultiBar, Pie , Line , MultiBarHorizontal . But I am not able to find a option for the same . Can any body please guide on this.

**Comment by liquidpele** [comment]
Put the chart in a div, give the div a background color.

**Comment by TojThank** [comment]
Hi 
I am looking for something like 
![background](https://cloud.githubusercontent.com/assets/28049656/25477384/f8d840e8-2b5a-11e7-97f2-3e264b86ed0f.jpg)

putting the chart in div and giving the div a background color gives output like 
![image](https://cloud.githubusercontent.com/assets/28049656/25477511/679f5a16-2b5b-11e7-9aa7-38c03d4cfa26.png)

**Comment by liquidpele** [comment]
There isn't a nvd3 option for that.   You could try looking to do it with CSS, but honestly I don't think d3 puts an object there in the shape you're wanting.   Your best bet is to probably float the svg on top of a div that's positioned to be the exact size you need under the chart.   It won't be responsive but at least it'll look how you want.  

If you want to add the option to nvd3 to allow this behavior, please send us a pull request :)

**Comment by TojThank** [comment]
Thanks for the input :)
