### ISSUE TITLE
Bar chart x-axis label cut off when staggerLabels(true)

### ISSUE THREAD

**Issue by rjbriody** [novus/nvd3#2022]
The x axis label is cut off when `.staggerLabels(true)` is used in conjunction with an xAxis label for the bar chart. It appears as though the chart is not taking the additional x axis labels' height into account when they are staggered (but I am not familiar w/ the underlying code so that is just a guess). 

This can be easily reproduced using the Live Code - Discrete Bar Chart example from the main webpage.

**This screenshot shows things working correctly**
![image](https://cloud.githubusercontent.com/assets/492786/25459541/9a6ff6ee-2a93-11e7-89a5-42fdaabad988.png)

**This screenshot shows the x axis label being cut off**
![image](https://cloud.githubusercontent.com/assets/492786/25459503/650d0fdc-2a93-11e7-8f32-9b7faac8a4a6.png)

Code used:
```
nv.addGraph(function() {
  var chart = nv.models.discreteBarChart()
    .x(function(d) { return d.label })
    .y(function(d) { return d.value })
    .staggerLabels(true)
    .tooltips(false)
    .showValues(true)

chart.xAxis.axisLabel('WILL BE CUT OFF')
        
  d3.select('#chart svg')
    .datum(data)
    .transition().duration(500)
    .call(chart);
  nv.utils.windowResize(chart.update);

  return chart;
});
```

Browsers: 
Chrome Version 57.0.2987.133 (64-bit)
Safari Version 10.1 (11603.1.30.0.34)

**Comment by liquidpele** [comment]
You can adjust for that by adding some padding to the bottom of the chart via the "margin" option.  

https://nvd3-community.github.io/nvd3/examples/documentation.html#discreteBarChart

**Comment by rjbriody** [comment]
`chart.staggerLabels(true).margin({bottom: 60});` seems to be an acceptable work-around. Thanks for that!

I'll let you decide if this ticket should remain open or not.
