### ISSUE TITLE
chart.title is not a function

### ISSUE THREAD

**Issue by ConstantinoSchillebeeckx** [novus/nvd3#2035]
Is `.title()` not a function anymore? 

The [documentation](https://nvd3-community.github.io/nvd3/examples/documentation.html) seems to specify it:
>var chart = nv.models.pieChart();
chart.width(500);
chart.title('stuff').titleOffset(-10);
chart.options({height: 500, donut: true});

Yet when I call the following, I get a ".title is not a function" error:
```javascript
var chart = nv.models.scatterChart()
  .useVoronoi(true)
  .color(d3.scale.category10().range())
  .duration(300)
  .title('moo');
```

**Comment by liquidpele** [comment]
Well, pieChart doesn't use a title anyway, only donutChart does because it goes in the middle of the donut...   that's an interesting but though that it inherits it from pie.js, that should probably only be in donutChart.js instead of being inherited like that...

**Comment by ConstantinoSchillebeeckx** [comment]
I'm rendering multiple scatter plots on a single page - looks like I'm going to have to manually insert a title?

**Comment by liquidpele** [comment]
Also your posted example appears to be using scatterChart anyway.

**Comment by liquidpele** [comment]
Each chart type has different options... title isn't an option for scatterChart.   If you want to make it an option though, send us a pull request :)
