### ISSUE TITLE
For lineChart and historicalBarChart, x-axis labels/grids are not centered

### ISSUE THREAD

**Issue by sujit77** [novus/nvd3#2060]
- [x] X-axis labels/grids are not in sync with points in line or bar for lineChart and historicalBarChart. 
- [x] X-axis grid points to incorrect point drawn over chart.
- [x] X-axis labels don't remain centered at different scale.

Working example - https://jsfiddle.net/sujit77/pp7Ljh17/

I tried to translate `ticks` present under `g` having classes `nv-x nv-axis nvd3-svg`, and it seemed to be working.

Also, in my example, X label 'Jun 25' should be shown. But due to some calculation NVD3 is showing 'Jun 26'. which is misalligned and pointing to incorrect point.

I have tested with different data at different resolution and similar issue I can see for different points.

![grid not synced with point](https://user-images.githubusercontent.com/26189654/27732907-1a7a1e3c-5db1-11e7-8cb7-3fa851d38141.png)

![incorrect pointed labels](https://user-images.githubusercontent.com/26189654/27732912-2038517c-5db1-11e7-8602-8aadad3fe2a0.png)

![historical chart label misallignment](https://user-images.githubusercontent.com/26189654/27733095-e4d9d55a-5db1-11e7-8315-c64b06412a60.png)

![label alignment](https://user-images.githubusercontent.com/26189654/27733165-47c7d13a-5db2-11e7-914e-96f0bfdd078e.png)

**Comment by sujit77** [comment]
I think all above mentioned issues can be fixed just by adjusting translate value of `ticks` present under `g` with class `nv-x nv-axis nvd3-svg`

**Comment by sujit77** [comment]
I found similar issue [here](https://stackoverflow.com/questions/33959649/nvd3-line-chart-tics-wrongly-aligned-to-grid-when-using-datetype-on-xaxis)

In his case, solution lies in the date formatting of X-axis label. 
But the same is not working for me.
New [working URL](https://jsfiddle.net/sujit77/pp7Ljh17/1/)

**Comment by jeznag** [comment]
Seems to be due to not setting xScale.

Fixed if you do `chart.xScale(d3.time.scale())` as per liquidpele's comment here: https://github.com/novus/nvd3/issues/1114

**Comment by sujit77** [comment]
@jeznag Thanks, `chart.xScale(d3.time.scale())` works perfectly in this situation.
