### ISSUE TITLE
Incompatible GPL 3 license of bullet.js with APL nvd3

### ISSUE THREAD

**Issue by bolkedebruin** [novus/nvd3#2064]
Hi there,

We are using nvd3 in Apache Airflow. While doing due diligence on our licenses we came by an issue in nvd3 which needs clarification.

bullet.js does not specify a license by itself. With some creative googleing we end up at https://bl.ocks.org/mbostock/4061961 which states that bullet.js is licensed under GPL3. Which is not compatible with the APL.

There might be an issue with bullet.js itself being licensed under GPL as is seems to be based on BSD code but that is another issue.

Can you please provide clarity?

**Comment by bolkedebruin** [comment]
I have looked at the history of nvd3 “bullet” implementation and its history says it is copied from d3-examples (https://github.com/novus/nvd3/commit/b7670eeaffe45a23bae1797306750c2b6ae8bcce)  which is located at: https://github.com/d3/d3-plugins/blob/master/bullet/bullet.js , this is authored by the same author as the “protovis” version, but is licensed under a BSD 3 clause: https://github.com/d3/d3-plugins/blob/master/LICENSE.

It should be fine, just like a confirmation.

**Comment by bolkedebruin** [comment]
@mbostock would you mind sharing your opinion here? I reached out by email, but not sure if that is working.

Issue is that the "bullerChart" commit is before what I can find as a first commit as d3 examples (d3-plugins).

**Comment by mbostock** [comment]
Yes, bullet.js is BSD-licensed. (If you like, you can consider it dual-licensed, so you can also use the GPL if you prefer.) You can obtain a BSD-licensed version from the d3-plugins repository or from an earlier version of the d3 repository:

https://github.com/d3/d3/blob/40be541c4cc27b18d82688c86dea55c205384f80/examples/bullet/bullet.js
https://github.com/d3/d3-plugins/blob/master/bullet/bullet.js

**Comment by bolkedebruin** [comment]
Thanks.
