### ISSUE TITLE
How to make charts responsive?

### ISSUE THREAD

**Issue by m-oliv** [novus/nvd3#2091]
Hi everyone,

I am using NVD3 to plot some info on my platform, but I don't seem to be able to make the charts responsive.

This is the chart that I currently have:

![Line Chart](https://i.imgur.com/t3soSRS.png)

As you can see, the yAxis labels are cut. If the chart was responsive, it should scale with the parent container, meaning that the yAxis labels would instead remain inside the container.

To fix this, I've tried to add the _viewBox_ parameter to the SVG and setting the _preserveAspectRatio_ parameter, but the result hasn't changed.

I have also tried to set the CSS _overflow_ property to _visible_, but the only thing that I accomplished was having the labels "spilling" out of the container.

This is the JavaScript code I'm using to create the chart:
`nv.addGraph(function () {
                        chart = nv.models.lineChart()
                            .useInteractiveGuideline(false);

                        if (data.hasOwnProperty("key") && isColumnTotalChart || isRowTotalChart) {
                            chart.xAxis
                                .axisLabel(data.chartDataset.key);
                        }

                        chart.xAxis.tickValues(data.chartLabelIndexes)
                            .tickFormat(function (d) {
                                return data.chartLabels[d];
                            });

                        chart.yAxis.tickFormat(d3.format(',.1f'));

                        if (chartData.labels.length > 10) {
                            chart.xAxis.rotateLabels(-90);
                        }

                        chart.xAxis.showMaxMin(true);

                        d3.selectAll(chartSelectedSvg + " > *").remove();
                        d3.select(chartSelectedSvg)
                            .attr('viewBox', '0 0 600,600')
                            .attr('preserveAspectRatio', 'xMaxYMid')
                            .datum(data.chartDataset)
                            .transition().duration(500)
                            .call(chart);

                        nv.utils.windowResize(chart.update);

                        return chart;
                    });`

This is my HTML:

`<div ng-show="chartColumnData.data.length !== 0">
                                <div id="chartTotalColumns" ng-show="chartColumnData.data.length !== 0">
                                    <svg></svg>
                                </div>
                                <div layout="row" layout-padding layout-align="center center" ng-show="chartColumnData.data.length !== 0">
                                </div>
                            </div>`

...and, finally, this is the CSS I'm using:
`div>svg {
    min-height: 30vh;
    margin: 0 auto;
    display: block;
}`

Is there any way to make the chart adapt to the parent container's size?

**Comment by m-oliv** [comment]
I've figured it out. To fix the issue, I only have to adjust the margins.

**Comment by liquidpele** [comment]
Yup, the d3 placement requires strict margin control... it would be nice to make it automatic but no one has ever taken that on.
