### ISSUE TITLE
Multichart stateChange not being called (bug)

### ISSUE THREAD

**Issue by marina1349** [novus/nvd3#2100]
I am trying to hook onto the stateChange event for the multichart:

`        chart.dispatch.on('stateChange', function (newState) {
          console.log('test');
        });  `

However I am getting the following error:
`Uncaught TypeError: Cannot read property 'on' of undefined`

Any ideas what I am doing wrong? I have provided an example in fiddler using a simplified version of the example for the multichart.

NVD3 version used:
**1.8.6**
Browser and OS used:
**Chrome**
Live Example: Jsfiddle
**https://jsfiddle.net/u3or7emp/**

**Comment by bgth** [comment]
Hi @marina1349. Can you please check this? #1446

**Comment by marina1349** [comment]
Hi bgth,

I tried implementing that solution, I have moved the code into the callback but I am still getting the error (https://jsfiddle.net/c0nr705z/). 

That post has a downvote and the thread is closed. It doesn't seem like there is a solution unless I messed up my implementation somewhere.

**Comment by marina1349** [comment]
I managed to find the problem. Multicharts do not have an implementation for the stateChange and changeState events. I've fixed it by forking nvd3 and implementing them myself.

**Comment by mjy78** [comment]
Hi @marina1349 is your implementation of the event handlers for multi charts available in a pull request or forked repo?

**Comment by marina1349** [comment]
Hey Michael,

I'm sorry it took so long to get back to you. I forgot about this email. We
created a branch on github with our changes, it's available here:
https://github.com/JamesZeinzu/nvd3/tree/fix-statechange-events

Hope that helps!
Marina

**Comment by liquidpele** [comment]
Send us a pull request if you'd like your addition in main :)
