### ISSUE TITLE
Audit/remove commented code

### ISSUE THREAD

**Issue by rustybailey** [novus/nvd3#213]
Throughout nv.d3.js, there are several areas where chunks of code are commented out, such as [here](https://github.com/novus/nvd3/blob/master/nv.d3.js#L572-L579), [here](https://github.com/novus/nvd3/blob/master/nv.d3.js#L572-L579), and [here](https://github.com/novus/nvd3/blob/master/nv.d3.js#L965-L1055). In most instances, there is no explanation as to why it is commented out -- it just is.

It would be great if before this current development branch is merged into master that there would be an audit of all the code that is completely commented out, and the code is either: 
> 1. Deleted ( *best case* )
2. Uncommented because it is useful/needed.
3. Additionally commented as to why it is still there ( *very worst case* ).

Would love to know what you think.

**Comment by liquidpele** [comment]
I did most of this in my cleanup.
