### ISSUE TITLE
I have issue for hr_dashboard module.

### ISSUE THREAD

**Issue by manisharpatil** [novus/nvd3#2159]
I have issue for clicking on hr dashboard module. How to resolve it?

Error: QWeb2 - template['hr_dashboard.dashboard']: Runtime Error: TypeError: dict.widget.employee_data is undefined.

![2018-04-27-192255_1024x768_scrot](https://user-images.githubusercontent.com/32096964/39415648-81c7d466-4c63-11e8-86f3-bddefdcb2cdb.png)

Any help would be greatly appreciated.

**Comment by DonFeraRRi** [comment]
I am Also Facing the same issue. When I click on HR Dashboard, I also see the same screen.

**Comment by liquidpele** [comment]
Hi there!  Unfortunately, this project is the open-source nvd3 chart project, and I'm a volunteer that manages it (I don't work for novus).  You will likely need to contact novus support regarding that.
