### ISSUE TITLE
Checking out the latest Stable release

### ISSUE THREAD

**Issue by Murkantilism** [novus/nvd3#2207]
NVD3 version used: 1.8.2

Browser and OS used: N/A

Live Example: N/A

Expected Behaviour:
Master branch shows the (current) latest version as 1.8.6

Present Behaviour:
Master branch shows the version as 1.8.6-dev

Any more information regarding the issue:
I appear to be experiencing the same confusion [as this user 2 years ago](https://github.com/novus/nvd3/issues/1651).

Upgrading from 1.8.2 to latest stable release, I checked out the `master` branch of this repo where `-dev` implies to me that this is not a stable version, but I was expecting master to only have stable releases.

Is this simply an overlooked typo/error where -dev wasn't stripped before pushing out 1.8.6 release? If not, how do I go about checking out the latest stable version, such as 1.8.5?

**Comment by liquidpele** [comment]
Master branch is dev.   Use the git tag for the version you want.

**Comment by Murkantilism** [comment]
Thank you, `git checkout  v1.8.6` worked like a charm
