### ISSUE TITLE
Offering maintainer help around providing NDV3 life support

### ISSUE THREAD

**Issue by mistercrunch** [novus/nvd3#2222]
Maintainers!

Our project at https://github.com/apache/incubator-superset uses NVD3 heavily and we'd like to offer help maintaining the project here. 

We'd like to:
* review key PRs and merge them (mostly bug fixes and small tweaks, no big changes)
* publish new versions periodically

What we need:
* write access to this repo
* access to publish to nvd3's npm

You can look the project and my Github handle, I worked on Apache Airflow and Apache Superset and feel like your project would be in better shape with the little help we'd like to provide.

Alternatively we can fork and publish another package, but we'd rather help out here a little instead of doing that.

What do you think?

**Comment by liquidpele** [comment]
FYI, I've forked to https://github.com/nvd3/nvd3 if they don't reply here ;)

**Comment by mistercrunch** [comment]
@liquidpele, do you have an alternative npm package you publish from https://github.com/nvd3/nvd3 ? Do you personally have rights to publish to the `nvd3` npm package? We're interested in publishing `1.8.7` from current master ASAP, and maintaining that `1.x` for now. We may be able to contribute in the `D3v4` effort, but that's unclear at this time.

**Comment by mistercrunch** [comment]
Fork is here https://github.com/preset-io/nvd3, we'll be publishing/maintaining a package on npm: [nvd3-fork](https://www.npmjs.com/package/nvd3-fork)
