### ISSUE TITLE
multiBarTimeSeriesChart, need example code

### ISSUE THREAD

**Issue by Sigfried** [novus/nvd3#229]
multiBarTimeSeriesChart (it's there in models) might be close to what I need, but without example code or any indication of what kind of data it expects, I'm not sure how to get started with it.

What I'm trying to make is a chart showing events over time for multiple subjects. It will eventually be very cool, with features for aligning event sequences by specific event types and stuff. If anyone can provide any guidance in writing a new nvd3 model, I would sure be appreciative. I'm going to make this thing one way or another, but if I manage to make it as an nvd3 model, I'll be happy to share it with the community.

Thanks for the cool stuff.

**Comment by liquidpele** [comment]
I think this model was nuked?  closing.
