### ISSUE TITLE
Upgrade to d3 v3.3

### ISSUE THREAD

**Issue by rustybailey** [novus/nvd3#233]
d3 v3.3 was just released: https://github.com/mbostock/d3/releases/tag/v3.3.0

Among several new features, a couple things have also been deprecated/disabled, such as:
> - Add axis.innerTickSize and axis.outerTickSize; **deprecates multi-argument axis.tickSize.**
> - **Disable axis.tickSubdivide;** use post-selection and multiple axes instead.

When upgrading, nvd3 code should be changed to reflect this.

**Comment by liquidpele** [comment]
3.4.4+ now, cheers
