### ISSUE TITLE
Date x-axis doesn't align well

### ISSUE THREAD

**Issue by yelululiu** [novus/nvd3#237]
Hi,

I'm attempting to set date axis, but the x-axis doesn't align well. Any pointer? Thanks in advance.
http://jsfiddle.net/yelululiu/pMdYq/2/

Regards,
Louie

**Comment by Fireworks** [comment]
@ktmud Our data was UTC based and I struggled to figure out how to implement a scaling solution.  This worked flawlessly.  Thanks!
