### ISSUE TITLE
useInteractiveGuideline for lineWithFocusChart

### ISSUE THREAD

**Issue by nerocrux** [novus/nvd3#239]
Hi, I found that useInteractiveGuideline has been added to lineChart and cumulativeLineChart recently, and I wonder that if useInteractiveGuideline for lineWithFocusChart is on going, or is it possible to do so.
Thanks in advance!

**Comment by liquidpele** [comment]
Not yet, but I'd like to combine the lineChart and lineWithFocusChart so it would get the option then.
