### ISSUE TITLE
[multiBar] Add an option for create multi stacked bar chart

### ISSUE THREAD

**Issue by julianfox** [novus/nvd3#245]
Create a setting for create multi stacked bar chart as this example : 

![clusterstackchart](https://f.cloud.github.com/assets/1648714/1057434/8a5ee32e-1173-11e3-9435-d79099e8d09d.png)

**Comment by liquidpele** [comment]
I think this is a bad idea in most cases so I don't see this coming into nvd3, closing this issue and good luck!
