### ISSUE TITLE
What is the best way to add data to a line chart?

### ISSUE THREAD

**Issue by nickdesaulniers** [novus/nvd3#246]
I'm still learning the ropes when it comes to d3.  I've modified a local version of [lineChartSVGResize](https://github.com/novus/nvd3/blob/master/examples/lineChartSVGResize.html) to store the results of the call to `sinAndCos` to a variable, `data`, and then push data to it then update:

```javascript
data[0].values.push({ x: ++x, y: newY });
d3.select('#chart1 svg').datum(data).transition().duration(0).call(chart);
```

Currently, this is just in an interval but I'm looking to update via WebSockets.

But this leaves bubbles on each point.  Is there a better way to update the data and chart?

**Comment by liquidpele** [comment]
Add data to the original data object and call chart.update()
