### ISSUE TITLE
ShowValue without decimal.

### ISSUE THREAD

**Issue by ncubo** [novus/nvd3#251]
Somebody know wich es the property that I have to change for show the numbers without decimal over the bar?.. I changed "chart.yAxis.tickFormat(d3.format('.f'));" , but that just is for the axis.. 
![screen shot 2013-09-04 at 3 01 11 pm](https://f.cloud.github.com/assets/5167534/1083205/adf42972-1595-11e3-95d6-dcfd970e7887.png)

**Comment by tontonjulien** [comment]
thx @ncubo the doc is so incomplete!

**Comment by liquidpele** [comment]
https://nvd3-community.github.io/nvd3/examples/documentation.html

The examples and descriptions are defined in the json object at the bottom of the documentation.html file in the repo... if you'd like to help fill in the blank spots please send us a PR!    Keep in mind I'm not the original author so the stuff I already documented I had to reverse engineer myself already.
