### ISSUE TITLE
Add scatter chart to multichart

### ISSUE THREAD

**Issue by satishv-denali** [novus/nvd3#255]
How do I add a scatter chart to multichart graph. Thanks in advance.

**Comment by Kepro** [comment]
is there some timeline for this? :)

**Comment by liquidpele** [comment]
technically you can already accomplish this by using a line the line chart actually has a scatter chart on top of it for the points so you can just make a line and hide the lines with CSS and only display the points

**Comment by Kepro** [comment]
but this is not a solution if i want to use symbols etc...

**Comment by npezolano** [comment]
Bumping this old issue since the current example isn't displaying scatters but has them referenced.

https://github.com/novus/nvd3/blob/master/examples/multiChart.html

**Comment by liquidpele** [comment]
scatter was added to multichart in the master branch already.  

https://github.com/novus/nvd3/blob/master/src/models/multiChart.js#L34

If you'd like to modify the example, feel free to do so and send us a pull request.   Cheers!
