### ISSUE TITLE
Problem with tooltip in Safari

### ISSUE THREAD

**Issue by ncubo** [novus/nvd3#256]
I had a problem with the legends before when I had more than one tab.. The legends was showing like the image...

![screen shot 2013-09-01 at 7 13 45 pm](https://f.cloud.github.com/assets/5167534/1091774/9395ebaa-166d-11e3-8bb2-b16fb5d8a118.png)

That problem was solved using visibility:hidden instead of display:none, but when I do that, in safari doesn't show the tooltip and I can't press the legend for display the lines..

**Comment by liquidpele** [comment]
seems to work fine on safari now.
