### ISSUE TITLE
[Question] How to add a contextmenu event handling in lineWithFocusChart?

### ISSUE THREAD

**Issue by gofranshukair** [novus/nvd3#262]
I am trying to add new context menu event handling to the line chart but I can not think of the right way to do it to get the data of the point that the mouse clicking at a point of time.
I am using nvd3 in smartGWT
here is the code :

$wnd.nv.addGraph(function() {
			  var chart = $wnd.nv.models.lineWithFocusChart()
			      .margin({top: 30, right: 20, bottom: 20, left: 80});
		
			  chart.xAxis
			      .tickFormat(function(d) {
		          return $wnd.d3.time.format('%x')(new Date(d))
		        });
			  chart.x2Axis
			    .tickFormat(function(d) {
		         return $wnd.d3.time.format('%x')(new Date(d))
		        });
			
			  chart.yAxis
      			.tickFormat(function(d) {
      			var str=d.toString();	
      			var n=str.indexOf(".");	
      			if(str.length<=6 && str.length>3 && n==-1){
      			var prefix = $wnd.d3.formatPrefix(1375);
      			return prefix.scale(d).toFixed()+prefix.symbol;
      			}
      			else
      			if(str.length>9 && n==-1){
      			var prefix = $wnd.d3.formatPrefix(137594020);
      			return prefix.scale(d).toFixed()+prefix.symbol;
      			}
      			else{
      				return $wnd.d3.format(',.2f')(d);
      			}
      			});
      			chart.y2Axis
      			.tickFormat(function(d) {
      			var str=d.toString();	
      			var n=str.indexOf(".");	
      			if(str.length<=6 && str.length>3 && n==-1){
      			var prefix = $wnd.d3.formatPrefix(1375);
      			return prefix.scale(d).toFixed()+prefix.symbol;
      			}
      			else
      			if(str.length>9 && n==-1){
      			var prefix = $wnd.d3.formatPrefix(137594020);
      			return prefix.scale(d).toFixed()+prefix.symbol;
      			}
      			else{
      				return $wnd.d3.format(',.2f')(d);
      			}
      			});
  			 
  			 
  			 var div = $wnd.d3.select("body").append("div")   
             .attr("class", "contextMenu")               
             .style("opacity", 0);
			 $wnd.d3.select('#'+d3TimelineTabId+' svg').on('contextmenu', function(data, index) {
		     var x;
		     var y;
		     
		      if ($wnd.d3.event.pageX || $wnd.d3.event.pageY) {
		     		x = $wnd.d3.event.pageX;
		            y = $wnd.d3.event.pageY;
		      } else if ($wnd.d3.event.clientX || $wnd.d3.event.clientY) {
		           x = $wnd.d3.event.clientX + $doc.body.scrollLeft + $doc.documentElement.scrollLeft;
		           y = $wnd.d3.event.clientY + $doc.body.scrollTop + $doc.documentElement.scrollTop;
		      }
		 	    div.transition()        
                 .duration(200)      
                  .style("opacity", .9);      
                div.html(data[0] + "<br/>")
                 .style('position', 'absolute')  
                .style("left", (x) + "px")     
                .style("top", (y - 28) + "px");    
                         
              $wnd.alert("hi");           
		      $wnd.d3.event.preventDefault();
		     });
			chart.width(750);
			chart.height(500);
			
			
			
			  $wnd.d3.select('#'+d3TimelineTabId+' svg')
			      .datum(dateStampedData)
			    .transition().duration(500)
			      .call(chart);
			
			  $wnd.nv.utils.windowResize(chart.update);
		      
			  return chart;
			});

**Comment by robinfhu** [comment]
I don't think I can help you here given that I have no experience with smartGWT.

As for getting the data for a mouse click, the elementClick dispatch contains lots of point data. That may help.
