### ISSUE TITLE
Strict-mode does not allow assignment to undefined variables

### ISSUE THREAD

**Issue by tstar** [novus/nvd3#264]
I encountered an error minimization library nv.d3 1.1.10b with Microsoft Ajax JS-minifier:

While minimizing the JS-code read from the file "/Scripts/nv.d3.js", using the Microsoft Ajax JS-minifier syntax error has occurred!

See more information about the error:

Error message: Strict-mode does not allow assignment to undefined variables: singlePoint

Error Code: JS1300
Severity: 0
Subcategory: run-time
File: /Scripts/nv.d3.js
The starting line: 9781
The initial symbol: 79
The final line: 9781
End character: 90

At this point, this is such a code:

// If scale's domain don't have a range, slightly adjust to make one... so a chart can show a single data point
if (x.domain()[0] === x.domain()[1] || y.domain()[0] === y.domain()[1]) singlePoint = true;

Can you fix those little mistake that would nv.d3 library has become friendly to Ajax JS-minifier?

Thank you.

**Comment by liquidpele** [comment]
The getX thing was fixed, cheers.
