### ISSUE TITLE
PieChart expected-data-structure differs from on-site documentation

### ISSUE THREAD

**Issue by joehannes** [novus/nvd3#274]
Through a post on stackoverflow I found, that looking at the source-code examples the pieChart expected data-structure differs from, e.g., the barchart data ...
There is to be no leading key, values object, but solely the data-tupels wrapped in an array!
Please either change the on-site doc or, even better, unify the way the data structure works across all charts.

**Comment by liquidpele** [comment]
new examples and docs now, closing.
