### ISSUE TITLE
is there a version of nv.d3 that has a working stackedAreaChart?

### ISSUE THREAD

**Issue by zackd** [novus/nvd3#276]
Hi, 

 so I've tried all available versions, also tried master and development branches

for every version I tried stackedAreaChart either has no animated transitions or transitions are broken.

What version is used at http://nvd3.org/ghpages/stackedArea.html ? Where can I get it ?

(I just scraped the source files from the demo - all works)

**Comment by liquidpele** [comment]
should be good at this point... I hope!
