### ISSUE TITLE
Tooltip old and new way

### ISSUE THREAD

**Issue by corneadoug** [novus/nvd3#280]
I am currently making a new features for the tooltip, and having a hard time understanding the way tooltip works.

Basically, we are currently using nv.tooltip.show(); in the models
However it is said that this is the old way and it is kept for backward compatibility

I then guess that the new way would be to include the tooltip in the chart models considering this example:

var tip = nv.models.tooltip().gravity('w').distance(23)
                .data(myDataObject);
tip();

Obviously no model is handeling it for now so I'm checking before I implement it.
It makes perfect sense to me that tooltip is an attribute of any chart and should be modified/set when we instantiate the chart.

I'm even quite surprised that nvd3 is not made in a more Object and attribute fashion

**Comment by liquidpele** [comment]
I'll be adding the tooltip info to the documentation soon, I'm digging into a lot of that code right now.
