### ISSUE TITLE
No useInteractiveGuideline in lineWithFocusChart avalible 

### ISSUE THREAD

**Issue by UltimateFighter** [novus/nvd3#283]

**Comment by liquidpele** [comment]
We should merge lineChart and lineChartWithFocus, which I think is the real fix.  I'll make a different issue for that.

**Comment by achikin** [comment]
Hi, are there any news about interactive guideline for line with focus chart?

**Comment by liquidpele** [comment]
I'm planning to merge lineChart and lineChartWithFocus soon, which would resolve this.  I did the same with linePlusBar and linePlusBarWithFocus already.

**Comment by dileepkeeppalli** [comment]
Is this issue is resolved? I am still not getting interactiveGuideline when chart type making as lineWithFocusChart.

**Comment by liquidpele** [comment]
Nope.  Our todo list is quite big!  If someone wants, feel free to do it and send us a pull request :)
