### ISSUE TITLE
TypeError: Cannot read property 'baseVal' of undefined

### ISSUE THREAD

**Issue by aarthi0808** [novus/nvd3#285]
Whie creating NVD3 discrete bar chart with Node js,it throws following error

  var t = g.transform.baseVal.consolidate();

TypeError: Cannot read property 'baseVal' of undefined
    at d3.transform (file:///Users/administrator/Downloads/nodejs/d3.js:5347:28)
    at Object.d3.transform (file:///Users/administrator/Downloads/nodejs/d3.js:5350:7)
    at d3_interpolateTransform (file:///Users/administrator/Downloads/nodejs/d3.js:5394:35)
    at Object.<anonymous> (file:///Users/administrator/Downloads/nodejs/d3.js:7697:32)
    at d3_Map.<anonymous> (file:///Users/administrator/Downloads/nodejs/d3.js:7858:31)
    at d3_Map.d3_class.forEach (file:///Users/administrator/Downloads/nodejs/d3.js:271:13)
    at start (file:///Users/administrator/Downloads/nodejs/d3.js:7857:28)
    at Object.callback (file:///Users/administrator/Downloads/nodejs/d3.js:7851:38)
    at d3_timer_mark (file:///Users/administrator/Downloads/nodejs/d3.js:2075:80)
    at d3_timer_step [as _onTimeout] (file:///Users/administrator/Downloads/nodejs/d3.js:2048:15)

**Comment by liquidpele** [comment]
should be fixed in latest.

**Comment by edote** [comment]
Hello Folks,

I'm building couple of charts in NodeJS using JSDOM, and they all render great (multibarchart, discrete barchart and line chart), except piechart.

I keep getting this error. I tried touching the source and I think there is some issue with the durations. I tried forcing the library to run renderWatch without any duration and I get only the legend and the labels positioned on one place.

I'm stuck on this for longer period. Also please note that in the settings I don't use transition().duration() and I force duration(0) to the chart object.

I would really appreciate if you can take a look over the piechart function and make sure that everything is fine.

Thanks in advance!
Cheers!

**Comment by liquidpele** [comment]
Are you using nvd3 version 1.8.1?   If not do that first.   If there is still an issue, please create a jsfiddle that shows the problem, linking to latest code in the master branch via rawgit.com.

**Comment by edote** [comment]
Hello,

thanks for the answer. Yes I use nvd3 version 1.8.1 and d3 version 3.5.6.
Please note that same code for rendering piechart works fine while executed on the browser, but when rendering in NodeJS, I receive this error.

I can't create a fiddle as it is complex piece of code and it requires NodeJS to run it, so I will paste the function that I use to render this pie chart:

var external_scripts = [__dirname + "/d3.js", __dirname + "/nvd3.js"];
 var htmlStub = '<html><head></head><body><div id="chart_div"><svg style="width:'+(parameters.width)+'px;height:'+(options.outer_height)+'px;"></svg></div></body></html>';

    jsdom.env({
      features : { QuerySelector : true}
      , scripts: external_scripts
      , html : htmlStub
      , done : function(errors, window) {
            var el = window.document.querySelector('#chart_div svg');
            var data_set = that.prepare_data(data, item); // this prepares data format
            var my_colors = that.get_colors(data_json.length) // my function for colors
           
            window.nv.addGraph(function() { 
              var chart = window.nv.models.pieChart()
                                    .x(function(d) { 
                                        if(parameters.colspan < 2 && d.key.length > 16)
                                            return d.key.substring(0,10)+'...'; 
                                        else
                                            return d.key; 
                                    })
                                    .y(function(d) { return d.y; })
                                    .labelType('value')
                                    .showLabels(true)
                                    .showLegend(true)
                                    .color(dblab_colors)
                                    .valueFormat(function(d){ return numeral(d).format('0a');})
                                    .labelThreshold(0.05)
                                    .duration(0)
                                    .donut(true);
              
              window.d3.select(el)
                .datum(data_set)
                .call(chart);
              
              callback(window.document.querySelector('#chart_div').innerHTML);
            });
      }
    });


I use nvd3 through the window object as they are executed with jsdom. Please note that same code works for discrete bar chart, multi bar chart and simple line chart. 

Your help will be really appreciated!
Thanks

**Comment by edote** [comment]
Any solution on this?

I tried debugging the issue and it is something related with timers and initial transitions of the pie chart. I have complete dashboard with all the charts that I need and they all work perfect except this pieChart.

Your help will be very much appreciated.
Thank you!

**Comment by maximeturenne** [comment]
Hi,

I am doing the same kind of project.

I found out that the real issue is with jsdom and the transitions used by d3 for SVG nodes. 

When you make a PieChart with nvd3, under the hood d3 will build the SVG using transitions. Since jsdom does not fully implement all svg features like transitions, d3 will crash when building the svg. 

The walkaround I found for the piechart is very ugly and I am looking for something better.
I commented some codes in the d3.transform function (line 5945):

```
d3.transform = function(string) {
    var g = d3_document.createElementNS(d3.ns.prefix.svg, "g");
    return (d3.transform = function(string) {
        if (string != null) {
        //g.setAttribute("transform", string);
        //var t = g.transform.baseVal.consolidate();
      }
      //return new d3_transform(t ? t.matrix : d3_transformIdentity);
      return new d3_transform(d3_transformIdentity);
    })(string);
  };
```


That way, the piechart will be created, but some feature like showLabel will only work with default value.

```
 "dependencies": {
    "body-parser": "^1.17.2",
    "d3": "^3.5.2",
    "express": "^4.15.3",
    "jsdom": "^11.0.0",
    "nvd3": "^1.8.5"
  }
```

I don't think this issue should be closed since this is not fixed in any way...

**Comment by liquidpele** [comment]
This doesn't seem like an nvd3 issue as much as a d3 thing and nodejs limitation.
