### ISSUE TITLE
Multiple data types on the same graph

### ISSUE THREAD

**Issue by tyokota** [novus/nvd3#286]
I would like to add a fourth value (e.g.,'year' in the following example) that can be called to load a different set of data. For example, I would like to create a multibarchart with the following variables: X=month, Y=value, Z=group, and W=year. The graph would show the values by month with stacked bars of different groups. Another option, perhaps as a drop down menu, can filter the Year the data was measured and reload the graph.

Is this possible?

**Comment by liquidpele** [comment]
I'm not really sure what they're asking... from 2013 so just closing as ancient.
