### ISSUE TITLE
[Line Chart] How to create an ordinal/discrete xAxis?

### ISSUE THREAD

**Issue by lestopher** [novus/nvd3#29]
I thought that I could set  scale of the axis by doing the following:

      var chart;
      var xScale = d3.scale.ordinal()
                      .domain(_.map(seriesDef[0].values, function(d) {
                        return d.x;
                      }))
                      // .rangeBands([0, seriesDef[0].values.length - 1]);

      nv.addGraph(function() {
        chart = nv.models.lineChart();

        chart.x(function(d, i) { return String(d.x); })
             .y(function(d) { return d.y; });

        chart.xAxis.scale(xScale);

        chart.yAxis
          .tickFormat(d3.format(',.2f'));

        d3.select(that.chartElement.find('svg')[0])
            .datum(seriesDef)
          .transition().duration(500)
            .call(chart);

        nv.utils.windowResize(chart.update);

        return chart;
      });
  
Here's what seriesDef looks like:
  
    
    {
      "area": false,
      "key": "Total Amount By Term",
      "values":
        [
          {
            "x": "199520",
            "y": 1119707
          },
          {
            "x": "199510",
            "y": 1253042
          },
          {
            "x": "199610",
            "y":  868849
          },
          {
            "x": "199540",
            "y": 50
          },
          {
            "x": "199430",
            "y":  6803
          },
          {
            "x": "199810",
            "y":  1850
          },
          {
            "x": "200820",
            "y":  30
          }
        ]
    }
  
  
The xAxis still ends up looking like an interval
![nvd3linechart](https://f.cloud.github.com/assets/1037741/52202/7ddfc0ca-59f2-11e2-9ddc-813d885d0a35.png)

Any suggestions?

**Comment by robinfhu** [comment]
Don't use an ordinal scale.

Instead, set chart.x(function(d,i){ return i;})
And then in the chart.xAxis.tickFormat function, return the label you want to show depending on the index.

**Comment by kevalbhatt** [comment]
@robinfhu worked for me thanx
