### ISSUE TITLE
LineChart: Only one dataset is shown when the datasets have the same key (or no key), tooltips are working though.

### ISSUE THREAD

**Issue by TN1ck** [novus/nvd3#291]
When the data looks like this: `[{values: [...]}, {values: [...]}]`
or like this: `[{key: "key1," values: [...]}, {key: "key1", values: [...]}]`

Only one of the two datasets is shown. Here is a jsfiddle, you would expect the two charts would behave the same.

http://jsfiddle.net/3s7Te/1/

I've tested this with the newest version as well - same problem. I've only encountered the problem with lineCharts, barCharts work fine.

I've found the problem:
https://github.com/novus/nvd3/blob/master/src/models/line.js#L107

     var groups = wrap.select('.nv-groups').selectAll('.nv-group')
          .data(function(d) { return d }, function(d) { return d.key });

you can fix it with for example:

     var groups = wrap.select('.nv-groups').selectAll('.nv-group')
         .data(function(d) { return d }, function(d, i) { return d.key + i });

**Comment by liquidpele** [comment]
I updated the jsfiddle to 1.7, it looks like it's still an issue... the "key" attribute of the data is the same for both series which causes the problem... seems silly but probably should be able to handle that. 

http://jsfiddle.net/3s7Te/9/

**Comment by liquidpele** [comment]
should be fixed now.

**Comment by liquidpele** [comment]
Had to revert due to https://github.com/novus/nvd3/issues/803, will look at robin's suggestion.
