### ISSUE TITLE
multiChart: Area/Bar charts are rendered on top of lines

### ISSUE THREAD

**Issue by ZicklePop** [novus/nvd3#293]
In src/models/multiChart.js from around line 97 the code strictly renders lines under area charts.

Shouldn't it be more like https://github.com/JakeBilbrey/nvd3/commit/1acad80b666e774b91d5c31824a624f1ae0566b4#diff-b5254de5addcaf88c0900e46af95e3d7 ?

(Preferably it'd be based on the order of the chart data, but this change was quicker for me to implement. I also cannot think of a reason I would have a line behind a solid for a chart.)

**Comment by liquidpele** [comment]
Still an issue... if line points are under an area the tooltip doesn't display for the points.

**Comment by liquidpele** [comment]
Okay, this pull request to nvd3-community might resolve this for linePlusBarChart, since it allows swapping which axis the lines/bars use.... though I'm not sure that's the right solution... thoughts? 

@robinfhu @joshjordan @portante

https://github.com/nvd3-community/nvd3/pull/54

**Comment by robinfhu** [comment]
@liquidpele just at quick glance, it's a lot of code for a minor issue.  Makes me kind of uneasy.

**Comment by liquidpele** [comment]
Removed my last comment, two different things I thought were related but probably not :p

**Comment by robinfhu** [comment]
Can't you just set pointer-events:none; in the CSS for the area section? Will that get tooltips to show for the line underneath?

**Comment by liquidpele** [comment]
Neat, that does fix it although the areas stop getting darker on hover then....  but also the area section doesn't have *any* kind of tooltip there, which seems like a bug too?   Plus, the lines should still probably be on top of the bars, both for multichart and for linePlusBar.

**Comment by thcrock** [comment]
I was able to fix that using a more granular pointer-events rule.

`pointer-events: visibleStroke`

This will only bring the area up to the front (and display a tooltip) if you hover over the line at the top of the area fill. 

As far as the original bug (lines getting rendered behind areas by default), it seems that it still exists in the development branch. A pull request was attempted for this, but it didn't get merged in for whatever reason. The relevant code is here:

https://github.com/uxmaster/nvd3/commit/4150a6578a5ba94f022abb34144e8120a6c82bfc#diff-b5254de5addcaf88c0900e46af95e3d7R97

Somebody could probably isolate this change into its own commit and do a pull request fairly quickly. I'll take a stab at it, but I don't know how soon I'll be able to do that. For now, we're using a workaround similar to this (for individual graphs).

d3.selection.prototype.moveToFront = function() {
    return this.each(function(){
        this.parentNode.appendChild(this);
    });
};

d3.select('#chartxxxxxx .lines1Wrap').moveToFront();
d3.select('#chartxxxxxx .lines2Wrap').moveToFront();

**Comment by leongaban** [comment]
Hi @thcrock I tried your fix here, but to no avail: http://stackoverflow.com/questions/33000725/how-to-position-nvd3-line-graph-above-all-other-area-bar-graphs

Actually got `moveToFront is not a function` error.

Is there another solution?

**Comment by j2kenton** [comment]
For bar charts, I successfully use:

    var groups = d3.selectAll(".nv-groups")[0][0];
    var series0 = d3.selectAll(".nv-series-0")[0][0];

    if (typeof groups != "undefined") {
      groups.appendChild(series0);
    }
This is based on @asarenski's answer above and http://stackoverflow.com/questions/33000725/how-to-position-nvd3-line-graph-above-all-other-area-bar-graphs and implement in angular-nvd3, in the $scope.options.chart.callback property.

Presumably the same would work for lines.
