### ISSUE TITLE
New chart type enhancement

### ISSUE THREAD

**Issue by fdurden** [novus/nvd3#294]
Hi,

Would you consider implementing what is called a rings chart, it's a compact way of representing hierarchical data like file system folders etc... It can be thought of as a hierarchical doughnut chart. GNOME has a disk usage analyzer that represents data like this:

http://www.marzocca.net/linux/baobab/baobab-ringschart.html
https://en.wikipedia.org/wiki/Disk_Usage_Analyzer

BR. Thanks!

**Comment by liquidpele** [comment]
Planning on it... aka sunburst!   It's my fav ❤❤❤

I plan to use this demo as the base:   http://bl.ocks.org/kerryrodden/477c1bfb081b783f80ad

**Comment by robinfhu** [comment]
There's a newer feature request, so closing this as a duplicate.
