### ISSUE TITLE
multiple call to length in lineChart model?

### ISSUE THREAD

**Issue by whoughton** [novus/nvd3#297]
https://github.com/novus/nvd3/blob/master/src/models/lineChart.js#L98

Seems like you are calling length on both the object values and the returned data. Changing this to:

```javascript
if (!data || !data.length || !data.filter(function(d) { return d.values }).length) {
```

Seems to make it work for me. But being new to nv.d3 I am not sure if it is me or not.

**Comment by liquidpele** [comment]
Invalid, it is correct as-is.
