### ISSUE TITLE
[lineWithFocusChart] Selecting a small area on the focus chart results in buggy display

### ISSUE THREAD

**Issue by eforrester** [novus/nvd3#298]
Here's a jsfiddle that shows most of what I'm seeing: http://jsfiddle.net/wmyW8/19/ (it uses the latest version from github)

This can also be seen on the sample chart at http://nvd3.org/ghpages/lineWithFocus.html

When you begin to select an area in the focus chart, it goes through a few states when the area selected is very small. Unfortunately this happens every time you select an area, because all selections start off with zero width. Therefore, the user always sees this flash of weird-looking stuff. This problem becomes more pronounced when xAxis.tickValues() is set.

The states appear to be:
1) When the width is exactly 0 (or maybe -1?) the entire chart is visible in the upper portion of the display
2) When the width is a handful of pixels wide, x axis values are displayed, but no chart data is displayed. If the selected area include a data point, you can hover over it in the centre of the chart. ***At this point, the extents of the x axis become incorrect***.
3) When it gets a bit wider (possibly when the selected area begins to include 2 data points?) then chart data becomes visible. Note that the data points get pushed to the outer edges of the chart, regardless of where they lie within the selected area on the bottom.

In state 2, when xAxis.tickValues() is set all of the tick values get crammed in the middle of the chart (because the extents have become incorrect): it's when this flashes on screen that the problem is really noticeable.

I've attached screen captures showing these various states. I think that the incorrect extents is the root cause of the problem.
![0 width selected](https://f.cloud.github.com/assets/1918909/1258347/077935a6-2bbb-11e3-9494-0758e3b76f47.jpg)
![1 data point selected - highlight](https://f.cloud.github.com/assets/1918909/1258348/0a5ed5b4-2bbb-11e3-92a4-8286fc883aa1.jpg)
![1 data point selected - no highlight](https://f.cloud.github.com/assets/1918909/1258350/0e96f0e4-2bbb-11e3-8a12-a23c495a3daf.jpg)
![2 datapoints highlighted](https://f.cloud.github.com/assets/1918909/1258352/14082d4a-2bbb-11e3-9d1f-d5406d46e6e7.jpg)

Thanks for making such a cool and useful library :)

**Comment by liquidpele** [comment]
I played with it, this is just a misunderstanding of what the focus is doing.   It's focusing on a subset of the data in the top graph, not zooming into the full graph, so for just a few data points it'll look a bit weird... that's just how the tech works... i.e. it's doing a focus not a zoom/pan.
