### ISSUE TITLE
log scale with scatter chart does not render properly

### ISSUE THREAD

**Issue by rnpenguin** [novus/nvd3#299]
Log scale with scatter chart does not render properly; everything is below 0.  I was able to get it to render properly using scatterPlusLineChart but during debugging I get:

Error: Invalid value for <line> attribute y2="NaN"
Error: Invalid value for <line> attribute y1="NaN"

Error: Invalid value for <line> attribute y2="Infinity"
Error: Invalid value for <line> attribute y1="Infinity"

My y value above 40, so there should be no infinity error. Please advise.

**Comment by liquidpele** [comment]
duplicate of https://github.com/novus/nvd3/issues/620
