### ISSUE TITLE
tag v1.1.13-beta contains a malformed bower.json

### ISSUE THREAD

**Issue by dcolens** [novus/nvd3#302]
which is an issue, because if one has for example a dependency like "~v1.1.10-beta" bower will resolve it to v1.1.13-beta and fail to parse bower.json because it is malformed:

https://github.com/novus/nvd3/blob/v1.1.13-beta/bower.json#L21

I'd do a pull request, but this tag is not in any of the branches.

Thanks for patching this.

**Comment by liquidpele** [comment]
should be fixed.
