### ISSUE TITLE
chart.interactiveLayer.tooltip.valueFormatter is ignored

### ISSUE THREAD

**Issue by jfsiii** [novus/nvd3#303]
I'm trying to use the valueFormatter with the cumulative line chart, but cannot get it to call the supplied function.

```
chart.interactiveLayer.tooltip
  // works as expected
  .headerFormatter(function(d) {
    console.log('headerFormatter called');
    return 'new header:'  + (new Date(d)).toDateString();
  })
  // doesn't work as expected
  .valueFormatter(function(d,i) {
    console.log('valueFormatter called');
    return 'Y U NO TIP?';
  })
```

example at: http://jsbin.com/urEkAYu/2/edit

Even though calling `chart.interactiveLayer.tooltip.valueFormatter()`, shows the new function, https://github.com/novus/nvd3/blob/development/src/tooltip.js#L104 is still using the [initial value for valueFormatter](https://github.com/novus/nvd3/blob/development/src/tooltip.js#L58)

**Comment by liquidpele** [comment]
tooltips allow easy format overriding now via chart.tooltip.headerFormatter and chart.tooltip.valueFormatter options. https://github.com/novus/nvd3/pull/851

**Comment by iainctduncan** [comment]
Sorry to be asking this here, but how do we access chart.tooltip.valueFormatter from client code? Have not been able to find this. :/

**Comment by Ernisto** [comment]
It doesn't work for interactive mode

**Comment by Ernisto** [comment]
Please fix this issue

**Comment by lstar19** [comment]
Agree with @Ernisto the valueformatter is not working in interactive mode. The headerformatter seems fine.
