### ISSUE TITLE
Legend and Labels stays appeared even when dataset is 0/ null

### ISSUE THREAD

**Issue by ajjublr** [novus/nvd3#304]
I am trying add/remove data to a chart dynamically, say with a click event. Whenever i remove the last data (where the dataset is null []) the chart shows 'no data available'. but the label, legend, and tooltip of the last array element still shows up.. I know i can make it disappear from jquery or d3 methods. But wondering is it an issue to be taken care by default or am i missing something in here ...

**Comment by liquidpele** [comment]
should be fixed with the recent noData fix submitted to nvd3-community
