### ISSUE TITLE
Default nv.dev to false

### ISSUE THREAD

**Issue by k3n** [novus/nvd3#308]
It seems backwards that the code ships with the development flag enabled by default. Is this intentional?

```js
nv.dev = true //set false when in production
```

As-is, users get debugging messages in the console log. Not a huge deal, but I'd guess that a majority of non-novus devs won't need it, and actual users (non-dev) of course should never need it either.

**Comment by atav32** [comment]
+1 pleeeeease

**Comment by robinfhu** [comment]
Agreed, let me see what this nv.dev thing is used for...

**Comment by robinfhu** [comment]
Changed nv.dev to false.
