### ISSUE TITLE
Line+area chart

### ISSUE THREAD

**Issue by jimerino** [novus/nvd3#310]
Hi there!

I'm trying to create this graph of a forecast

![Forecast](https://f.cloud.github.com/assets/5390887/1317607/d1d9d580-32aa-11e3-83db-fac168933389.png)

It's a line chart with 2 areas: inner one is the 80% probability that real data will be inside, the outer is a 95% probability.

I've seen on samples there's no line+area chart model. But even the area chart can't specify a [upper, lower] range on each point.

But I've seen to there's more models on the source code than on the samples. Then...

Is there any way to do that?

If not, I can try to create a new model to fit that. In that case, which model can be the proper one to modify to create the new one?

Thanks in advance.

**Comment by liquidpele** [comment]
This is not a thing currently.   This issue is replaced by https://github.com/novus/nvd3/issues/311
