### ISSUE TITLE
How to draw a line chart and a scatter chart together?

### ISSUE THREAD

**Issue by calfzhou** [novus/nvd3#321]
I found that multiChart doesn't support scatter, and scatterPlusLineChart only draws a straight line. Is there any way to draw a normal line chart together with a scatter chart?

![image](https://f.cloud.github.com/assets/3761553/1359436/695f6f32-37dd-11e3-9365-1b0a05e921af.png)

**Comment by ptoche** [comment]
Here's a related approach:

http://stackoverflow.com/questions/27892806/css-styling-of-points-in-figure

The relevant code is this:

n$setTemplate(afterScript = '<style>
  .nv-point {
    stroke-opacity: 1!important;
    stroke-width: 6px!important;
    fill-opacity: 1!important;
  } 
</style>'
)

**Comment by liquidpele** [comment]
I think making an attribute in the data for a line to just show the scatter points would be a great enhancement.  That's different than just making a scatter chart in multichart as it's just a style issue.

**Comment by Sutikshan** [comment]
:+1: +1

**Comment by liquidpele** [comment]
Oh, this is done in multiChart now, someone added scatter models to that so you can do both line and scatter there together.

**Comment by hldawe** [comment]
Apologies for my naive question but from which version is this ability to code line and scatter together available? Is it in the current stable version or do I need to get a later version? Many thanks!

**Comment by hldawe** [comment]
Apologies again. Please ignore my last question - I have got it to work!

**Comment by lijianliu** [comment]
@calfzhou Your full code still works very well in 2016! Thanks for sharing! This is exactly what I am looking for.

**Comment by mars0i** [comment]
Thanks very much calvzhou!  Can someone explain to me how those CSS lines manage to choose the display of the sine data and make it into circles (or squares)?  I don't see the connection.  I'm not getting this to work in October 2016, but I may be doing something wrong.  I need to understand the code, in any event; I'm trying to do something similar using nvd3 with Clojurescript, so copy-and-modify without understanding won't be enough.)
