### ISSUE TITLE
Add .nvd3 prefix to svg css

### ISSUE THREAD

**Issue by simogeo** [novus/nvd3#326]
First of all, congrats for this wonderful library. It is quite impressive.

Working with d3 allow user to create svg and I guess it is not rare than the page generate SVG from nvd3 and d3 itself.

Actually, the css style contains some [SVG rules dedicated to nvd3 SVg tags](https://github.com/novus/nvd3/blob/master/nv.d3.css#L146) only but that may affect all SVG tags in the current page.

I would give you the advice of prefixing it  such as `.nvd3 svg`, `.nvd3 svg text`, `.nvd3 svg .title` to prevent any styles changes.

The html code should be like that : 

I d'ont know whether the ndv3 class should be added manually by the developer or automatically by the library when generating chart.
```html
<div id="chart-container">
   <div id="scatter-chart" class='ndv3 with-3d-shadow with-transitions'>
      <svg></svg>
   </div>
</div>
```

Thanks again for that lib!

**Comment by liquidpele** [comment]
fixed in latest version.
