### ISSUE TITLE
Remove all grid lines or from one axis in multichart and force Y to 0

### ISSUE THREAD

**Issue by MartijnThomas** [novus/nvd3#328]
I'd like to remove the either all the gridlines or just the gridlines of one of the Y axis in a multiChart as now it looks a bit wierd with all the double lines.

![graph](https://f.cloud.github.com/assets/3611378/1414356/60eb31ec-3e7c-11e3-9693-f19d1df7a018.PNG)

I tried the solutions in this [issue](https://github.com/novus/nvd3/issues/59) but that did not work, also i tried turning the opacity for the .tick to 0, but that did also fail.

The same problem is with the Y axis, I can't get the Y axis to be forced to 0, all the regular options fail.

**Comment by liquidpele** [comment]
Yes, using CSS is a good solution for this.

**Comment by rpn2142** [comment]
To keep X-axis and but not the grid lines

.tick line {
  visibility: hidden;
}
.nv-y .tick:first-child line {
  visibility: visible;
  stroke:#384452;
}
