### ISSUE TITLE
Scatter chart tests & examples only show circles. Ignore other shapes.

### ISSUE THREAD

**Issue by jfsiii** [novus/nvd3#333]
On both the master and development branches scatter charts are not respecting the `shape` argument.

Confirmed in:

 * test/ScatterChartTest.html
 * examples/scatterChart.html
 * examples/scatterPlusLineChart.html

**Comment by Resseguie** [comment]
@jfsiii the requirement for `onlyCircles()` was fully removed as of 4eb44eb2eac6c936fb28667debb7c871b2e95373

Should this issue be closed?

@m48u you can set a `color` property for a data point to color them individually. Alternatively, you can set the chart.color property to your own function that can determine color dynamically based on whatever you want.
http://nvd3-community.github.io/nvd3/examples/documentation.html#scatterChart

**Comment by liquidpele** [comment]
yep also you can now use custom symbol! This should be resolved so I'll go ahead and close it

**Comment by Resseguie** [comment]
Thanks, I hadn't noticed the custom symbol. I'll look into it. I'm actively working on something can can possibly use that.

**Comment by flyingxu** [comment]
For anyone who is looking for  an example of  custom symbol, here is the wiki page:  https://github.com/novus/nvd3/wiki/Data-Attributes#custom-symbols

**Comment by liquidpele** [comment]
The scatter chart example in the examples directory also has a custom symbol :)
