### ISSUE TITLE
Real-time update BarChart and LineChart is weird

### ISSUE THREAD

**Issue by yangpu** [novus/nvd3#335]
Issue 1: To run example /test/realTimeChartTest.html, add two streams (stream A and stream B) to bar chart, and the color of stream is changed (the color of stream A is changed to the color of stream B, and the color of stream B is changed to the color of stream A) whenever call chart.update to render the new data point (and pop up the head value from the data array).

Issue 2: change chart type to LineChart, the chart has not been moved to left smoothly and it wiggle the line path.

After searched, some posts mentioned that the issue is related to path interpolation:
http://stackoverflow.com/questions/15330390/real-time-line-graph-with-nvd3-js
http://bost.ocks.org/mike/path/
http://jsfiddle.net/chrisJamesC/buRcx/1/

Could some help to make nvd3 real-time smooth chart? thanks.

**Comment by ocombe** [comment]
Did any of you found a way to make this happen ? Or do I have to use pure D3 and forget about nvD3 for now ?

**Comment by robinfhu** [comment]
Try to code it in d3. I haven't given the real time update feature much thought yet.
