### ISSUE TITLE
Discrete bar with multiple series are getting thinner vs one Series..

### ISSUE THREAD

**Issue by phillycoder** [novus/nvd3#340]
http://jsfiddle.net/phillycoder/8DAQX/1/

**Comment by mcoquet** [comment]
I'm experiencing the same issue. It seems to be due to the width of the columns being calculated based on the absolute number of items (spread through all series) instead of being calculated based on the longest series.

Is there a fix for this in sight? Would you be open to getting a pull request?

**Comment by liquidpele** [comment]
I updated the fiddle to use the latest dev code and to use multiBarChart since it has multiple series items since that is what multiBarChart is for.    

http://jsfiddle.net/8DAQX/3/
