### ISSUE TITLE
MultiChart: How can I change bar chats in a MultiChart to be stacked?

### ISSUE THREAD

**Issue by ktarui** [novus/nvd3#341]
Bar charts are hard-corded as "not stacked" in the MultiChart's chart function.
Just giving users a setter like "chart.barStacked" would make this chart more useful.

**Comment by liquidpele** [comment]
This was answered.

**Comment by dileepkeeppalli** [comment]
Thanks defessler it worked for me too

**Comment by jdillard** [comment]
This worked for me, but the highest bar is chopped off the top as if the y axis bounds aren't adjusted properly.

Here it is inverted (~50k and ~20k on the left most bar): 
<img width="1053" alt="screen shot 2016-05-29 at 11 54 30 am" src="https://cloud.githubusercontent.com/assets/3474095/15634869/5859d13a-2594-11e6-843d-136358731319.png">

Here it is not inverted and it only shows the ~50k:
<img width="1041" alt="screen shot 2016-05-29 at 11 55 10 am" src="https://cloud.githubusercontent.com/assets/3474095/15634886/a9a62fb6-2594-11e6-8f59-56bc33d6aef4.png">

I haven't been able to find the reason just yet, but figured I would report in case someone else had the issue an might not have noticed. Version is 1.8.2.

**Comment by douglasg14b** [comment]
@jdillard Same issue here, where you ever able to figure it out? It cuts off the tops of the bars for me.

**Comment by gaetancollaud** [comment]
Same issue here, the top is cropped. If someone has a quickfix it would be welcome.

**Comment by liquidpele** [comment]
I think I remembered someone fixing that... try the latest master branch code.

**Comment by gaetancollaud** [comment]
You're right, use the master branch fix the issue. Thanks !

Do you know when the next release is planned ? Using the master branch isn't very good for reproductible builds.

**Comment by liquidpele** [comment]
I recently merged some stuff in, and I usually wait a while before making a new version just in case someone finds issues created by those merges...

**Comment by gaetancollaud** [comment]
Ok, I'm looking forward for the next release. In the meantime I will fork this repos and create a tag so I'm sure that nothing wrong goes to production.

**Comment by Wol** [comment]
The top half being clipped seems to be fixed, but now some of the areas can now overlap the X axis.

Plunkr here: http://plnkr.co/edit/FGA8zzUNx2au1Sg3EWxJ?p=preview

Original 1.8.5 version of the library
![screen shot 2017-06-05 at 15 16 08](https://cloud.githubusercontent.com/assets/981125/26787526/3937aa28-4a02-11e7-8354-b1eef60978d8.png)

Current master: https://cdn.rawgit.com/novus/nvd3/6bfd6786/build/nv.d3.min.js
![screen shot 2017-06-05 at 15 16 37](https://cloud.githubusercontent.com/assets/981125/26787528/3afe47c2-4a02-11e7-88ac-16f0be05f9cf.png)
