### ISSUE TITLE
Line chart with 2 yAxis

### ISSUE THREAD

**Issue by ncubo** [novus/nvd3#345]
Somebody know if I can make a graph with 2 yAxis?.. similar to linePlusBarChart.. because when I try to make a graph with two lines here.. I can show the lines but the second yAxis doesn't show..

**Comment by liquidpele** [comment]
multichart can do this, see the example, it has a line on each y axis.  Also, issues with multichart shoudl be all fixed at this point.  Cheers!

**Comment by jufemaiz** [comment]
@liquidpele which "multichart" are you referring to?

**Comment by liquidpele** [comment]
No it doesn't have the focus element.   I think the linePlusBarChart allows for 2 lines too and that has a focus, you could try that... otherwise you'd have to extend the lineWishFocusChart model to handle 2 y axis... if you do that please send us a pull request!

**Comment by liquidpele** [comment]
Also, just FYI you can see the examples in use here:    http://nvd3-community.github.io/nvd3/examples/site.html as well as on nvd3.org

**Comment by jufemaiz** [comment]
@liquidpele roger that! Will do. We have a use case for it. Just working out how best to approach it :)

**Comment by liquidpele** [comment]
For any issues, check the development branch first, then open an issue if you still see the issue.

**Comment by grahambryan** [comment]
was a focus element for the 2 y axis ever established?
