### ISSUE TITLE
"Uncaught ReferenceError: defined is not defined"nv.d3.js:6852 using lineWithFocusChart

### ISSUE THREAD

**Issue by devanl** [novus/nvd3#348]
Running snippets from the Live Code example  v1.1.10-beta in Google Chrome I get the error, "Uncaught ReferenceError: defined is not defined"nv.d3.js:6852.  

	function myPlotter(path, id)
	{
	
		d3.json(path, function(data) {

			nv.addGraph(function() {
			  var chart = nv.models.lineWithFocusChart();
			
			  chart.xAxis
			      .tickFormat(d3.format(',f'));
			
			  chart.yAxis
			      .tickFormat(d3.format(',.2f'));
			
			  chart.y2Axis
			      .tickFormat(d3.format(',.2f'));
			
			  d3.select("#" + id)
			      .datum(sinAndCos(data))
			    .transition().duration(500)
			      .call(chart);
			
			  nv.utils.windowResize(chart.update);
			
			  return chart;
			});	
			
		});
	}

**Comment by liquidpele** [comment]
Closing due to age, if this is still an issue in the latest version please reopen, thanks.
