### ISSUE TITLE
Updating with no data does not clear old data from the chart.

### ISSUE THREAD

**Issue by jgrund** [novus/nvd3#349]
If a chart is populated with data and then update is called after the data has been emptied, the noData text will overlay the existing data.

Consider if the current data should be cleared from the chart as it can be confusing to see both at the same time.

To reproduce (altered from http://nvd3.org/ghpages/multiBar.html):

```
var chart;
var datas = data();

nv.addGraph(function() {
    chart = nv.models.multiBarChart();

    chart.xAxis
        .tickFormat(d3.format(',f'));

    chart.yAxis
        .tickFormat(d3.format(',.1f'));
  
    d3.select('#chart svg')
        .datum(datas)
      .transition().duration(500).call(chart);
  
    nv.utils.windowResize(chart.update);
  
    return chart;
});

window.setTimeout(function () {
  datas.length = 0;
  
  chart.update();
}, 3000);     
```

**Comment by liptga** [comment]
I do simply this in my "update" function before calling the chart update function:
```javascript
if ( data.length == 0 ) {
     d3.select('svg').html("");
}

//do normal chart update call here...
```

You may need to select your svg different way. In my case that was the only one in the frame.

**Comment by liquidpele** [comment]
This was a bug that was brought up in nvd3-community too... we should handle removing data from the chart better, currently all kinds of bad stuff happens.

**Comment by liquidpele** [comment]
Fixed by https://github.com/nvd3-community/nvd3/pull/63 and will likely be merged into the novus code.

**Comment by robinfhu** [comment]
Oh yeah I need to merge nvd3-community:development soon.

**Comment by liquidpele** [comment]
Should be fixed in dev branch now.

**Comment by moneytree-doug** [comment]
@liquidpele Thanks, Ill take a look tomorrow

**Comment by leocongote** [comment]
i have noticed that the library have the following code for detect if is empty the data array:
if ( angular.isArray( data ) && (data.length === 0 ) ) and the problem here is that (data.lenght===0) is false because the array is not zero , so what i did was to check if all the data[*].values are equal to zero, if this is true so we must empty the chart. here is the code:

inside the "checkElementID" function


```
var lengthArray=0;
data.forEach(function(d){
      if(d.values.length!=0){
        lengthArray=d.values.length;
     }
})
if ( angular.isArray( data ) && (data.length === 0 ||  lengthArray==0) )
```

what do you think about this solution?, it works for me.

Thanks for that amazing library!!!

**Comment by liquidpele** [comment]
Send us a pull request based on the current development branch ;)

**Comment by jufemaiz** [comment]
*like*

**Comment by jgrund** [comment]
Thanks! However, this fix takes care of removing the chart but does not clean up any existing tooltips.

**Comment by liquidpele** [comment]
This issue has been closed, please open a new issue for anything further, thanks!

**Comment by jgrund** [comment]
Thanks, opened: #998
