### ISSUE TITLE
error in x-Axis-Ticks and -axisLabels (in all nvd3-Versions)

### ISSUE THREAD

**Issue by UltimateFighter** [novus/nvd3#351]
Problems:
- to many ticks (more than 1)
- ticks have too little distance
- xaxis lable ('date') too far left

When i fill the linePlusBarChart with this data (monthly x-axis):

[
  {
    "key" : "Quantity" ,
    "bar": true,
    "values" : [ [ 1384297200000 , 0] ]
  },
  {
    "key" : "Price" ,
    "values" : [ [ 1384297200000 , 71.89] ]
  }
]

here is an example-fiddle: http://jsfiddle.net/5Gqp6/6/

nvd3 version: 1.1.14b

!! With lineChart it looks like good:  http://jsfiddle.net/5Gqp6/7/

**Comment by liquidpele** [comment]
fixed in latest:   http://jsfiddle.net/5Gqp6/8/
