### ISSUE TITLE
lineWithFocusChart shows incompletly graph on top

### ISSUE THREAD

**Issue by UltimateFighter** [novus/nvd3#356]
ever the next right and/or left data is not in focus-chart selection, the top chat shows incorrectly and not completly line(s).

(you can reproduce it in your own examples)

![image](https://f.cloud.github.com/assets/3225563/1582238/56217c90-51ea-11e3-9d37-1455f7e317fb.png)

**Comment by liquidpele** [comment]
You'll see this with too few data points, the lines need 2 points to connect, your left side isn'g including the next point there.
