### ISSUE TITLE
ANy technique for "Auto Height" ?

### ISSUE THREAD

**Issue by homerlex** [novus/nvd3#358]
When I have a few items in my horizontal grouped bar it looks OK:
http://screencast.com/t/E5l3OQ6pfqT

When I have a bunch its all squished together:
http://screencast.com/t/EjC3uuiCZ

Any ideas for dynamic height of the chart based on the number of elements?

**Comment by liquidpele** [comment]
You'll have to adjust the svg container size accordingly, it *shouldn't* auto-adjust like that all by itself becaues it would change the overall page layout.
