### ISSUE TITLE
rotateLabels for discreteBarChart?

### ISSUE THREAD

**Issue by homerlex** [novus/nvd3#359]
the rotateLabels() function seems to have no effect on discreteBarCharts. Is there any way to rotate the labels on this type of chart?

**Comment by liquidpele** [comment]
Please try using multiBarChart instead... the only difference is multiBarChart doesn't have the showValues option, and I'd rather add that then more to discreteBarChart

**Comment by ErvinLlojku** [comment]
I use css to rotate the labels:
```
.nvd3 .nv-axis .tick.zero text {
      transform: rotate(-90deg);
}
```
