### ISSUE TITLE
Cannot render in phantomJS

### ISSUE THREAD

**Issue by arunkjn** [novus/nvd3#367]
When rendering the examples in phantomJS, I get the following error.
`
TypeError: 'undefined' is not a function (evaluating 'nv.utils.optionsFunc.bind(chart)')
`

the script used is -  
`
phantomjs examples/rasterize.js http://localhost:8000/examples/pie.html test.png          
`
This is related to https://github.com/ariya/phantomjs/issues/10952 and https://bugs.webkit.org/show_bug.cgi?id=14547

Note that this is not the issue with earlier releases. The charts on nvd3.org render fine (with nvd3 v0.0.1a)

Details-
nvd3 - 1.1.15b
phantomjs - 1.9.2

**Comment by madvas** [comment]
Thanks @triomen ! including shim worked like a charm for me

**Comment by mgenov** [comment]
I got similar issue on v1.8.1. 

```javascript
PhantomJS 1.9.8 (Mac OS X) ERROR
	TypeError: 'undefined' is not a function (evaluating 'nv.utils.renderWatch(dispatch, duration)')
	at /Users/mgenov/go/src/github.com/mgenov/webapp/vendor/nvd3/build/nv.d3.js:10873
```

It looks like that PhantomJS is having release troubles and is hard to use it. Can it be solved in nvd3 ?

**Comment by mgenov** [comment]
Not a phantomjs issue. It looks like that it doesn't work and on chrome. 

Chrome 44.0.2403 (Mac OS X 10.10.5) ERROR
	Uncaught TypeError: nv.utils.renderWatch is not a function
	at /Users/mgenov/go/src/github.com/clouway/telcong-admin/web/vendor/nvd3/build/nv.d3.js:10873

I'll fire up new issue.
