### ISSUE TITLE
2 line/scatter series with same x and y values gives error when using voronoi

### ISSUE THREAD

**Issue by sizeight** [novus/nvd3#368]
Rendering a chart with the 2 series below causes a JS error with D3V3 but works fine with D2V2. The 2 series have the exact same 5th value of 1.07, and this causes the error.
Error message:
Uncaught TypeError: Cannot read property 'data' of undefined 
```
[
    {
        "key": "Series 1" ,
        "values": [[1030752000000,11.42],[1033344000000,12.08],[1036022400000,12.32],[1038614400000,11.37],[1041292800000,11.07]]
    },
    {
        "key": "Series 2" ,
        "values": [[1030752000000,11.5],[1033344000000,12.24],[1036022400000,12.6],[1038614400000,11.7],[1041292800000,11.07]]
    }
]
```

**Comment by liquidpele** [comment]
This looks to still be an issue in the stackedAreaChart example if you use regular tooltips and not the guideline.  Interestingly I couldn't reproduce errors with the lineChart though...

**Comment by liquidpele** [comment]
Okay, I think https://github.com/novus/nvd3/pull/880 will fix this, although I'd like a better solution eventually, please let me know if anyone still has issues with it!
