### ISSUE TITLE
How do I modify the tooltip position?

### ISSUE THREAD

**Issue by Nerian** [novus/nvd3#372]
Hi,

I am using tooltips but the tooltip appear just where the mouse is. I want the tooltip to appear 20px at the top of the mouse position. How can I achieve this?

Is there a way to add an offset of 20px to the tooltip?

I see in tooltip.js that there are `gravity`, `distance`, `snapDistance` that seems to be related to what I want to accomplish. How do I access and modify them to suit a particular chart's tooltips?

```javascript
nv.addGraph(function() {
        var chart = nv.models.pieChart()
            .x(function(d) { return d.label })
            .y(function(d) { return d.value })
            .showLegend(false)
            .showLabels(true);

          chart.tooltipContent(function(key, y, e, graph) {
            return '<p>' + key + ': ' + y + '</p>'
          });

          d3.select(place)
              .datum(data)
            .transition().duration(1200)
              .call(chart);

        return chart;
      });
```

![captura de pantalla 2013-12-03 a la s 20 32 28](https://f.cloud.github.com/assets/259568/1667194/bb1122e2-5c51-11e3-9368-379654b503d1.png)

Thanks!

**Comment by liquidpele** [comment]
Looks to be answered.
