### ISSUE TITLE
How to set the yaxis domain

### ISSUE THREAD

**Issue by Nerian** [novus/nvd3#375]
If you have this data:

``` ruby
[ 
  { 
      values: [ { x: 0, y: 0}, {x: 1, y:0} ], 
      key: 'Sine Wave'  
  } ]
```

You will get a chart as this:

![captura de pantalla 2013-12-05 a la s 15 02 10](https://f.cloud.github.com/assets/259568/1682989/1085e6bc-5db6-11e3-8066-b79355bd7d07.png)

But in my case it makes no sense to have negative values. I am measuring the hits on a page. Is there a way to modify the domain of the yAxis so as to not show the negative values?

In other words, I'd like to just see this:

![captura de pantalla 2013-12-05 a la s 15 06 05](https://f.cloud.github.com/assets/259568/1683009/6f7155a8-5db6-11e3-837c-3b78bfe34a06.png)

**Comment by azhai** [comment]
Or only set the minValue:
chart..forceY(0);
