### ISSUE TITLE
linechart viewfinder rendered without right handle when initialized with brushExtent

### ISSUE THREAD

**Issue by fbuchinger** [novus/nvd3#385]
When intializing the linechart with a viewfinder and a fixed `brushExtent` (e.g. `[200, 250]`), the right handle of the viewfinder is only partially rendered. Its rectangle "cover" is missing:

![linechart_viewfinder_fixed_brushextent](https://f.cloud.github.com/assets/287434/1753263/d6a4b2e4-6638-11e3-83e3-49dc1cbabd60.png)

**Comment by NSudhir** [comment]
Hi can you send me the code for this chart?

**Comment by liquidpele** [comment]
This is a duplicate of this more recent bug (which I added a jsfiddle for that reproduces it)

**Comment by liquidpele** [comment]
the other issue: https://github.com/novus/nvd3/issues/855
