### ISSUE TITLE
X axis not displaying in discreteBar

### ISSUE THREAD

**Issue by severa** [novus/nvd3#392]
v: 1.1.15b
The x-axis zero line is not displaying in discreteBarCharts. 

The opacity of the x-axis line is controllable in the css file (line 226), however, even setting that to non-zero will not display the x-axis line if the grid lines in the chart are displayed because the svg element for the horizontal grids, which are part of the y-axis g element, are drawn on top of the x-axis line. This is a function of the code generally setting the x-axis first, then the y-axis. 

It is easy to fix this by switching the order of the axis svg generation by moving line 3377 (x-axis creation) down 4 lines to below the y-axis creation, however, based on comments in the js, there seems to be some desire to change how axes displaying is controlled as well as some confusion about how to manage the zero line characteristics. 

FWIW IMHO, being able to turn the axis lines on and off from the code would be preferable to CSS. 

Note this issue likely exists for other graphs that use grid lines, though I did not test them all.

**Comment by liquidpele** [comment]
showXAxis() and showYAxis() options are available, cheers.

**Comment by cloudeeo** [comment]
Actually this does not work for the axis itself but only for the labels.

**Comment by liquidpele** [comment]
Try with latest 1.7 version... Seemed to work fine when I tested it.
