### ISSUE TITLE
What does the directionality of stacked area chart stream view indicate?

### ISSUE THREAD

**Issue by atuttle** [novus/nvd3#394]
![evercruit](https://f.cloud.github.com/assets/46990/1801072/1a95f176-6bdd-11e3-90fa-e8d49d1e2f8c.png)

This is a typical stacked area chart from my app. I would have assumed that the directionality of the stream view would indicate total volume -- as if the whole thing were just 1 big line-chart... except our total volume has been going up, not down, as would be indicated if my assumption were true.

So I'm just curious... what does this actually indicate? Why does this chart appear to be "trending down"?

**Comment by liquidpele** [comment]
That's weird, but this is really old so maybe not an issue and no example code for reproducing this, so closing.

**Comment by jufemaiz** [comment]
Ref: https://github.com/novus/nvd3/issues/416
