### ISSUE TITLE
stackedAreaChart: Add support for multiple y-axes

### ISSUE THREAD

**Issue by chardie-va** [novus/nvd3#399]
At present, nvd3 doesn't support multiple y-axes for stackedAreaCharts.  It would be helpful for graph readability if this support were added in order to allow duplication of the default y-axis (less need for reading left to right along the full length of the graph).

So, to be clear, this isn't a request for support of multiple y data sets, simply for duplication of the existent y-axis for readability.

**Comment by liquidpele** [comment]
Stacked area charts require that the bars all be using the same axis to be stacked, it really doesn't make sense to stack things that are using different axis.
