### ISSUE TITLE
multiChart: series (right axis) hardcoded

### ISSUE THREAD

**Issue by jorgetutor** [novus/nvd3#401]
Hi! On the multiChart.js there is hardcoded the "(right axis)" text, so this is a problem for non english sites.

```
line 109: series.key = series.originalKey + (series.yAxis == 1 ? '' : ' (right axis)');
```

I would like to help submitting a patch, 

- Adding a new public variable like: serieRightAxisAppend. This way you can pass an empty string to append nothing.

- Other, please tell me :)

What is the best option? 

Thanks for this awesome library!

**Comment by liquidpele** [comment]
This was made adjustable, cheers.

**Comment by improvisio** [comment]
@liquidpele Are you sure this has been fixed? I still see the original code (and have the same issue unfortunately)
