### ISSUE TITLE
Version on live examples doesn't match download version?

### ISSUE THREAD

**Issue by sbromberger** [novus/nvd3#403]
(Version on live examples appears to be 0.0.1a. Version for download is 1.1.15b as of yesterday.)

It appears that the version of nvd3 used at http://nvd3.org/livecode isn't what's currently available for download, and there are some differences. First, some of the data structures (see, e.g., line charts) have changed a bit. Second, some CSS styling doesn't work. The current version does not like CSS styling to remove the non-zero gridlines:
```
.tick:not(.zero) {
  opacity: 0;
}
```

Even with !important, this does not produce the same result as in the livecode site, which happily removes all gridlines and leaves the X axis intact. (No gridlines are removed in the latest version, leading me to believe that the X axis isn't classed with "zero".)

As a related aside, how DO you remove the inner gridlines (without removing the X axis entirely) in the latest version?

**Comment by liquidpele** [comment]
shoudl be updated.
