### ISSUE TITLE
incompatible with latest version of d3

### ISSUE THREAD

**Issue by christophlingg** [novus/nvd3#405]
I had problems using the latest version of d3 with the latest version of nvd3, other people have similar problems which might be caused for the same reason.

Bs using the version included in the **/lib** directory the java script error disappeared.

http://stackoverflow.com/questions/17624111/nvd3-line-chart-uncaught-typeerror-cannot-read-property-x-of-undefined/20994982#20994982

**Comment by liquidpele** [comment]
shoudl be fixed.
