### ISSUE TITLE
Better documentation request

### ISSUE THREAD

**Issue by novodinia** [novus/nvd3#407]
I'm looking at the examples, and I'm not seeing any comments explaining what the data points represent. I'm looking at the cumulative line chart example at http://nvd3.org/livecode/#codemirrorNav and I don't know, e.g., what the values for Series1 represent. How are the dates generated for the xAxis? Maybe this?

    chart.xAxis
      .tickFormat(function(d) {
        return d3.time.format('%x')(new Date(d))
      });

I'm guessing this is ho, though, I don't understand what's going on. I also don't understand how it's just 4 days showing. That's also part of not knowing how the xAxis dates are generated, I suppose. If anyone can help clarify some of this, I would deeply appreciate it. Thanks for all the hard work and helpful feedback so far!

**Comment by liquidpele** [comment]
in progress http://nvd3-community.github.io/nvd3/examples/documentation.html
