### ISSUE TITLE
Error: Problem parsing d=""

### ISSUE THREAD

**Issue by johvik** [novus/nvd3#408]
I get this error when dragging one of the cursors over the other on in lineWithFocusChart charts for example: http://nvd3.org/ghpages/lineWithFocus.html

Full stack frame from Chrome:
```
Error: Problem parsing d="" d3.v2.js:394
attrFunction d3.v2.js:394
(anonymous function) d3.v2.js:3860
d3_selection_each d3.v2.js:509
d3_selectionPrototype.each d3.v2.js:3859
d3_selectionPrototype.attr d3.v2.js:3638
(anonymous function) nv.d3.js:3490
(anonymous function) d3.v2.js:3860
d3_selection_each d3.v2.js:509
d3_selectionPrototype.each d3.v2.js:3859
chart nv.d3.js:3349
d3_selectionPrototype.call d3.v2.js:3864
onBrush nv.d3.js:4745
event d3.v2.js:64
(anonymous function) d3.v2.js:175
brushmove d3.v2.js:4604
wrapper d3.v2.js:492
```
I also reproduced the error in Firefox.
The chart still seems to be working but I would like to get rid of the error.

**Comment by liquidpele** [comment]
Please see if you can reproduce with the latest version.  Since this is over a year old I'll close for now, please re-open if you can reproduce, thanks!
