### ISSUE TITLE
Issue in stacked chart

### ISSUE THREAD

**Issue by dizzyatgithub** [novus/nvd3#414]
![nvd3 js live code examples powered by codemirror](https://f.cloud.github.com/assets/6428792/1939665/15a5fbaa-7f67-11e3-8d33-8f4166d6da2b.png)
![nvd3 js live code examples powered by codemirror 1](https://f.cloud.github.com/assets/6428792/1939666/15adc1d2-7f67-11e3-9fe5-918d1c82fa75.png)

Look at the second image and the blank data inside the bar.

**Comment by liquidpele** [comment]
Should be fixed... try the latest dev code and if not re-open and provide a jsfiddle, thanks!
