### ISSUE TITLE
stacked area chart with focus bar

### ISSUE THREAD

**Issue by jquadrin** [novus/nvd3#417]
wheres the code for this?

**Comment by liquidpele** [comment]
should probably add focus ability to all the graphs really... I wonder if there is way to refactor that out into it's own component that they can all use...

**Comment by whitelynx** [comment]
:+1: I've also been looking for this; I want to display server utilization stats (like CPU usage), which lends itself very well to a stacked area chart, but I want to make it easy for the user to look at different slices of time.

**Comment by liquidpele** [comment]
This isn't currently a feature, but if someone does it please send us a pull request and we'll merge it in, cheers!

**Comment by Snuggert** [comment]
Does this mean you are pulling my request?

**Comment by liquidpele** [comment]
Oh, looks like the novus guys are doing some cleanup.   I plan to merge your thing, but I wanted to cut a point release before that.
