### ISSUE TITLE
No highlight for x-axis

### ISSUE THREAD

**Issue by m48u** [novus/nvd3#418]
Hi there,

Here is a plnkr of what I just mentioned
http://plnkr.co/edit/eyfanyRrm27GmaSu8Pnq?p=preview

What I did: Copied the example code from the website (there is everthing fine) but as you can see in the plnkr there is no highlight for the x-axis (same for discrete bar charts). I also tried to explicitly highlight the axis with .highlightZero(true) but it didn't work either.
Is there an other option that I could use or is there another problen?

Thanks in advance
m48u

**Comment by liquidpele** [comment]
We removed the highlightZero option and just added a "zero" css class to that line so you can style it how you like now.
