### ISSUE TITLE
Error: Problem parsing d="M0......"

### ISSUE THREAD

**Issue by m48u** [novus/nvd3#420]
Hi there,

I don't know if this is related to nvd3 or directly to d3 so I start posting it here.
Here is a plnkr to demonstrate the problem:
http://plnkr.co/edit/s4A9FHEblFwCYuiQMdU3?p=preview

Everthing looks find but if I change the shape of the data series the console will be flooded with error messages. At the first sight everthing looks good but the tooltips aren't working like before (no lines to the axes any more)

What's the problem here?
Thanks in advance

**Comment by joshjordan** [comment]
This was a bug with `d3`.
