### ISSUE TITLE
Scatter plot incorrectly responds to selections

### ISSUE THREAD

**Issue by benjh33** [novus/nvd3#424]
Apologies if you're aware, I didn't see a scatter plot issue.

Initially thought this was an rCharts problem. The legend buttons remove the appropriate observations but when you mouse over the plot, they observations are replaced with the next color on the color scale.

Here's my example, but it's the same on your site.
http://benjh33.github.io/2014/01/22/NVD3_and_RCharts/

**Comment by liquidpele** [comment]
should be fixed in latest.
