### ISSUE TITLE
Custom container for tooltips

### ISSUE THREAD

**Issue by quentindemetz** [novus/nvd3#425]
Today, tooltips are created as a `div` that sits after the corresponding `svg` node.

I'm having issues with the tooltip being clipped when the svg container has `overflow: hidden` (in a carousel for example).

Is it possible to decided the tooltip's containing element? I tried modifying some of the nv.tooltip code but the tooltip ends up in the wrong position.

Thanks

**Comment by liquidpele** [comment]
Tooltip is added to body now isn't it?   I think this is out of date.
