### ISSUE TITLE
tooltip & axis formatting decoupling

### ISSUE THREAD

**Issue by milroc** [novus/nvd3#428]
nvd3 tightly couples the axis formatting to the tooltip display format, without anyway for the developer to override it.

http://stackoverflow.com/questions/19424344/nvd3-js-yaxis-and-tooltip-different-percision is an example of this limitation for a line graph. 

It is however everywhere in the nvd3 library. Was this by design?

**Comment by jenslonkowski** [comment]
Another solution for me is to use the context (this) as a conditional inside the tickFormat function of the yAxis object:
```
function(d) {
    // case for tooltip
    if (this === window) return ...;
    // case for yAxis
    return ...;
}
```

**Comment by liquidpele** [comment]
Probably worth doing this, tagging as enhancement request.

**Comment by floribon** [comment]
+1, for now using @jenslonkowski hack. This only allows to edit the heading, a full control over the template would be highly preferable.

**Comment by jufemaiz** [comment]
Any thoughts?

**Comment by robinfhu** [comment]
I recognize it's not obvious, but there should be a way to override that tooltip.

Try this:

lineChart.interactiveLayer.tooltip.contentGenerator(  ...your function...)

**Comment by liquidpele** [comment]
lineChart.interactiveLayer.tooltip.contentGenerator( ...your function...)

Yup, I do that exact thing for the ohlcChart to override the tooltip from historicalBarChart.

**Comment by robinfhu** [comment]
PR opened.

**Comment by diaabaraka** [comment]
@jenslonkowski Nice Hack!
