### ISSUE TITLE
scatterChart not filtering points correctly?

### ISSUE THREAD

**Issue by seiyria** [novus/nvd3#432]
I'm using a scatterChart and I'm having problems getting it to filter data correctly. My data objects all have a `size`, and the ones with a `size` of 0, I don't want to be present in the chart. I set the filter function like so:

`chart.scatter.pointActive(function(d) { return d.size > 0 });`

But still the points that have a value of 0 are visible. Any ideas why? It seems like it should work based on what I saw in scatterChart.js, so I'm a bit perplexed.

**Comment by liquidpele** [comment]
Should be fixed in latest version, if not please reopen, thanks!
