### ISSUE TITLE
Legend Labels width always uses approximation

### ISSUE THREAD

**Issue by Robinson7D** [novus/nvd3#449]
The code snippet below always throws an error and falls into the `catch` section because the relevant selection will leave  `legendText`  as a 1-element Array (and Arrays do not have `getComputedTextLength` function). Require `.node()`

```
var legendText = d3.select(this).select('text');
var nodeTextLength;
try {
  nodeTextLength = legendText.getComputedTextLength();
  // ... etc
```

**Comment by liquidpele** [comment]
Already fixed in latest :)
