### ISSUE TITLE
Axis reversed and line going out of graph

### ISSUE THREAD

**Issue by MuyBien** [novus/nvd3#487]
Hi everybody !
I use nvd3 to display evolution of a data throught time. In most of the case, it's rendering fine but sometimes I have a strange line and the y axis is reversed (max to min). The JSON is contructed with the same script as the other lines and all other charts are rendering fine.

![bug-nvd3](https://cloud.githubusercontent.com/assets/1921522/2601075/d82738a4-bb0a-11e3-9260-c1863fd2242b.png)

What is the problem ?
Here is the JSON used to make a graph like that : 

```
[{"type":"LINE","label":"Evolution","values":[{"x":1383433200000,"y":"2"},{"x":1386025200000,"y":"6"},{"x":1388703600000,"y":"7"},{"x":1391382000000,"y":"11"},{"x":1393801200000,"y":"19"},{"x":1396476000000,"y":"20"}],"colors":[],"labels":[],"xkey":"x","ykeys":[]}]
```

And the code to generate the lineChart :

```
nv.addGraph(function() {

            var lineChart = nv.models.lineChart()
                .margin({left: 25})
                .width(width)
                .height(height)
                .showLegend(false)
                .tooltipContent( function(key, x, y, e, graph) {
                    return '<p>' +  x + ' : ' + y + '</p>';
                  });

            lineChart.xAxis
              .showMaxMin(false)
              .tickFormat( function(value) { return d3.time.format("%d %b %Y")(new Date(value)); });

            lineChart.yAxis
              .tickFormat(d3.format(',.0f'));

            d3.select(graphDiv).append("svg")
                .datum(dataArray)
                .transition().duration(1200)
                .attr('width', width)
                .attr('height', height)
                .call(lineChart);

            return lineChart;
        });
```

I can make a JSFiddle but I cannot find one with all the scripts already. If you have one, I will do it to test.

Thanks ;)

**Comment by konuch** [comment]
Thanks, had a same problem. Changing values to numbers solved the issue.
