### ISSUE TITLE
Scatter Chart: Legend double click results not as expected

### ISSUE THREAD

**Issue by iShiblee** [novus/nvd3#488]
When new data is loaded to the scatter chart, the legend double click no longer performs visibility toggle operation.

e.g. If this code is used more than once to update the values.
<code>d3.select('#svg')
      .datum(data(4,40))
    .transition().duration(500)
      .call(chart);</code>

**Comment by liquidpele** [comment]
Please provide a jsfiddle or similar that reproduces the problem using the latest version, thanks!  Closing for now.
