### ISSUE TITLE
chart with [one line one scatter] in yAxis1, and two lines in yAxis2 ??

### ISSUE THREAD

**Issue by PascalAntoniou** [novus/nvd3#489]
Hi,

I'm trying to create the chart described in the title. Incorporating multiple lines is straight forward (haven't tried adding the scatter yet, does scatterPlusLineChart support multiple lines?).

The problem is adding a second yAxis and matching 2 of the 3 lines to the second yAxis.

Tried a lineChart, y1Axis,  y2Axis or yAxis1, yAxis2 and a corresponding yAxis: 1 (or 2) property to the data JSON. This doesn't work. 

Tried a multiChart, and the yAxis1 and corresponding JSON property method works, but for some reason clicking on the legend to select a line *never* results in the sole line of yAxis1 to dissapear, it's always visible. Even worse, setting .useInteractiveGuideline(true)  on the multiChart makes the whole chart dissapear, so I can only get the chart with the old tooltips...

Am I doing something completely wrong?? What's the standard method of incorporating more axes in nvd3?

**Comment by liquidpele** [comment]
scatter isn't part of multichart yet... if you build it send us a pull request :)
