### ISSUE TITLE
unable to hook into legend to make custom

### ISSUE THREAD

**Issue by pkpp1233** [novus/nvd3#490]
i've been browsing the api but i can't figure out a way to hook my own custom legend into a multi bar chart.

i'd like to replace the bubble legend with a multisort that'll be more scalable when there are more options to choose from.

any way to open up the legend to simply create a custom design and then provide the hooks for selecting?

**Comment by liquidpele** [comment]
You'll want to build it in html and set/unset the "disabled" attribute on the series in question and then call chart.update, or dispatch the state to the graph using chart.dispatch.
