### ISSUE TITLE
ie8 error line 7849

### ISSUE THREAD

**Issue by olivierGM** [novus/nvd3#491]
I am using r2d3 with nvd3. And when i'm trying to use nvd3 i'm getting an error : 
User Agent: Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 6.1; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; Media Center PC 6.0; .NET4.0C; .NET4.0E; InfoPath.3)
Timestamp: Mon, 7 Apr 2014 18:23:12 UTC
Message: Object doesn't support this property or method
Line: 7849
Char: 3
Code: 0
URI: http://localhost:9001/bower_components/nvd3/nv.d3.js

Which is :   chart.options = nv.utils.optionsFunc.bind(chart);

**Comment by liquidpele** [comment]
don't use IE8... ew.
