### ISSUE TITLE
pieChart layout breaks when mixing very big and very small values

### ISSUE THREAD

**Issue by jayme-github** [novus/nvd3#492]
I have very small (< 0) and very high (> 1000) values mixed in one pieChart.
It seems that this breaks the layout of the pieChart:

http://jsfiddle.net/BRHK8/1/

I'm not familiar with d3/nvd3 so I'm unsure how to track this down.

**Comment by liquidpele** [comment]
The example looks fine in chrome now, was probably a chrome issue.
