### ISSUE TITLE
dynamic time tickformat for axis?

### ISSUE THREAD

**Issue by NerdGGuy** [novus/nvd3#495]
Trying to think of the best (pushable) solution for a dynamic tickformat depending on range. Any expert thoughts? As far as I can tell tickformat only gets passed the current value which isn't enough to grab the range (without painfully updating a more global object).

E.g. If the range is within the same day only display time. But if it spreads over multiple days display date etc. Think a time based lineWithFocusChart that only displays the date/year when needed.

**Comment by raphael-psr** [comment]
Is there any solutions to this problem?
