### ISSUE TITLE
Warning about nv.utils.windowResize (memory leak)

### ISSUE THREAD

**Issue by cstephe** [novus/nvd3#504]
I'm using nvd3 in a single page angular app.
If you use this window resize and send in the most obvious nv.utils.windowResize(chart.update) Your chart will never be garbage collected.

I know this isn't the fault of the utils, however its pretty easy to miss.
I wanted to post this here since It took me awhile to track down this leak.  

In angular I suggest:

```
    var resizeEventPromise;
    window.onresize = function(){
        $timeout.cancel(resizeEventPromise);
        resizeEventPromise = $timeout(function(){
            $rootScope.$broadcast("WINDOW_RESIZED");
        }, 100)
    };
```
then with your chart:
```
scope.$on("WINDOW_RESIZED", chart.update);
```

**Comment by floribon** [comment]
The issue still exists with nvd3 1.7.1, and it took me a while to understand my memory leak was coming from that.

I think nvd3 charts should expose a `destroy` public method that would take care of that and any other things we migh discover later on.

**Comment by liquidpele** [comment]
OK reopening for investigation.

**Comment by BrutalBrutus** [comment]
The only way I could thwart the resize error was to use the solution posted by dazhbog.

**Comment by liquidpele** [comment]
you might also look at things like https://krispo.github.io/angular-nvd3/ as wrapping non-angular code in an angular app often leads to these kinds of issues.

**Comment by liquidpele** [comment]
As for this issue, I'm going to close it as I don't see anything to really "fix" per se, but if anyone would like to submit a pull request that would make it easier to handle with angular then please feel free.

**Comment by xskid** [comment]
@liquidpele , was this problem solved already ?

**Comment by Skinner927** [comment]
For anyone that stumbles upon this issue and is working in Angular, my solution was to modify `windowResize`. The method is backwards compatible, but now you pass $scope in as a param so the destroy hookup is done automatically for you. 

    nv.utils.windowResize = function(scope, handler) {
        // Legacy support
        if(typeof scope === 'function'){
            handler = scope;
            scope = undefined;
            nv.deprecated('WARNING: Failed to pass $scope when binding to windowResize event');
        }
    
        if (window.addEventListener) {
            window.addEventListener('resize', handler);
        } else {
            nv.log("ERROR: Failed to bind to window.resize with: ", handler);
        }
        // return object with clear function to remove the single added callback.
        var retObj = {
            callback: handler,
            clear: function() {
                window.removeEventListener('resize', handler);
            }
        };
    
        // Hookup our auto-destroy if passed scope
        if(scope){
            scope.$on('$destroy', function(){
                'use strict';
                retObj.clear();
            });
        }
    
        return retObj;
    };
