### ISSUE TITLE
multichart legend actions

### ISSUE THREAD

**Issue by nickbithrey** [novus/nvd3#542]
What is shown is that when removing any line series, there is no effect when the line is expected to be hidden, when removing a bar series, it works as expected with hiding that series until the final bar series, where there is no effect. Havent tried anything on stacks yet.
here is a jsFiddle http://jsfiddle.net/z4aZ4/78/

**Comment by tsenga** [comment]
Seems to work in nvd3 1.7.1

**Comment by liquidpele** [comment]
Cool thanks for checking!
