### ISSUE TITLE
multichart and linePlusBar chart line behind bars

### ISSUE THREAD

**Issue by nickbithrey** [novus/nvd3#543]
For both the multichart and linePlusBar charts, then line is very feint and noticed to be behind the bars (not infront) even though the z-index specifies otherwise (which I did notice).
Here is a jsFiddle http://jsfiddle.net/z4aZ4/78/

Using some hacking methods, found that this was due to the line element being last in the 'g' element, and putting this first in the list brought the line to the top. This then made the tooltop go crazy on which i cannot explain.

**Comment by liquidpele** [comment]
duplicated of:  https://github.com/novus/nvd3/issues/293
