### ISSUE TITLE
interactiveBisect fails to correctly locate item for versions of d3 >= 3.4.4

### ISSUE THREAD

**Issue by bfhobbes** [novus/nvd3#554]
It seems that a change in d3 version 3.4.4 to d3.bisector has broken the interactiveBisect functionality. 
_d3.bisector_ now supports a comparator argument if the method passed takes two parameters instead of the one needed for an accessor ( https://github.com/mbostock/d3/wiki/Arrays#d3_bisector )
Unfortunately _nv.interactiveBisect_ is passing 
```
function(d,i) { return d.x;}
```
Which is being interpreted by _d3.bisect_ as a comparator, and stopping the interactiveBisect working, ( it will only hilight the 0th or 1st data point. )

**Comment by portante** [comment]
@sudheesh001, please check out the development branch as of https://github.com/novus/nvd3/commit/b0142818b07ab9d2b29ff5aaccd516863c311af6, you should see that now nvd3 is working with 3.4.4 and later, but NOT with any version earlier.

**Comment by robinfhu** [comment]
Yeah nvd3 as it stands now doesn't work with d3 3.4.4 or later.  We have a fix in the development branch.

**Comment by robinfhu** [comment]
Linked https://github.com/novus/nvd3/issues/760
