### ISSUE TITLE
interactiveGuideLine with lineChartWithFocus not work on chrome/opera works on FF/IE

### ISSUE THREAD

**Issue by c3j35tb3** [novus/nvd3#557]
Hi. I have added guidLines to line chart with this code: https://github.com/wrapp/nvd3/commit/3886bd219da2a05fe1fca8945d8dc8728d79ac3e

It works well in FF and IE but not work with chrome and opera. How could I fix it?

EDIT1. I find out that chrome don't hook mousemove over svg element, only when point ot specific data value (for example if I have [x:710, y:63] and point to it I get tooltip. If I point over or under this value I don't get tooltip. I must point to line). 

Black dots are where mouse points:

FF examaple (guidLine is visible even If I point over the blue line):
![ff](https://cloud.githubusercontent.com/assets/7630796/3016997/be153a4a-df74-11e3-9e85-ab4e7d1b7cac.png)

Chrome example (guidLine is visble only when I point on blue line):
![chrome](https://cloud.githubusercontent.com/assets/7630796/3017005/d80f30fe-df74-11e3-9596-3ffa8927a3cd.png)

**Comment by liquidpele** [comment]
Seems fixed.
