### ISSUE TITLE
Local variable Layer overrides global constructor function Layer

### ISSUE THREAD

**Issue by scarfacedeb** [novus/nvd3#559]
I'm getting `undefined is not a function` exceptions, because of this:
`var Layer = new Layer({` lines in models. (e.g. https://github.com/novus/nvd3/blob/refactor/2.0.0-dev/src/models/line/lineWithFocusChart.js#L17)

I think, that the issue here is that `var Layer` statement creates new local-to-the-current-function variable `Layer` and it makes an old global Layer constructor function unreachable. (`new Layer` statement now refers to Layer local variable, instead of construction function)

It seems to me that the best way to solve is to rename `Layer` local variable to `layer`.

I'm using the latest `refactor/2.0.0-dev` branch.

P.S. Also, I noticed that [nv.d3.js](https://github.com/novus/nvd3/blob/refactor/2.0.0-dev/nv.d3.js) file in that branch is almost empty and I had to generate it myself using `grunt production`.

**Comment by liquidpele** [comment]
Looks like an issue with the 2.0 branch taht was never completed.
