### ISSUE TITLE
Does fish eye works only in the iframe or it not the case 

### ISSUE THREAD

**Issue by vineelal** [novus/nvd3#567]
I have included the scatter chart inside a div and not an iframe and enabled fisheye option like below. But the fisheye option is not working.

  chart = nv.models.scatterChart()
                        .x(function (d) {
                            return d.x;
                        })
                        .y(function (d) {
                            return d.y;
                        })       
                        .showDistX(true)
                        .showDistY(true)
                        .xPadding(true)
                        .yPadding(true)
                        .fisheye(2);

**Comment by liquidpele** [comment]
The fisheye stuff was removed.
