### ISSUE TITLE
InteractiveLayer Tooltip x and y value formatting 

### ISSUE THREAD

**Issue by sayerhs** [novus/nvd3#573]
`interactiveLayer.tooltip` should receive the actual x and y values from data and not strings that are returned by x- and y-axis label formatter. For example, in `nv.models.lineChart` the `xValue` seen by `tooltip.headerFormatter` is 

```js
var xValue = xAxis.tickFormat()(chart.x()(singlePoint,pointIndex));
```

This should be 

```js
var xValue = chart.x()(singlePoint, pointIndex);
```

An example use case is when the x-axis has date/time values. I want to use d3.time.format.multi for the x-axis labels, but use a custom headerFormatter to show the full date/time in the tooltip. 

```js
// Formatting for x-axis
var customTimeFormat = d3.time.format.multi([
       ["%I:%M %p", function(d) { return d.getHours(); }],
       ["%b %d", function(d) { return d.getDate() != 1; }],
       ["%B", function(d) { return d.getMonth(); }],
       ["%Y", function() { return true; }]
     ]);

// ... initialize nvd3 chart...

// set xAxis label
chart.xAxis.tickFormat(customFormat)

// Override tooltip xValue format
var hdrfmt = d3.time.format("%a %b %d %H:%M %Y");
chart.interactiveLayer.tooltip.headerFormatter(hdrfmt);
```

Currently this fails because d3.time.format(...) receives a string and returns `undefined` and therefore `headerFormatter` generates an error.

**Comment by jufemaiz** [comment]
Care to provide back? :(

**Comment by robinfhu** [comment]
The fix is to override interactiveLayer.tooltip.contentGenerator.  It's not obvious unfortunately.  I should provide some examples.

**Comment by robinfhu** [comment]
Similar to issue #428

**Comment by jufemaiz** [comment]
:+1: thanks!

**Comment by robinfhu** [comment]
PR opened.
