### ISSUE TITLE
Disable legend for one series

### ISSUE THREAD

**Issue by Bluescreen00** [novus/nvd3#574]
Is there a ways to disable the legend icon for one of the series in the nv.models.lineChart() chart or can I only disable all of them? Further is there a way to disable automatically connecting data points? My goal is to create a scatter/bubble plot inside the line chart. 
Cheers

**Comment by liquidpele** [comment]
There is not a way to disable items in the legend itself, but you can set a series to be off by default using the "disabled" attribute on the series.
