### ISSUE TITLE
Tooltip data: e.series.bar is always undefined, causing wrong tickFormat to be chosen. 

### ISSUE THREAD

**Issue by kerryz** [novus/nvd3#576]
In Line Plus Bar With Focus Chart the function showTooltip uses meta data from a provided element argument to determine which y-axis to use, and from that, which tickformat: 
```
var showTooltip = function(e, offsetElement) {
    ....
    y = (e.series.bar ? y1Axis : y2Axis)
```
The problem is that e.series.bar is always undefined, even for the bars. If you open linePlusBarWithFocusChart.html and hover over a bar, you'll see that it uses the format of the wrong (price) axis.

**Comment by liquidpele** [comment]
This should be fixed with https://github.com/novus/nvd3/pull/851

Closing, but let us know if that doesn't fix it once merged :)
