### ISSUE TITLE
Utter fail on usability

### ISSUE THREAD

**Issue by ftrotter** [novus/nvd3#577]
Hi.
 I want to use a chart. You have a chart would work perfectly. 
I need to figure out what format to put the data to put in your chart.

But you dont have example data. You have a function that generates random data. Now I have to figure out what that function outputs in order to figure out what the data is. 

I just want to cut and paste some javascript, and quickly figure out what I need to do on the server side to make it work. 

It is reeeeaaalllly cool that your demo site generates a random chart every time. But does that actually help your first time users understand how to you use your charts? No. Not at all. It is a barrier to entry that wastes user time. 

It seems obvious what the data generation tool function because you already understand what it does. In short, you have made your demo site cool for yourselves at the expense of your end user experience. 

I cannot tell you how much this frustrates me as a first time user.

-FT

**Comment by ftrotter** [comment]
Just getting back to this. 

I know that this is not a software issue. This is a bug for your documentation. The fact that you regard a bug for usability and documentation as an invalid issue is a huge problem. 

I do not need to hire a developer, I am a developer, but I am a developer with limited time to learn. Javascript is not a language I am comfortable with. However, I do get how open source works. I am happy to contribute, either sourcecode, documentation or financially to get the things I need. The first thing that I can and do contribute is clear, constructive criticism. How an open source project reacts is very telling. 

I gave you a detailed description of how your documentation and demo could be improved for first time learners. Rather than actually address the underlying issue of unclear documentation and demos, you chose to write me two notes that assure me that my problem is invalid, because **you do not also have them**. Essentially I made a criticism about how your documentation works for beginners, and you told me that I was wrong, because two non-beginners do not have my problem. Then you closed the bug, without doing anything that I can tell to address the problem. 

Why even bother continuing this discussion, when someone else has already written something perfectly compelling: http://www.catb.org/~esr/writings/cups-horror.html

**Comment by Snuggert** [comment]
-  There is literally a folder called examples in the project's root directory.

- Posting a link to an article complaining about a graphical user interface being to difficult for random end-users isn't at all linked to development. Prior knowledge of JS is expected.
