### ISSUE TITLE
export focus data

### ISSUE THREAD

**Issue by selvavalluvan** [novus/nvd3#578]
I have a doubt with one of the SVG tools in nvd3. In the Line with Focus Chart is there any way to export the data which the brush is focused to. 

For example I have a huge data in my Line with focus chart graph. I am selecting some data in the focus. I want that particular focused data in a different external file. I tried with some of the brush tools. It did not work out. Could you please help me here. It would be grateful.

Thanks.

**Comment by liquidpele** [comment]
Use chart.brushExtent() to return the brush.extent() as defined in d3:

https://github.com/mbostock/d3/wiki/SVG-Controls#brush_extent
