### ISSUE TITLE
make stripe colors for grids in nvd3js

### ISSUE THREAD

**Issue by alin92** [novus/nvd3#583]
any idea how can i color the grids in stripes for eg like this 
 http://i.stack.imgur.com/2c812.png

here is [fiddle](http://nvd3.org/livecode/index.html#codemirrorNav) which shows a sample line graph that i am using in my app. I want that fiddle to have stripes like in image.

**Comment by liquidpele** [comment]
This isn't currently an option that I'm aware of... if you can show a d3 block that demos such a thing that would be helpful... closing for now since this is a very old issue.
