### ISSUE TITLE
Fill Opacity is always set to 75%

### ISSUE THREAD

**Issue by federicocasares** [novus/nvd3#586]
I have noticed that fill-opacity is always set to .75 in the different elements of most charts (for example, the bars in bar graphs). Is there a way to change this? I need very specific colors in some charts I'm making and I can't seem to get them because they always get rendered in this semi-transparent fashion.

**Comment by eaganan** [comment]
Hi, I have the same issue with a discreteBarChart,  could you tell me how you solved it.

Very thanks.

**Comment by liquidpele** [comment]
override the default CSS.

**Comment by eaganan** [comment]
Hi, I used 
.nv-group.nv-series-0 {fill-opacity:1 !important;}

it works!!

Thanks
