### ISSUE TITLE
Overlay 2 charts?

### ISSUE THREAD

**Issue by denishaskin** [novus/nvd3#589]
Is my understanding correct that I cannot overlay 2 NVD3 charts?  I'm using the stackedArea chart and I would really like to be able to overlay a simple line chart over it (with a different Y axis).

Without really investigating, my sense is that I would need to fork and create a new model? (probably starting from stackedArea and linePlusBarChart as examples)

**Comment by liquidpele** [comment]
You'd need to implement it and send us a pull request.  Thanks!
