### ISSUE TITLE
How can disable the 'areaClick.toggle' on the Stacked Area Chart?

### ISSUE THREAD

**Issue by demogar** [novus/nvd3#590]
Hello!

I'd like to be able to disable the "toggle" functionality on the Stacked Area Charts, so when an area is clicked, the section doesn't get "focused".

The documentation is very poor on this matter, and I really don't see this possibility based on the source code, but maybe I'm missing something.

Any thoughts?

**Comment by liquidpele** [comment]
Seems like an obvious option to add... marking as enhancement request.

**Comment by liquidpele** [comment]
This is easy, just do this:

    chart.stacked.dispatch.on('areaClick.toggle', null);

But make sure you do it AFTER the .datum(...).call(chart) and inside the 'addGraph' block... so that the chart object is created and it has already gone through the generation code so that your code over-writes the already created dispatch.   Cheers.

**Comment by PeterVermont** [comment]
I found that in addition to 
`chart.stacked.dispatch.on('areaClick.toggle', null);`
I also had to disable the 'areaClick' event:
`chart.stacked.dispatch.on('areaClick', null);`

**Comment by JonHanna** [comment]
The above no longer works. After using it, the area click toggle still fires.
