### ISSUE TITLE
scale.nice not working

### ISSUE THREAD

**Issue by torfuspolymorphus** [novus/nvd3#594]
I'm trying to use the [`scale.nice`](https://github.com/mbostock/d3/wiki/Quantitative-Scales#wiki-linear_nice) method to extend my y-axis scale to nice values. This is easily done in D3 (see [fiddle](http://jsfiddle.net/torf/xBHQ8/)):

    var s = d3.scale.linear()
        .domain([1, 1.9])
        .nice(1);

However, it seems that this doesn't work with NVD3, at least not with the line chart that I tried it with. I've prepared [a fiddle showing the problem](http://jsfiddle.net/torf/gvBNf/). In my opinion, `chart.yScale().nice(1)` should do what I want, but it doesn't. Neither does `chart.yAxis.scale().nice(1)` nor `chart.yAxis.axis.scale().nice(1)`.

**Comment by kdkavanagh** [comment]
Anyone find a fix for this?

**Comment by liquidpele** [comment]
I think you should be able to create a new d3 scale, set the nice value, and then set it to be the scale within nvd3:

var custom_scale = d3.scale.linear()
    .domain([1, 1.9])
    .nice(1);

chart.xScale(custom_scale);

**Comment by gagandp** [comment]
I am trying to implement scale.nice in nvd3 line chart,the axis are not rounding off to nice values. @liquidpele I am still not getting it why you have closed that issue  (scale.nice not working #594)

**Comment by graemebr** [comment]
I tried using `chart.xScale(custom_scale)` on a multiBarChart, but I wasn't able to get the `scale.nice` method to work. However, I found a workaround:
```
const maxValue = 42 // max value from data
const ticks = 6

const niceYScale = d3.scale.linear()
  .domain([0, maxValue])
  .nice(ticks);

const chart = nv.models.multiBarChart()
  .forceY(niceYScale.domain());

chart.yAxis.ticks(ticks);
```
