### ISSUE TITLE
how i can put more lines in Line Plus Bar Chart using nvd3.js?

### ISSUE THREAD

**Issue by ihsansatriawan** [novus/nvd3#598]
i'm newbie in javascript and i want to try to visualize data using javascript especially d3.js. I found example graph what i want to build in nvd3.js (http://nvd3.org/examples/linePlusBar.html) this is line and bar chart combine in one place,,i try to modified it to same like (http://www.highcharts.com/demo/combo-multi-axes), but i still can not do that.

My question is, how i can put more lines in in Line Plus Bar Chart using nvd3.js ?

Thanks :)

**Comment by liquidpele** [comment]
It currently handles up to 2 lines, for more you'll have to modify it and perhaps send us a pull request.   Cheers.
