### ISSUE TITLE
scale.clamp not working

### ISSUE THREAD

**Issue by mmanela** [novus/nvd3#600]
This is similar to the issue [scale.nice not working](https://github.com/novus/nvd3/issues/594). When I try to use the scale clamp function it does not do anything. I created a [repro to show](http://jsfiddle.net/mmanela/TkH2h/). But  in short none of these seem to do anything:

    chart.yScale().clamp(1.5);
    chart.yAxis.scale().clamp(1.5);
    chart.yAxis.axis.scale().clamp(1.5);

I tested on both a lineChart and a linePlusBarChart.

**Comment by liquidpele** [comment]
Same as the other one... try creating the scale and set the clamp, then pass it as the replacement scale to the yScale() option.
