### ISSUE TITLE
Charts are not showing up. Only texts appear in the UI

### ISSUE THREAD

**Issue by vkjv** [novus/nvd3#605]
I am trying to use nvd3 charts for one of my application. I use dojo framework to build the client side ui. I have attached a sample code which creates a donut pie chart in the given dom node. The issue i am seeing here is, the chart only shows the text instead of the graphics. Element inspection revealed no issues as i could see necessary elements such as svg, and paths etc in the elements tree. But somehow, this chart wont show up properly in the ui. 
define([ "dojo/_base/declare",
    "dijit/_Widget", "dojo/_base/lang"],

    function (declare, _Widget, lang) {

        var PieChart = declare("chart.DonutPieChart", [_Widget], {

            constructor:function (params) {
                this.dataArray = params.componentParams.slices;
                this.style = "width: 300px; height: 200px; float:left";
            },

            buildRendering:function () {
                this.domNode = dojo.create("div");
                /*this.legendDiv = dojo.create("div", {
                    style:"width: 100%; height: 50px;"
                });*/

                // The chart's div must be added to the DOM for it to render correctly.
                // The analysis pane will check if we are already added so it doesn't get added twice.
                this.parentDiv.set("content", this);
                /*if (this.parentDiv.domNode) {
                 this.parentDiv.domNode.appendChild(this.legendDiv);
                 this.parentDiv.domNode.style.background='#EFEFEF';
                 this.parentDiv.domNode.style.padding='3px';
                 }*/
            },

            postCreate:function () {

                var width = this.domNode.clientWidth;
                var height = this.domNode.clientHeight;
                var svgNode = dojo.create("svg", {
                    id : "chartsvg",
                    style : "width:"+width+";height:"+height
                });

                var testdata = [
                    {
                        key: "One",
                        y: 5
                    },
                    {
                        key: "Two",
                        y: 2
                    },
                    {
                        key: "Three",
                        y: 9
                    },
                    {
                        key: "Four",
                        y: 7
                    },
                    {
                        key: "Five",
                        y: 4
                    },
                    {
                        key: "Six",
                        y: 3
                    },
                    {
                        key: "Seven",
                        y: .5
                    }
                ];
                this.domNode.appendChild(svgNode);
                nv.addGraph(lang.hitch(this, function() {
                    var chart = nv.models.pieChart()
                            .x(function(d) { return d.key })
                            .y(function(d) { return d.y })
                            .width(width)
                            .height(height)
                            .showLabels(true)     //Display pie labels
                            .labelThreshold(.05)  //Configure the minimum slice size for labels to show up
                            .labelType("value") //Configure what type of data to show in the label. Can be "key", "value" or "percent"
                            .donut(true)          //Turn on Donut mode. Makes pie chart look tasty!
                            .donutRatio(0.35);     //Configure how big you want the donut hole size to be.

                    /*chart.color(function(d){
                        return d.fill;
                    });*/

                    d3.select(svgNode)
                        .datum(testdata)
                        .transition().duration(350)
                        .attr('width', width)
                        .attr('height', height)
                        .call(chart);

                    nv.utils.windowResize(chart.update);

                    return chart;
                }));

            },

            startup:function () {
                this.inherited(arguments);
            },

            resize:function() {
            }
        });
        return PieChart;
    });

I suspect this could be due to conflicting css, or js files that the wrapper html file refers to. But i could not figure out the exact problem here. The html has links to 100s of css and js files. 
Any help is much appreciated.

**Comment by liquidpele** [comment]
Appears to be building it within another framework which is causing problems.  If you can reproduce things with only nvd3 in a jsfiddle please re-open, closing for now.

**Comment by iamsimha** [comment]
Even I was facing this issue. After some debugging, I found out that dojo was overwriting the native "Date.now" function to return a String datetime, instead of unix epoch timestamp. This messed up the timer calculations in d3 and none of the d3 transitions which used d3's internal timer worked. So this cannot be fixed in nvd3.js.

The workaround/fix I applied was to replace "Date.now"  with "+Date.now" in d3.js. +Date.now() returns a unix timestamp and everything works as expected.

**Comment by sacharbit** [comment]
I have the same problem but I don't use dates in the chart. I tried with a pie chart, a line chart and a histogram chart but none worked. I think it's a css conflict as well. I used a svg with a specific id for each graph and put them in a seperate container. Also, I don't have any other library other than nvd3 and Jquery but I don't think this should be problem.

**Comment by jeffhongxiao** [comment]
Is there a fix for this bug? i'm seeing this issue using: 
* nvd3: 1.8.5
* d3: 3.5.7
* jquery: 3.2.1

**Comment by jeffhongxiao** [comment]
https://jsfiddle.net/jeffxiao/pu2jfpvq/3/ shows the bug

**Comment by jeznag** [comment]
Jeff's scenario can be fixed by doing `d3.select('#container').append('svg').attr('id', 'svg2');` instead of using jQuery to add the SVG element. I suspect the same would apply with the Dojo example.
