### ISSUE TITLE
forceX in multiBarChart throws

### ISSUE THREAD

**Issue by doronaviguy** [novus/nvd3#607]
during update , of the data the following line throws an error.
chart.forceX([ 0, 99]);

in multiBarChart throws 
Cannot read property 'apply' of undefined

```javascript

chart.forceX([minX, maxX]);
```
                           

the same code works fine in 'stackedAreaChart'.
 le

**Comment by liquidpele** [comment]
multibarchart does not have a forceX function, just forceY... 

http://nvd3-community.github.io/nvd3/examples/documentation.html#multiBarChart

We would welcome pull requests to increase such functionality though!

**Comment by as6325400** [comment]
Why is there no `forceX` method? Is there a specific reason for this?

Or is there an alternative way to achieve the same result?
