### ISSUE TITLE
Legend click from a checkbox

### ISSUE THREAD

**Issue by josephmilla** [novus/nvd3#608]
Okay, so there are 2 components in this. First is a checkbox that has a list of groups. Second is the 3 nvd3 graphs that has different parameters based on the groups listed in the checkbox. I'm wondering how I could trigger a click event from the checkbox such that the parameters showing up in the three graphs are only from the group selected in the checkbox.

The keys for the graphs are the same as the names in the checkbox.

Checkbox:
- A Group
- B Group
- C Group

Graph1 (Ages):
- A Group Age Data Set
- B Group Age Data Set
- C Group Age Data Set

Graph2 (Heights):
- A Group Height Data Set
- B Group Height Data Set
- C Group Height Data Set

Graph3 (Weights):
- A Group Weight Data Set
- B Group Weight Data Set
- C Group Weight Data Set

**Comment by liquidpele** [comment]
You can either disable all but the series data you want to display, or just rebuild the chart itself, up you you :)
