### ISSUE TITLE
multichart legend click does not hide data

### ISSUE THREAD

**Issue by routrahul** [novus/nvd3#610]
I am quite new to d3.js and nvd3 and have found nvd3 a great starting place to build up charts on the go. I however started using the multichart example and have found an issue on that.The multichart example is working perfectly fine when rendering the chart for the first time. If i try to click on the legend and filter the data values the chart redraws but the the data series is not removed. 
I am attaching the screen shot for your reference. 
It would be of great help if anyone could give any pointers on this.
![capture](https://cloud.githubusercontent.com/assets/4100923/3442096/b0894fd6-010e-11e4-820f-b87ca1193f80.PNG)

**Comment by liquidpele** [comment]
should be fixed in latest.
