### ISSUE TITLE
Discrete bar chart columns too wide

### ISSUE THREAD

**Issue by noamtz** [novus/nvd3#612]
Hi,
Is there a way to configure max-with to bars in discrete bar chart?

the problem is when there is only one bar on the chart it is extremely wide.

Thanks!
![image](https://cloud.githubusercontent.com/assets/2631641/3460746/85e98946-021a-11e4-95e5-4b0ec8ae82f8.png)

**Comment by liquidpele** [comment]
Not currently, but we'd welcome pull requests :)
