### ISSUE TITLE
update line chart with additional series

### ISSUE THREAD

**Issue by rahul-desai3** [novus/nvd3#614]
As of now, I am re-drawing the chart by passing the new series along with the old series'. Can we do better? Is there a direct way to do this?

jsFiddle: http://jsfiddle.net/rdesai/vfe2B/39/embedded/result/ (changing values in textbox will update the chart)

**Comment by liquidpele** [comment]
You can add or update a series and then call chart.update().   There are currently issues with removing a series though, just fyi.
