### ISSUE TITLE
y-axis is not displayed for linear graphs

### ISSUE THREAD

**Issue by marksandler2** [novus/nvd3#621]
The  example on linear chart, sets the y-label, it is not however displayed:

http://nvd3.org/livecode/index.html#codemirrorNav

![image](https://cloud.githubusercontent.com/assets/6980056/3560017/d1e3b0c2-0956-11e4-9a19-ac20d668816c.png)

The same y-label is displayed fine on scatter charts.

**Comment by liquidpele** [comment]
Should be fixed on latest version.
