### ISSUE TITLE
Multiple area chart on same page not rendering 

### ISSUE THREAD

**Issue by nileshpgaikwad** [novus/nvd3#624]
Hi,

I am using nvd3.js for area chart creation. As a requirement, we need to create multiple graph on same page, using carousel. We send the data for multiple graphs to function in for loop.
But only first graph is being plotted, rest graphs are show weird. On examining those, it is found few parameters are not received to rest all graphs

same is being observed,  when we implement two graphs on same page, in two different div elements.
![graph](https://cloud.githubusercontent.com/assets/6417868/3597312/5ad852a8-0cd0-11e4-9438-0f355b513300.jpg)

**Comment by liquidpele** [comment]
Multiple graphs per page should work fine, not sure why you'd see this but I suspect the data/options you're passing the graphs isn't quite correct.
