### ISSUE TITLE
Why is my NVD3 Line Chart inverted ?

### ISSUE THREAD

**Issue by Griga123** [novus/nvd3#625]
Hi there,

I'm using ZoomData (vizualisation service) with NVD3.js to add new templates.
I'm facing a problem with the NVD3 Line Chart. I understood the basics, and got it working properly with my data.
In this example, i am using dates on the X axis, and sales (number) on the Y axis.
The problem is my graph is left-oriented, and i have no idea why.
Here is an image of my Line Chart : http://hpics.li/d066e46

I made a JS Fiddle for you to see my basic NVD3 code : http://jsfiddle.net/A2GK4/
What is the problem here ? Is there a way to correctly rotate the chart ?
Thanks !

**Comment by liquidpele** [comment]
You need to sort your data by the x value, otherwise the line jumps back and forth.
