### ISSUE TITLE
nvd3 css svg in global scope

### ISSUE THREAD

**Issue by MartinAmps** [novus/nvd3#628]
Adding the nvd3 css breaks leaflet... See:

http://jsfiddle.net/U97MM/1/
vs 
http://jsfiddle.net/U97MM/0/ 

Adding nvd3.css kills the circle.

Seems to be due to this being declared in a global scope:

svg {
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
  /* Trying to get SVG to act like a greedy block in all browsers */
  display: block;
  width:100%;
  height:100%;
}

**Comment by liquidpele** [comment]
Fixed.
