### ISSUE TITLE
LinePlusBarChart: right axis problem when series disabled

### ISSUE THREAD

**Issue by sasa72** [novus/nvd3#633]
Take a LinePlusBarChart, for example   http://nvd3.org/examples/linePlusBar.html

Disable legend for "Quantity (left axis)" -> the bars and the left axis disappear. OK.

Disable legend for "Price(right axis)" -> the line disappears, but the right axis is still there and has the scale from -1 to 1.

**Comment by liquidpele** [comment]
Fixed in latest version, thanks for reporting!
