### ISSUE TITLE
with-3d-shadow with-transitions tooltips with pieChart

### ISSUE THREAD

**Issue by neilhwatson** [novus/nvd3#637]
Greetings,

I have a piechart and a scatter chart. The pretty tooltips work on the scatter chart, but not on the piechart. Have I done something wrong?

I have this on a pieChart:

        <div id="hosts" class="with-3d-shadow with-transitions">
            <svg></svg>
         </div> 

And this on a scatterPlusLineChart

         <div id="chart" class="with-3d-shadow with-transitions">
                     <svg></svg>
         </div>

**Comment by liquidpele** [comment]
Not enough info here, I con't figure out what his issue is.
