### ISSUE TITLE
Stacked Area Chart demo example doesn't show values correctly within a tooltip in an 'expanded' (percentage) mode.

### ISSUE THREAD

**Issue by ovvn** [novus/nvd3#641]
I'm looking at the demo example at http://nvd3.org/examples/stackedArea.html and it's not clear for me why doesn't the sum of the values within a tooltip in the 'expanded' (percentage) mode equal to 100?

**Comment by liquidpele** [comment]
the expanded view is just a view, the original values are all displayed in the tooltip still, not the %.
