### ISSUE TITLE
tickFormat can not obtain correct value

### ISSUE THREAD

**Issue by angelazou** [novus/nvd3#644]
All the code is available here, including the dataset https://gist.github.com/angelazou/1d2d389f9cb28397b799

On line 40, when I use the second set of data (data[1]), the tickFormat callback only return value ranging from -1 to 1, in the interval of 0.2, rather than the date string that I have returned in the x function value

    chart.xAxis.axisLabel( xlabel ).tickFormat( function( d ) {
      return d3.time.format( '%Y-%m-%d' )( new Date( d ) ); //Here d is always -1 to 1, why?
    } );

**Comment by liquidpele** [comment]
There are working examples in the examples dir that use tickFormat.... e.g.   chart.yAxis1.tickFormat(d3.format(',.1f'));

Please give a jsfiddle or something demoing the example problem.  Closing for now though.
