### ISSUE TITLE
line Plus Bar With Focus - small graph is not shown

### ISSUE THREAD

**Issue by scoda70** [novus/nvd3#646]
Hi, 
I'm new in d3 and javascript and I have a problem with line Plus Bar With Focus Chart. In example provided by Novus team chart displays both small and big graph. But when I use data from my database it displays only big graph. Even that the small graph is not shown, the focus works.
Could you help me find where is the error?
Here is my code:

d3.json("jsondata.php",function(error,data){   
nv.addGraph(function() {
    var chart = nv.models.linePlusBarWithFocusChart()
        .margin({top: 30, right: 60, bottom: 50, left: 70})
         .x(function(d) { return new Date(d[0]).getTime(); })
         .y(function(d) { return d[1] % 30; })

    chart.xAxis.tickFormat(function(d) {
      console.log(d);
      var dx = d || 0;
      if (dx > 0) {
           return d3.time.format('%d/%m %H:%I')(new Date(dx)); 
      }
      return null;
    });

    chart.x2Axis.tickFormat(function(d) {
      return d3.time.format('%d/%m %H:%I')(new Date(d)); 
    });
    
    d3.select('#chart1 svg')
        .datum(data)
        .transition().duration(500).call(chart);

    nv.utils.windowResize(chart.update);

    return chart;
});
});

**Comment by liquidpele** [comment]
This is really old so closing, if you still have the issue please open a new issue with a working jsfiddle or something showing the issue.
