### ISSUE TITLE
How to disable Legend "on click" interaction / behaviour

### ISSUE THREAD

**Issue by rplxgithub** [novus/nvd3#65]
How to disable legend "onClick" toggle behavior for NVD3 charts?

**Comment by miguelrincon** [comment]
If anyone comes across this tread, in v1.8.1 this will disable the click event.

    chart.legend.updateState(false);

**Comment by anthonysubramani** [comment]
@dsherret Your solution worked for me

**Comment by geethaar09** [comment]
I'm having an issue with nvd3 piechart and need some help.

Initially when my app loads, I register a callback on legendClick --> chart.legend.dispatch.on('legendClick', onLegendClick) which works fine when you click on the legends,etc.

Then,we have a drop down option for selecting a group, which will basically reload the chart with new data. And now I'm calling the same code above on legendClick. But somehow it does not get registered again. So now I get the values from initial load and data will be incorrect. 

I even tried to do this to remove the listener, chart.legend.dispatch.on('legendClick', null) before adding it again. but it did not work.

Has anyone faced this issue?

**Comment by czue** [comment]
https://github.com/novus/nvd3/issues/65#issuecomment-153973280 works great. 

getting greedy, but is there also any easy way to disable the pointer change on hover?
