### ISSUE TITLE
Questions about a drawn chart

### ISSUE THREAD

**Issue by benzmuircroft** [novus/nvd3#650]
How do I access the lines display.y data after a chart has been drawn?

How do I draw on a chart after it has been drawn?

Why am I seeing a large diagonal line on my chart here > http://stackoverflow.com/questions/25606757/nvd3-cumulative-linechart-missing-overall-slope-also-huge-line-appearing

Thanks

**Comment by liquidpele** [comment]
You just save the data objects and can modify them as needed. 

You call chart.update() to update the chart.

No idea without a code example on jsfiddle or similar :)
