### ISSUE TITLE
Dynamic values from function(d) in .forceY()?

### ISSUE THREAD

**Issue by mashdot** [novus/nvd3#651]
Apologies for the poor title but not quite sure how to explain it better.

I am using `nv.models.lineChart()`, and currently have JSON file data providing me with `key` and `values`: `x:` `y:` and extra `z:`.

```
[
    {
        "key": "content001",
        "values": [
            {
                "x": "2014-09-01 17:56:32",
                "y": "7484333047808",
                "z": "11166914969600"
            }
        ]
    },
    {
        "key": "content002",
        "values": [
            {
                "x": "2014-08-27 11:05:01",
                "y": "5355062575104",
                "z": "6657199308800"
            }
        ]
    }
]
```
What I am wanting to do is use `z:` to define the maximum for the yAxis.

I thought I would be able to do something like this:

```
chart.yAxis
   .forceY([0, function(d) { return d.z; }])
```

But this does not work.

Is there a way for me to pull `z:` dynamically so the `forceY` scale changes as I select the series?

The context of all this is that I want to graph volume usage, where `y:` is used volume space out of a total available `z:` volume space. 

The two `content00`'s differ in their total available space, and thus when clicking the control radio button for each series I want `forceY` to change accordingly: `.forceY([0,11166914969600])` and `.forceY([0,6657199308800])`, etc.

Thanks

**Comment by liquidpele** [comment]
forceY takes an array of values, not functions.

**Comment by mashdot** [comment]
Thanks for the replies! Sorry I should have updated this a good while ago. 

In the end I used the following:

````javascript
// Get and set data
var dateFormatIn =  d3.time.format('%Y-%m-%d %H:%M:%S');
var getX = function(d) { return dateFormatIn.parse(d.x); } // valid linear. http://j.mp/1sISLJb
var getY = function(d) { return +d.y / 1000000; } // Convert to Terabytes
var getZ = function(d) { return +d.z / 1000000; } // Convert to Terabytes

// Minipulate data
var xAxisFormatter = function(d) { return d3.time.format("%Y-%m-%d")(new Date(d)); }
var yAxisFormatter = function(d) { return d3.format(",.0f")(d); }

// Create domain ranges from Y and Z
var min = d3.min(data, function(d) { return d3.min(d.values, getY) * 0.2 }); // * 0.8 for bottom padding
var max = d3.max(data, function(d) { return d3.max(d.values, getZ) }); // Using "volume_size_total"

// Create chart
nv.addGraph(function() {
  chart = nv.models.lineChart()
  chart.options({
    x: getX,
    y: getY,
    yDomain: [min,max],
    ...
````
Which gave me this:

![screenshot](https://cloud.githubusercontent.com/assets/679292/6369367/9d6a0a86-bcdd-11e4-89d3-88e73fb3ab30.png)

When I have a chance I'll push up a Git repo of the whole code as an example.

**Comment by Chandru1427** [comment]
Hi I tried the above , but im getting only min max values , not rounded off values like your line chart.
