### ISSUE TITLE
Race condition, null pointer exception on line 11190

### ISSUE THREAD

**Issue by JasonKeirstead** [novus/nvd3#659]
I have a page in which I am drawing many graphs with lots of data. I was finiding that I was getting this null pointer on line 11190 on a regular basis. My investigation found out that the cause was this setTimeout(updateInteractiveLayer, 300) which calls updateInteractiveLayer every 300ms while data is being loaded... if you are manipulating the data model while this is going on, it can result in an NPE.

The fix for this was simple, I just check if 'd" is first define as below. This simple change fixed the exception.

11193c11193

<                 if (!d || d.data.length === 0)
---
>                 if (d.data.length === 0)

**Comment by liquidpele** [comment]
Fixed in latest.
