### ISSUE TITLE
Selections (highlights) in nvd3 charts

### ISSUE THREAD

**Issue by varvarvar** [novus/nvd3#660]
Hello Everybody,

I apologize if asking a question in the wrong place... The question I am deeply concerned about is as follows: is it possible to "highlight" elements, or parts of those elements, in nvd charts? 

By highlighting I mean any kind of distinguishing for the user the appearance of a particular chart element or its part. This can be drawing on top, changing the css class or whatever...

Just to clarify when highlighting makes sense, imagine communicating charts with one chart responding to brush events from another chart.

Highlighting of a part of a chart element can occur, for example, in a bar chart, when a bar correspond to some aggregated value of a group and selection represents part of this group.

**Comment by liquidpele** [comment]
This is not a current feature but if you want to create it and send us a pull request that would be awesome.  Cheers.
