### ISSUE TITLE
Incorrect size of data points on scatter plots

### ISSUE THREAD

**Issue by weaksauce** [novus/nvd3#667]
Math.random() in all the examples **seem** to work ok but the first point/group is always a small point.
In addition I have found that when the size of the point does not change from group to group or stays static from the last point, the size is not respected. 

tested on my system with 5 groups each with 1 point in them. adding an extra point to the beginning allows the chart to work correct but there is a points at the origin that are the default size. 

```javascript
chartdata[<%= i %>].values.push({
                        x: <%= concept[:s] %>
                      , y: <%= concept[:r] %>
                      , size: 0.8<%= i+2 %>2
                      , shape: '<%= ['circle', 'cross', 'triangle-up', 'triangle-down', 'diamond', 'square'][i%6] %>'  //Configure the shape of each scatter point.
                 });
```
changing that to 
```javascript
chartdata[<%= i % >].values.push({
                        x: 0.0
                      , y: 0.0
                      , size: 0.00000000000000000001
                      , shape: 'circle'
                 });
chartdata[<%= i %>].values.push({
                        x: <%= concept[:s] %>
                      , y: <%= concept[:r] %>
                      , size: 0.8<%= i+2 %>2
                      , shape: '<%= ['circle', 'cross', 'triangle-up', 'triangle-down', 'diamond', 'square'][i%6] %>' 
                 });
```
fixed the point. It's in an erb loop that's why there are <%= %> sprinkled throughout. I have verified that the data being generated by the erb system is correct and looks good.

**Comment by liquidpele** [comment]
This is pretty old so closing for now, if it's still an issue with the latest version please reopen but provide an example of the issue in jsfiddle or similar site so we can see it, thanks!
