### ISSUE TITLE
how to add a dark theme?

### ISSUE THREAD

**Issue by majj** [novus/nvd3#669]
when set background-color:#000 and update nv.d3.css:
.nv-legend-text {   stroke: #fff; ...
the text is cloudy
![image 20](https://cloud.githubusercontent.com/assets/543810/4298150/6ec0d41c-3e1b-11e4-86c2-52df20c5e537.png)

**Comment by liquidpele** [comment]
To override css in a style attribute, us the "!important" option in your CSS.   Cheers.
