### ISSUE TITLE
Invalid value for <path> attribute d="" on linePlusBarWithFocusChart

### ISSUE THREAD

**Issue by fontanon** [novus/nvd3#670]
Even on the ```linePlusBarWithFocusChart``` example (```examples/linePlusBarWithFocusChart.html```) , when clicking in the focus area, you can see the following error in the inspector:

```javascript
Error: Invalid value for <path> attribute d="" attrNull
d3.v3.js:7211
```

It seems to be an innocent error, but it affects when you set mouse events on the chart. As an example, try to include the following code before ```return chart;``` (remember to include jquery library too):

```javascript
    $(".nv-bar").click(function (e) {
      console.log (e.target.__data__);
    });
```
It reports the x,y values when clicking on the bars, but after clicking in the focus area and the error raises, mouse events stops working.

**Comment by liquidpele** [comment]
I think I might have fixed this (along with a bunch of other stuff), please check the latest version 1.7.1 and see if you still have any issues... closing for now, please re-open if needed :)
