### ISSUE TITLE
Lines in lineChart are not removed until chart is updated manually

### ISSUE THREAD

**Issue by alleroux** [novus/nvd3#672]
I'm using a lineChart to generate a chart.  Multiple lines can be added to the chart.  When I attempt to remove the lines by modifying the datum the chart doesn't update immediately.  I have to call the update function to get the chart to update.  Is this as designed or is there another way I should be doing this?  I tried with the latest dev branch code to make sure the issue wasn't addressed already.

**Comment by liquidpele** [comment]
Interesting... hey everyone else, is it supposed to do that?  I didn't even think it was supposed to add new lines unless you called chart.udpate()

**Comment by robinfhu** [comment]
This is how it is supposed to work. chart.update() must be called after modifying the data.  This isn't like angularJS where there is two way data binding.
