### ISSUE TITLE
Series selection lost on data update in mutiChart

### ISSUE THREAD

**Issue by mickours** [novus/nvd3#675]
Hi,
I have a multiChart graph and when I update the data the series selection (made with clicks the legend) is lost.
The data update is made with this function:
```
d3.json('gui_data.json', function(error, data) {
    if (error) return console.warn(error);
    d3.select('#chart1 svg')
        .datum(data)
        .transition().duration(500).call(chart);
  });
```
Is there any way to conserve the selection state over the update or is it a kind of bug?

**Comment by liquidpele** [comment]
Don't re-bind via datum, just update the object data itself and call chart.update().  As-is, you're re-building the whole chart from scratch which is why it resets.
