### ISSUE TITLE
ShowValues(True) On horizontalbarchart but not standard multi bar chart

### ISSUE THREAD

**Issue by engy123** [novus/nvd3#676]
I was wondering if anyone could advise why the horizontal bar chart is capable of showing values at the top of the bars, whilst the standard multi bar chart is not? They are both exactly the same just rotated a little, is there anything I can do to get it to work? As soon as I put in showvalues(true) it doesn't load up.

Thanks

**Comment by liquidpele** [comment]
Yea, looks to be a missing option there... Implement it and send us a pull request :)

**Comment by robinfhu** [comment]
Not necessarily a missing option; it's missing by design. For a multi-bar chart it's hard to show values on top of each bar without things overlapping.  Unless you rotate the labels vertically?  See what I mean?   If you find a cool solution submit a PR and let us know.
