### ISSUE TITLE
Stacked Area Chart brakes if data arrays aren't the same size

### ISSUE THREAD

**Issue by brunomperes** [novus/nvd3#681]
To replicate the bug (can be done on the Live Code):
- Remove one element of any of the array "values"

The chart won't be generated and the console outputs:
```
Uncaught TypeError: Cannot read property 'y' of undefined       nv.d3.js:13406
```

The version is the same available on the Live Code, 1.1.11b. Though it also happens on 1.1.15b, on line nv.d3.js:13473

I suggest to use a value 0 if no value is given on the data set

**Comment by liquidpele** [comment]
Please test with the latest code, I fixed a lot of stuff around multichart, thanks!   Closing for now, pelase re-open if it's still an issue!   :)
