### ISSUE TITLE
Line chart: single point is not shown when set xDomain/forceX and yDomain/forceY

### ISSUE THREAD

**Issue by abhishekkasera** [novus/nvd3#684]
In line chart, single point is not shown when set xDomain/forceX and yDomain/forceY. 
Is there is any option to show a single point in graph?

**Comment by liquidpele** [comment]
single point should be working in latest code :)

**Comment by adishap** [comment]
If their is single point on chart and we have applied forceY on graph it is invisible we need to hover on it to see the point. 

```
            nv.addGraph(function() {
                var chart = nv.models.lineChart()
                    .useInteractiveGuideline(true)
                    .showLegend(true);

                //calculate the xScale
                var xScale = chart.xAxis.scale();
                chart.forceX([xScale(new Date(startDate)), xScale(new Date(endDate))]);
                chart.forceY([0, 100]);

                chart.xAxis.axisLabel("Date").tickFormat(function(d) {
                    return d3.time.format('%d/%m/%y')(new Date(d))
                });

                chart.yAxis.axisLabel("percentage (%)")
                    .tickFormat(d3.format(","));

                d3.select('#chart svg')
                    .datum(chartData)
                    .call(chart);

                //Update the chart when window resizes.
                nv.utils.windowResize(function() { chart.update() });
                return chart;
            });
```

@liquidpele [commented](https://github.com/novus/nvd3/issues/684#issuecomment-73637957) in issue([#684](https://github.com/novus/nvd3/issues/684)) that it should work with latest code and I am using latest build of nvd3.

One more solution I found was http://stackoverflow.com/questions/39696320/single-point-not-shown-in-nvd3-line-chart . but it says if `data.length === 1` than remove forceY. But In my use case I need to show y axis from 0 to 100. Is their any other possible solution?
