### ISSUE TITLE
Stacked area chart

### ISSUE THREAD

**Issue by fshort** [novus/nvd3#694]
Using the stacked area chart with date/time on the X axis. When you mouse over a section, the tootip date doesnt match the date in the x axis. This is demonstrated in the existing example here: http://nvd3.org/examples/stackedArea.html

mousing over data around 11/09/2004 on the x axis shows data a month before or after. Generally, seems that the values displayed along the x axis dont accurately represent the data at that point in the chart.

**Comment by liquidpele** [comment]
Seems fine to me...
