### ISSUE TITLE
Bar chart spacing not even

### ISSUE THREAD

**Issue by andrewtnisbet** [novus/nvd3#698]
I am having a problem with the bars in a bar and line graph not being spaced evenly for certain smaller data sets.  Larger sets seem to work fine(first two are data sets with problems, third is a larger data set that is working as expected)

![screen shot 2014-10-14 at 11 23 20 pm](https://cloud.githubusercontent.com/assets/8950119/4640878/70c3f15a-542c-11e4-9d38-d003483ab336.png)
![screen shot 2014-10-14 at 11 26 58 pm](https://cloud.githubusercontent.com/assets/8950119/4640879/7268da3e-542c-11e4-8705-f8e14d108797.png)
![screen shot 2014-10-14 at 11 24 34 pm](https://cloud.githubusercontent.com/assets/8950119/4640881/769f59fc-542c-11e4-9313-b5a25b59a9ba.png)

My options are set up as follows:

    graphOptions = {
        chart: {
          type: chartType,
          height: height,
          width: width,
          margin : {
            top: 0,
            right: 50,
            bottom: 50,
            left:  50
          },
          color:[
          '#c7c7c7',
          '#ff7f0e'
          ],
          x: function(d){ return d[0];},
          y: function(d){ return d[1];},
          xAxis: {
            showMaxMin: true,
            tickFormat: function(d) {
              var newDate = new Date(d);
              var xDate = '';
              if (xGraduation === 'monthly')
              {
                xDate = d3.time.format('%m/%y')(newDate);
                //xDate = d3.time.format('%x')(newDate);
              }
              else
              {
                xDate = d3.time.format('%x')(newDate);

              }
              return xDate;
              },
            staggerLabels: true
          },
          y1Axis: {
            axisLabel: y1Label,
            tickFormat: function(d){
              return  y1Graduation + d3.format(',.2f')(d);}
          },
          y2Axis: {
            axisLabel: y2Label,
            tickFormat: function(d) {
              return y2Graduation + d3.format(',.2f ')(d);
            }
          }
        }
      };

using  
  "angular-nvd3": "~0.0.9",
  "d3": "~3.3.13"

I have tried adjusting the width of the chart, but that doesn't seem to make any difference.  If anyone has any guidance on other things I could try, I would really appreciate it.  

Thanks.

**Comment by robinfhu** [comment]
It is probably this line that is causing the problem:
x: function(d){ return d[0];}

If the x-values are not evenly spaced, the bars won't be either.  The only way to get evenly spaced bars is to return the "index" in your x accessor function, like this:

x: function(d,i) { return i;}
