### ISSUE TITLE
reduceXticks in all models

### ISSUE THREAD

**Issue by tomasz-tomczyk** [novus/nvd3#70]
For graphs with dates on X-axis, in a short date range, the dates may repeat for multiple ticks. I believe reduceXTicks on multiBarChart model resolves this, but it's not implemented in multiChart or lineChart models and most others.

It was discussed here: http://stackoverflow.com/questions/14799511/how-can-i-keep-tick-marks-from-repeating-when-i-have-a-small-number-of-dates-on but I was wondering if there's a simpler solution of porting this function to other models?

**Comment by liquidpele** [comment]
ticks should not have repeated values anymore as of 1.7.0.

**Comment by oravecz** [comment]
I take it there is no support added for the kinda side request in this thread?
```
.ticks(d3.time.minute, 15)
```

**Comment by liquidpele** [comment]
You can do chart.xAxis.ticks(...) and it just passes it to d3. 

https://nvd3-community.github.io/nvd3/examples/documentation.html

https://github.com/novus/nvd3/blob/master/src/models/axis.js#L52

**Comment by scrayWC** [comment]
Hello there, I am using NVD3 line charts and have been trying to use chart.xAxis.ticks(d3.time.day,1) to set stop the ticks from duplicating the dates I formatted for the x axis and it is not doing anything. But when I go into axis.js and set line 61 to axis.ticks(d3.time.day,1) it works just fine but it messes with the other charts as well. Trying to figure out away to customize it to just one chart. I thought me adding chart.xAxis.ticks to the chart in use in the controller would do the trick. Could someone please help me to figure out why this is not be working?
