### ISSUE TITLE
Sort x-axis in horizontal multibar chart

### ISSUE THREAD

**Issue by Martin1887Privado** [novus/nvd3#700]
I'm working in a sorted horizontal multibar chart. I.e., a chart sorted with values from highest to lowest. This works ok if you put data in order in a serie, however, with two or more series the data is not reordered and also labels that are present in second serie but not in first are shown the last.

Is it possible sort data correctly, putting data that are present only in last series sorted among data of first serie? If not, is it possible implementing it?

Thanks.

**Comment by robinfhu** [comment]
I don't understand your request.  Can you please upload some diagrams explaining what you mean and then re-open this. Thanks.

**Comment by Martin1887Privado** [comment]
Sorry, I fixed it restructuring data array before calling chart, I though that I had commented it. Issue is correctly closed.
