### ISSUE TITLE
Large count of legend items

### ISSUE THREAD

**Issue by rbelmega** [novus/nvd3#701]
Is there any possibility to display a large count of legend items? Because for now if we have such situation we can see only legend with a little-little chart

**Comment by liquidpele** [comment]
Yea, I think the legend should handle more items than it currently does.   As I said in a similar issue brought up in nvd3-community, I think after a certain number the legend should hide the label text and display it on hover over the dots or something.   However, keep in mind that there are only so many colors that look different so too many data points is going to be confusing... ideally you need to break your data up in a more reasonable way.

**Comment by robinfhu** [comment]
I mean, how much is "large count"?  Do you think the below chart is reasonable?
![pie with lots of legend](https://cloud.githubusercontent.com/assets/3769532/6120705/231053fe-b0a7-11e4-920c-9b68ead6ae3a.jpg)

Visualizations should have meaningful limits.

**Comment by vineelal** [comment]
Can we limit the legends count,  in the above example you have 30 legend. Can we limit only legend to 5 ? And how can we achieve that ?

**Comment by liquidpele** [comment]
Currently the you can disable the whole legend, but it's kind of silly to only show some items in the legend but not everything.  If you have an idea to make the legend handle large numbers of series better send us a pull request :)

**Comment by jlherren** [comment]
I don't think it's silly at all to limit the legend. I have a pie chart where I'd like to add a legend for the 15 largest slices and the rest will just have the tool tip.

**Comment by liquidpele** [comment]
Perhaps a compromise is to have an attribute on the series that says to NOT show it in the legend, so that someone could specifically do this if they wanted but the default would be to show them all.

**Comment by jlherren** [comment]
Sounds like the best and most flexible solution to me.

I also noticed that I'm unable to restrict the legend's size on my pieChart with chart.legend.height(10), it seems to do nothing at all.
