### ISSUE TITLE
Tooltip rendering has slowed down considerably with new chrome version (v38)

### ISSUE THREAD

**Issue by sherinkurian** [novus/nvd3#702]
Hi,

Our line charts that don't use interactive-guideline has slowed down considerably with the latest chrome upgrade (version 38). The tooltips take a good 15 seconds and over before they show up. I can repro this problem on the nvd3 examples page too - http://nvd3.org/examples/lineWithFocus.html. We have tried chrome 37 and chrome 38 on Mac 10.9 and the graphs work fine with chrome version 37 but very slow with 38. 

Is anyone else having this problem?

Thanks!
Sherin

**Comment by liquidpele** [comment]
Should be fixed in latest novus version.

**Comment by venu-gande** [comment]
I had the same problem. I just stopped using voronoi for tooltip.. Everything works fine now ..

**Comment by liquidpele** [comment]
Should be fixed in latest nvd3 version 1.7.x+, thanks!
