### ISSUE TITLE
Shadow DOM issues

### ISSUE THREAD

**Issue by naunga** [novus/nvd3#703]
The tooltips do not render correctly due to styles being encapsulated and because the logic placing tooltip containers within the DOM does not account for the fact that chart's parent element may be within a shadow DOM. 

Encountered these issues while working on a Polymer element to encapsulate nvd3 charts. You can take a look at that project here: https://github.com/naunga/polychart-element

**Comment by liquidpele** [comment]
You'll need to send us a pull request  that handles only the issue itself
