### ISSUE TITLE
trouble in refactor/2.0.0-dev

### ISSUE THREAD

**Issue by elroliv** [novus/nvd3#708]
Hello,
i have just test your dev branch and i have seen a trouble in main nvd3.js file.
This file is almost blank and it is used in your examples.
-------
3 lines (2 sloc) 0.019 kb
(function(){
})();)
--------
that's why html pages render is white in example but when i change link to minified file, it's look fine.

i hope it's help you.

https://github.com/novus/nvd3/tree/refactor/2.0.0-dev

**Comment by liquidpele** [comment]
new version should be fixed, thanks for reporting!
