### ISSUE TITLE
Arcs in numbers in pie chart

### ISSUE THREAD

**Issue by Martin1887Privado** [novus/nvd3#709]
When show numbers outside pie chart it is difficult visualize them and they overlap when series are little in percentage the entire chart. This should be solved joining the numbers with an arc and putting them further.

There is a threshold to not showing low values, but this solution is incomplete because low numbers are also important.

Thanks a lot.

**Comment by liquidpele** [comment]
Please send us a pull request if you're interested in modifying the current behavior, thanks!
