### ISSUE TITLE
date range slider issue for linewithfocus chart

### ISSUE THREAD

**Issue by madasuk** [novus/nvd3#711]
I am facing problem with Date Range Slider for linewithfocus chart. I have applied all possible fixes from the discussion (http://stackoverflow.com/questions/26251727/nvd3-chart-strange-behavior-with-date-range-slider/26638343?noredirect=1#comment41909680_26638343) but still date range slider is not working correctly. Please see my plunker at http://plnkr.co/edit/2te6QVmErJpmUIBgYJEA?p=preview. Is there any solution to this?

**Comment by robinfhu** [comment]
See the example we have in the examples/ folder. There is a working chart there. No reason why this shouldn't work.
