### ISSUE TITLE
Linechart interactive tooltips weird issue

### ISSUE THREAD

**Issue by TonyWael** [novus/nvd3#712]
Hi!
I'm using your library to generate a linechart, and gave some data:
![screen shot 2014-10-31 at 13 39 44](https://cloud.githubusercontent.com/assets/3015633/4860694/095d9116-60fb-11e4-8ffd-31be132cf892.png)

![screen shot 2014-10-31 at 13 40 25](https://cloud.githubusercontent.com/assets/3015633/4860701/1d788be2-60fb-11e4-94fb-6fe1022fae03.png)

# The problem is, the interactive guideline shows up like this (specifically note the tooltips):

![screen shot 2014-10-31 at 13 35 10](https://cloud.githubusercontent.com/assets/3015633/4860813/5468ee16-60fc-11e4-84d9-4ae86dad2454.png)

![screen shot 2014-10-31 at 13 35 19](https://cloud.githubusercontent.com/assets/3015633/4860823/81317ca6-60fc-11e4-852d-2c0a67b4b163.png)
Note that I only get a tooltip at the start and end of the linechart.

# Now, I set `useInteractiveGuideline(false)`

![screen shot 2014-10-31 at 13 34 59](https://cloud.githubusercontent.com/assets/3015633/4860829/91bba0e2-60fc-11e4-947a-193678b5cf52.png)

This DOES show up correctly, but is very laggy and I'd like to use `useInteractiveGuideline(true)`.

Is this a bug in my code, or a bug in your code?

Thanks in advance!

**Comment by liquidpele** [comment]
This bug should be fixed in the latest novus version now, please re-open if you have further issues, thanks for reporting!
