### ISSUE TITLE
Legend overlapping text: Why keys are mangled?

### ISSUE THREAD

**Issue by umrashrf** [novus/nvd3#713]
I can't seem to figure out what's wrong with this. The same functionality with different string input yields different visualization for keys.

Bad: http://jsfiddle.net/gdj2yrtj/8/embedded/result/
Good: http://jsfiddle.net/gdj2yrtj/11/embedded/result/

**Comment by robinfhu** [comment]
It's weird. I think the key being mangled is too long of a string, and our code is somehow not handling that right.  Workaround for now is to just shorten the key to something else.

**Comment by robinfhu** [comment]
For a workaround right now, add this line:

       chart.legend.align(false);
