### ISSUE TITLE
lineChart is missing the rotateLabels method

### ISSUE THREAD

**Issue by raphaelcruzeiro** [novus/nvd3#718]
Currently, it's not possible to rotate the line chart's labels on 1.1.15 (the same problem applies to 2.0 if I am not mistaken). This can easily be solved by implementing the same existing logic from the other charts.

I can send a PR for 1.1.15 if the maintainers are willing to merge it.

**Comment by robinfhu** [comment]
lineChart.xAxis.rotateLabels(90);
