### ISSUE TITLE
Difference between supported browser on home page and README

### ISSUE THREAD

**Issue by DanielApt** [novus/nvd3#722]
On the [home page](http://nvd3.org/) it is mentioned that IE10 is supported (and no mention of IE9).

In the [README.md](https://github.com/novus/nvd3/blob/master/README.md) it is mentioned that *IE9* and IE10 are supported.

This should be consistent, and I'd assume that support for IE9 has been dropped (at least the homepage doesn't work for me in IE9).

Happy to change once I get a confirmation which one is correct.

**Comment by robinfhu** [comment]
Thanks for letting us know!
