### ISSUE TITLE
Is there a way to get the chart to increase the max y tick so that it is a tick higher than the max value?

### ISSUE THREAD

**Issue by cmb0335** [novus/nvd3#725]
For example if the following are the y values:

[22, 53, 62, 95]

The tick values are something like:

[0, 10, 20, 30, 40, 50, 60, 70, 80, 90]

Is there anyway to make it go to the next tick value so that the chart is not maxed at 95? i.e. 100?

**Comment by robinfhu** [comment]
All charts should have a 'forceY' option.  This is defined in scatter.js.  You can specify values that are forced onto the y-scale.

**Comment by robinfhu** [comment]
Example:
lineChart.forceY([95])

**Comment by Craicerjack** [comment]
@robinfhu the `multiChart()` does not seem to have this option. Throwing a `chart.forceY is not a function` error

**Comment by liquidpele** [comment]
Indeed. 

https://nvd3-community.github.io/nvd3/examples/documentation.html#multiChart
