### ISSUE TITLE
Misaligned div contents in website [gh-pages]

### ISSUE THREAD

**Issue by sudheesh001** [novus/nvd3#728]
![screen shot 2014-11-25 at 7 21 31 pm](https://cloud.githubusercontent.com/assets/4545925/5183797/3907979a-74d8-11e4-93e2-2e4583355cfd.png)

The screenshot above describes the problem, after the `<h2> Getting Started </h2>` the div that has the content regarding the getting started has a division segment coming out from the left side of the seemingly left border line and is denoted with a lighter color, where as the same pattern hasn't been followed for the content present in `About NVD3` section.

A really good option would be to align the heading and the content together in one line or to follow the standard where the headings are placed outside the  `<div>` so that the paper fold effect can be obtained. Also it'd be great if the footer containing the copyright is center aligned on the page.

If this is a issue that'd require fixing, i'd love to volunteer to fix it. @robinfhu

**Comment by robinfhu** [comment]
Thanks, not necessary right now though.
