### ISSUE TITLE
Error: Invalid value for <rect> attribute y="NaN", height="NaN" 

### ISSUE THREAD

**Issue by kawanet** [novus/nvd3#73]
On MultiBar, in a case y is undefined or null, following errors would be fired.

> Error: Invalid value for <rect> attribute y="NaN"  
> Error: Invalid value for <rect> attribute height="NaN"   

Related (but missing) issue #281: "bars on multibar and discretebar now are 1 px high even if they are 0"

See also: https://github.com/novus/nvd3/commit/cf9bb41be678630a3d4c4ef79cdeb6ac0d1e9e42

**Comment by rxbyes** [comment]
Error: Invalid value for <rect> attribute y="NaN"

**Comment by liquidpele** [comment]
@rxbyes if you can reproduce this error on the latest "development" branch?  Are there reproduction steps?

**Comment by rxbyes** [comment]
this.marketingSearch = function (url, obj) {
        var dt = [];
        $http.get(url).then(function (resp) {
            var result = resp.data.result == null ? [] : resp.data.result;
            for (var x = 0; x < obj.timeData.length; x++) {
                var y = 10;
                for (var i = 0; i < result.length; i++) {
                    if (result[i].time == obj.timeData[x].time) {
                        y = result[i].visit == null ? 0 : result[i].visit;
                        break;
                    }
                }
                dt.push({
                    x: obj.timeData[x].time == null ? 0 : obj.timeData[x].time,
                    y: y
                });
            }
        });
        return dt;
    };
    this.targetType = function () {
        return ['search', 'email', 'internal', 'social', 'unknown'];
    };
    this.targetName = function () {
        return ['查询', '邮件', '内部', '社交平台', '未知'];
    };
    this.marketingReadMultib = function (obj) {
        var targetType = this.targetType();
        var targetName = this.targetName();
        var results = [];
        for (var i = 0; i < targetType.length; i++) {
            var url = 'marketing/getSource?view=trend&source=' + targetType[i] + '&end_time=' + obj.endFormat + '&index=order';
            results[i] = {};
            results[i].key = targetName[i];
            results[i].values = this.marketingSearch(url, obj);
        }
        return results;
    };

**Comment by rxbyes** [comment]
Images can be displayed properly, but the console error ：Invalid value for attribute y="NaN"

**Comment by liquidpele** [comment]
You'll need to provide a jsfiddle or similar page that demonstrates the error.  If I can see it happening then it shouldn't be very hard to fix.  Thanks!

**Comment by rxbyes** [comment]
d3.min.js:1 Error: Invalid value for <rect> attribute y="NaN"
2015-02-28 10:51:43.248d3.min.js:1 Error: Invalid value for <rect>
attribute y="NaN"
2015-02-28 10:51:43.249d3.min.js:1 Error: Invalid value for <rect>
attribute y="NaN"
2015-02-28 10:51:43.249d3.min.js:1 Error: Invalid value for <rect>
attribute y="NaN"
2015-02-28 10:51:43.250d3.min.js:1 Error: Invalid value for <rect>
attribute y="NaN"
2015-02-28 10:51:43.571angular.js:11383 TypeError: Cannot read property '1'
of undefined
    at n (d3.min.js:4)
    at SVGGElement.<anonymous> (nv.d3.js:8712)
    at d3.min.js:5
    at R (d3.min.js:1)
    at Array.Ns.each (d3.min.js:5)
    at Array.chart (nv.d3.js:8687)
    at Array.da.call (d3.min.js:3)
    at SVGSVGElement.<anonymous> (nv.d3.js:9393)
    at d3.min.js:5
    at R (d3.min.js:1)
2015-02-28 10:51:43.599angular.js:11383 TypeError: Cannot read property '1'
of undefined
    at n (d3.min.js:4)
    at SVGGElement.<anonymous> (nv.d3.js:8712)
    at d3.min.js:5
    at R (d3.min.js:1)
    at Array.Ns.each (d3.min.js:5)
    at Array.chart (nv.d3.js:8687)
    at Array.da.call (d3.min.js:3)
    at SVGSVGElement.<anonymous> (nv.d3.js:9393)
    at d3.min.js:5
    at R (d3.min.js:1)

2015-02-28 9:42 GMT+08:00 liquidpele <notifications@github.com>:

**Comment by liquidpele** [comment]
You'll need to provide a jsfiddle or similar page that demonstrates the error.  

For example, here is one using the latest code that shows MultiBarChart.  Just edit this to show the issue.  Otherwise I can't invest the time into looking into this. 

http://jsfiddle.net/8DAQX/3/

**Comment by rxbyes** [comment]
I will now look at a complex scene, thank you!

2015-02-28 11:04 GMT+08:00 liquidpele <notifications@github.com>:

**Comment by BeOleg** [comment]
Still able to reproduce?
was this ever solved?

**Comment by tomhamiltonstubber** [comment]
I can reproduce this and need a solve for it.
