### ISSUE TITLE
TooltipPosition calculated on svg's width or it's parent div's width

### ISSUE THREAD

**Issue by kchojhu** [novus/nvd3#733]
Currently on nv.tooltip.calcToolTipPosition method it calculates the 'y' position based on window's width.  This is a problem when I have to display 2 graphs side by side and I don't want the tooptip eclipsing to other graph.  If svg has been given a width then it should calculate based off on that in my opinion.  Also, thanks for the code!!!!

**Comment by robinfhu** [comment]
We have examples in the examples/ folder of graphs side by side. Can you look to see if the issue is present there?
