### ISSUE TITLE
Bower.json lists incorrect dependency

### ISSUE THREAD

**Issue by MProuts** [novus/nvd3#740]
#### wiki
> You will also need the D3.js library. Use the version in lib/d3.v3.js.

#### lib/d3.v3.js
```js
...
var d3 = {
    version: "3.1.5"
  };
...
```

#### bower.json 
```json
...
"dependencies": {
    "d3": "~3.3.13"
  }
...
```

I believe the wiki is correct.  Installing nvd3 using bower can lead to errors like: 
```
Uncaught TypeError: Cannot read property 'x' of undefined
```

This issue is also documented [here](http://stackoverflow.com/questions/17624111/nvd3-line-chart-uncaught-typeerror-cannot-read-property-x-of-undefined/20994982#20994982).

**Comment by robinfhu** [comment]
Thanks @liquidpele

**Comment by robinfhu** [comment]
I will investigate and make sure the right d3 version is being used.
