### ISSUE TITLE
Add a d3 force-directed graph

### ISSUE THREAD

**Issue by kkasravi** [novus/nvd3#747]
example is here
http://bl.ocks.org/mbostock/4062045

**Comment by liquidpele** [comment]
It's one of the items I've looked at adding to https://github.com/nvd3-community/nvd3, but there are others I'm more interested in doing first... e.g. http://bl.ocks.org/mbostock/4348373

Feel free to add a model and send me a pull request though if you want :)

**Comment by kkasravi** [comment]
Thanks, I'll fork and submit a PR that references this issue.

**Comment by liquidpele** [comment]
Make sure you fork from nvd3-community then, and not this project ;)

**Comment by kkasravi** [comment]
Ah ok. Thanks.

**Comment by IPWright83** [comment]
@liquidpele Any chance you can get the Novus guys to issue a pull request to the readme of this project - directing people to the community version for more info? I always wondered if development had stopped, and it took a bit of digging and jumping to discover the community one.

**Comment by kkasravi** [comment]
created the issue here https://github.com/nvd3-community/nvd3/issues/40
