### ISSUE TITLE
Expand x-axis for the future data

### ISSUE THREAD

**Issue by LeoAref** [novus/nvd3#748]
I have an API returns data about the people count for this week, and the API returns data for the elapsed days only.

I want to make x-axis display 7 days, and without making the remaining days in this week with "zero" values.

I want to make something like that...
![line-chart](https://cloud.githubusercontent.com/assets/6577222/5720132/903e3a16-9b28-11e4-8089-34711d3bfbf9.png)

**Comment by jozefvaclavik** [comment]
Yeah, you wanna be playing with xDomain and xRange.. These values are set up by default from your data, but in most of the graphs you can override them.. Just play with them and you will see how it works..

**Comment by LeoAref** [comment]
@jozefvaclavik OK, I'll try to play with them and see if that do what I want, Thanks.

**Comment by LeoAref** [comment]
@jozefvaclavik , can you please help me with controlling the chart grid
I want to show grid x-axis with the same number of the values, so if the chart displays 10 values on x-axis >> grid has 10 vertical gray lines.

**Comment by robinfhu** [comment]
@LeoAref yes, you can modify the data to contain 'null' values for the future points.  I believe 'null' is ignored by the line chart.
