### ISSUE TITLE
RE: Stack/Stream/Expanded Chart

### ISSUE THREAD

**Issue by NSudhir** [novus/nvd3#749]
Hi i have a problem in rendering this chart. We are using analaytics api in our organization.Pulling the data from reports in sales force and displaying the data in the charts. I do no how to send a data in to a report which is of this structure    
date	           IE	       Chrome	Firefox	Safari	Opera
11-Oct-13  41.62	  22.36	  25.58      9.13	  1.22
11-Oct-14  41.95	   22.15	   25.78	8.79	          1.25
So if you guys have any experience on this can you share the code for me.
Thanks.

**Comment by robinfhu** [comment]
There are examples in the repository.  Those should explain how to format the data for the chart.
