### ISSUE TITLE
 Is it possible to set minimum width of bar for MultibarHorizontal chart? 

### ISSUE THREAD

**Issue by HareramKumar** [novus/nvd3#750]
Hi
Is it possible to set minimum width of bar for MultibarHorizontal chart? What I mean is if I have values like 1000 for one stack and 4 for next stack, then 600 for next stack on same bar in that case 4 appears with very thin bar. So is it possible to set a minimum width like 20 or so?

Like in this example below you can see 4 or 3 are appearing with very thin bar, which is not visible for the user.

![image](https://cloud.githubusercontent.com/assets/10562036/5777257/a5c65fae-9db6-11e4-82d8-065ebddb19eb.png)

**Comment by robinfhu** [comment]
It's not possible now, but perhaps you can handle this yourself?  You need to preprocess your data so that very small values have a minimum value.
