### ISSUE TITLE
Line color as gradient?

### ISSUE THREAD

**Issue by hurricanemichael** [novus/nvd3#751]
Using nv.models.linechart, is it possible to set the color of a line to a gradient instead of a static color?

For example, in D3, http://bl.ocks.org/mbostock/3969722 (Gradient Encoding) allows this.  

Essentially, I want my line to be red above a Y value, and Blue below the same Y value.  

Any help would be greatly appreciated.

**Comment by robinfhu** [comment]
This feature not supported at this time.
