### ISSUE TITLE
Interactive Bisect code broken for d3 3.5

### ISSUE THREAD

**Issue by robinfhu** [novus/nvd3#754]
These tests currently break in the development branch:

     ✗ accessor in index mode - existing item
	expected 1 to equal 7

      ✗ accessor in index mode - inbetween item 1
	expected 1 to equal 7

      ✗ accessor in index mode - inbetween item 2
	expected 1 to equal 8

Question: why doesn't this code work with d3 v3.5?

**Comment by portante** [comment]
I think because of https://github.com/mbostock/d3/wiki/Arrays#d3_bisector.

Bisector now considers the given function as an accessor if it has one parameter and as a comparator if it has two, and we always use two.

Will post a proposed fix.

**Comment by robinfhu** [comment]
Yes I just saw: https://github.com/mbostock/d3/commit/3c7cc81b6233289263525b581d635ad9f8d9dd37

This screws up my logic.  Yeah would love to see a fix.

**Comment by portante** [comment]
@robinfhu, if you have a better solution, I'm all ears, but it appears that D3 broke the API contract as of v3.4.4.

**Comment by portante** [comment]
@robinfhu, looks like we can close this one now.
