### ISSUE TITLE
Replace tooltip position utility functions with d3.mouse(container)

### ISSUE THREAD

**Issue by benderTheCrime** [novus/nvd3#768]
We can trim ~100 lines of code from the tooltip code and still product the expected result by performing all necessary positioning using d3.mouse on the container and then transforming using the gravity and distance. This is to some extent related to https://github.com/novus/nvd3/issues/765. I have  sneaking suspicion this has something to do with performance. Happy to make a commit/PR reflecting this change if everyone feels it is an improvement.

**Comment by robinfhu** [comment]
Submit a PR with your fix, and if things still work in all the browsers we'll accept it.

**Comment by liquidpele** [comment]
I'm a bit curious about this, since we've had a lot of reports of the tooltip positioning not working in all cases.  Can you make a pull request or at least an example of how this would work and what makes it a better solution?
