### ISSUE TITLE
Tooltip doesn't work with MultiBarChart or LineChart in mobile app build over Ionic

### ISSUE THREAD

**Issue by gopalyadav5** [novus/nvd3#769]
Currently I am using MultiBarChart and LineChart of nvd3 library . Everything works fine on web browser but tooltip does not work in hybrid mobile app which is build over Ionic Framework.

There should be a way to call tooltip on touch events or tap event or clicking event.

**Comment by liquidpele** [comment]
tooltip works fine on my android.

**Comment by gopalyadav5** [comment]
It is not working on Iphone / Ipad.

I am building an application for IOS and I have tested it but tooltip doesn't seems to work on it.
It would be a great help if you can look around it.

**Comment by liquidpele** [comment]
let me find my ipad and check...

**Comment by liquidpele** [comment]
Also works fine on my iPad using safari

**Comment by joshjordan** [comment]
@gopalyadav5 can you help us find a more specific, reproducible case? A
jsfiddle would be ideal.

**Comment by gopalyadav5** [comment]
@liquidpele Well, yes tooltip works fine on browser i.e, safari / chrome / mozilla.
If you are creating nvd3 multibar chart using plain nvd3 components, like you are creating HTML using nvd3 library. Then, yes its working on browser.

But, what exactly I am doing is that I am building a hybrid App using cordova to build the application. So, after building the application and installing the file (.apk / .ipa) , tooltip does not seems to work as the clicking events is not supported with tooltip for multibarcharts. 
MouseHover and MouseOut events are called to show and hide the tooltip for Multibarcharts , which certainly does not work in mobile apps. 

I think, now you can figure out my point.

**Comment by joshjordan** [comment]
You're right - nvd3 does not support tap events for tooltips. We'd welcome
a pull request that supported the cases you're seeing. You can open a PR
even in its early stage if you want to use it as a starting point for a
conversation about how it sohuld work.

**Comment by liquidpele** [comment]
Someone submitted some code that I think probably does this for pie charts, but I never finished reviewing it... something to start with perhaps? 

https://github.com/nvd3-community/nvd3/pull/19

**Comment by Serveurperso** [comment]
Hello, tooltips never work on any browser if I use a basic linegraph with a timeFormat like this :
````
        chart.lines.xScale(d3.time.scale());
        var timeFormat = d3.time.format('%H:%M:%S');
        chart.xAxis
            .showMaxMin(false)
            .tickFormat(timeFormat)
        ;
````

if I remove timeFormat tooltips work

**Comment by udaykanth3** [comment]
how to display values(x,y) on the line chart graph using NVD3...with out tooltip ...i wnt to see the values on the graph ..in ipad ?? if possible reply me ...

**Comment by liquidpele** [comment]
Line chart does not currently support showing values besides tooltips.  Tooltips should work on the iPad though.

**Comment by udaykanth3** [comment]
k..fine any other way to display values on the line chart ..using NVD3..without elementMouseout,elementMousein ....directly i wnt to display the (x,y) point on the graph..plzz if any knws message me ....
