### ISSUE TITLE
multiBarChart or multiChart with focus

### ISSUE THREAD

**Issue by vishal1shukla2** [novus/nvd3#770]
Is it possible to have focus area like lineWithFocusChart & linePlusBarWithFocusChart. I would like to propose this feature if this is not possible already.

**Comment by liquidpele** [comment]
It is not currently implemented, but feel free to code it up and send us a pull request!   We rely on a lot of community enhancement submissions :)

**Comment by vishal1shukla2** [comment]
Sure. I am not expert JS developer, but I managed to get this working with just couple of small glitches, I am sure these would be pretty small fix for other contributors. Is it possible to send pull request for code in such state?

**Comment by joshjordan** [comment]
Please do send the pull request. We can help you get it into an acceptable
state.

**Comment by vishal1shukla2** [comment]
Pull request #778. Thanks.
