### ISSUE TITLE
Scatter Charts: Axes Look and feel completely changed

### ISSUE THREAD

**Issue by robinfhu** [novus/nvd3#773]
Okay, so I am starting to discover just how much has changed with NVD3.  @liquidpele , can you shed some light as to why our scatterChart look and feel changed so dramatically? The images were taken from test/ScatterChartTest.html

Old version (1.2)
![screen shot 2015-02-10 at 4 47 50 pm](https://cloud.githubusercontent.com/assets/3769532/6137189/f0f4479c-b144-11e4-8608-47f23eb82616.png)

New version (master branch)
![screen shot 2015-02-10 at 4 49 22 pm](https://cloud.githubusercontent.com/assets/3769532/6137191/f427b6d8-b144-11e4-8794-a5ffad42568d.png)

Why are there so many axes lines missing?  What happened to the xPadding and yPadding options?  Thanks.

**Comment by liquidpele** [comment]
so...   the xPadding and yPadding... I'm confused, they seem to vanish between commit 847a4bfa2319814f912e4f8ee8342eee31459b4d and 446e285f66965bf23e1e304c457fa6de7761571d but github doesn't show the commits as removing those!   Very strange... 

https://github.com/novus/nvd3/commit/847a4bfa2319814f912e4f8ee8342eee31459b4d
https://github.com/novus/nvd3/commit/446e285f66965bf23e1e304c457fa6de7761571d

https://github.com/novus/nvd3/blob/446e285f66965bf23e1e304c457fa6de7761571d/src/models/scatterChart.js
https://github.com/novus/nvd3/blob/847a4bfa2319814f912e4f8ee8342eee31459b4d/src/models/scatterChart.js

am I missing something?

**Comment by robinfhu** [comment]
@liquidpele , it may have been accidentally removed during a merge conflict.  We need to bring it back at some point.  I volunteer to take care of it since we need it in our software.

**Comment by robinfhu** [comment]
The axes tick spacing also bothers me, don't know why that change happened.

**Comment by liquidpele** [comment]
Hmm, I don't recall changing the axis for the scatter chart... at least not intentionally...

**Comment by robinfhu** [comment]
I'm sure with a little digging we can find the commit that made the change.

**Comment by robinfhu** [comment]
It's probably related to: https://github.com/liquidpele/nvd3/commit/a37473e7f5d55d6311b5384e8c8296fef9a294c9

**Comment by robinfhu** [comment]
Okay, found solution to the axes issue.  If I just override xAxis.ticks to something like '10', it works.

See screenshot of what I want:
![scatter chart with axes](https://cloud.githubusercontent.com/assets/3769532/6241777/04967048-b6f1-11e4-9064-e850c9a5313e.jpg)

**Comment by robinfhu** [comment]
As for xPadding and yPadding, I'm okay with leaving that option out.  There are ways you can fiddle around with scatter.xDomain and scatter.yDomain to get the padding effect.
