### ISSUE TITLE
Pie Chart is completely disturbed when there are more legends

### ISSUE THREAD

**Issue by vineelal** [novus/nvd3#776]
![piechart](https://cloud.githubusercontent.com/assets/4658864/6142797/a0d7d130-b1e3-11e4-9598-d6d104786402.jpg)

**Comment by vineelal** [comment]
In the following pie chart we have too many legends, so the chart is plotting too small. This issue is very crucial.

**Comment by joshjordan** [comment]
What do you expect the legend to do in this case? This seems like
reasonable behavior, given the parameters you passed to nvd3. To make the
visualization more useful, I'd expect that you need to bucket the values
into logical groupings.

**Comment by robinfhu** [comment]
Closing, this request isn't reasonable at this time.
