### ISSUE TITLE
Scatter Chart: Legend clipping past margin

### ISSUE THREAD

**Issue by robinfhu** [novus/nvd3#777]
To reproduce, checkout the 'development' branch, run 'grunt', and open test/ScatterChartTest.html.
I recorded a video of the issue:
![scatter chart legend bug](https://cloud.githubusercontent.com/assets/3769532/6151605/f90db918-b1e4-11e4-927d-0412596b2e68.gif)

It seems the scatter legend is clipped.  When you click on the legend, or update the chart another way, the legend appears in the right location.

**Comment by portante** [comment]
@robinfhu, do the examples load the proper css file?

**Comment by robinfhu** [comment]
@portante it is, I made sure to have grunt copy src/nv.d3.css to the build/ folder.  It looks like this is a chart model coding issue anyway.

**Comment by enricoros** [comment]
Confirmed, same behavior here. Seems That it's the multi-line legend that breaks it.

**Comment by enricoros** [comment]
Workaround, you can make the legend wider (currently hardcoded to be half the screen size), by editing nv.d3.js and hacking the following:

    @@ -9912,7 +9912,7 @@ nv.models.scatterChart = function() {

                // Legend
                if (showLegend) {
    -                legend.width( availableWidth / 2 );
    +                legend.width( 2 * availableWidth / 3 );

                    wrap.select('.nv-legendWrap')
                        .datum(data)
    @@ -9925,7 +9925,7 @@ nv.models.scatterChart = function() {
                    }

                    wrap.select('.nv-legendWrap')
    -                    .attr('transform', 'translate(' + (availableWidth / 2) + ',' + (-margin.top) +')');
    +                    .attr('transform', 'translate(' + (1 * availableWidth / 3) + ',' + (-margin.top) +')');
                }

                // Main Chart Component(s)

**Comment by robinfhu** [comment]
Issued a PR to fix the issue.
