### ISSUE TITLE
I'd like to make a sunburst graph.   They are purty.  

### ISSUE THREAD

**Issue by liquidpele** [novus/nvd3#781]
I'd like to create a sunburst model.  I think these things are supa sweet.  

http://bl.ocks.org/kerryrodden/477c1bfb081b783f80ad

**Comment by robinfhu** [comment]
That surprisingly didn't take a lot of code.  It needs tooltips I think.  Go for it!

**Comment by liquidpele** [comment]
Okay, so just to voice my thoughts, next up is to add the chart with legend and tooltips.   As part of this, I'm going to make a version of the tooltip that just follows next to the mouse and set that to work on pie/donut charts too.  It makes the most sense for those graph types that don't have a specific coordinate to appear in relation to, and should resolve the tooltip issues with piecharts even in IE since the mouse should never be over the tooltip in that case.

**Comment by liquidpele** [comment]
This is completed.  It's basic but easy to extend as needed.

**Comment by robinfhu** [comment]
:+1:
