### ISSUE TITLE
Click on a line charts legend breaks tooltips in IE11

### ISSUE THREAD

**Issue by mpGitHub** [novus/nvd3#783]
Line chart issue:

Clicking on a Legend to filter just on that item breaks the tooltip. This same bug occurs if you update the chart via: d3.select("#myChart").datum(chartData).call(chart);

The problem seems to occur because duplicate IDs for "nv-point-clips" are created every time the chart is updated. Duplicate ids for "nv-point-clips" are created in chrome as well, but chrome seems to handle this situation better. Still, updating the chart many times could potentially cause 100's of these duplicates to occur bloating it and eventually slowing the chart down.

If I manually delete all DOM elements for "nv-point-clips" except for the last one the tool tips start working properly in IE11.

Can something be added to clean up the old "nv-point-clips" before new ones are added? The duplicates/old ones are created/left here:
* <g class="nv-linesWrap nvd3-svg"
   * <g class="nv-scattterWrap nvd3-svg" 
      * <g id="nv-point-clips" **(old one)**
      * <g id="nv-point-clips" **(old one)** 
      * <g id="nv-point-clips" **(old one)** 
      * <g id="nv-point-clips" **(current chart - keep this one)**

**Comment by mpGitHub** [comment]
I found a hack workaround until this is fixed. 

Inside nv.d3.js add this line at the top of function chart() that removes all existing "nv-point-clips" before the chart is updated.  

function chart(selection) {
   // Clear out current data before updating    
   d3.select("#nv-point-clips").remove();
   ...

**Comment by liquidpele** [comment]
Well you wouldn't want to do that in case there was more than one chart on the page... you'd want to do the select based off the container for that chart, not off the global d3 object.

**Comment by mpGitHub** [comment]
Good call.  

I tweaked my previous call to take into account just the existing nv-point-clips in that SVG object.  This seems to handle the issue with multiple charts.  This code should be cleaned up, but adding this code to the top of function chart() seemed to fix this.

var containId = $(this)[0].parentNode.parentNode.id ;
$("#" + containId).find("#nv-point-clips").remove();

Thanks

**Comment by robinfhu** [comment]
Oh this is a problem.  Chart.update does seem to add nv-point-clips without removing previous ones.
![point clips added](https://cloud.githubusercontent.com/assets/3769532/6429437/2c26b24c-bf9f-11e4-929b-a19ae5605950.jpg)

**Comment by robinfhu** [comment]
@mpGitHub @liquidpele opened a PR with the fix.
