### ISSUE TITLE
Updating an existing chart breaks the double click selection in the legend

### ISSUE THREAD

**Issue by mpGitHub** [novus/nvd3#784]
Line Chart:
 
If you update an existing chart with new data the double click on the legend to only display that line breaks.

Update an existing chart via:

      d3.select("#myChart svg")
         .datum(chartData)
         .call(chart);

Now when trying to double click on any legend items will no longer work.  There seems to be some type of leftover confusion with the events.  Perhaps an unbind of the event might fix this?

I worked around this by removing the legend before doing the update by doing the following: 
      $("#myChart").find(".nv-legend").remove();

Could this type of process be handled within the default code instead?

Thanks

**Comment by robinfhu** [comment]
I was able to reproduce this bug I think.  Working on this.

**Comment by robinfhu** [comment]
@mpGitHub I issued a pull request to fix this.  See if my change solves your problem.
