### ISSUE TITLE
Hiding Tooltip on clicking outside the bars area in MultiBarCharts

### ISSUE THREAD

**Issue by gopalyadav5** [novus/nvd3#792]
I am using clicking event to fire the tooltip in MultiBarCharts. If I click on a bar the tooltip appears and shows the data and on clicking another bar, previous generated tooltip gets cleared and a new tooltip appears. But I am facing a problem that, if I click somewhere inside the chart area but not on the bars the last tooltip persists. I am looking for  a solution that tooltip gets hidden if i click somewhere outside.

This is the code snippet I am using to call tooltip on click event.

multibar.dispatch.on("elementClick.tooltip", function(e) {
    if (tooltips) nv.tooltip.cleanup();
    e.pos = [e.pos[0] + margin.left, e.pos[1] + margin.top];
    dispatch.tooltipShow(e);
  });

**Comment by liquidpele** [comment]
Shouldn't be an issue anymore:  https://github.com/novus/nvd3/pull/851
