### ISSUE TITLE
2 separate line charts in IE11 causes the tooltip to break

### ISSUE THREAD

**Issue by mpGitHub** [novus/nvd3#794]
IE 11 and two separate Line charts.

Two separate line charts on a single web page cause problems with each other when useInteractiveGuideline is off.  Make sure that the lines in each have slightly different values.  I used 2 lines on each chart with only a few dots on each line to keep it simple.

In the first chart all datapoints properly show the tooltip on hover.  On the second chart only some of the data points show tooltiops.  The problem appears to be a conflict in the duplicate IDs between each chart for "nv-clip-0", "nv-clip-1", "nv-clip-2", etc between the two charts.

In the chart that works correctly for the tooltips I manually changed the ID for each of these to "nv-clip-0XXX", "nv-clip-1XXX", etc.  This broke the tooltips on the first chart as expected, but now the 2nd chart works perfectly for the tooltips.

I'm guessing the problem occurs somewhere inside (useVoronoi == true) and the mouseEventCallback.  We need a way to prevent the different graphs from interfering with one another.  

Thoughts?

**Comment by robinfhu** [comment]
We'll need to update the code to give each clipping path a unique id.  I think we do that for historicalBarChart

**Comment by mpGitHub** [comment]
Anyone who wants a hack workaround for now following Robin Hu's suggestion:

First make sure each Div container that will have a chart in it has a unique ID.

// Then modify the nv.d3 code as follows
nv.models.scatter = function() {
...
function chart(selection) {

    // GRAB container DIV ID and use that to make the nv-clip unique
    var closeDivId = "X" ;
    var closeDiv = $(this).closest("div") ;
    if (closeDiv.length > 0)
       closeDivId = closeDiv[0].id ;

...

// Then anyplace '#nv-clip-" is referenced add in the closeDivId to make it unique.
// Eg.
.attr("clip-path", function(d,i) { return "url(#nv-clip-"+**closeDivId**+i+")"; })

**Comment by liquidpele** [comment]
This should be fixed now I think.  https://github.com/novus/nvd3/pull/851
