### ISSUE TITLE
multiBarHorizontalChart showing grayscaled colors

### ISSUE THREAD

**Issue by thostetler** [novus/nvd3#796]
![selection_002](https://cloud.githubusercontent.com/assets/6970899/6220253/42f18afc-b602-11e4-9a3b-595c0a0b0bd4.png)

Check out http://jsfiddle.net/timh06/k9tz6taL/1/

MultiBarHorizontalChart seems to be having an issue with colors showing up grayscaled.

Versions: 
* NVD3 1.7.1
* D3 3.1.5 (same thing occuring with latest version however)

**Comment by liquidpele** [comment]
Try the development branch and see if that fixes the issue for you, I think this was fixed by a contributor already.

**Comment by thostetler** [comment]
Thanks for the quick reply, unfortunately it looks like it's doing the same thing for me with the development branch as well.  Unless I'm doing something weird in the implementation.

Here is an updated fiddle: http://jsfiddle.net/timh06/k9tz6taL/3/

**Comment by liquidpele** [comment]
Interesting... 

Here it is working fine using the nvd3-community dev branch:   http://jsfiddle.net/k9tz6taL/5/

Here it is broken using the novus nvd3 dev branch:  http://jsfiddle.net/7Lenath7/1/

@robinfhu didn't you merge in the community dev branch the other day?  I would think this should be merged already...

**Comment by robinfhu** [comment]
Yep I've been merging it in. Did you remember to build the nv.d3.js file?

**Comment by thostetler** [comment]
I was able to get it working by cloning the repo and building the dev branch myself.  The latest seems to have the fix.

**Comment by liquidpele** [comment]
Awesome, closing this issue then, cheers!
