### ISSUE TITLE
Labels are broken on donut chart example

### ISSUE THREAD

**Issue by liquidpele** [novus/nvd3#801]
Not sure when it happened, but the donut chart labels, when displayed outside the slices, are all overlapping and on the top.

**Comment by mgold** [comment]
I may be interested in helping, but [this page](http://nvd3.org/examples/pie.html) looks fine to me.

**Comment by liquidpele** [comment]
I think the code on nvd3.org is way out of date.  To see the issue you'd need to clone the development branch and view the index.html file to see the new examples page.

**Comment by mgold** [comment]
This doesn't look so bad?
![screen shot 2015-02-24 at 11 23 44 pm](https://cloud.githubusercontent.com/assets/1191970/6364954/61c51144-bc7c-11e4-9846-78af93cb5ae9.png)

**Comment by liquidpele** [comment]
Look at the donut that's a complete circle, it has labels too, they're all above it overlapping each over.

**Comment by mgold** [comment]
Sorry, still not following.
![screen shot 2015-02-24 at 11 32 33 pm](https://cloud.githubusercontent.com/assets/1191970/6365003/76484be4-bc7d-11e4-9c3d-f74247cdc61a.png)

I tried playing with it and I can't get overlapping labels. It _does_ continue to say 100% even when some of the slices are hidden.

**Comment by liquidpele** [comment]
Yea the 100% is just a hard coded example text, maybe should have just put woot for that one too... 

Well, that's weird...  I wonder if it's only if you build latest?  Or maybe it's just me or I'm crazy :p  

Try building with "grunt production" and then see if it breaks?

**Comment by mgold** [comment]
Yup, that does it. I never rang grunt before, just used index.html as it was. Bisecting from the last commit to modify index.html, I found that the bug was introduced in e571fac7d22b424.

I'll try to get a fix up in the next few days if someone doesn't beat me to it.

**Comment by liquidpele** [comment]
Oh, that commit was to fix this other defect it seems:   https://github.com/novus/nvd3/pull/647

Thanks for at least hunting down the guilty commit!

**Comment by liquidpele** [comment]
should be fixed now.
