### ISSUE TITLE
Lines flash when a prior series is disabled

### ISSUE THREAD

**Issue by liquidpele** [novus/nvd3#803]
reproduce steps:

1. View lineChart example
2. disable the last series "Fill Opacity" by clicking it's circle in the legend, notice that it vanishes and the other lines do NOT flicker
3. enable the last series again
4. disable the first series "Sine Wave", notice all lines flash off and on.  This is especially bad on firefox, which takes almost a full second to redraw all the lines.

**Comment by robinfhu** [comment]
This was introduced in the development branch. Not happening on master.

**Comment by liquidpele** [comment]
Yea, I found it was due to this commit by me, not sure why it's causing that yet

https://github.com/novus/nvd3/commit/ec20666c8ac1b5fa0ed443df8ecbdb25e3124603

**Comment by liquidpele** [comment]
I reverted it, apparently it needs the key to stay the same and disabling stuff changes the i value...

**Comment by robinfhu** [comment]
Okay, I see.

Then what you need to do I think is create your own 'seriesIndex'

> data.forEach(function(d, i){ d.seriesIndex = i;}

And then in the select.data() function, do something like:

> .data(function(d){return d;},   function(d){ return d.key + d.seriesIndex;})
