### ISSUE TITLE
Add linechart feature to fill area above a line

### ISSUE THREAD

**Issue by mpGitHub** [novus/nvd3#805]
Add a new option to handle filling area above a line via a single properly:

// Position after isArea.  true/false option to indicate filling area above/below the line.
, areaTop = function(d){return d.areaTop }

// inside chart() 
            areaPaths.watchTransition(renderWatch, 'line: areaPaths')
                .attr('d', function(d) {
                
                //  Check if areaTop and if so apply style to fill the top area
                if (areaTop(d))
                    // This fills in the area above the line
                    return d3.svg.area()
                        .interpolate(interpolate)
                        .defined(defined)
                        .x(function(d,i) { return nv.utils.NaNtoZero(x(getX(d,i))) })
                        .y0(0)
                        .y1(function(d,i) { return nv.utils.NaNtoZero(y(getY(d,i))) })
                        .apply(this, [d.values]) ;
                else
                    // This fills in the area below the line
                    return d3.svg.area()
                        .interpolate(interpolate)
                        .defined(defined)
                        .x(function(d,i) { return nv.utils.NaNtoZero(x(getX(d,i))) })
                        .y0(function(d,i) { return nv.utils.NaNtoZero(y(getY(d,i))) })
                        .y1(function(d,i) { return y( y.domain()[0] <= 0 ? y.domain()[1] >= 0 ? 0 : y.domain()[1] : y.domain()[0] ) })
                        //.y1(function(d,i) { return y0(0) }) //assuming 0 is within y domain.. may need to tweak this
                        .apply(this, [d.values]) ;
 
//Then simply call by passing the following in the declaration
            ,area    : true
            ,areaTop : true

**Comment by liquidpele** [comment]
I'm confused, what would this look like and what is the use case?

**Comment by mpGitHub** [comment]
I  used it as a means to show a target area.  Some objectives might be ascending and some descending.  
   Ascending Objective - Might be reaching a target Net Revenue of >= $100.
   Descending Objective - Might be having < 5 outstanding claims for the month.

If the metric is ascending the target area would be above the line in the graph.  If the metric was descending obviously the target area is below the line.  

This helps depict a clear understanding when one of the objectives is in the wanted target area.

**Comment by liquidpele** [comment]
That seems more confusing than a line that goes up and down...

**Comment by liquidpele** [comment]
Maybe you could show a screenshot of it?

**Comment by mpGitHub** [comment]
![target_area](https://cloud.githubusercontent.com/assets/8506767/6270076/fc3ba9cc-b81c-11e4-9460-2077d6897baf.png)

**Comment by mpGitHub** [comment]
There is sparse data in this example and I modified the line's name, but should give you an example

**Comment by liquidpele** [comment]
Ah, I see what you mean now.  Interesting.  However, for the use of zones, I don't think adding a line there is the right solution... shouldn't it really just be a mostly transparent colored area without the line or legend item?  @robinfhu what do you think?

**Comment by mpGitHub** [comment]
I could see using a transparent colored area, but this allows an interactive show/hide of the target line/area plus the auto display of the Target point on hover.  I felt it was easier to leverage the existing functionality.

**Comment by liquidpele** [comment]
Well I'd be up for considering this, but it really should be a pull request from you with the modifications instead of an issue.  Make sure to read https://github.com/novus/nvd3#a-few-rules-for-pull-requests

I'll close this issue for now and look forward to the pull request.
