### ISSUE TITLE
Stacked bar charts, multiBarChart seems correct while multiBarHorizontalChart bars layout on top of each tother

### ISSUE THREAD

**Issue by jquince** [novus/nvd3#807]
If the values in a group are on opposite sides of the axis as per the demo http://nvd3.org/examples/multiBarHorizontal.html then stacked renders fine.
but with both positive, and I assume negative, the bars overlap instead of stacking.

Here is a jsbin
http://jsbin.com/yodaqekipu/3/edit?js,output

**Comment by liquidpele** [comment]
Your jsbin seems really messed up.... I tried to reproduce with the multibarhorizontal.html file by just making all the values positive like so:

    for (var k in long_short_data) {
        for (var j in long_short_data[k]['values']) {
            long_short_data[k]['values'][j]['value'] = Math.abs(long_short_data[k]['values'][j]['value']);
        }
    }

However, everything seems to work fine in this case...

**Comment by jquince** [comment]
Ok, I see what's wrong some how my data has strings instead of numbers.
