### ISSUE TITLE
Tooltips not being removed after moving out of the chart

### ISSUE THREAD

**Issue by RenatoUtsch** [novus/nvd3#808]
I think I reported this problem before or saw someone reporting it, but I can't find it here.

If you open the line chart example (examples/lineChart.html), you notice that the tooltip div is reused while the user is moving his mouse inside the chart area. This is a good thing, but after the user moves out of the chart, it is only marked as 'nvtooltip-pending-removal', but not removed.

**Comment by robinfhu** [comment]
Is this the same problem as: https://github.com/novus/nvd3/issues/771 ?

**Comment by RenatoUtsch** [comment]
Yes, it is the same.

I don't know why I couldn't find it again... You can close it as duplicate.
