### ISSUE TITLE
Interactive Guideline tooltip position doesn't account for containers with scroll offset

### ISSUE THREAD

**Issue by jamesspencer** [novus/nvd3#809]
I'm using nvd3 to render some charts in a div that has the following CSS applied:

    overflow-y: auto;
    overflow-x: hidden;

This isn't accounted for in `nv.tooltip.calcTooltipPosition` as only the window scroll offset is inspected. If the containing div is scrolled, the tooltip position is calculated incorrectly.

I imagine an elegant solution would be to traverse the DOM upwards, storing a cumulative result of all scroll offsets. I'll see if I can put together a PR.

**Comment by liquidpele** [comment]
Hmm, I thought this was a duplicate but I guess not.    There is a related pull request though:   https://github.com/novus/nvd3/pull/460

**Comment by liquidpele** [comment]
This should be fixed by https://github.com/novus/nvd3/pull/851 I think.

**Comment by jamesspencer** [comment]
Thanks!
