### ISSUE TITLE
Please support xScale in multiChart

### ISSUE THREAD

**Issue by steveloft** [novus/nvd3#814]
I'd like a graph with two Y axes with different scales, and xScale(d3.time.scale.utc()) so I think I need to use multiChart, but this does not I think support xScale yet?

Steve

**Comment by liquidpele** [comment]
Multichart provides yAxis1 and yAxis2 objects:

http://nvd3-community.github.io/nvd3/examples/documentation.html#multiChart

Those can then in turn be tuned via options:   http://nvd3-community.github.io/nvd3/examples/documentation.html#axis

**Comment by steveloft** [comment]
Thanks. I'm having trouble getting the multiChart to plot correctly, where a similar lineChart with two lines works OK.  Here is the lineChart - http://jsfiddle.net/klaatu/40reuLgo/1/ which looks OK, and here is the multiChart - http://jsfiddle.net/klaatu/a4ev1nxt/1/

Could you tell me what I'm doing wrong, please?

Steve

**Comment by Gorzas** [comment]
Same problem here. I haven't figure out how can I use a date as xAxis in multiChart. With version 1.8.0 this is kind of fixed, but the xAxis doesn't fits with the data lines.

**Comment by liquidpele** [comment]
Those jsfiddles are not using the latest code in master (please use rawgit.com to link to the latest in master) which is necessary for showing bugs.  If you're just wanting an example of how to use multichart, please see https://nvd3-community.github.io/nvd3/examples/multiChart.html

**Comment by Gorzas** [comment]
Using the current version on master, with MultiChart doesn't show the dates correctly (it works fine with LineCharts): https://jsfiddle.net/rrr8oyqy/

Could it be something done wrong in the JSFiddle?

**Comment by krmarien** [comment]
I added a fix in this pull request (#1916). 
It is not the cleanest solution, but straight forward.

Example: [http://plnkr.co/edit/TOcSRfEEp5YnnfiJ6Afd?p=preview](http://plnkr.co/edit/TOcSRfEEp5YnnfiJ6Afd?p=preview)
