### ISSUE TITLE
Focus Chart Path Transition Wiggle

### ISSUE THREAD

**Issue by eschlon** [novus/nvd3#816]
Trying to build a Line with Focus chart and noticed an annoying wiggle when scrubbing through the data (essentially [this](http://bost.ocks.org/mike/path/) problem). The issue is not present on the example on nvd3.org (and is not present locally when I grab the js used there). It is present in both master and dev branches here. You can replicate it by just loading the lineWithFocusChart.html example in either branch, zooming in and scrubbing through the chart.

**Comment by robinfhu** [comment]
Yeah something changed in the line with focus code during all our merges.  You're right, it used to never do that.

**Comment by liquidpele** [comment]
This was probably due to me combining the linePlusBar and linePlusBarWithFocus charts... maybe the latter had a specific interpolation set?

**Comment by robinfhu** [comment]
But why would that affect the lineWithFocus chart?

**Comment by liquidpele** [comment]
Oh whoops I got confused.  No idea then, but lineplusbar does it too anyway...

**Comment by robinfhu** [comment]
Did a git bisect, and this started happening after @fshao816 added the 'renderWatch' functionality.  Looking into this...

**Comment by robinfhu** [comment]
The only solution I have is to turn of transition duration for the lines.  Let me pull request this.

**Comment by robinfhu** [comment]
@eschlon PR opened.
