### ISSUE TITLE
discretebarchart doesn't have a legend

### ISSUE THREAD

**Issue by mcoquet** [novus/nvd3#817]
I'd love to have discreteBarChart with a legend. 

I don't know if this is by design or by accident, but I don't see a technical reason not to support it.

Happy to have a go at it and submit a PR if you are open to it.

Cheers

**Comment by liquidpele** [comment]
Check out multiBarChart.  Really, I'm not sure why we have discreteBarChart still, @robinfhu do you know if there is something special about it than you can't do with multiBarChart?

**Comment by mcoquet** [comment]
the reason i used it was because it looked like the simplest chart to scratch my itch from reading the docs :) I'm trying out multiBarChart now. Seems to work :)

**Comment by robinfhu** [comment]
Discrete bars shouldn't need a legend.  It's by design.  Each bar should have a label underneath and a value on top, so what would a legend serve?

**Comment by liquidpele** [comment]
@robinfhu if we added the showValues option to multiBar wouldn't it function the same as discreteBar?   I'm curious if we can remove discreteBar as duplicate functionality...

**Comment by robinfhu** [comment]
@liquidpele  don't remove discreteBar because we do kind of use it in our software.  But I see what you are saying.  I think there are still subtle differences.  Like discreteBar has a different color for each bar.  

I'm on the fence on this.

**Comment by robinfhu** [comment]
@liquidpele I think one of the reasons discreteBar was made is for the 'showValues' feature,  Also it's nice to have a separate piece of cleaner code.

MultiBar has complex features like 'grouped' and 'stacked', and it has some weird logic to color things in shades.  

One solution, is we can copy over discreteBar code to our own internal repo.  We remove it from NVD3, and replace the discreteBarChart.html example with a multiBarChart styled to look the same as before.

**Comment by liquidpele** [comment]
Well, not rush on it or anything, I was mostly just curious if I was missing some other big difference.
