### ISSUE TITLE
Donut chart shows 100% even when filters active

### ISSUE THREAD

**Issue by mgold** [novus/nvd3#819]
The example donut chart in the development branch is title "100%", which is placed in the center of the donut. This is fine.... until one hides some of the data, and it's not longer 100%.

![screen shot 2015-02-25 at 11 05 18 pm](https://cloud.githubusercontent.com/assets/1191970/6386170/cad41a06-bd42-11e4-9620-dc8e19c2c537.png)

The simplest option is to use another string literal as the title.

The tile [can be set based on the data](https://github.com/novus/nvd3/blob/master/src/models/pie.js#L115-L117) but is not called when a series is disabled. Arguably, changing the title based on data filters is a handy feature (and the title can be supplied as a function or string, which NVD3 passes off to D3 never the wiser). The logic of figuring out the current percentage is delegated to the example code, not the library.

**Comment by liquidpele** [comment]
Honestly a percent there doesn't make much sense in any case, what would probalby be most helpful is a way to have update it when you hover over a slice so you could add the value of the slice there.

**Comment by liquidpele** [comment]
Closing this since it's not really a bug or anything, but feel free to send up a pull request that changes things and we'll review it.   Cheers!

**Comment by mgold** [comment]
Thanks, I'll see if I can some up with anything worthwhile.
