### ISSUE TITLE
multiBarChart showValues doesn't work?

### ISSUE THREAD

**Issue by mcoquet** [novus/nvd3#820]
Hi, I want to have a multiBarChart with stacked bars - and that works as expected, but I want to remove the yAxis and have the values displayed on the bars, as I would with discreteBarChart. 

Is this achievable with multiBarChart? If not, what chart should I be using to get this effect?

All the best

**Comment by robinfhu** [comment]
Use a multiBar horizontal chart, which allows you to add labels to each bar.

**Comment by mcoquet** [comment]
can I rotate it 90º ?

**Comment by robinfhu** [comment]
There's no feature to rotate the multibar horizontal chart.

**Comment by mcoquet** [comment]
@robinfhu thanks for the input. 

I ended up using discreteBarChart as its the only one that gives me the closest behaviour to what I need. 

All the best!
