### ISSUE TITLE
v1.8.0.alpha

### ISSUE THREAD

**Issue by jufemaiz** [novus/nvd3#832]
build/nv.d3.js: Errors on lines: 2998, 3000, 7903, 9321, 9329, 10188, 10191
src/models/discreteBar.js: 61,63
src/models/multiChart.js: 61,63
src/models/scatter.js: 82,90
src/models/sparkline.js: 32,35

Whitespace between reference to "x" or "y" and "domain". Eg:

https://github.com/novus/nvd3/blob/master/build/nv.d3.js#L2998-L3000

```
            x   .domain(xDomain || d3.merge(seriesData).map(function(d) { return d.x }))
                .rangeBands(xRange || [0, availableWidth], .1);
            y   .domain(yDomain || d3.extent(d3.merge(seriesData).map(function(d) { return d.y }).concat(forceY)));
```

Raising errors in Chrome.

**Comment by jufemaiz** [comment]
Ah crap. Never mind >< Mistaken error sorry guys :(

**Comment by robinfhu** [comment]
:-)
