### ISSUE TITLE
stackedAreaChart falls apart if x-points are not aligned

### ISSUE THREAD

**Issue by OhJeez** [novus/nvd3#834]
If X points are not aligned, points of area above don't stack above the value below, but above the nearest defined point to the left of the area below.
See:
http://jsfiddle.net/xu1qz34u/4/

**Comment by robinfhu** [comment]
Yeah you can't do that, this is not defined behavior.

**Comment by OhJeez** [comment]
Then I think it should be noted in examples/documentation.

**Comment by robinfhu** [comment]
Okay I will keep that in mind.
