### ISSUE TITLE
Bar for 0 value in Chrome

### ISSUE THREAD

**Issue by wojteklenny** [novus/nvd3#835]
In Chrome there's a bar for 0 value displayed in multiBarHorizontalChart.
http://jsfiddle.net/dv41rhcc/ - see 'test3' and 'D' data series. 
In Firefox it works well.

**Comment by liquidpele** [comment]
You can remove the zero lines with CSS, I updated your demo to do so:

http://jsfiddle.net/dv41rhcc/1/

**Comment by wojteklenny** [comment]
Thanks for help.
