### ISSUE TITLE
MultiBarChart incorrect tooltip position within negative values

### ISSUE THREAD

**Issue by mtkachev** [novus/nvd3#836]
Hi all,

Found an issue related to tooltip position in case when mouse cursor over the block with negative value.
Here is an example: http://jsfiddle.net/L5ay9ek3/2/ . Move mouse over the left bottom block and observe tooltip position.

Could you please clarify if there are any workaround exists for this issue?
Thanks.

Max.

**Comment by liquidpele** [comment]
I'm in the process of changing a lot of the tooltips to be mouse-following, including for blocks and pie charts, so this should be fixed by that  :)

**Comment by liquidpele** [comment]
Closing this for now.  The tooltips will be redone and better in 1.8.0 :)

**Comment by robinfhu** [comment]
We're counting on you @liquidpele :-)

**Comment by liquidpele** [comment]
So close... Only multichart left!

**Comment by joshjordan** [comment]
Kickin ass. Nice job.
