### ISSUE TITLE
Download links on the website broken

### ISSUE THREAD

**Issue by WoLpH** [novus/nvd3#837]
Both the development and production links on the frontpage are broken.

http://nvd3.org/index.html

**Comment by liquidpele** [comment]
@robinfhu the broken links are in the text:

    Download the latest nv.d3.js (version 1.1 beta). Get the development version, or minified production version.

**Comment by robinfhu** [comment]
Yep, looks like it's because we moved things to the build/ folder.

**Comment by robinfhu** [comment]
Fixed. Updated download links to point to v 1.7.1

**Comment by robinfhu** [comment]
Btw, we use gh-pages to host the site.

Git checkout origin/gh-pages to update the site content, and then push it to origin/gh-pages

**Comment by WoLpH** [comment]
Good to know, next time I'll fix it myself :)

**Comment by robinfhu** [comment]
@WoLpH yeah you can issue pull requests against that branch.
