### ISSUE TITLE
HistoricalBarChart shouldn't set the valueFormatter every time the mouse moves

### ISSUE THREAD

**Issue by heliodor** [novus/nvd3#839]
The HistoricalBarChart sets the valueFormatter every time the mouse moves. Shouldn't this be set only once, at init time? This behavior prevents the user from setting the valueFormatter himself.

Setting the x-value formatter works:

chart.interactiveLayer.tooltip.headerFormatter(function (d) { ... });

Setting the y-value formatter doesn't:

chart.interactiveLayer.tooltip.valueFormatter(function (d, i) { ... });

**Comment by robinfhu** [comment]
Yes, I had a PR open https://github.com/novus/nvd3/pull/831 to fix this.  @liquidpele  is fixing all the tooltip code right now, so this should be fixed in development soon.
