### ISSUE TITLE
Can't set chart.yAxis.tickFormat() in stackedAreaChart

### ISSUE THREAD

**Issue by kreidles** [novus/nvd3#840]
First, thanks for writing nvd3 - it's a great product!

Unfortunately, I ran into a problem with version 1.7.1.  I'm creating a stackedAreaChart as follows:

            var chart;
            nv.addGraph(function() {
                chart = nv.models.stackedAreaChart()
                    .margin({right: 100})
                    .useInteractiveGuideline(true)
                    .x(function(d) { return $scope.formatMonth.parse(d[0]); })
                    .y(function(d) { return d[1] })
                    .rightAlignYAxis(true)
                    .controlLabels({stacked: "Stacked"})
                    .duration(500);

                chart.xAxis.tickFormat(function(d) { return d3.time.format('%b, %Y')(new Date(d)) });
                chart.yAxis.tickFormat(d3.format(',.2s'));

                chart.color(["#003950", "#698B22", "#B4CDCD", "#4C4322", "#B45B49", "#E59138", "#CDCDC1", "#FFA812", "#8E2323"]);

                d3.select('#chart svg')
                    .datum(data)
                    .call(chart);

                nv.utils.windowResize(chart.update);
                return chart;
            });

The chart displays fine and the xAxis is correct.  However, the tick formats do not change on the Y-axis.  I can change the format by  editing the nv.d3.js file on line 10865:

        , yAxisTickFormat = d3.format(',.2f')
       
I can't find a way to update this value through the api though.  Any help is appreciated.

Thanks.

**Comment by liquidpele** [comment]
Try chart.yAxis.tickFormat(d3.format(',.2f'))

**Comment by kreidles** [comment]
Thanks for the response.  The code you suggest works only for the d3.format(',.2f') - I am unable set the format to anything except d3.format(',.2f')).

For example,  adding the code

chart.yAxis.tickFormat(d3.format(',.2s'));

has no effect.  I have also tried other numeric formats, but these also have no influence on the plot axis.

**Comment by robinfhu** [comment]
There's a bug in the code.

**Comment by robinfhu** [comment]
This has been fixed in the development branch.

**Comment by robinfhu** [comment]
We don't have a releasable version.  If you want to make your own build, checkout the code from development branch, 'npm install', and run 'grunt'.

**Comment by robinfhu** [comment]
@liquidpele how about we build dist/nv.d3.js in the development branch and create a pre-release tag for it?

**Comment by liquidpele** [comment]
sure if you want to :)

**Comment by robinfhu** [comment]
@liquidpele , okay, I'll take care of that.

**Comment by rkofman** [comment]
Thank you for fixing this! I was just going to submit a duplicate issue, and then thought of searching closed issues first. Go, You! :)

**Comment by luisrudge** [comment]
where's the pre release tag?
