### ISSUE TITLE
donut pie chart will shrink if in Bootstrap 3 tabs

### ISSUE THREAD

**Issue by maplesap** [novus/nvd3#843]
Hi, I'm having a problem with v1.7.1. If I have a donut pie chart inside a bootstrap tab, the pie sections will shrink if moused over.

This does not happen in v1.1.15-beta.

Here is a plnkr:
http://plnkr.co/edit/G1Q8QiFpLnsA9116o2wq?p=preview

(click second tab and mouse over)

The current workarounds are to either:
(1) use v1.1.15-beta
(2) set `growOnHover: false` if using v1.7.1

The issue is described in more detail here:
https://github.com/nvd3-community/nvd3/issues/70
krispo/angular-nvd3#92

**Comment by robinfhu** [comment]
Whoa, that is weird.  So much has changed with pie charts I haven't been able to keep up.  Maybe this has to do with that new growOnHover feature that was added?

![small pies](https://cloud.githubusercontent.com/assets/3769532/6490634/bf09d980-c275-11e4-8ec9-cdefd0cf29a0.jpg)

**Comment by robinfhu** [comment]
@maplesap do you think you can help look into this?  Fire up a debugger and find the solution?

**Comment by robinfhu** [comment]
Just diving into the code, it looks like this has to do with 'arcRadius' being dependent on the availableWidth and availableHeight.

So clearly, something about the bootstrap tabs is causing that calculation to not work.

**Comment by liquidpele** [comment]
Yup, I copied an example of changing the radius off stackoverflow so I guess I messed up a calculation somwhere :p

**Comment by robinfhu** [comment]
@liquidpele I trust that you will find an elegant solution :-)

**Comment by liquidpele** [comment]
Fixed in the above PR, closing this bug now.

**Comment by venkatasunil4** [comment]
Hi,
I did not use Bootstrap tabs, but using bootstrap. The pie chart is displayed small and changes to it actual size on window resize[minimizing the window and maximizing the window]. Can you check this.
