### ISSUE TITLE
Tooltips disable the very hover state that gives them life

### ISSUE THREAD

**Issue by wraybowling** [novus/nvd3#846]
to reproduce: hover over a bar or point. So long as your cursor rests on top of the tooltip itself, hover state is transferred away from the bar or point, the tooltip disappears, hover is renewed, and the process cycles again and again ad infinitum giving them a sort of "flicker".

expected behavior: the tooltip doesn't affect the mechanisms that make them show up OR contributes to the events that keep the tooltip around.
 - gRaphael does a fine job by capturing the entire column of a bar — not just the visible part http://g.raphaeljs.com/barchart2.html

solutions you may find:

 - Other sorts of tooltips are not usually trying to play with an SVG. Some folks will talk about using z-index and positioning to solve tooltip woes. That doesn't work here. Twiddling the z-index only pushed the tooltip behind the chart entirely. Pushing the chart back further behind the tooltip restores the issue.

**Comment by liquidpele** [comment]
I'm already refactoring all the tooltips currently, should be fixed when I'm done :)

**Comment by wraybowling** [comment]
It was sort of a false alarm anyway. I had removed the default nvd3 css which included pointer-events:none; I brought that back as the quickest remedy. Thanks for looking at this ticket though.
