### ISSUE TITLE
passing object array on nv.utils.getColor causes error

### ISSUE THREAD

**Issue by mgenov** [novus/nvd3#854]
It seems that in some situations nvd3 is passing object array for colors and 

```javascript
if (color instanceof Array) 
```
is not detecting where the provided object is array, where 

```javascript
if (Array.isArray && Array.isArray(color)) {}
```
is returning the correct result. This is the error which I'm getting before my fix: 
![screen shot 2015-03-08 at 6 07 56 pm](https://cloud.githubusercontent.com/assets/209223/6546499/22dbc0a4-c5be-11e4-95bd-ceae75c645e1.png)

Improving of getColor function with using of Array.isArray do the trick and make it working: 
```javascript
nv.utils.getColor = function(color) {
    //if you pass in nothing, get default colors back
    if (!arguments.length) {
        return nv.utils.defaultColor();

    //if passed an array, wrap it in a function
    } else if(color instanceof Array) {
        return function (d, i) {
            return d.color || color[i % color.length];
        };
    // if passed an array (objects?), wrap it in a function    
    } else if(Array.isArray && Array.isArray(color)) {
        return function (d, i) {
            return d.color || color[i % color.length];
        };
    //if passed a function, return the function, or whatever it may be
    //external libs, such as angularjs-nvd3-directives use this
    } else {
        //can't really help it if someone passes rubbish as color
        return color;
    }
};
```

This is the snippet that I'm using for testing: 
```javascript
nv.addGraph(function () {
                var chart = nv.models.lineChart()
                                .x(function (d) {
                                    return d[0];
                                })
                                .y(function (d) {
                                    return d[1] / 1000 / 1000;
                                })
                                .color(d3.scale.category10().range())
                                .useInteractiveGuideline(true)
                        ;

                chart.xAxis
                        .tickFormat(function (d) {
                            return d3.time.format('%H:%M')(new Date(d))
                        });

                chart.yAxis.tickFormat(d3.format('.02f'));

                d3.select(parent)
                        .datum(data)
                        .transition().duration(500)
                        .call(chart);

                nv.utils.windowResize(chart.update);

                return chart;
            });
        }
```

Note that passed data is not having color property. Just "key" and values.

**Comment by mgenov** [comment]
Here is a screenshot from chrome debugger that shows actual value of the passed color: 

![screen shot 2015-03-08 at 6 13 31 pm](https://cloud.githubusercontent.com/assets/209223/6546525/f999d81a-c5be-11e4-91bb-8bd1ff5158b0.png)

**Comment by liquidpele** [comment]
I'm trying to figure out why in the world the instanceof would be failing for you, the best I can find is that apparently it failes if the array was created in a different iframe ( see http://stackoverflow.com/questions/22289727/difference-between-using-array-isarray-and-instanceof-array), are you loading d3 in a separate frame or something?

**Comment by mgenov** [comment]
Yes, this is my case. D3 and nvd3 are loaded in different iframe.

**Comment by mgenov** [comment]
Actually I'm integrating nvd3 in a GWT app and the GWT code is loaded in one iframe which schedules script loading of D3 and nvd3 in the root page by importing script and style at runtime.

**Comment by liquidpele** [comment]
I opened a PR for this, closing.
