### ISSUE TITLE
Tooltips for charts with directive names containing 'g' are assigned to parent element instead and are no longer displayed with chart. 

### ISSUE THREAD

**Issue by camille-cowley** [novus/nvd3#858]
Tooltips for charts with directive names containing 'g' are assigned to parent body element instead and are no longer displayed with chart. 
Relates to: in tooltip.js line 345 (dev branch), method nv.tooltip.show

Has the regex /g|svg/i perhaps this was meant to be g or svg tags with the flag /i but the regex does not match only these patterns, ( /^g|svg$/i is used further down and perhaps the method call for a non svg parent or a regex revision should be considered). However this means that tags such as a custom nvd3-guidline-chart etc would be flagged as a svg element simply because the name includes the letter g. To allow the tooltips to correctly associate back to the chart element the regex can be edited for the intended result.  

To test add a directive for a chart (can copy and paste an existing chart directive & matching functions with a new name including the letter g). By editing the regex the tooltips are correctly associated back to the right parent element and display above the chart correctly.

**Comment by liquidpele** [comment]
I'm pretty sure I removed that in my tooltip refactor:   https://github.com/novus/nvd3/pull/851

**Comment by camille-cowley** [comment]
Sweet as.  It looks like #851 just hasn't been merged then in the development branch. I noticed there have been quite a few tooltip changes in #851, any idea on when they might get merged into the main branches?

**Comment by camille-cowley** [comment]
Pending #851 to be merged.

**Comment by liquidpele** [comment]
It'll probably get merged in the next day or so.
