### ISSUE TITLE
Bower availability

### ISSUE THREAD

**Issue by jareware** [novus/nvd3#86]
Hey,

[Bower](http://twitter.github.com/bower/) is one of the [most widely used](https://github.com/wilmoore/frontend-packagers) frontend package managers, and your upstream [is also using it](https://github.com/mbostock/d3/blob/master/component.json). 

Would you be willing to consider making NVD3 available on Bower as well?  Would love to be able to just:

    bower install nvd3

Cheers,

\- Jarno

**Comment by robinfhu** [comment]
You can also install just with bower install git://github.com/novus/nvd3.git
