### ISSUE TITLE
lineplusbarchart - timeline showing year1970 if number of bars is 7 and lower

### ISSUE THREAD

**Issue by lucas03** [novus/nvd3#865]
Is this a bug or is there a minimum data volume that should be visualized by graph? http://stackoverflow.com/questions/28920202/line-plus-bar-chart-invalid-dates-showing-in-timeline

**Comment by liquidpele** [comment]
Hi there, can you provide a jsfiddle (or similar online demo site) that shows the issue using the latest version?   Thanks!

**Comment by lucas03** [comment]
Sure, here it is:
http://jsfiddle.net/g7s19osx/1/

**Comment by liquidpele** [comment]
you're giving it bad data... I updated it to use latest d3 and nvd3 and fixed it up for you:

http://jsfiddle.net/g7s19osx/2/

I have an empty hidden line there because it throws errors without a line, if you want just bars you should probably be using either historicalBarChart or multiBarChart.

**Comment by lucas03** [comment]
ok, thanks a lot.
