### ISSUE TITLE
tooltipContent documentation wrong for scatterChart

### ISSUE THREAD

**Issue by Resseguie** [novus/nvd3#866]
The documentation for the tooltipContent function for scatterChart is wrong here:
http://nvd3-community.github.io/nvd3/examples/documentation.html#scatterChart

It should accept function of form:
function(key, x, y, pointTooltip, e, chart)

It looks like those docs are generated, but I couldn't find where to offer a PR. I'm happy to if someone will point me in the right direction.

**Comment by liquidpele** [comment]
quoting the docs:

    Function used to build the tooltip content. **The variables passed to the function can depend on the chart (i.e. it depends on what makes sense for the chart) so you might want to console.log stuff when playing with this to see what's available.**

**Comment by liquidpele** [comment]
Also the data passed changed recently due to tooltip refactor ;)

**Comment by Resseguie** [comment]
Ah, that might have been what threw me off. I thought it was just something out of sync between the forks.
