### ISSUE TITLE
Showing the legend in multiBarHorizontalChart breaks color-per-series in version 1.7.1.

### ISSUE THREAD

**Issue by mtr** [novus/nvd3#867]
Hi,

I searched through the issues in the tracker, but didn't detect this issue as already reported.  I have created [an example in Plunker](http://plnkr.co/edit/V085PNbVMV9u9TNlf3oU?p=preview) that shows how enabling the legend causes the color per series in multiBarHorizontalChart to break.

[The plunk](http://plnkr.co/edit/V085PNbVMV9u9TNlf3oU?p=preview) is basically and updated example, based on NVD3's existing [Horizontal Multi-Bar Chart example](http://nvd3.org/examples/multiBarHorizontal.html).

The code that causes this seems to be the block that starts with
```js
            if (showLegend) {
                legend.width(availableWidth - controlWidth());

                if (multibar.barColor())
                    data.forEach(function(series,i) {
                        series.color = d3.rgb('#ccc').darker(i * 1.5).toString();
                    });
…
```
around [line 177 in `multiBarHorizontalChart.js`](https://github.com/novus/nvd3/blob/v1.7.1/src/models/multiBarHorizontalChart.js#L177).

**Comment by liquidpele** [comment]
Could have sworn we fixed that.... Can you try the development branch instead of 1.7.1?

**Comment by robinfhu** [comment]
Use this pre-release version: https://github.com/novus/nvd3/releases/tag/v1.8.1-alpha

**Comment by mtr** [comment]
Great!  This seems to have been fixed in v1.8.1-alpha, just like you said, and as [my updated plunker shows](http://plnkr.co/edit/kdOVxmrRAbp0rOE6G2Sa?p=preview).  Thanks for your suggestions @robinfhu and @liquidpele.  Thank you!

**Comment by robinfhu** [comment]
You're welcome!  Please test v1.8.1 and see if other charts still work as you expect.

**Comment by liquidpele** [comment]
Hmm I need to document the new options still....
