### ISSUE TITLE
Add links to a CDN

### ISSUE THREAD

**Issue by NameFILIP** [novus/nvd3#868]
When I add CSS and JS files from the [nvd3](http://nvd3.org/) main page, it doesn't work as expected. In Chrome's console it prints: 

```
Resource interpreted as Stylesheet but transferred with MIME type text/plain: 
"https://raw.githubusercontent.com/novus/nvd3/master/src/nv.d3.css".
```

An explanation of the issue - https://rawgit.com/faq

I suggest changing links from
https://raw.githubusercontent.com/novus/nvd3/master/build/nv.d3.css
to
https://cdn.rawgit.com/novus/nvd3/v1.7.1/build/nv.d3.css or https://cdnjs.cloudflare.com/ajax/libs/nvd3/1.7.0/nv.d3.css

**Comment by liquidpele** [comment]
That is GitHub not us.

**Comment by liquidpele** [comment]
Google "rawgit"

**Comment by liquidpele** [comment]
Oh wait you mean instruxtions on our page are wrong?

**Comment by NameFILIP** [comment]
Yes, I mean to change links in the instructions

**Comment by liquidpele** [comment]
Ah okay, we should change the links to be to:

https://cdn.rawgit.com/novus/nvd3/master/build/nv.d3.js

https://cdn.rawgit.com/novus/nvd3/master/build/nv.d3.min.js

(rawgit will keep their cdn updated based on the actual git files)

**Comment by liquidpele** [comment]
Fixed by @NameFILIP
