### ISSUE TITLE
Custom colors in pie chart ignored

### ISSUE THREAD

**Issue by swiesner** [novus/nvd3#870]
If one sets custom colors in your data elements, the color gets ignored in a pie chart. The legend is colored correctly, though. You can evaluate this in the live code also. Just set one data element in the JSON data to e.g. color = #505050 and watch how the legend is updated but the chart itself is not.

**Comment by liquidpele** [comment]
What version did you reproduce this on?

**Comment by swiesner** [comment]
Realised it when we changed version from like 1.1.15 to the actual stable. You can reproduce it with the actual live code on nvd3.org/livecode/index.html, just select the pie chart and give one data a color value. It does work inside other charts though.

**Comment by liquidpele** [comment]
Fixed in https://github.com/novus/nvd3/pull/882
