### ISSUE TITLE
exporting function

### ISSUE THREAD

**Issue by SHARUKH-SD** [novus/nvd3#871]
pls update module to export the chart into pdf /png or both it would be really helpfull!! 

Ty,
Well Wishing Developer

**Comment by liquidpele** [comment]
This isn't on the roadmap currently, feel free to fork and send us a pull request though!

**Comment by SHARUKH-SD** [comment]
I feel nvd3 is so cool , with this one function I think its perfect (apart from minor bugs) any ways i wrote custom function to import but it would be great if there is an option just like downloadPng: true  , any ways thx fr quick response

**Comment by SHARUKH-SD** [comment]
and I am new on git so dont know much on pull requests , I forked it anyway :D
