### ISSUE TITLE
Missing examples

### ISSUE THREAD

**Issue by bartiosze** [novus/nvd3#878]
I noticed there are some missing examples in the `examples/` directory. Are those missing examples placeholders for nice-to-have examples or was `examples/index.html` left unchanged after the examples' sources were removed? 

I'm curious about those crossfilter and horizon examples.

I might also work on something that need polishing (with my limited JS skills).

**Comment by liquidpele** [comment]
That file is old...open site.html instead :)

**Comment by bartiosze** [comment]
oh, then I'll close the issue. 
Or do you want a PR removing this file?

**Comment by liquidpele** [comment]
no I left it because I wasn't sure if the Novus guys were still using that or not
