### ISSUE TITLE
Axis not rescaling with resize (issue with axis.ticks())

### ISSUE THREAD

**Issue by RenatoUtsch** [novus/nvd3#895]
I noticed that something that used to happen with the old nvd3 (the version on the website) that was very important for responsive designs stopped happening somewhere between the creation of nvd3-community and here.

If you open an example at nvd3.org and look at it with no zoom and then zoom it in, you'll notice that the axis adds and removes ticks according to the chart size:

- Before Zoom
![screen shot 2015-03-17 at 5 13 54 pm](https://cloud.githubusercontent.com/assets/836333/6696558/02f35628-ccc9-11e4-9705-b37ffb9d54a7.png)

- After Zoom
![screen shot 2015-03-17 at 5 13 04 pm](https://cloud.githubusercontent.com/assets/836333/6696570/178b46ae-ccc9-11e4-8996-c8364ab36729.png)

In the new nvd3, if I try to do the same thing with the examples, the ticks are not removed and get cramped together in the axis. This is bad.

- Before Zoom
![screen shot 2015-03-17 at 5 20 00 pm](https://cloud.githubusercontent.com/assets/836333/6696680/d4e27e34-ccc9-11e4-9b30-19bed83e1a9f.png)

- After Zoom
![screen shot 2015-03-17 at 5 20 11 pm](https://cloud.githubusercontent.com/assets/836333/6696684/dae23414-ccc9-11e4-8c4e-dfcaa2351557.png)

This is something that needs to be fixed, because it is one of the most important aspects of responsivity.

**Comment by robinfhu** [comment]
Yeah, I see what you mean. Looking at it

**Comment by robinfhu** [comment]
It was one of my changes: 6f57104

**Comment by robinfhu** [comment]
I had tried to fix https://github.com/novus/nvd3/pull/601, but it looks like I broke the original functionality, which had the chart automatically figure out the ticks.

**Comment by robinfhu** [comment]
There needs to be a way we can reconcile the ability to let users set the number of ticks they want, and allow the charts to automatically figure out the number of ticks.

**Comment by robinfhu** [comment]
One idea I have is to add a new property to nv.model.axis, called "autoTicks". If autoTicks is set to true, the axis will ignore the ticks() property and just try to automatically figure out the number of ticks to show, just like before.

**Comment by liquidpele** [comment]
I'm confused why your commit broke that...

**Comment by RenatoUtsch** [comment]
That may be a good idea, but why not implement the original functionality in axis.ticks() and allow it to be overriden?

**Comment by robinfhu** [comment]
I need to look at it in more detail, but I have a theory @liquidpele as to why my change broke it.

The zoom behavior must trigger a window.resize event, which in turn triggers a chart.update().  On subsequent update cycles, axis.ticks() is NON-null, and so it retains its original value.


@RenatoUtsch  If you zoom in and then refresh the page, the ticks magically auto size correctly.

**Comment by RenatoUtsch** [comment]
It makes sense. Then the ticks are not being recalculated by chart.update()?

**Comment by liquidpele** [comment]
Ah, it probably inherits ticks() from d3 I bet.

**Comment by robinfhu** [comment]
The ticks are being calculated on the first chart.update, and then that same tick number is being used on each subsequent chart.update().  

In the past, the tick number would be recalculated, but I added logic to prevent that (not intentional, I tried to solve #601 )

**Comment by liquidpele** [comment]
you can probably leave your fix and in axis.js instead of inheriting the ticks function from d3 overwrite it in the nv.models.axis code.

**Comment by robinfhu** [comment]
nv.models.axis is not inheriting .ticks from d3.svg.axis (unless I misunderstood what you meant)

**Comment by liquidpele** [comment]
Oh right, nevermind :p

**Comment by RenatoUtsch** [comment]
So, any updates on this?

**Comment by robinfhu** [comment]
@RenatoUtsch I just haven't had the time to get to this, sorry!

**Comment by liquidpele** [comment]
I might have time to look at it tonight.  I think I might just make a global way to track if an option was set by nvd3 or overridden.

**Comment by RenatoUtsch** [comment]
This issue was fixed with @liquidpele's pull request.
