### ISSUE TITLE
Highlight area between axis values on line chart with focus

### ISSUE THREAD

**Issue by featalion** [novus/nvd3#902]
Hi!

I want to add the feature to the `lineWithFocusChart` model (or, better, all line models), which highlights custom intervals. For example, my chart has xAxis values from 0 to 100, and I want to highlight intervals 3 .. 25, and 59 .. 86.

Could you please point me to the right way to realise it. I am kinda new to D3 / NVD3, so, any help will be appreciated. I will make pull request, when complete the feature.

If I missed existing possibility to do that, let me know.

Thanks in advance!

**Comment by liquidpele** [comment]
Sure!  First you need to fork our project on github, then clone your forked git repo.   Follow the directions on our main readme for building and unit tests... this requires understanding of command line.  The source is all under the "src" directory, and when building the final files it puts them into the "build" directory. You can see samples/examples in the "examples" directory by viewing the "site.html" file... that uses the files in the "build" folder so to see your changes there you need to build.  Under the "src" directory and then "models" there are files for each component... including a lineWithFocusChart.js... this uses the line.js file, which in turn uses the scatter.js file, so they use each other and inherit from each other too.  If you start with those files that should get you started.   Cheers!

**Comment by featalion** [comment]
Thanks for the answer. I have investigated source code of NVD3 some hours today. But, as I said, I am new to D3 library, too. Could you please point me to the basics, that I will need to know to complete the feature. D3 isn't small and it isn't so easy to find right API parts to accomplish the task. Thanks again!

**Comment by liquidpele** [comment]
https://github.com/mbostock/d3/wiki/Tutorials
