### ISSUE TITLE
nvd3 bower have no nv.models.indentedTree()

### ISSUE THREAD

**Issue by HedCET** [novus/nvd3#904]
i tried also from ur build folder nv.d3.js but fails
```nv.models.indentedTree()``` only available in http://nvd3.org/assets/js/nv.d3.js here only ?

**Comment by liquidpele** [comment]
indented tree was removed from the project because it didn't fit with it very well, there are a plethora of indented tree plugins for jquery/angular/etc available online that work far better.

**Comment by robinfhu** [comment]
Yeah we don't have it anymore.  Found a nice plugin on Google: http://ludo.cubicphuse.nl/jquery-treetable/
