### ISSUE TITLE
margin top not working

### ISSUE THREAD

**Issue by joneschrisan** [novus/nvd3#905]
Margin top doesn't seem to be working for any chart I have looked at.

Left, right, and bottom how ever are working fine.

**Comment by liquidpele** [comment]
dupciate of https://github.com/novus/nvd3/issues/515

**Comment by joneschrisan** [comment]
True it's a duplicate of that issue. But that issue has been closed and the issue still exists.

**Comment by robinfhu** [comment]
I know, I just haven't been able to get to this issue.  This issue is actually really hard to solve, due to all the different ways margin top is used throughout the code.

**Comment by liquidpele** [comment]
#515 is not closed.
