### ISSUE TITLE
Word wrap when legend name is too long

### ISSUE THREAD

**Issue by rbsl-jogendra** [novus/nvd3#906]
If legend name is long in that case legend does not display properly. Is there any way by which we can wrap the legend name text.

**Comment by liquidpele** [comment]
Hi there, can you provide a jsfiddle that demonstrates the issue?

**Comment by liquidpele** [comment]
or a screenshot if that's easier, just make sure you're using the latest development branch code!

**Comment by rbsl-jogendra** [comment]
please find attached screenshot 
![selection_004](https://cloud.githubusercontent.com/assets/9459742/6763798/852620d4-cfb3-11e4-9331-fca6af4764a1.png)

**Comment by liquidpele** [comment]
What do you think the proper thing to do is in this case?

**Comment by robinfhu** [comment]
scrollbars.

**Comment by liquidpele** [comment]
can you do scroll bars within an SVG?

**Comment by robinfhu** [comment]
i don't know, but for this situation the only solution is for the user to truncate their label.
