### ISSUE TITLE
Feature: Scatter Plot over a map

### ISSUE THREAD

**Issue by joneschrisan** [novus/nvd3#914]
It would be nice to have the ability to have a scatter plot style chart over a map to show location information. For example a good use would be, hits on a site and the amount of hits per location per user / ip etc.

If this already exists then there is no documentation for it right now.

**Comment by liquidpele** [comment]
well you could certainly hover the nvd3 chart over a picture or other SVG of a map and it would probably work just fine considering that latitude and longitude are coordinates

**Comment by robinfhu** [comment]
NVD3 doesn't have this ability natively.  I've played around with D3 map projections before and they are not too difficult to figure out.  Checkout this one:

http://bl.ocks.org/mbostock/4090848

**Comment by robinfhu** [comment]
More: https://github.com/mbostock/d3/wiki/Geo-Projections
