### ISSUE TITLE
Colors not working for bar chart?

### ISSUE THREAD

**Issue by weagle08** [novus/nvd3#916]
I'm defining my series like so:
```javascript
                        var item = {
                                key: key,
                                color: settings.chartColors[count],
                                values: [
                                    {

                                        label: $scope.name,
                                        value: data[key]
                                    }
                                ]
                            };
```

however the color property is ignored. Is there something special I have to do to use specific colors on bar chart? I'm just getting gray scale atm with above data.

**Comment by robinfhu** [comment]
1. Which chart type is this? Multibar, discretebar?
2. Use https://github.com/novus/nvd3/releases/tag/v1.8.1-alpha and see if issue persists

**Comment by weagle08** [comment]
The problem is coming when using the multiBarHorizontalChart. Will check the alpha ASAP and respond back.

**Comment by liquidpele** [comment]
Oops sorry

**Comment by enricoros** [comment]
I had the same issue, and probably 1a89ba181f416f308 fixed it (I don't see the code in v1.8.1-alpha).

To fix it manually, edit nv.models.multiBarHorizontalChart commenting out this code:
```
             if (showLegend) {
                 legend.width(availableWidth - controlWidth());
 
-                if (multibar.barColor())
+                /*if (multibar.barColor())
                     data.forEach(function(series,i) {
                         series.color = d3.rgb('#ccc').darker(i * 1.5).toString();
-                    });
+                    });*/
 
                 g.select('.nv-legendWrap')
                     .datum(data)
```

**Comment by liquidpele** [comment]
Yup, we fixed a few color issues recently... check the latest in the development branch :)

**Comment by weagle08** [comment]
commenting out those lines worked enricoros.. didn't get to try the alpha. Thanks guys!

**Comment by weagle08** [comment]
The fix actually didn't work... I had colors being returned by my barColor function which isn't ideal because the legend doesn't update with the returned color.

**Comment by weagle08** [comment]
Success with the alpha!!!! The tooltips are 100% better as well!

Thanks!

**Comment by liquidpele** [comment]
awesome glad to hear it!
