### ISSUE TITLE
Box plots

### ISSUE THREAD

**Issue by Turgar** [novus/nvd3#925]
Would it make sense to add box-and-whisker plots to NVD3? I wrote some code for one of my own use cases -- I have an example running on my Github page: https://turgar.github.io/

It seems fairly basic, but the code is here if it's helpful:
https://github.com/Turgar/Turgar.github.io/blob/master/src/nv.d3.boxplot.js
https://github.com/Turgar/Turgar.github.io/blob/master/src/nv.d3.box.css

![image](https://cloud.githubusercontent.com/assets/11513691/6911373/c9548c38-d72d-11e4-9278-1f9ad067e47e.png)

**Comment by liquidpele** [comment]
Oh, that's cool...  do you think you could make a pull request to our development branch?    

Also, shouldn't you have a line for the median like here?   http://www.datavizcatalogue.com/methods/box_plot.html

**Comment by Turgar** [comment]
Here's the pull request: https://github.com/novus/nvd3/pull/926

There is a median line currently, but it doesn't contrast with the boxes... a dotted or solid black line would probably be better.

**Comment by liquidpele** [comment]
Closing this, will track via the pull request now.
