### ISSUE TITLE
linePlusBarWithFocusChart discontinued

### ISSUE THREAD

**Issue by areski** [novus/nvd3#935]
I could not find linePlusBarWithFocusChart in the last stable version 1.7?
I wonder if it has been removed or merged with an other chart?

**Comment by liquidpele** [comment]
I combined that and linePlusBarChart  ... see the example where you can toggle the focus part :)

http://nvd3-community.github.io/nvd3/examples/linePlusBarChart.html

**Comment by liquidpele** [comment]
See the focusEnable option to do the toggle.  

http://nvd3-community.github.io/nvd3/examples/documentation.html#linePlusBarChart

**Comment by areski** [comment]
Thanks for the fast answer @liquidpele

**Comment by liquidpele** [comment]
Sure, happy easter :)

**Comment by areski** [comment]
Happy Easter to you too!
