### ISSUE TITLE
x-axis labels not matching mouse over popup

### ISSUE THREAD

**Issue by chdemars** [novus/nvd3#940]
On some of my charts, the x-axis labels and the guide lines don't match the chart or the mouse over popup window. I have attached a screenshot, notice how the '2001' label and its associated guide line are well to the right of the actual data point.

On other charts with a denser dataset the labels, guide lines, and data points all seem to line up.

I am using the latest version of D3 and nvd3, but this problem was present in an earlier version that I upgraded from in hopes of fixing the problem.

Is there any reason why this would occur? Can it be fixed?

![pwg-charterror](https://cloud.githubusercontent.com/assets/2342525/7036858/6cf65f80-dd4e-11e4-84cc-753676d8e7a7.png)

**Comment by liquidpele** [comment]
That's usually a format issue... i.e. the date of the point isn't actually "2001", it's something like "July 25th 2001", so the line is where it should be, but you're formatting the date to be just 2001 so it looks weird.

**Comment by liquidpele** [comment]
PS:  If you're certain it's really a bug, then if you can provide a jsfiddle that demonstrates the problem I'll take a look. Closing for now though.
