### ISSUE TITLE
Vertical Line Chart

### ISSUE THREAD

**Issue by Mattdjuret** [novus/nvd3#941]
Is this possible to draw a vertical line chart with NVD3?

I need to make a chart looking like this one: [amcharts vertical line chart](http://www.amcharts.com/demos/vertical-line-chart/).

I have tried to make a new model from nv.models.lineChart and make it vertical by switching x and y, but I can´t figure out how to do it.

Please help!

**Comment by liquidpele** [comment]
You could try ordering the points so that it draws the line that way and not using the interactive guideline, not sure if htat would work or not though, never tried!   If not, feel free to create a model for it and send us a pull request :)

**Comment by liquidpele** [comment]
Going to go ahead and close this, let me know if you have any other questions though, cheers.
