### ISSUE TITLE
Stacked Area "Expanded" view does not handle a point where all y values are 0

### ISSUE THREAD

**Issue by lucaslin** [novus/nvd3#945]
See this plunker for the problem behavior:
http://plnkr.co/edit/cafRVbvPyHbUdKhrD7FS?p=preview

I believe this behavior happens because of a divide-by-zero: 0/0

**What is the desired behavior?**

I can imagine the desired behavior could be showing all the series go to 0%, like in this plunker:
http://plnkr.co/edit/XCfyP5yZSWZzX1LZygiO?p=preview

...or showing each series being at 100/n %.

**Comment by liquidpele** [comment]
In your "fixed" plunkr I get "Uncaught TypeError: undefined is not a function"

**Comment by lucaslin** [comment]
Sorry. Looks like Plunker can't handle the size of the nvd3.js file.
I see this error in the console too, though it still works in Chrome for me despite that.

I just made a website to host it: http://nvd3stackedarea.parseapp.com/

**Comment by liquidpele** [comment]
Ah okay, yep that looks like a bug then.   It also looks like you did something to fix it... if you can send a pull request to the development branch (not master) then we'll take a look and merge it :)

**Comment by liquidpele** [comment]
Fixed by his pull request.
