### ISSUE TITLE
nv-axisMaxMin

### ISSUE THREAD

**Issue by nicholasehamilton** [novus/nvd3#948]
This is more of a simple feature request.

Along the x axis, I notice that the first label and last label BOTH belong to the css class 'nv-axisMaxMin'

It would be good if there was a unique css class for the minimum, and another for the maximum, because I would like to, for instance, left-align the minimum, and right-align the maximum labels.

 At the moment they both belong to the same css class, and don't utilise an 'id' tag.

**Comment by liquidpele** [comment]
Hey that's not a bad idea!  However it's a pretty specific feature...  if you want to take a stab at it and send us a pull request we'll check it out and merge it in, just make sure to send the pull request to the development branch and not master!  :)

**Comment by nicholasehamilton** [comment]
I have made the changes and lodged a pull request.

**Comment by pravnviji** [comment]
I am facing the same problem with this nv-axisMaxMin. In scenario i can format the data for all label in x-axis expect Max/Min .. can u suggest ?
