### ISSUE TITLE
ohlc chart with tooltip problems.

### ISSUE THREAD

**Issue by RenatoUtsch** [novus/nvd3#952]
The ohlc chart tooltip isn't fading after I scroll out of the chart area.

Screenshot of the problem:
![screen shot 2015-04-10 at 1 45 45 pm](https://cloud.githubusercontent.com/assets/836333/7092403/066819de-df88-11e4-8d00-2d1a0c0f7cdc.png)

**Comment by RenatoUtsch** [comment]
Actually...

The problem happens on the examples page also:
http://nvd3-community.github.io/nvd3/examples/site.html

**Comment by RenatoUtsch** [comment]
The Time Series chart has the same problem.

**Comment by RenatoUtsch** [comment]
@liquidpele, this is related to your new tooltip code, isn't it?

**Comment by liquidpele** [comment]
I'll take a look when I get some time...

**Comment by liquidpele** [comment]
should be fixed now, closing.

**Comment by RenatoUtsch** [comment]
Fixed it, thanks.
