### ISSUE TITLE
multiChart with viewfinder

### ISSUE THREAD

**Issue by ImranAhmed** [novus/nvd3#961]
Hi all,

Is this supported by the library yet?. I am looking for an example of a multiChart with a view finder similar to linePlusBarchart.

multichart
https://nvd3-community.github.io/nvd3/examples/multiChart.html

linePlusBarChart
https://nvd3-community.github.io/nvd3/examples/linePlusBarChart.html

Thanks,

**Comment by liquidpele** [comment]
multichart doesn't have the focus functionality, someone tried to work on adding it but I don't think it ever was completed... feel free to try and implement it and send us a pull request :)
