### ISSUE TITLE
LineChart Interactive Guideline broken with missing data

### ISSUE THREAD

**Issue by LeeMendelowitz** [novus/nvd3#963]
Adding missing data with null/undefined x or y values is a way to break up the line into discontinuous segments in a line chart, but the missing values mess up the interactive guidlelines. Sometimes the wrong point is highlighted, as shown in screenshots below.

![error_missing_data2_wrong_point](https://cloud.githubusercontent.com/assets/2424933/7182386/f3d49dba-e41e-11e4-9ddc-b68cfffe7687.png)

![error_missing_data1](https://cloud.githubusercontent.com/assets/2424933/7182390/f5bfdd6a-e41e-11e4-8e7c-d19c0cb223e2.png)

**Comment by RenatoUtsch** [comment]
Should this issue be closed?

**Comment by liquidpele** [comment]
yep
