### ISSUE TITLE
Position of view finder

### ISSUE THREAD

**Issue by ImranAhmed** [novus/nvd3#969]
Hi,

Is there anyway to change the psoition of the view finder on the lineplusbarchart.

I was able to do the following:
 
d3.select('#myChart .nv-context').attr('transform', 'translate(0,390)');

This will move the view finder further below the chart however when you click the legend left/right axis and redraw the chart the viewfinder moves back to it's original position.

**Comment by liquidpele** [comment]
Nope, there isn't currently any option for that.  Feel free to add it if you want and send us a pull request!  If you do that, please branch the development branch to do so, and also add the option to the  lineWithFocusChart as well.

**Comment by ImranAhmed** [comment]
Thanks for prompt reply. 

Here is an example of the problem for anyoen lese who coems along: http://jsfiddle.net/_ImranA/tkjjnj2d/

I've just moved the position of the viewfinder using:

    d3.select('#chart .nv-context').attr('transform', 'translate(0,270)');

However when you press the legend 1uanntity/price notice how it goes bacn to its original predefined position. Thanks.

**Comment by liquidpele** [comment]
Yea, the nvd3 code positions it by translate too, so when you update it gets overwritten.  You can maybe try some other css trick, but ideally we would have a padding option for between the chart and the viewfinder that it uses when it calculates all that stuff.

**Comment by iamfedericofabiano** [comment]
@ImranAhmed How did you add the focus chart under the main one with bar chart???
any help is appreciate

**Comment by ImranAhmed** [comment]
@iamfedericofabiano have a look at the example here: 
https://nvd3-community.github.io/nvd3/examples/linePlusBarChart.html

source code:
https://github.com/nvd3-community/nvd3/blob/gh-pages/examples/linePlusBarChart.html

You need to configure the chart type as follows:

`
chart = nv.models.linePlusBarChart()
`

**Comment by iamfedericofabiano** [comment]
@ImranAhmed Is there a way to set up only a chart with bar and the focus? (without the line graph inside)

**Comment by ImranAhmed** [comment]
@iamfedericofabiano i think you'll need a chart type that specifically supports that. I managed to get it working using the same chart type by providing an empty datum for the y-axis and then using some css to hide the axis and labels. A specific chart type to support this will be better, if there is one.

http://jsfiddle.net/_ImranA/yy0qwcf0/
