### ISSUE TITLE
pie chart is not using defined x() and y() functions when generating tooltips

### ISSUE THREAD

**Issue by smargu27** [novus/nvd3#970]
pie chart is currently using the following code to generate tooltip data:

pie.dispatch.on('elementMouseover.tooltip', function(evt) {
        evt['series'] = {
            key: evt.data.key,
            value: evt.data.y,
            color: evt.color
        };
        tooltip.data(evt).hidden(false);
    });

It doesn't work if you data is structured differently and a custom x(), y() functions were specified for the chart. 

I tested locally with the following code and it seems to work correctly:

    pie.dispatch.on('elementMouseover.tooltip', function(evt) {
        evt['series'] = {
            key: pie.x()(evt.data),
            value: pie.y()(evt.data),
            color: evt.color
        };
        tooltip.data(evt).hidden(false);
    });

**Comment by liquidpele** [comment]
Did you grab and compile the latest in the development branch?  Pressure sure I fixed that several weeks ago...

**Comment by smargu27** [comment]
I checked out the development branch. pieChart.js still has the code that uses data.key and data.y values. Thats where I took the code snippet from.

**Comment by smargu27** [comment]
I looks to be fixed on the gh-pages branch.

**Comment by liquidpele** [comment]
https://github.com/novus/nvd3/blob/development/src/models/pieChart.js#L182

**Comment by smargu27** [comment]
My appologies, I was using:

https://github.com/nvd3-community/nvd3/blob/development/src/models/pieChart.js

Whats the differences between novus/nvd3 and nvd3-community/nvd3. Which one should I be using?

**Comment by smargu27** [comment]
And yes, i just realized I added the bug to the wrong project...

**Comment by liquidpele** [comment]
nvd3-community is basically just maintenance, they added me to the repo here so I've just been doing all my dev work on it since the main nvd3.org site links to here.  Sorry for any confusion!
