### ISSUE TITLE
Scatter chart tooltip, hover and distribution broken

### ISSUE THREAD

**Issue by RenatoUtsch** [novus/nvd3#971]
If I open the test/ScatterChartTest.html test, you can notice readily that the X and Y distributions are being extended incorrectly.

Also, If I change the width or the height of the page, the tooltip (and the distribution and the hover effect) stops appearing if I mouse over a point. Maybe they are being calculated incorrectly? Dunno.

@liquidpele remember when you noticed this under my poly-nvd3 scatter chart? It seems it is happening with the normal nvd3 outside shadow DOM too.

**Comment by RenatoUtsch** [comment]
Researched a little bit.

The problem with the distributions being extended incorrectly was introduced in commit 5e121c2.

The  resize bug was introduced in an earler commit, will research more.

**Comment by RenatoUtsch** [comment]
Researched a little more.

The resize bug was introduced in commit 60b4ded.

**Comment by RenatoUtsch** [comment]
Removing the line added to models/scatter.js in 60b4ded seems to solve the resize issue.

@robinfhu, why did you add that line? Is it safe to revert it? (it seems so)

**Comment by robinfhu** [comment]
Oh no you can't remove that otherwise this issue will manifest itself: https://github.com/novus/nvd3/issues/783

**Comment by liquidpele** [comment]
The commit you say the distribution bug was in looks like just a merge it doesn't look like the original commit

**Comment by RenatoUtsch** [comment]
@liquidpele
Yes, it was just a merge, I didn't have the time to look which commit it was. But it was in that merge.

@robinfhu 
Then this fix is wrong, because it brought up another issue hehe

**Comment by robinfhu** [comment]
@RenatoUtsch the fix isn't wrong.  If the other issue is brought up that issue should be fixed, but the original behavior was grossly incorrect.  Having a bunch of nv-clip-paths on the DOM is wrong.

**Comment by RenatoUtsch** [comment]
@robinfhu true, sry. Then we need to figure out why this is happening.

**Comment by liquidpele** [comment]
I fixed the resize issue by just redoing some of the logic, see the PR above.

**Comment by liquidpele** [comment]
@RenatoUtsch when you say "The problem with the distributions being extended incorrectly", do you mean how the colored lines that appear on hover that are supposed to go from the point to each axis?  I notice on the testing page that they're not appearing where they should be, or are too long or short.  Is that what you're referring to?

**Comment by RenatoUtsch** [comment]
@liquidpele yeah that's it.

Em ter, 21 de abr de 2015 00:16, liquidpele <notifications@github.com>
escreveu:

**Comment by m48u** [comment]
I got some problems (using AngularJS and nvd3 1.8.1) with tooltip alignment of guidelines. It seems that some path lines are calculated wrong in the y2 value.

Don't wonder about other values, I used own values and not the example above
![image](https://cloud.githubusercontent.com/assets/3088389/8591270/5b4e08b0-2627-11e5-8ca3-33376ee473c4.png)
