### ISSUE TITLE
want to Create a DualAxisBarChart using NVD3

### ISSUE THREAD

**Issue by vkumarOST** [novus/nvd3#973]
I want to create a DualAxisBarchart but kind of stuck. Tried many way but actually am able to create Two yAxis but instead to create two separate bar its creating two bar at the same place please suggest me some approach am creating this using multichart() function. looks like current functionality not supporting 

![graph](https://cloud.githubusercontent.com/assets/6815297/7215228/3e8f8086-e5eb-11e4-8091-2597a14394bc.JPG)

**Comment by lucaslin** [comment]
I'd recommend posting this question on [StackOverflow (under the nvd3.js tag)](http://stackoverflow.com/questions/tagged/nvd3.js). This area of the NVD3 github is for issues (like bug tracking and improvements). Also, when you post there, I'd recommend using an online tool like Plunker or JSFiddle to share your code and the result. Feel free to fork [this example](http://plnkr.co/edit/Q4ohxfLaepnOnApDCVQK?p=preview) as a starting point.
