### ISSUE TITLE
multiBarChart tooltip rendering border artifacts in FireFox

### ISSUE THREAD

**Issue by bradgreens** [novus/nvd3#975]
In FireFox 37 on OSX 10.10, the chart's tooltip is producing border artifacts that stick around like in the following screenshot: 
![screen shot 2015-04-20 at 8 54 22 am](https://cloud.githubusercontent.com/assets/284366/7236277/cfa8f0d0-e748-11e4-8f9e-188b84565c27.png)
 
I narrowed the cause of this glitch down to the `.nvtooltip` `font-size` property. I believe FireFox has a rendering bug related to it, although I haven't tried to produce a truly minimal example of it.

The workaround, is to simply set the tooltip to any font-size other than `13px`. Such as:
```
.nvtooltip {
  // Warning: FireFox glitches with 13px font-size.
  font-size: 13.1px;
}
```

**Comment by liquidpele** [comment]
You probably want to submit a bug to Mozilla:   https://bugzilla.mozilla.org/

For yourself, you can easily work around it by overriding the tooltip font size using the !important flag.
