### ISSUE TITLE
yAxis min becomes -1 when all points' y values are 0 (stackedAreaChart)

### ISSUE THREAD

**Issue by lucaslin** [novus/nvd3#976]
Not sure if this is intentional, but the behavior seems odd, since the default is to always show the yAxis starting at 0, even when some (but not all) points' y values are 0.

See Plunk:
http://plnkr.co/edit/umasgIoekdoWcVjvigHM?p=preview

Seems like it's a result of stackedArea's dependence on scatter:

            // If scale's domain don't have a range, slightly adjust to make one... so a chart can show a single data point
            if (x.domain()[0] === x.domain()[1] || y.domain()[0] === y.domain()[1]) singlePoint = true;
            if (x.domain()[0] === x.domain()[1])
                x.domain()[0] ?
                    x.domain([x.domain()[0] - x.domain()[0] * 0.01, x.domain()[1] + x.domain()[1] * 0.01])
                    : x.domain([-1,1]);

            if (y.domain()[0] === y.domain()[1])
                y.domain()[0] ?
                    y.domain([y.domain()[0] - y.domain()[0] * 0.01, y.domain()[1] + y.domain()[1] * 0.01])
                    : y.domain([-1,1]);

            if ( isNaN(x.domain()[0])) {
                x.domain([-1,1]);
            }

            if ( isNaN(y.domain()[0])) {
                y.domain([-1,1]);
            }

This line in particular `y.domain()[0] ?` seems to be checking for null, NaN, etc., but the value 0 also fails this condition.

**Comment by lucaslin** [comment]
Maybe we can add a `defaultDomain` option that the user can specify?

**Comment by lucaslin** [comment]
Also, part of this domain checking code is [copied across many charts](https://github.com/novus/nvd3/search?l=javascript&q=%5B-1+%2C1%5D&utf8=%E2%9C%93). Maybe we can create a `util` function to perform it as well? Something like:

    updateDisplayDomain(scale, default)

(probably with a better name)

**Comment by liquidpele** [comment]
It looks like stackedAreaChart builds the y axis scale using stackedArea.yScale() which inherits it from scatter.js, so there is probably a calculation within scatter that causes that...

**Comment by lucaslin** [comment]
Yes. That's where the code above is from. Is it possible that we could allow the user to set the default domain?

For my use-case, it's weird that all my stackedAreaCharts' y-axes start at 0, unless all the data points are 0, in which case it starts at -1.

For example, I'm trying to show 2 metrics side-by-side for the same thing (Metric A and Metric B for 'Thing'):
![image](https://cloud.githubusercontent.com/assets/1623899/7311995/0730ca16-e9f9-11e4-8d9f-28689150cca4.png)
It would be ideal for their y-axes to match.

**Comment by zocoi** [comment]
likely related to #968

**Comment by lucaslin** [comment]
How would you set a hard Max/Min on a chart? It seems `forceY` only ensures its arguments are included in the domain: "List of numbers to Force into the Y scale (ie. 0, or a max / min, etc.).  This ensures the numbers are in the Y domain but doesn't override the whole domain.  This option only applies if you have not overridden the whole domain with the yDomain option." The other option seems to be overwriting the whole domain.

For example, is there an easy way of setting the Min of the domain to 0, but allowing the Max to be calculated as normal? (even for charts in general, not just stackedArea)

**Comment by liquidpele** [comment]
Fix was merged.

**Comment by meenu1** [comment]
When y values are zero, If we use forceY: [0, 1]. y axis will not come -1.
