### ISSUE TITLE
(Possible bug?) How to use the historical bar chart

### ISSUE THREAD

**Issue by RenatoUtsch** [novus/nvd3#988]
Hey, I was wondering about something rather strange of the historical bar chart: when plotting a graph, it uses kind of an index for each datum in the x axis.

For example, if I want to plot one bar every 15 minutes in the X-Axis, I have to make an increasing index: (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, ...). When setting the axis format, I have to multiply this index by 15 and sum the initial time.

Why can't I just use, for example, timestamps for the historical bar chart? If I do this the tooltips and the interactive guideline get all messed up and the X axis shows only one value.

An example:
https://jsfiddle.net/0kg2L8ea/

The interactive guideline and the tooltips get all messed up, even though the chart is plotted just fine. Is this a bug?

**Comment by robinfhu** [comment]
Historical Bar Chart uses an increasing index because it ensures the bars are spaced exactly evenly.

**Comment by RenatoUtsch** [comment]
But can't this be hidden from the user? Like creating an index under the cover but using the values that aren't increasing indexes when displaying the values in the X-axis?

**Comment by RenatoUtsch** [comment]
I discovered why this example gets the tooltips messed up. Actually, it is not because they are timestamps, but because they are in descending order: the first datum is about the newest day, the second datum about the day before, etc.

Shouldn't we sort the data with respect to the date before using it? Or do we expect that the data is ordered in an ascending order?

**Comment by robinfhu** [comment]
nvd3 right now expects data to be in ascending order.

**Comment by RenatoUtsch** [comment]
Okay, so I just have to sort it before sending to nvd3.

Thanks.
