### ISSUE TITLE
it throws error when resizing

### ISSUE THREAD

**Issue by schengcrouchingtiger** [novus/nvd3#989]
Uncaught TypeError: Cannot read property '2' of undefinedd3.js:8560 (anonymous function)d3.js:890 d3_selection_eachd3.js:8559 d3_transitionPrototype.eachnv.d3.js:2190 chartnv.d3.js:2199 nv.models.bulletChart.selection.each.chart.updatenv.d3.js:904 nv.utils.windowResize.window.onresizenv.d3.js:903 nv.utils.windowResize.window.onresizenv.d3.js:903 nv.utils.windowResize.window.onresize

// 
// Easy way to bind multiple functions to window.onresize
// TODO: give a way to remove a function after its bound, other than removing all of them
nv.utils.windowResize = function(fun){
  if (fun === undefined) return;
  var oldresize = window.onresize;

  window.onresize = function(e) {
    if (typeof oldresize == 'function') oldresize(e);
    fun(e);
  }
}

**Comment by liquidpele** [comment]
Are you using the latest development branch?    

Can you provide a jsfiddle or plunkr that demonstrates the error?

**Comment by schengcrouchingtiger** [comment]
I just found out that it only occurs on the bulletChart. Other charts I
tested had no such problem.

You can just throw in a bulletChart and test it out.

this is the versions I use:

    "d3": "~3.5.5",
    "nvd3": "~v1.1.15-beta",
    "angularjs-nvd3-directives": "~0.0.7"



On Thu, Apr 23, 2015 at 4:29 PM, liquidpele <notifications@github.com>
wrote:

> Are you using the latest development branch?
>
> Can you provide a jsfiddle or plunkr that demonstrates the error?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/novus/nvd3/issues/989#issuecomment-95735444>.
>



-- 
Regards
Shanhong Cheng
shanhongcheng@gmail.com

**Comment by schengcrouchingtiger** [comment]
I just found out that it only occurs on the bulletChart. Other charts I tested had no such problem. 

You can just throw in a bulletChart and test it out.

this is the versions I use:

    "d3": "~3.5.5",
    "nvd3": "~v1.1.15-beta",
    "angularjs-nvd3-directives": "~0.0.7"

**Comment by schengcrouchingtiger** [comment]
I just git clone the repo.

start a static web server.

and visit

http://localhost:9005/bulletChart.html

and resize, it throws the error

**Comment by liquidpele** [comment]
Your'e specifying 1.1.15-beta... the latest is 1.7.0, and we have a 1.8.1-alpha right now... you need to test the latest development branch, it has literally hundreds of fixes, several new charts, and the tooltips have been completely refactored :)
