### ISSUE TITLE
Invert chart

### ISSUE THREAD

**Issue by dieuhd** [novus/nvd3#997]
I have a follow chart
![screen shot 2015-04-27 at 11 33 14](https://cloud.githubusercontent.com/assets/3165692/7340847/5e7330ae-ecd1-11e4-9a5a-6ef38b830fbc.png)

and I want to invert it as follow
![screen shot 2015-04-27 at 11 33 47](https://cloud.githubusercontent.com/assets/3165692/7340850/7004bf54-ecd1-11e4-82e0-bc68d18259ea.png)

Is there a way to do it ??

**Comment by liquidpele** [comment]
You'd have to use negative numbers, and then use the axis/tooltip value formatting functions to display the number as positive.

**Comment by liquidpele** [comment]
.e.g. something like this (off the top of my head, so this might not be exactly right):

    chart.yAxis.tickFormat(function(d){ return Math.abs(d); });

http://nvd3-community.github.io/nvd3/examples/documentation.html

**Comment by dieuhd** [comment]
@liquidpele :+1:  thanhks
